import { chapterMarkup, sourceLink as ref, workedCheck as check, escapeCode } from "./lesson-template";

const nvidia = "https://docs.nvidia.com/enterprise-reference-architectures/hgx-ai-factory/latest/components.html";
const amd = "https://rocm.docs.amd.com/en/docs-7.2.4/how-to/rocm-for-ai/inference-optimization/workload.html";
const tpu = "https://docs.cloud.google.com/tpu/docs/tpu7x";
const trn2 = "https://awsdocs-neuron.readthedocs-hosted.com/en/v2.31.1/about-neuron/arch/neuron-hardware/trainium2.html";
const trn3 = "https://awsdocs-neuron.readthedocs-hosted.com/en/latest/about-neuron/arch/neuron-hardware/trainium3.html";
const groq = "https://groq.com/wp-content/uploads/2023/05/GroqISCAPaper2022_ASoftwareDefinedTensorStreamingMultiprocessorForLargeScaleMachineLearning-1.pdf";
const source = (url: string, text: string) => `<a href="${url}" target="_blank" rel="noreferrer">${text}</a>`;

export const acceleratorChapter = chapterMarkup(
  "accelerator-atlas", "Read a machine beyond its FLOPS", "A comparative hardware atlas: follow storage, instructions and communication through GPUs, TPUs, Trainium, streaming processors, wafers and local systems. Source audit: September 14, 2026.", `
<section class="lesson" id="accelerator-comparison-contract" data-lesson="How to compare accelerators"><header><span>Comparison method</span><h3>Specify the boundary before you compare the number</h3></header>
<p>An accelerator is a compromise among programmable control, arithmetic, local storage and communication. The useful question is: can this exact model, precision, context length and concurrency run within the required latency, cost and quality? A chip's advertised arithmetic rate is only one constraint. A compiler that cannot lower your operator, or a runtime that cannot manage its state, can be the binding constraint.</p>
<p>Read the names at their physical scale. A <strong>die</strong> is one manufactured piece of silicon; a <strong>package</strong> can connect several dies. A server or node adds host processors, memory, networking and software. HBM means <strong>high-bandwidth memory</strong>: stacked DRAM attached close to an accelerator. SRAM is smaller local storage used for caches or explicitly managed buffers. DRAM requires periodic refresh; SRAM retains its state while powered without that refresh operation. Both lose ordinary working state when power is removed.</p>
<div class="method-table"><table><caption>Five annotations every hardware comparison needs</caption><thead><tr><th scope="col">Quantity</th><th scope="col">Declare</th><th scope="col">Common misreading</th></tr></thead><tbody><tr><th scope="row">Compute</th><td>Input/accumulator dtype; dense or structured sparse; multiply-add = two operations</td><td>FP4 sparse peak presented as BF16 dense performance</td></tr><tr><th scope="row">Memory</th><td>Per die, accelerator package, server or pod; GB versus GiB; usable allocation</td><td>Aggregate rack HBM treated as one local buffer</td></tr><tr><th scope="row">Bandwidth</th><td>HBM, SRAM, one network direction, or sum of ports</td><td>Summed local SRAM reads compared to off-chip HBM as a direct speedup</td></tr><tr><th scope="row">Measurement</th><td>Model revision, batch, prompt/output lengths, quality and tail latency</td><td>Offline throughput used to promise interactive responsiveness</td></tr><tr><th scope="row">Status</th><td>Shipped platform, documented cloud offering, announcement or author result</td><td>A roadmap date treated as available capacity in your region</td></tr></tbody></table></div>
<p>Tables below preserve the source's capacity units. A source that says GB is not silently converted into GiB. <code>1 GiB = 2³⁰ bytes</code>; <code>1 GB = 10⁹ bytes</code>. In the teaching calculations, every capacity is explicitly GiB and every bandwidth explicitly decimal bytes per second. Platform documentation supports availability of a product family; it does not establish today's stock or cloud quota.</p>
<p>MLPerf defines workloads, quality thresholds, load scenarios and divisions to constrain comparisons; its power methodology measures a full system. Use its submission details to identify a configuration, then run your application's request distribution and quality checks.</p>${ref("https://mlcommons.org/benchmarks/inference-datacenter/", "MLCommons: inference scenarios, quality constraints, divisions and system power")}
</section>
<section class="lesson" id="accelerator-memory-atlas" data-lesson="Memory and peak specifications"><header><span>Reference atlas</span><h3>Capacity determines placement; bandwidth constrains the next step</h3></header>
<div class="method-table"><table><caption>Documented per-accelerator storage; peaks are vendor specifications, checked September 14, 2026</caption><thead><tr><th scope="col">Device / edition</th><th scope="col">Local large memory</th><th scope="col">Peak memory bandwidth</th><th scope="col">Evidence and status</th></tr></thead><tbody>
<tr><th scope="row">NVIDIA H100 SXM</th><td>80 GB HBM3</td><td>3.35 TB/s</td><td>${source("https://www.nvidia.com/en-us/data-center/h100/","H100 SXM specification, checked September 16, 2026")}; <a href="#h100-kernel-example">worked Hopper example</a></td></tr>
<tr><th scope="row">NVIDIA H200 SXM</th><td>141 GB HBM3e</td><td>4.8 TB/s</td><td>${source(nvidia,"HGX reference platform")}; established Hopper example</td></tr>
<tr><th scope="row">NVIDIA B200 SXM</th><td>180 GB HBM3e</td><td>Up to 8 TB/s</td><td>${source(nvidia,"HGX deployment specification")}; do not replace with generic 192 GB Blackwell silicon figures</td></tr>
<tr><th scope="row">NVIDIA B300 SXM</th><td>288 GB HBM3e</td><td>Up to 8 TB/s</td><td>${source(nvidia,"HGX B300 reference platform")}; eight-GPU node has about 2.30 TB aggregate</td></tr>
<tr><th scope="row">NVIDIA Rubin GPU</th><td>Up to 288 GB HBM4</td><td>Up to 22 TB/s</td><td>${source("https://developer.nvidia.com/blog/inside-nvidia-rubin-gpu-architecture-powering-the-era-of-agentic-ai/","July 21, 2026 architecture disclosure")}; deployment availability must be checked separately</td></tr>
<tr><th scope="row">AMD MI300X / MI325X</th><td>192 GB HBM3 / 256 GB HBM3e</td><td>5.3 / 6.0 TB/s</td><td>${source(amd,"ROCm 7.2.4 workload guide")}; CDNA 3</td></tr>
<tr><th scope="row">AMD MI350X / MI355X</th><td>288 GB HBM3e each</td><td>8.0 TB/s each</td><td>${source(amd,"ROCm 7.2.4 workload guide")}; CDNA 4, different power/cooling envelopes</td></tr>
<tr><th scope="row">Google TPU v5p / v6e Trillium</th><td>95 / 32 GiB HBM per chip</td><td>2,765 / 1,638 GB/s</td><td>${source(tpu,"Cloud TPU comparison table")}; distinct scaling/capacity choices</td></tr>
<tr><th scope="row">Google TPU7x Ironwood</th><td>192 GiB HBM per chip</td><td>7,380 GB/s</td><td>${source(tpu,"Cloud TPU7x deployment documentation")}; 9,216-chip pod footprint</td></tr>
<tr><th scope="row">AWS Trainium2</th><td>96 GiB device memory</td><td>2.9 TB/s</td><td>${source(trn2,"Neuron architecture specification")}; eight physical NeuronCore-v3 cores</td></tr>
<tr><th scope="row">AWS Trainium3</th><td>144 GiB device memory</td><td>4.9 TB/s headline</td><td>${source(trn3,"Neuron architecture specification")}; NKI architecture guide instead states 4.7 TB/s</td></tr>
<tr><th scope="row">Intel Gaudi 3</th><td>128 GB HBM2e</td><td>3.7 TB/s</td><td>${source("https://community.intel.com/t5/Blogs/Tech-Innovation/Artificial-Intelligence-AI/Deploying-Llama-4-Scout-and-Maverick-Models-on-Intel-Gaudi-3/post/1699547","Intel deployment and architecture guide")}; eight matrix engines and 64 tensor processor cores</td></tr>
</tbody></table></div>
<p>These are capacity and movement facts, not a ranked benchmark. The TPU documentation labels capacity GiB while some product pages round it to GB; AMD also uses GiB in its architecture tables. Retain the chosen table's units and query actual allocatable memory on your deployment. AWS's two Trainium3 guides disagree on 4.9 versus 4.7 TB/s and on some communication-engine counts. This atlas keeps the headline value as a vendor specification and excludes disputed engine counts from its comparisons.</p>
${ref("https://awsdocs-neuron.readthedocs-hosted.com/en/latest/nki/guides/architecture/trainium3_arch.html", "Trainium3 NKI architecture guide: the conflicting 4.7 TB/s value")}
<p>Rubin is included as a dated disclosed architecture. NVIDIA's launch statement says partner products start in the second half of 2026; that statement alone does not verify a particular rentable instance or delivered rack. Trainium3's December 2, 2025 notice explicitly announces general availability of Trn3 UltraServers. Those are different kinds of evidence.</p>
${ref("https://nvidianews.nvidia.com/_gallery/download_pdf/695c39b23d633240d175d8e6/", "NVIDIA Rubin launch: production and partner availability window")}${ref("https://aws.amazon.com/about-aws/whats-new/2025/12/amazon-ec2-trn3-ultraservers/", "AWS: Trn3 UltraServer general availability, December 2, 2025")}
</section>
<section class="lesson" id="accelerator-programming-models" data-lesson="Programming models"><header><span>What your kernel becomes</span><h3>The same GEMM reaches different instruction machines</h3></header>
<figure class="architecture-figure"><figcaption><span>Original schematic · execution contracts</span><strong>From a tensor graph to timed movement</strong></figcaption><div class="architecture-scroll"><svg viewBox="0 0 840 320" role="img" aria-labelledby="accelerator-flow-title accelerator-flow-desc"><title id="accelerator-flow-title">Four ways of executing a tensor program</title><desc id="accelerator-flow-desc">GPU threads run in dynamically scheduled warps or wavefronts and use matrix units. TPU kernels move tiles from HBM to vector memory and matrix units. Trainium kernels move through scratch buffers, tensor engines and partial-sum memory. A streaming compiler schedules SRAM, arithmetic and network arrivals explicitly.</desc><g fill="none" stroke="currentColor" stroke-width="1.2"><path d="M180 48H215M400 48H435M180 118H215M400 118H435M180 188H215M400 188H435M180 258H215M400 258H435"/><rect x="10" y="20" width="170" height="54"/><rect x="215" y="20" width="185" height="54"/><rect x="435" y="20" width="390" height="54"/><rect x="10" y="90" width="170" height="54"/><rect x="215" y="90" width="185" height="54"/><rect x="435" y="90" width="390" height="54"/><rect x="10" y="160" width="170" height="54"/><rect x="215" y="160" width="185" height="54"/><rect x="435" y="160" width="390" height="54"/><rect x="10" y="230" width="170" height="54"/><rect x="215" y="230" width="185" height="54"/><rect x="435" y="230" width="390" height="54"/></g><g font-size="15"><text x="22" y="52">CUDA / HIP</text><text x="230" y="52">Thread groups</text><text x="450" y="44">HBM → shared / registers → matrix units</text><text x="450" y="65" font-size="12">Warp / wavefront readiness guides scheduling</text><text x="22" y="122">JAX / Pallas / XLA</text><text x="230" y="122">Tiled tensor program</text><text x="450" y="114">HBM → VMEM → vector / matrix units</text><text x="450" y="135" font-size="12">Compiler pipelines movement and computation</text><text x="22" y="192">Neuron / NKI</text><text x="230" y="192">Tiles + engine ops</text><text x="450" y="184">HBM → SBUF → Tensor Engine → PSUM</text><text x="450" y="205" font-size="12">Layout, engine dependencies and DMA matter</text><text x="22" y="262">Groq TSP compiler</text><text x="230" y="262">Time + placement</text><text x="450" y="254">Distributed SRAM ↔ compute ↔ fabric</text><text x="450" y="275" font-size="12">Schedule includes expected data arrival</text></g></svg></div><p class="figure-boundary">Logical execution paths, not transistor floorplans. Every architecture also has host orchestration and system software.</p></figure>
<p>CUDA and HIP expose thread groups, synchronization and memory spaces. A CUDA warp has 32 threads; an AMD CDNA wavefront has 64 lanes. An algorithm may port cleanly while warp reductions, tile layout, occupancy assumptions and low-precision formats need redesign. MI300's FP8 FNUZ encodings and MI350's OCP FP8/MX support are a concrete portability boundary, even when tensors have the same nominal bit width.</p>${ref("https://docs.nvidia.com/cuda/cuda-programming-guide/01-introduction/programming-model.html", "CUDA execution and memory model")}${ref(amd,"ROCm: CDNA 3 versus CDNA 4 datatype and locality differences")}
<p>A TPU TensorCore contains scalar, vector and matrix units; this vendor term does not mean the same component as an NVIDIA Tensor Core. Pallas exposes HBM, vector memory (VMEM), scalar memory and synchronization. A tile must reach the fast memory used by the computation. NKI similarly exposes scratch-buffer (SBUF) and partial-sum (PSUM) placement around specialized engines. In both cases the useful mental model is a dependency graph with concrete storage lifetimes.</p>${ref("https://docs.jax.dev/en/latest/pallas/tpu/pipelining.html", "JAX: TPU memories, compute units and pipelining")}${ref("https://awsdocs-neuron.readthedocs-hosted.com/en/latest/nki/guides/architecture/trainium2_arch.html", "NKI: Trainium2 memory and compute architecture")}
<p>The hardware-table unit also needs to match the framework's device unit. TPU7x has two chiplets with separate memory spaces, and JAX exposes two devices per physical chip. Its 192 GiB per-chip capacity must therefore not be assumed to be one directly local allocation on every framework device. Communication between chiplets is part of a real placement plan, even though both belong to the same physical chip.</p>${ref(tpu,"Google TPU7x: chiplets, separate memory spaces and framework device exposure")}
${check("Exercise: can a reduction written around 32-lane shuffles be assumed correct on a 64-lane wavefront?", "No. State which lanes participate, which value each lane owns and where the final sum must reside. Use the target's subgroup primitives or rewrite the reduction, then verify odd sizes and partially occupied groups. A compiler accepting the source does not prove the reduction's ownership contract.")}
</section>
<section class="lesson" id="accelerator-sram-machines" data-lesson="SRAM streaming and wafer-scale systems"><header><span>Different storage economics</span><h3>Put more working state next to the arithmetic</h3></header>
<p>The 2022 Groq Tensor Streaming Processor paper describes 220 MiB of SRAM contributed by each TSP to a distributed memory space. It schedules communication explicitly, including link timing, to maintain deterministic execution. This is an architectural case study, not a specification for every subsequent Groq-branded device. A cloud request still has queueing, networking and service-level behavior outside that static schedule.</p>${ref(groq,"Abts et al., ISCA 2022: distributed SRAM and compiler-scheduled networking")}
<p>Cerebras WSE-3 distributes 44 GB of SRAM and 900,000 cores across a wafer. The published 21 PB/s number is aggregate local SRAM bandwidth. It is not the bandwidth of one external connection, nor proof that every model reads all its weights at that rate. External model storage and a wafer's SRAM are separate budgets. Mapping, tensor placement and inter-wafer movement determine what is actually local.</p>${ref("https://www.cerebras.ai/press-release/cerebras-announces-third-generation-wafer-scale-engine", "Cerebras WSE-3 announcement: wafer capacity and core count")}${ref("https://www.cerebras.ai/blog/disaggregated-inference", "Cerebras: WSE-3 local bandwidth and heterogeneous prefill/decode disclosure")}
<p>On August 18, 2026, Cerebras announced CS-4 using WSE-3 Turbo (WSE-3T): 44 GB SRAM, 900,000 cores and 43.2 PB/s aggregate local memory bandwidth per wafer in its disclosure. Those are WSE-3T wafer figures; the three-wafer CS-4 system advertises 129.6 PB/s in aggregate, a different comparison boundary. Treat its speedup and energy statements as vendor results for specified workloads. The unchanged SRAM capacity means faster local movement does not by itself make a larger resident model fit.</p>${ref("https://investors.cerebras.ai/news-releases/news-release-details/cerebras-unveils-cs-4-30-times-faster-gpu-based-solutions", "Cerebras: CS-4 / WSE-3T announcement, August 18, 2026")}
<h4>Derive a capacity lower bound, then find what it excludes</h4><p>A hypothetical 70-billion-parameter model with exactly 4 bits per weight needs 35 billion bytes before scales, buffers and state. Using the paper's 220 MiB per TSP, <code>ceil(35×10⁹ / (220×2²⁰)) = 152</code> TSPs is a weight-capacity lower bound. It does not establish a supported 152-device topology or a runnable placement. It excludes compiler reservations, network buffers and KV state. WSE-3's 44 GB headline can hold those weight bytes arithmetically; that alone does not validate a single-wafer deployment.</p>
${check("Exercise: does 21 PB/s divided by 8 TB/s prove a 2,625× application speedup?", "No. The numerator sums many local SRAM paths, while the denominator measures a different HBM boundary. Capacity, placement, arithmetic, synchronization and network traffic differ. To compare applications, match model, quality, request load and measured latency at the system boundary.")}
</section>
<section class="lesson" id="accelerator-capacity" data-lesson="Interactive model residency and KV budgets"><header><span>Capacity workbench</span><h3>Weights fit before the fourth request arrives</h3></header>
<p>For a conventional grouped-query attention cache with L layers, H KV heads, head dimension D, context S and s bytes per stored scalar, one sequence consumes <code>2LHDSs</code> bytes. The leading two counts keys and values. Model weights are shared across requests; each independent request has its own KV state unless prefix-sharing semantics explicitly allow reuse.</p>
<figure class="textbook-lab method-lab" id="accelerator-capacity-lab"><figcaption><span>Interactive · declared 70B teaching model</span><strong>Choose storage precision and request concurrency</strong><p>80 layers, 8 KV heads, dimension 128; an 8 GiB runtime reserve. Quantized formats use one byte of scale metadata per 32 weights. This models storage accounting, not a named checkpoint or a quantization implementation.</p></figcaption><div class="method-toolbar"><label>Capacity<select data-capacity-memory><option>48</option><option selected>80</option><option>96</option><option>144</option><option>192</option><option>288</option></select> GiB</label><label>Weight bits<select data-capacity-bits><option selected>4</option><option>8</option><option>16</option></select></label><label>Context<select data-capacity-context><option>8192</option><option selected>32768</option><option>131072</option></select></label><label>KV bytes / scalar<select data-capacity-kv><option>1</option><option selected>2</option></select></label><label>Sequences<select data-capacity-batch><option>1</option><option>2</option><option>3</option><option selected>4</option><option>8</option><option>16</option></select></label></div><div class="capacity-readout" data-capacity-result aria-live="polite"></div><div class="capacity-bars" data-capacity-bars></div><p class="figure-boundary" data-capacity-transfer></p><p class="figure-boundary">Excludes allocator fragmentation, page rounding, scale metadata for KV, activations exceeding the fixed reserve and distributed replication. Halving KV storage does not establish acceptable model quality. The exact arithmetic is tested in accelerator-math.test.ts.</p></figure>
<h4>Work the default case by hand</h4><p>Weights require <code>70×10⁹×0.5 + (70×10⁹/32)×1 = 37.1875 GB ≈ 34.63 GiB</code>. Each 32,768-token sequence uses <code>2×80×8×128×32768×2 = 10 GiB</code>. An 80 GiB budget minus 8 GiB reserve and 34.63 GiB weights leaves about 37.37 GiB: three complete sequences fit, four do not. A request's maximum context setting is a capacity commitment if the runtime reserves it up front; paged allocation can instead grow with actual tokens.</p>
<p>MLA stores a different state representation; recurrent layers hold matrix state rather than a full conventional KV history. Their formulas belong in the <a href="#frontier-mla">MLA</a> and <a href="#frontier-hybrid">hybrid architecture</a> lessons. Applying this GQA formula to those models would overstate or mischaracterize their state.</p>
</section>
<section class="lesson" id="accelerator-local-systems" data-lesson="CPUs and edge devices"><header><span>Local and edge systems</span><h3>A shared addressable pool still has finite bandwidth</h3></header>
<p>A CPU provides general control, branch handling and vector instructions, with cache and DRAM shared across cores according to the system topology. It is useful for tokenization, scheduling, small models, some sparse operations and a correctness reference. A GPU can provide more parallel matrix throughput, but small launches, transfers and unsupported operations can consume the expected gain. First establish the complete task's latency distribution.</p>
<p>Apple's M4 Max is a concrete local example: its October 2024 announcement specifies up to 128 GB unified memory and 546 GB/s memory bandwidth. These are SoC-level resources shared with the operating system and other workloads, not 128 GB of dedicated model storage. MLX arrays use shared memory accessible by CPU and GPU, avoiding a separate physical CPU-to-GPU copy for the same array. Dependencies and execution completion still matter.</p>${ref("https://www.apple.com/sg/newsroom/2024/10/apple-introduces-m4-pro-and-m4-max/", "Apple M4 Max: dated unified-memory example")}${ref("https://ml-explore.github.io/mlx/build/html/usage/unified_memory.html", "MLX: unified memory and stream synchronization")}
<p>For a hypothetical dense 8B model stored at exactly 4 bits per weight, one complete weight sweep is 4 GB. Dividing by 546 GB/s gives a 7.33 ms ideal bandwidth lower bound per unbatched sweep. It is not a tokens-per-second prediction: scale metadata, actual cache reuse, kernel efficiency, KV reads, output projections and other workloads change traffic and achievable bandwidth. A phone NPU, laptop GPU and datacenter GPU also expose different supported operators and precision paths.</p>
${check("Exercise: the OS reports 128 GB of physical memory. Can a 127 GB checkpoint safely load?", "That number ignores the OS, loader copies, execution buffers, KV cache and runtime allocation limits. Measure available memory and the peak during loading and inference. Memory mapping or swap may change loading behavior while severely changing latency; physical capacity is not a promise of a stable working set.")}
</section>
<section class="lesson" id="accelerator-topology-fit" data-lesson="Matching hardware to workloads"><header><span>From chip to deployment</span><h3>Match the communication pattern to the physical domain</h3></header>
<div class="method-table"><table><caption>Workload-to-machine reasoning, not product recommendations</caption><thead><tr><th scope="col">Workload</th><th scope="col">First scarce resource</th><th scope="col">Placement experiment</th></tr></thead><tbody><tr><th scope="row">Large dense training</th><td>Matmul throughput, optimizer/activation memory, collective critical path</td><td>Keep frequent tensor-parallel traffic in a strong scale-up domain; measure data-parallel overlap</td></tr><tr><th scope="row">Small-batch dense decode</th><td>Weight/KV movement, launch latency</td><td>Compare quantized local residency, weight reuse and the cost of another tensor-parallel rank</td></tr><tr><th scope="row">MoE with many experts</th><td>Total expert residency, dispatch imbalance, all-to-all traffic</td><td>Profile tokens per expert and network path; active parameters alone are insufficient</td></tr><tr><th scope="row">Long prompt, short answer</th><td>Prefill attention and first-token delay</td><td>Compare chunked prefill to a separate prefill pool, including KV transfer</td></tr><tr><th scope="row">Long answer, strict inter-token delay</th><td>Decode scheduling and interference</td><td>Measure a dedicated decode pool and its admission limits</td></tr><tr><th scope="row">Local assistant</th><td>Available memory, power, sustained thermal envelope</td><td>Measure warm and sustained runs with realistic context and other applications</td></tr></tbody></table></div>
<p>Gaudi integrates Ethernet ports; a TPU pod uses its inter-chip interconnect (ICI); Trainium uses NeuronLink; NVIDIA scale-up systems use NVLink and switches. Those links do not remove serialization, queueing or topology. A 24-port headline is not 24 independent full-rate routes to every peer. A multi-chip address space does not make a remote byte as cheap as a local SRAM byte.</p>${ref("https://www.intel.com/content/www/us/en/newsroom/news/next-generation-ai-solutions-xeon-6-gaudi-3.html", "Intel: Gaudi 3 compute, HBM and integrated Ethernet")}${ref(tpu,"Google: TPU ICI and datacenter-network scope")}${ref(trn3,"AWS: NeuronLink-v4 device interconnect")}
<p>Eight devices with 192 GiB each contain 1,536 GiB aggregate. If a serving process replicates 40 GiB of common weights on each, that replication consumes 320 GiB, leaving 1,216 GiB before runtime buffers and KV state. Tensor or expert sharding can change which bytes replicate; it introduces communication and ownership requirements. A sum of capacities is the start of a placement proof, not its conclusion.</p>
</section>
<section class="lesson" id="accelerator-portability-lab" data-lesson="Porting an operation"><header><span>Practical lab</span><h3>Carry the numerical contract across the compiler boundary</h3></header>
<p>Continue in <a href="#portable-kernels">Programming across accelerators</a> for the interactive execution comparison and worked <a href="#h100-kernel-example">H100</a>, <a href="#mi300x-kernel-example">MI300X</a>, <a href="#tpu-kernel-example">TPU</a> and <a href="#trainium-kernel-example">Trainium</a> examples.</p>
<p>Use one operation from the CUDA chapter—matrix multiplication or row-wise normalization—and write down shapes, layouts, dtypes, accumulation, masks and error tolerances before choosing a second backend. Build a CPU reference, exercise non-tile-aligned sizes, then inspect the compiled memory and kernel timeline. Correctness and supported shapes are independent of the framework accepting the graph.</p>
<div class="lesson-code"><div><h4>A portable experiment record</h4></div><pre><code>${escapeCode(`operation: row_norm
shape_cases: [[7, 33], [128, 1024], [513, 4097]]
input_dtype: float32
accumulation_dtype: float32
reference: explicit mean and population variance
special_cases: constant_rows, large_offset_small_variance
report:
  - max_absolute_error
  - max_relative_error_on_nonzero_reference
  - warm_device_time_excluding_compilation
  - end_to_end_time_including_transfers
  - scratch_memory_and_launch_count
  - device_compiler_runtime_versions`)}</code></pre></div>
<p>On TPU, start with JAX/Pallas and inspect HBM-to-VMEM movement. On Trainium, inspect NKI tiles, SBUF/PSUM use and engine dependencies. On AMD, use HIP or the supported Triton path and inspect wavefront assumptions. These are distinct labs, not a promise that a CUDA binary executes on each device. For TPU7x specifically, the current Cloud documentation supports JAX and PyTorch and explicitly excludes TensorFlow; older TPU examples in this almanac do not establish Ironwood compatibility.</p>${ref("https://docs.jax.dev/en/latest/pallas/tpu/quickstart.html", "Pallas: current TPU kernel quickstart")}${ref(tpu,"TPU7x: current framework support boundary")}
${check("Completion check: what evidence makes a port complete?", "The same declared operation passes adversarial numerical cases on the actual target; the compiled path uses supported operators without an unexpected fallback; device and end-to-end timing boundaries are explicit; peak memory and synchronization are measured; versions and a reproducible command are recorded. This atlas provides the reasoning and reference contract; a target-device run remains necessary.")}
</section>`);
