import { chapterMarkup, sourceLink as ref, workedCheck as check, escapeCode } from "./lesson-template";
import decoderSource from "../examples/pytorch/tiny_decoder.py?raw";
import trainSource from "../examples/pytorch/train.py?raw";
import serverSource from "../examples/pytorch/serve.py?raw";
import profilerSource from "../examples/pytorch/profile_decode.py?raw";

const code = (title: string, source: string) => `<details class="manual-code-details"><summary>${title}</summary><pre><code>${escapeCode(source)}</code></pre></details>`;

export const capstoneChapter = chapterMarkup("end-to-end", "Build, train, verify, then serve",
  "A complete small model gives every abstraction a place to land. Run a CPU training experiment, prove cached decoding, inspect a trace, and carry the same contracts into GPU serving.", `
<section class="lesson" id="capstone-contract" data-lesson="The complete experiment"><header><span>Capstone</span><h3>One artifact connects the whole learning path</h3></header>
<p>The companion in <code>examples/pytorch</code> starts with original text and ends with an HTTP endpoint backed by trained parameters. Its purpose is to make each step inspectable: text encoding, a causal decoder, shifted targets, backward, AdamW, a checkpoint, cached generation and admission control. The code runs on CPU with no downloaded weights or corpus.</p>
<p>The byte vocabulary contains 256 IDs. The default model uses width 64, four heads, two blocks, learned absolute positions, pre-LayerNorm, a GELU feed-forward layer and tied token/output weights. The context allocation is 128 positions; training windows default to 32. Allocating more positions does not train them or establish long-context quality. The TensorFlow companion uses different architectural choices; compare its RoPE/RMSNorm/SwiGLU mechanisms after understanding this smaller path.</p>
<figure class="textbook-lab"><figcaption><span>Figure 1.1</span><strong>The artifact chain</strong><p>Each transition needs a check before the next stage uses its result.</p></figcaption><div class="manual-sequence"><div><strong>Corpus → batches</strong><span>Byte encoding, corpus hash, sampled window positions.</span></div><div><strong>Loss → update</strong><span>Causal logits, shifted labels, gradients, clipped AdamW step.</span></div><div><strong>State → checkpoint</strong><span>Weights, optimizer moments, sampler RNG and completed update.</span></div><div><strong>Checkpoint → service</strong><span>Cached-equivalent generation, bounded admission and measured output.</span></div></div><p class="figure-boundary">Local educational CPU system. Multi-host synchronization, production reliability and GPU throughput require separate validation.</p></figure>
<div class="lesson-code"><div><h4>Run the complete companion from the repository root</h4></div><pre><code>python3.12 -m venv .venv
.venv/bin/python -m pip install -r examples/pytorch/requirements.txt
.venv/bin/python -m unittest discover -s examples/pytorch -p 'test_*.py' -v
.venv/bin/python examples/pytorch/train.py --updates 100
.venv/bin/python examples/pytorch/train.py --updates 125 --resume
.venv/bin/python examples/pytorch/profile_decode.py
.venv/bin/python examples/pytorch/serve.py</code></pre></div>
<p>Use a native Python supported by the pinned PyTorch wheel. On Apple Silicon, an Intel/Rosetta interpreter can select the wrong platform. The local companion pins PyTorch 2.8.0 as a reproducible teaching environment; that version is not a claim about the newest framework release.</p>
</section>
<section class="lesson" id="capstone-forward" data-lesson="Training, validation and generation"><header><span>Model implementation</span><h3>Use the same model to learn, measure and generate</h3></header>
<p>A forward pass takes token IDs and produces a score for every possible next token at every input position. What happens to those scores depends on the task. Training compares them with known answers and updates the weights. Validation measures those predictions on held-out text. Generation chooses a new token, appends it to the prompt and repeats with the weights fixed.</p>
<div class="method-table"><table><caption>Three uses of the same decoder</caption><thead><tr><th scope="col">Task</th><th scope="col">Next token comes from</th><th scope="col">Work after the forward pass</th></tr></thead><tbody><tr><th scope="row">Training</th><td>The recorded training sequence</td><td>Loss → backward → optimizer update</td></tr><tr><th scope="row">Validation loss</th><td>The held-out sequence</td><td>Accumulate loss; leave weights fixed</td></tr><tr><th scope="row">Generation</th><td>The model's scores and a selection rule</td><td>Append the chosen ID; run the next step</td></tr></tbody></table></div>
<p>With five recorded tokens, training creates four input/target pairs in one causal forward pass. With a four-token prompt, generating three new tokens takes one four-position <strong>prefill</strong> and two one-position <strong>decode</strong> calls when caching is enabled. Prefill's final scores already select the first output token. Each later call consumes the previous output and selects the next one. This sequential dependency explains why a training batch and a serving batch behave differently.</p>
<p>In PyTorch, <code>model.train()</code> and <code>model.eval()</code> control module behavior such as dropout; they do not perform training or disable gradients. Use <code>eval()</code> together with <code>no_grad()</code> or <code>inference_mode()</code> for forward-only evaluation. An optimizer step changes the weights. This decoder has no dropout or batch normalization, but keeping the distinction explicit prevents mistakes when extending it.</p>
${ref("https://docs.pytorch.org/docs/2.8/notes/autograd.html#locally-disabling-gradient-computation", "PyTorch 2.8: evaluation mode and gradient recording are separate controls")}
<details class="deep-dive"><summary>Work through every tensor shape</summary>
<p>Read a shape as a list of axis lengths. Here B counts sequences, T counts input positions in this call, D is the feature width, H is the number of attention heads, V is vocabulary size, and S counts all retained cache positions. Two four-token inputs have shape <code>[2,4]</code>; with D=64 their embeddings have shape <code>[2,4,64]</code>, containing 512 feature values. Their output scores have shape <code>[2,4,256]</code>.</p>
<p>Input IDs are [B,T]. Embedding and position lookup produce [B,T,D]. A fused QKV linear projection produces [B,T,3D]; splitting and exposing heads yields three arrays of [B,H,T,D/H]. Attention scores are [B,H,T,T] without a cache. Their masked softmax mixes values, and the heads are reassembled into [B,T,D]. The residual addition preserves that shape.</p>
<p>Each block normalizes before attention and before its MLP. The MLP expands width from D to 4D, applies GELU, and projects back. The final normalization feeds the tied vocabulary projection: [B,T,D] × [D,V] gives [B,T,V]. The returned cache contains one key/value pair per layer, each [B,H,S,D/H]. Autodiff records the training computation; inference mode skips gradient recording during generation.</p>
<p>The explicit attention implementation materializes its score matrix. That makes the causal mask easy to inspect but is not memory-efficient for long sequences. Once the correctness contract passes, replace it with an appropriate scaled-dot-product-attention backend and compare outputs and gradients across shapes and dtypes. Backend dispatch is a software/hardware decision; a high-level function name does not prove which kernel ran.</p>
${ref("https://docs.pytorch.org/docs/2.8/generated/torch.nn.functional.scaled_dot_product_attention.html", "PyTorch 2.8: attention semantics, masks and backends")}
</details>
${code("Read the complete decoder, including the cached-position mask", decoderSource)}
${check("You call model.eval(), compute a loss and call backward(). Have gradients been disabled?", "No. eval() changes training-sensitive module behavior. Without a no-grad context, operations involving trainable parameters can still build a graph and backward() can compute gradients. No optimizer update should run during validation or generation.")}
${check("Why does a one-token cached query need its absolute position?", "Its local query index is zero but its prefix may contain many earlier positions. The mask must permit every key at or before the absolute query position. A top-left one-row triangular mask would incorrectly leave only the first key visible.")}
</section>
<section class="lesson" id="capstone-training" data-lesson="Training and validation checks"><header><span>Training experiment</span><h3>A falling loss is the first diagnostic, not the last result</h3></header>
<p>A window has T+1 byte IDs. Feed the first T and use the last T as labels; each input position predicts the immediately following byte. This example uses equal-length fully valid windows, so a mean over B×T labels is the declared objective. Packed conversations, padding and unequal worker token counts require the masking and normalization rules developed in the training chapters.</p>
<p>Each update clears previous gradients, computes the loss, runs backward, clips the combined gradient norm, and applies AdamW. Clipping occurs after the complete gradient is available. The checkpoint records a completed update, so there is no partially accumulated microbatch state to reconstruct. The implementation seeds both initialization and the sampling generator, and rejects a changed corpus or training configuration on resume.</p>
<p>Before a large experiment, overfit a tiny debugging corpus. If a small model cannot reduce that loss, inspect labels, masking, gradients and optimizer updates. Then introduce a document-disjoint validation set: do not split neighboring overlapping windows from the same documents and call that independent evaluation. Remove duplicates across splits, fix the validation procedure, and reserve a final test set for decisions made after tuning.</p>
<p>The included repetitive text is a mechanics test and has no built-in held-out split. Its loss curve cannot establish general language modeling quality. For a real data experiment, use <code>--text train.txt</code>, pass <code>--validation-text validation.txt</code> for deterministic token-weighted evaluation over independent windows, and report per-token loss, tokenization, token count and sampling strategy. Training longer on this toy corpus cannot establish frontier reasoning ability.</p>
${code("Read the training loop and checkpoint contract", trainSource)}
${ref("https://docs.pytorch.org/tutorials/beginner/saving_loading_models.html", "PyTorch: model state and optimizer checkpointing")}
${check("The uninterrupted and resumed runs have the same loss but different optimizer moments. Is restart correct?", "No. Equal loss at one instant does not establish the same future update. Compare parameters, optimizer state, data position and random-number state at the same completed update. The companion test compares the tensors exactly on the same CPU environment.")}
</section>
<section class="lesson" id="capstone-cache" data-lesson="Cache correctness and memory"><header><span>Inference correctness</span><h3>The cache must change the work without changing the answer</h3></header>
<p>Run a full sequence and save every logit. Then process a prefix and feed the remaining tokens in differently sized chunks while appending K and V. Concatenating those chunk logits should match the full pass within declared tolerances. This catches an incorrect causal offset that an ordinary “generation returns text” smoke test can miss. The companion also compares greedy generated IDs with and without the cache.</p>
<p>Dense attention KV payload is <code>2×L×B×S×Hkv×Dh×s</code> bytes: two tensors, L layers, B sequences, S retained positions, Hkv key/value heads, Dh head width and s bytes per stored element. Use KV heads for GQA, not query heads. Allocator blocks, quantization scales, padding, replication and temporary buffers are additional terms.</p>
<div class="derivation"><h4>Two different scales</h4><p>The toy model at B=1, S=128, L=2, Hkv=4, Dh=16 and FP32 uses 131,072 KV payload bytes, or 128 KiB. A separate illustrative decoder with 32 layers, eight KV heads, head width 128, 8,192 positions and BF16 uses exactly 1 GiB per sequence. Four such sequences need 4 GiB of payload before allocator overhead.</p></div>
<p>The companion appends using <code>torch.cat</code>; that reallocates and copies growing tensors. Production systems preallocate or page storage and maintain explicit ownership and sequence lengths. Replacing a copy-heavy cache with a better allocator is valuable only if cached outputs remain correct and request completion/cancellation releases the right blocks.</p>
${check("Can you remove the oldest KV entry and leave learned absolute position indices unchanged without further thought?", "No. Eviction changes which history is visible, and the position scheme imposes its own contract. This example rejects context overflow rather than pretending a sliding window preserves the trained full-context computation. Windowed or rotary-position serving needs a separately specified and tested policy.")}
${ref("https://arxiv.org/abs/2309.06180", "PagedAttention: virtual-memory-inspired KV management")}
</section>
<section class="lesson" id="capstone-profile" data-lesson="Profiling and equal-work comparisons"><header><span>Performance evidence</span><h3>Measure the implementation you actually ran</h3></header>
<p>The profiler companion first asserts identical greedy output IDs, warms each path, and records seven whole-generation CPU timings. It reports the median and range for the same prompt length, output count and one-thread configuration. A separate profiling pass exports operator shapes and memory activity to a Chrome-compatible trace. Profiling overhead is excluded from the reported timing loop.</p>
<p>Read the trace from the outside inward. Locate the generation interval, repeated decoder calls, matrix multiplications, softmax, normalization and concatenations. The uncached path recomputes more prefix work; the cached path can still spend substantial time in small operators and copying. A tiny CPU model may not display the same bottleneck as a large GPU model.</p>
${code("Read the timing and trace exporter", profilerSource)}
<p>For GPU work, use appropriate device events or synchronization and separately measure host launch behavior. Inspect the CUDA kernel with Nsight Compute for memory transactions and instruction behavior, then the system with Nsight Systems for overlap and CPU gaps. Compare useful tokens per second at equal output semantics and quality; a different precision or decoding policy is a different experiment unless that difference is explicitly evaluated.</p>
${ref("https://docs.pytorch.org/tutorials/recipes/recipes/profiler_recipe.html", "PyTorch: operator profiling and trace export")}
${check("A kernel improves by 2× and originally occupied 20% of wall time. What is the maximum overall speedup if everything else stays fixed?", "The normalized new time is 0.8+0.2/2=0.9, so speedup is 1/0.9≈1.11×. The optimization saves 10% of total time. Overlap and shifted bottlenecks can change the real result, which is why the system interval must also be measured.")}
</section>
<section class="lesson" id="capstone-http" data-lesson="Serving over HTTP"><header><span>Service boundary</span><h3>Request handling adds state beyond the neural network</h3></header>
<p>The local server loads the checkpoint once, validates byte-length/context constraints, admits one generation, and returns the generated byte IDs plus decoded text. It rejects another generation with HTTP 503 while the worker is busy. That explicit capacity limit makes overload visible; production systems often queue, batch, prioritize and cancel work instead.</p>
<div class="lesson-code"><div><h4>Send a real request in another terminal</h4></div><pre><code>curl http://127.0.0.1:8091/health
curl http://127.0.0.1:8091/generate \\
  -H 'Content-Type: application/json' \\
  -d '{"prompt":"A token ","max_new_tokens":32}'</code></pre></div>
<p>The response reports whole generation time inside the worker. It is not streamed time to first token: the JSON arrives after generation finishes. UTF-8 decoding uses replacement for invalid generated byte sequences and also returns raw IDs so that rendering cannot hide what the model produced. A byte token and a subword token are different units; compare token throughput only with the tokenizer specified.</p>
${code("Read the complete bounded local server", serverSource)}
<p>To evolve this into a serving engine, separate request metadata from batch membership; preserve per-sequence positions and KV ownership; perform prefill and decode under a token budget; release blocks on completion, cancellation and error; and test prefix sharing with copy-on-write. Then add streaming, bounded queues, deadlines, observability and graceful shutdown. Each step must preserve the already-tested model semantics.</p>
</section>
<section class="lesson" id="capstone-vllm" data-lesson="GPU serving with vLLM"><header><span>GPU deployment lab</span><h3>Use a supported checkpoint and pin the engine</h3></header>
<p>The <a href="#framework-model-artifacts">framework comparison</a> explains the loader and architecture contracts behind this handoff. Keep this exercise's pinned engine version together with its commands; newer engine interfaces are documented separately in that chapter.</p>
<p>The custom byte decoder is not a vLLM checkpoint format. This second lab uses a supported public OPT checkpoint to learn an actual GPU engine’s lifecycle. Porting a custom architecture requires configuration/tokenizer metadata, weight-name mapping, implementation support and numerical equivalence checks; renaming a .pt file does not perform that conversion.</p>
<div class="lesson-code"><div><h4>Documented vLLM 0.12.0 exercise on a compatible NVIDIA Linux host</h4></div><pre><code>docker run --rm --gpus all --ipc=host \\
  -p 127.0.0.1:8000:8000 vllm/vllm-openai:v0.12.0 \\
  --model facebook/opt-125m --max-model-len 512 \\
  --generation-config vllm

curl http://127.0.0.1:8000/v1/completions \\
  -H 'Content-Type: application/json' \\
  -d '{"model":"facebook/opt-125m","prompt":"A tensor is", "max_tokens":32,"temperature":0}'</code></pre></div>
<p>This is a pinned instructional command, not a recommendation that 0.12.0 is the latest release. Check that release’s supported hardware and host-driver requirements. The image and model must be downloaded; hardware execution is a separate lab from the local CPU companion. OPT is used for a simple completion endpoint, not as a frontier model or a chat-tuned system.</p>
<p>In a matching vLLM environment, inspect <code>vllm bench serve --help</code>, then sweep request rates with a declared prompt/output distribution. Record request-level TTFT, time per output token, total latency, completion/error counts and goodput under specified service objectives. Keep warmup, cached prefixes and output-length behavior consistent across runs. A concurrency cap can make offered rate differ from actual launched rate; report both.</p>
<div class="lesson-code"><div><h4>One point in a load sweep using the same release</h4></div><pre><code>vllm bench serve --backend vllm --model facebook/opt-125m \\
  --base-url http://127.0.0.1:8000 --endpoint /v1/completions \\
  --dataset-name random --random-input-len 128 \\
  --random-output-len 64 --num-prompts 200 --request-rate 2 \\
  --goodput ttft:200 tpot:50 --percentile-metrics ttft,tpot,itl,e2el --save-result</code></pre></div>
<p>A synthetic load sweep diagnoses a system, not model quality. Add representative documents and conversations for capacity decisions. Record model and tokenizer revisions, engine/container version, GPU SKU and count, memory headroom, parallelism, dtype, cache policy, prompt distribution and exact sampling controls. Optimize one variable at a time, then re-run correctness and quality checks before accepting a faster configuration.</p>
${ref("https://docs.vllm.ai/en/v0.12.0/deployment/docker/", "vLLM 0.12.0: official Docker deployment")}
${ref("https://docs.vllm.ai/en/v0.12.0/serving/openai_compatible_server/", "vLLM 0.12.0: compatible completion endpoint")}
${ref("https://docs.vllm.ai/en/v0.12.0/cli/bench/serve/", "vLLM 0.12.0: benchmark arguments and goodput")}
</section>
<section class="lesson" id="capstone-assessment" data-lesson="Final engineering assessment"><header><span>Engineering assessment</span><h3>Finish with a result another person can reproduce</h3></header>
<div class="method-table"><table><caption>A cumulative project rubric</caption><thead><tr><th>Artifact</th><th>Passing evidence</th><th>Failure that the check should catch</th></tr></thead><tbody><tr><th>Training run</th><td>Exact config/data hash; loss curve; finite gradients; held-out evaluation for quality claims</td><td>Leaked validation data or a shifted-label bug</td></tr><tr><th>Restart</th><td>Same completed update, parameters, optimizer and random state after interruption</td><td>Restoring weights but resetting Adam moments</td></tr><tr><th>Kernel</th><td>Reference comparisons over tails and dtypes; sanitizer results; measured trace</td><td>Out-of-bounds loads, divergent barriers or wrong reduction</td></tr><tr><th>RTL</th><td>Self-checking simulation, stalled-output stability, synthesis and timing reports</td><td>A dropped transaction or negative setup slack</td></tr><tr><th>Inference</th><td>Full/cached logit equivalence; state reclamation on cancellation</td><td>Wrong position offset or leaked KV blocks</td></tr><tr><th>Serving</th><td>Equal-quality load sweep with latency tails, errors and goodput</td><td>Throughput gains bought by rejected work or excessive latency</td></tr><tr><th>Frontier comparison</th><td>Versioned primary sources and an explicit apples-to-apples baseline</td><td>Per-rack bandwidth compared with per-chip bandwidth</td></tr></tbody></table></div>
<p>For the final write-up, choose one bottleneck and explain its causal chain: what state existed, which bytes moved, what resource limited progress, what changed, and what measurement confirmed the effect. Include the unsuccessful hypothesis if its rejection explains the final choice. Separate tests performed on this machine from commands still needing a GPU, board or cluster.</p>
${check("Final oral check: why is a faster GEMM not enough to guarantee a faster LLM service?", "The service also performs attention, normalization, sampling, memory allocation, communication and scheduling; it handles queues and variable request lengths. The optimized GEMM must lie on the critical path, preserve numerics/quality, and leave enough memory and latency headroom. Confirm the result with an equal-work, equal-quality end-to-end load test.")}
</section>`);
