import { chapterMarkup, sourceLink as ref, workedCheck as check, escapeCode } from "./lesson-template";

const intel = 'https://www.intel.com/content/www/us/en/developer/articles/technical/intel64-and-ia32-architectures-optimization.html';
const arm = 'https://learn.arm.com/learning-paths/servers-and-cloud-computing/profiling-for-neoverse/additional-resources/';
const amd = 'https://www.amd.com/content/dam/amd/en/documents/epyc-technical-docs/tuning-guides/58026-epyc-9004-tg-fsi.pdf';
const vector = 'https://llvm.org/docs/Vectorizers.html';
const numa = 'https://docs.kernel.org/admin-guide/mm/numa_memory_policy.html';
const lesson = (id: string, title: string, body: string) => `<section class="lesson" id="${id}" data-lesson="${title}"><header><span>CPU architecture</span><h3>${title}</h3></header>${body}</section>`;
const code = (title: string, text: string) => `<details class="deep-dive"><summary>${title}</summary><pre><code>${escapeCode(text)}</code></pre></details>`;
const lab = (id: string, title: string, controls: string, boundary: string) => `<figure class="textbook-lab cpu-workbench" id="${id}"><figcaption><span>Interactive teaching model</span><strong>${title}</strong><p>${boundary}</p></figcaption><div class="method-toolbar">${controls}</div><div class="cpu-lab-readout" data-cpu-result aria-live="polite"></div><div class="cpu-lab-surface" data-cpu-drawing tabindex="0" role="region" aria-label="${title}; scroll horizontally if needed"></div><details class="cpu-lab-ledger"><summary>Read the exact trace</summary><div class="method-table" data-cpu-ledger tabindex="0"></div></details></figure>`;

export const cpuChapter = chapterMarkup('cpu', 'Inside a CPU', 'Follow a program from instructions and dependencies to caches, cores and memory controllers. Work through small machines, then connect them to C code and a real profiling experiment.', `
${lesson('cpu-instructions', 'An instruction set is a contract; a core is an implementation', `
<p>A CPU executes a program’s instructions while preserving a defined view of registers, memory and control flow. The <strong>instruction set architecture (ISA)</strong> specifies that view: which operations exist, their operands, exceptions and observable effects. The <strong>microarchitecture</strong> is the machinery that implements it. Two processors can run the same binary and still have different execution widths, cache sizes, branch predictors and performance.</p>
<p>Start with <code>y[i] = x[i] + 1</code>. The machine needs the address of x[i], a load of its value, an addition, the destination address and a store. A register is a named place for an immediate operand or result; it is not the same thing as a variable in your source. The compiler may keep a variable in a register, remove it, combine its work with another expression, or spill it to memory. Loop bookkeeping adds address updates, a comparison and a decision about the next iteration.</p>
${code('Read a load, an add and a store in RISC-V assembly', `# RV32I example: a0 points to x[i], a1 points to y[i].
# Aligned 32-bit integers; modulo-2^32 addition, not signed C overflow.
lw   t0, 0(a0)       # memory -> register
addi t0, t0, 1       # register -> register
sw   t0, 0(a1)       # register -> memory
# Address updates and the loop branch are omitted here.`)}
<p>RISC-V and AArch64 separate ordinary arithmetic from loads and stores. x86 also permits memory operands in many arithmetic instructions. Neither encoding style tells you how many internal operations a particular core will issue, or how long the program will take. Front ends can split instructions into internal operations, combine some patterns, and reuse decoded work. “One instruction” is therefore not a universal unit of useful computation.</p>
<p>Use three names when reading a specification: the ISA, the particular core design, and the complete processor/system. Arm Neoverse is a family of core designs used in server implementations; Intel and AMD both build x86 implementations. A system adds memory channels, interconnects, I/O and operating-system policy. “Arm versus x86” alone is too broad to predict your workload.</p>
${check('Does a 4 GHz CPU finish four billion loop iterations per second?', 'No. Frequency counts cycles per second. An iteration can require several instructions, instructions can overlap, and dependencies or memory can stall progress. At an average 8 cycles per iteration, 4 GHz would imply 500 million iterations/s before other limits; the 8 is a declared assumption, not an ISA property.')}
${ref('https://docs.riscv.org/reference/isa/v20240411/unpriv/rv32.html', 'RISC-V RV32I specification · registers, loads and stores')}
`)}
<div data-cpu-overview></div>
${lesson('cpu-dependencies', 'Execute ready work, then retire in program order', `
<p>An instruction has <strong>latency</strong>: the time from starting it until a dependent instruction can use its result. An execution unit also has a <strong>throughput</strong>: how frequently it can accept new work. A pipelined multiplier might accept an independent operation every cycle even if each result takes several cycles. These are different limits. A chain <code>s = s + x[i]</code> repeatedly needs the previous s; independent accumulators can expose more work, subject to the language’s numerical rules.</p>
<p>An out-of-order core tracks operand readiness and available resources. When an old load waits, a younger addition with ready inputs may execute. A <strong>reorder buffer</strong> tracks instructions until they can retire in program order. Retirement establishes the architectural result and supports precise exceptions: if an older instruction faults, younger speculative results must not become committed program state. A retired store can still be waiting to drain from a store buffer; retirement and visibility to another core are not synonyms.</p>
<p><strong>Register renaming</strong> separates a name from its current physical storage. In <code>r1 = load A; r2 = r1 + 1; r1 = B + C</code>, the last write to the name r1 need not wait for r2 to consume the earlier r1 if the two versions have different physical registers. The true dependency from the load to r2 remains. Renaming removes name conflicts, not the need for a value.</p>
${lab('cpu-issue-lab', 'Let an independent chain pass a waiting load', '<label>Issue policy<select data-cpu-issue-mode><option value="ready">Oldest ready operation</option><option value="ordered">Program order only</option></select></label><button data-cpu-issue-next>Advance one cycle</button><button data-cpu-issue-reset>Reset</button>', 'Six already-dispatched operations. One fully pipelined load issue and one ALU issue per cycle; loads take six cycles and ALU operations one. Retire at most two in order before issuing at each cycle boundary. Unlimited window, no cache, branch or front-end stalls. This isolates scheduling, not an Intel, AMD or Arm core.')}
<p>Read the rows as program order and the columns as cycle boundaries. Blue marks execution; a completed operation can wait for older work to retire. “Oldest ready” changes issue order, while retirement remains ordered. Toggle the policy with the same operation latencies to identify the independent work that covers the first load. Real hardware has bounded queues, more resource constraints and memory dependencies that this model omits.</p>
${check('Four dependent additions have latency 3 cycles each. Does a unit accepting one addition per cycle finish the chain in 4 cycles?', 'No. With the first addition starting at cycle 0, results become available at 3, 6, 9 and 12. Four independent additions could start at 0, 1, 2 and 3 on a unit with that issue rate, finishing at 3, 4, 5 and 6. This comparison assumes no other bottleneck.')}
${ref(intel, 'Intel optimization manuals · dependencies, scheduling and retirement')}
`)}
${lesson('cpu-branches', 'Prediction keeps the front end supplied', `
<p>A conditional branch chooses the next instruction address using a condition that may not be ready yet. Waiting for every condition would interrupt fetching. A branch predictor guesses a direction, while target prediction helps choose where to fetch. The core executes speculatively and checks the prediction when the branch resolves. A wrong path is discarded and fetching redirects. Cache and predictor effects may survive that discard even though wrong-path architectural results do not retire.</p>
<p>Predictability depends on history, not merely on the percentage of taken branches. A long run of taken outcomes followed by a rare exit differs from alternating outcomes. Modern predictors use richer histories and multiple structures. The small counter below deliberately forgets that history so you can see exactly what one state machine can and cannot learn.</p>
${lab('cpu-branch-lab', 'Train a two-bit predictor on one branch', '<label>Outcomes<select data-cpu-branch-pattern><option value="loop">Seven taken, then exit</option><option value="alternating">Taken / not taken</option><option value="phases">Eight taken, eight not taken</option></select></label><button data-cpu-branch-next>Resolve next branch</button><button data-cpu-branch-reset>Reset</button>', 'One saturating counter for one branch, initially weakly not taken (state 1). States 0/1 predict not taken; 2/3 predict taken. Resolve first, then move one state toward the outcome. No global history, address aliasing, target prediction or measured recovery penalty.')}
<p>A strong state needs two opposite outcomes to reverse its prediction. That inertia helps tolerate an isolated loop exit. Starting weakly not taken, the alternating sequence keeps this simple counter predicting the previous direction and misses every time. That is a counterexample for <em>this predictor</em>, not evidence that a modern CPU cannot learn alternation.</p>
<p>Replacing a branch with a conditional move or mask can reduce wrong-path work, but it may also compute both sides, lengthen a dependency chain or perform extra memory accesses. Inspect the emitted code: the compiler may already have removed the branch. Measure the realistic distribution of inputs and the complete operation, rather than assuming “branchless” always means faster.</p>
${check('With 20% branches, 5% mispredictions and an assumed 15-cycle recovery, what simple CPI cost is implied?', '0.20 × 0.05 × 15 = 0.15 added cycles per instruction in an additive model. With base CPI 0.5, that gives 0.65. Actual overlap, wrong-path work and recovery vary; this arithmetic is a budget, not a processor measurement.')}
${ref(arm, 'Arm Neoverse optimization and PMU guides · branch analysis')}
`)}
${lesson('cpu-caches', 'A cache stores lines, and each line has a place', `
<p>A load names bytes, but a cache normally fetches a <strong>cache line</strong>: an aligned block containing neighboring bytes. With an assumed 64-byte line, sixteen adjacent four-byte integers occupy one line. Reading the first can bring the other fifteen close to the core. This is spatial locality. Reusing a line before it is evicted is temporal locality. An array scan uses these opportunities differently from following pointers whose next address depends on the previous load.</p>
<p>A set-associative cache splits its storage into sets. An address selects one set; its line can occupy one of that set’s ways. A tag distinguishes different memory lines mapped to the same set. In a simplified physically indexed cache with S sets and 64-byte lines, <code>line = floor(address / 64)</code>, <code>set = line mod S</code>, and <code>tag = floor(line / S)</code>. Real caches may use virtual index bits, physical tags, hashing and implementation-specific replacement.</p>
${lab('cpu-cache-lab', 'Keep capacity fixed; change locality and associativity', '<label>Access pattern<select data-cpu-cache-pattern><option value="sequential">16 neighboring integers</option><option value="conflict">Alternate bytes 0 and 256</option><option value="capacity">Cycle through five lines</option></select></label><label>Ways<select data-cpu-cache-ways><option value="1">1 · direct mapped</option><option value="2">2 ways</option><option value="4">4 · fully associative</option></select></label><button data-cpu-cache-next>Read next address</button><button data-cpu-cache-reset>Reset</button>', 'Cold, read-only 256-byte cache: four 64-byte lines total. Exact least-recently-used replacement within each set. Reads allocate a line. No prefetching, writes, translation or lower caches. Bytes fetched count this modeled cache boundary, not DRAM traffic.')}
<p>The neighboring-integer trace has one cold miss and fifteen hits. Alternating addresses 0 and 256 produces twelve misses in the direct-mapped cache: both lines need set 0. Two ways hold both after their first misses, without increasing total capacity. Cycling over five lines still exceeds the fully associative four-line cache; every revisit misses under LRU. More associativity cannot create capacity.</p>
<p>Compulsory, conflict and capacity misses describe different explanations for misses relative to a chosen cache model. Coherence can also invalidate a line. A lower cache may satisfy an upper-cache miss without any DRAM read. Avoid adding all cache-miss counters as if they measured independent transfers at the same boundary.</p>
${check('Byte address 260 enters the two-way version. What are its line, set, tag and offset?', 'There are two sets. Line = floor(260/64) = 4; set = 4 mod 2 = 0; tag = floor(4/2) = 2; byte offset = 260 mod 64 = 4. The set chooses the candidate ways; the tag and valid state determine a hit.')}
${ref(intel, 'Intel optimization manuals · cache locality and memory access')}
`)}
${lesson('cpu-translation', 'A TLB miss, a cache miss and a page fault are different events', `
<p>A process normally uses virtual addresses. The memory-management unit translates a virtual page number to a physical page number and checks permissions. A <strong>translation lookaside buffer (TLB)</strong> caches recent translations. It does not hold the array’s values. A data cache holds memory lines. The lookup and translation paths can overlap in some cache organizations; a teaching diagram should not imply that every processor performs them as a strictly serial pair.</p>
<p>On a TLB miss, a hardware page-table walker on many server CPUs reads the relevant page-table entries. Those reads can themselves hit or miss caches. If the mapping is valid and permitted, execution can continue without entering the operating system. A <strong>page fault</strong> is different: translation or permissions require fault handling. It may allocate a zero-filled page, resolve copy-on-write, fetch missing data or reject an invalid access. It does not necessarily mean disk I/O.</p>
<p>For an illustrative 4 KiB page, virtual address <code>0x1234</code> has virtual page number 1 and offset <code>0x234</code> (564 bytes). If its page maps to physical frame <code>0xABC</code>, the physical address is <code>0xABC234</code>. The offset stays the same. Moving the page changes the frame mapping, while the process may continue using the same virtual address.</p>
<p>A TLB with 64 usable entries for 4 KiB pages would cover 256 KiB if each entry mapped a distinct page. That is <em>translation reach</em>, not data-cache capacity. Larger pages can increase reach but affect allocation, fragmentation and placement. Page sizes and TLB structures are platform-specific; inspect the target system rather than assuming every CPU uses 4 KiB pages.</p>
${check('The process takes a page fault during its first write after malloc. Does that prove the working set exceeded RAM?', 'No. The allocation can reserve virtual address space before all anonymous pages are physically backed. A first write can fault to allocate a page. Check the kind of fault and the memory policy; a minor first-touch fault is not evidence of swapping.')}
${ref('https://www.kernel.org/doc/html/latest/admin-guide/mm/concepts.html', 'Linux memory-management concepts · pages, faults and page tables')}
`)}
${lesson('cpu-load-store', 'Memory ordering is part of correctness', `
<p>The load/store unit calculates addresses and tracks memory operations. A store buffer can retain a store while execution continues. A later load by the same thread may receive a matching older store’s value through store-to-load forwarding. Unknown addresses, partial overlaps and ordering rules complicate that decision. Issuing a load early is not permission to return a value forbidden by the ISA or language model.</p>
<p><strong>Coherence</strong> coordinates copies of a memory location or cache line. <strong>Consistency and memory ordering</strong> constrain how operations across locations become observable. Coherent caches alone do not make a “write data, then set flag” protocol correct. The compiler can also transform a program under the language rules. In C and C++, an unsynchronized conflicting access to an ordinary object can be a data race with undefined behavior.</p>
<p>The following is a one-shot publication protocol. The publisher writes ordinary data before a release store. The consumer only reads that data after an acquire load observes the published flag. That synchronization makes the earlier data write visible according to the language memory model. This example has one publisher, one consumer, no later modification and a flag initialized before either thread starts. A repeatedly reused queue needs a fuller ownership protocol.</p>
${code('C11: publish one immutable value', `#include <stdatomic.h>
static int payload;
static atomic_int ready = 0;

void publish(void) {
    payload = 42;
    atomic_store_explicit(&ready, 1, memory_order_release);
}
int consume(void) {
    while (!atomic_load_explicit(&ready, memory_order_acquire)) {
        /* Teaching spin only; production waiting policy depends on latency. */
    }
    return payload;
}`)}
<p><code>volatile</code> is not a substitute for atomics or a mutex. A relaxed atomic operation is still atomic, but does not by itself establish the publication ordering above. Prefer an ordinary mutex or a tested concurrent structure when its cost is acceptable; weakening ordering requires a complete correctness argument, not merely a benchmark that happened to pass.</p>
${check('Can two cores safely increment the same ordinary integer because each integer write fits in a register?', 'No. An increment is a read-modify-write operation, and concurrent unsynchronized accesses can also violate the language memory model. Use suitable synchronization. Two threads each owning a distinct counter avoid that data race, but may still suffer false sharing if their counters occupy the same cache line.')}
${ref('https://llvm.org/docs/Atomics.html', 'LLVM atomic instructions and concurrency guide · ordering guarantees')}
`)}
${lesson('cpu-simd', 'Vectorize independent work and preserve its numerical contract', `
<p><strong>SIMD</strong> applies an instruction to multiple lanes. A 256-bit vector can hold eight 32-bit values; a vector add computes eight additions when all those lanes are useful. A multiply-add counts as two floating-point operations per active lane by the usual FLOP convention. These counts describe work per instruction, not sustained throughput: loads, stores, execution ports, frequency and dependency chains still matter.</p>
<p>Loop vectorization groups iterations; straight-line vectorization can group similar independent operations already present in a basic block. Compilers need to prove that grouping preserves behavior, or generate runtime checks and choose between versions. Possible pointer overlap, unsupported operations, control flow and short trip counts can limit the gain. A reduction also requires combining partial results.</p>
${code('An elementwise loop with a clear no-overlap contract', `#include <stddef.h>
void axpy(size_t n, float a,
          const float *restrict x, float *restrict y) {
    // For n accessed elements, x and y must not overlap.
    for (size_t i = 0; i < n; ++i)
        y[i] = a * x[i] + y[i];
}
// Clang: clang -O3 -Rpass=loop-vectorize -Rpass-missed=loop-vectorize \\
//             -Rpass-analysis=loop-vectorize -S kernel.c -o kernel.s`)}
<p><code>restrict</code> is a promise the caller must satisfy, not a request for an optional optimization. A vectorized loop may need a scalar or masked tail when n is not a multiple of its lane count. Misalignment may be supported by the ISA, but crossing cache-line or page boundaries can change the work. Contiguous structure-of-arrays layouts often help when a kernel uses one field from many records.</p>
<p>Intel and AMD x86 CPUs expose different subsets and costs for SSE/AVX-family instructions depending on the model. AArch64 has Advanced SIMD; some implementations support SVE/SVE2. RISC-V’s vector extension has its own length and mask model. Dispatch to supported code on the actual target. A vector register’s width does not directly tell you the execution unit’s physical width or the number of instructions it can sustain.</p>
<p>Reassociating floating-point sums can change rounding; fusing multiply and add can change it again. Decide whether you need bitwise equality, a tolerance or a more accurate accumulation algorithm before enabling aggressive floating-point transformations. The companion’s row/column sum uses small exact integer-valued doubles so its equality check does not accidentally test a different rounding order.</p>
${check('An eight-lane operation handles 19 elements. How many lanes carry useful work across three full-width groups?', '19 of 24 lane positions are useful: about 79.2%. A masked tail or scalar remainder handles the last three elements. This fraction does not include address generation, loads, stores or loop overhead and is not a speedup prediction.')}
${ref(vector, 'LLVM vectorization guide · legality, reductions, diagnostics and tails')}
`)}
${lesson('cpu-coherence', 'False sharing moves a line that the program did not mean to share', `
<p>Suppose thread A updates counter A and thread B updates counter B. Their variables are distinct and properly synchronized or privately owned. If both counters live in one cache line, writers can still compete for write ownership of that line. The coherence protocol works at a granularity larger than either variable. This is <strong>false sharing</strong>; true sharing occurs when the threads actually need the same data.</p>
<p>In a simplified invalidate-based protocol, a writer needs appropriate ownership before modifying its cached line. Other copies may be invalidated. A later writer on another core can require another ownership transfer. The data might come from another cache or a lower level: do not assume every transfer travels to DRAM. Exact protocol states, forwarding paths and inclusivity differ across implementations.</p>
<p>Padding can separate hot independently written fields, but it increases the memory footprint and can make read-mostly scans worse. A stronger design often keeps counters local for a batch and combines them less frequently. Alignment must apply to the allocation and to the array stride; adding bytes to a structure without checking its size and starting address is not a general proof that adjacent objects occupy different lines.</p>
<p>For a declared 64-byte line and an aligned array of eight 8-byte counters, all eight fit into one line. If each counter occupies its own aligned 64-byte slot, eight slots use 512 bytes. That trades space for less possible line sharing; it is not a promise of an eightfold speedup. The line size here is an explicit example, not a portable constant.</p>
${check('Two threads repeatedly read different words in the same cache line. Is that the harmful write-sharing pattern?', 'Not by itself. Shared read-only copies can coexist. Harmful false sharing requires sharing a coherence unit with at least one writer. Look for ownership traffic and the structure’s actual field offsets before adding padding.')}
${ref('https://docs.kernel.org/kernel-hacking/false-sharing.html', 'Linux false-sharing guide · layout, perf c2c and pahole')}
`)}
${lesson('cpu-cores-threads', 'A hardware thread is not another complete core', `
<p>A core includes front-end, scheduling and execution resources. <strong>Simultaneous multithreading (SMT)</strong> exposes multiple architectural execution contexts while sharing many of those resources. When one thread has no ready work, another may use otherwise idle capacity. When both demand the same saturated resource, they compete. Two logical CPUs reported by the OS can therefore be siblings on one core rather than two independent cores.</p>
<p>Operating-system scheduling is another layer. A runnable software thread may execute on a logical CPU, be preempted or migrate. A context switch changes which software state occupies the hardware context; it is not the same mechanism as issuing another already-resident SMT thread’s instruction. Affinity constrains where a thread may run, but does not automatically give it exclusive resources or move all of its memory.</p>
<p>Draw the topology before choosing a worker count: sockets, NUMA nodes, cache-sharing groups, physical cores and SMT siblings. These groups need not have matching boundaries. AMD EPYC systems, for example, expose placement considerations across their core complexes and memory configuration. Intel server topology and Arm server implementations have their own organization. Some CPUs have heterogeneous core types; a logical-CPU count hides those differences.</p>
<p>A serving process may have a request pool, a tokenizer pool, a numerical-library pool and a runtime worker pool. Eight requests each asking a library for eight threads can expose 64 runnable tasks on a much smaller machine. That oversubscription can increase queueing and tail latency even if a utilization graph stays busy. Choose one level to own parallelism for the hot region, then test other arrangements.</p>
${check('A kernel takes 20 ms on one core; 10% of its work is serial. What is the ideal eight-core limit before overhead?', 'Amdahl’s expression gives 1/(0.1 + 0.9/8) ≈ 4.71×, or 4.25 ms. Adding synchronization, imbalance and shared-bandwidth limits only reduces that ideal gain. Eight SMT contexts do not establish that eight independent cores are available.')}
${ref(amd, 'AMD EPYC 9004 tuning guide · topology, placement and workload tuning')}
`)}
${lesson('cpu-numa', 'Place the thread and its memory together', `
<p>In a NUMA system, the cost and bandwidth of accessing memory can depend on which CPU and memory node are involved. A pointer does not encode “local” in the source program. The same virtual allocation may be backed by physical pages near one worker and farther from another. Cross-node traffic also shares interconnect resources with other work.</p>
<p>Linux’s default memory policy normally prefers local allocation when a page is allocated, subject to allowed nodes, available memory and other policies. This motivates <strong>first-touch initialization</strong>: the worker that will use an anonymous page writes it first. It is a placement technique, not a guarantee that malloc itself allocated the page beside that worker. Shared/file-backed pages, explicit policies, huge pages and migration can change the story.</p>
<p>A common mistake is to initialize a large array on one thread, then spread its users across sockets. Their threads move while the pages retain the original placement. Pinning workers afterward does not, by itself, migrate the pages. Conversely, a memory-bound shared scan may benefit from spreading pages across controllers instead of placing everything near one thread. Match policy to who accesses the data and where the bandwidth is available.</p>
${code('Linux: inspect topology and compare declared placement policies', `lscpu -e=CPU,CORE,SOCKET,NODE
numactl --hardware
# Example node numbers only; inspect the machine before selecting them.
numactl --cpunodebind=0 --membind=0 ./cpu_bench rows 1024 20
numactl --cpunodebind=0 --membind=1 ./cpu_bench rows 1024 20
# This comparison needs a machine with both nodes and sufficient allowed memory.
# For an existing process, inspect /proc/PID/numa_maps.`)}
<p>Keep CPU placement, input size and work fixed when comparing memory policies. Read placement evidence as well as timing. The bandwidth of a remote streaming access and the latency of a dependent remote load are different experiments. On a single-node laptop, this lab has no local-versus-remote-node comparison to make.</p>
${check('A policy changes after every page is initialized. Must the next load use a newly selected node?', 'No. Allocation policy generally controls future allocations. Existing pages need an explicit supported migration or reallocation strategy to change placement, and placement can also be constrained by cpusets and capacity. Verify the actual mapping.')}
${ref(numa, 'Linux NUMA memory policy · allocation scope and existing pages')}
`)}
${lesson('cpu-measurement', 'Measure the limiting resource, not just CPU utilization', `
<p>Elapsed time is what the user waits for. CPU time counts time scheduled on processors and can sum across threads. Frequency counts cycles per second; instructions per cycle (IPC) divides retired instructions by an appropriate cycle count. None is a standalone score. A loop that does less work can finish sooner while reporting lower IPC; an efficient vector loop may retire fewer instructions for the same number of elements.</p>
<p>A useful first decomposition asks whether work is limited by supplying instructions, discarded speculative work, execution resources or memory. Intel’s top-down analysis gives architecture-specific metrics for these categories; Arm’s Neoverse guides also organize PMU measurements by bottleneck. Use the definitions for the exact processor and tool version. A count named cache-misses does not universally mean L1 misses or bytes read from DRAM.</p>
<p>For a hypothetical core completing one billion useful scalar additions, 0.5 seconds means two billion additions/s. A separate measurement of two billion instructions over one billion cycles gives IPC 2. These are different denominators. When comparing implementations, hold useful work and numerical behavior constant, and record elapsed time, instructions, cycles and relevant memory/branch events.</p>
${code('Linux perf: collect a small set of events before a detailed profile', `perf stat -r 5 -e cycles,instructions,branches,branch-misses \\
  ./cpu_bench rows 1024 20
perf stat -r 5 -e cycles,instructions,branches,branch-misses \\
  ./cpu_bench columns 1024 20
# Check event availability with perf list and inspect time-running/multiplexing.
# System policy may restrict PMU access; an unavailable event is not a zero count.
# On macOS use Instruments / supported counters, rather than these Linux commands.`)}
<p>Warm-up, page faults, CPU placement, frequency, thermals, competing work and compiler flags all affect the result. Report whether allocation and initialization are inside the measured interval. Use several repetitions and retain the spread, not only the fastest run. Count per useful element when input sizes differ. Profile a representative workload; an isolated hot loop can miss the cost of parsing, allocation and waiting around it.</p>
${check('Two runs have IPC 1 and IPC 2. Can you rank their completion time from those numbers?', 'No. Time is instructions / (IPC × cycle frequency) under consistent accounting. The instruction counts, frequencies, work and timing boundary may differ. Compare elapsed time for equal useful work, then use IPC and events to explain the difference.')}
${ref('https://www.intel.com/content/www/us/en/docs/vtune-profiler/cookbook/2024-1/top-down-microarchitecture-analysis-method.html', 'Intel VTune · top-down microarchitecture analysis')}
${ref('https://docs.kernel.org/admin-guide/perf-security.html', 'Linux perf events · access and measurement permissions')}
`)}
${lesson('cpu-practical-lab', 'Read the same matrix in two orders', `
<p>The native companion gives you a small experiment to compile and inspect. It stores an N×N matrix in row-major order, then computes the same sum with row-first and column-first traversal. Both visit every element exactly once. Adjacent row-first loads use nearby bytes. Column-first loads advance by N elements, changing cache and translation locality. The difference depends on matrix size and hardware; a small matrix that stays cached may behave very differently from a large one.</p>
<p>Use <code>examples/cpu</code>. The benchmark and kernels are separate translation units, built without link-time optimization so the caller does not hoist repeated pure sums out of the measured loop. Values are small integer-valued doubles; all permitted checksums are exactly representable. A self-test checks the traversal and vector-loop results before any performance interpretation. The printed time is a local measurement, not a built-in claim about a named CPU.</p>
${code('Build, check, run and inspect the C companion', `cd examples/cpu
make check
./cpu_bench rows 1024 20
./cpu_bench columns 1024 20
./cpu_bench chain 1024 20
./cpu_bench independent 1024 20
make assembly
# Read kernels.s and the compiler vectorization report.
# Use the same compiler and flags for comparisons.`)}
<p>First predict which traversal touches a new line sooner. Then test at several sizes, record the checksum, and inspect the generated loop. Compare chain and independent reductions as an additional experiment in available independent work. Strict floating-point rules may preserve the chained reduction; changing those rules is a separate experiment. A compiler can still transform the code, so a source-level label is not proof of a particular instruction schedule.</p>
<p>Extend the experiment one question at a time: transpose once before repeated column scans; tile a traversal; partition rows across workers; or add a strided gather. Include any conversion and coordination cost appropriate to the application. Preserve the useful work and verify the output after each change. A faster benchmark with missing elements is an incorrect implementation.</p>
${check('You transpose the matrix before timing and get a faster column scan. Have you shown an application speedup?', 'Only if excluding that transpose matches the application’s reuse boundary. For one scan, include the transpose. For repeated scans, report its amortized cost and the number of reuses. Also account for the second matrix’s memory footprint.')}
${ref(vector, 'LLVM vectorizer documentation · inspect transformations rather than guessing')}
`)}
${lesson('cpu-model-workloads', 'The CPU remains in the model’s critical path', `
<p>A model server uses CPUs for network handling, tokenization, request state, admission decisions, scheduling and runtime submission. CPU-only inference also executes the model’s numerical kernels there. A fast GPU does not remove these tasks. Look at the sequence from request arrival to completed response and identify which work overlaps and which work delays the next required stage.</p>
<p>Dense single-token matrix-vector work can repeatedly read large weights for relatively little reuse. Batching turns some of that work into matrix-matrix operations and can improve reuse, while changing latency and cache pressure. Quantization reduces the stored weight payload but adds scale handling, unpacking and different arithmetic. Vector instructions and library kernels help only if the layout, operator shapes and target support match.</p>
<p>As a declared lower-bound exercise, four billion weights at exactly four bits each occupy 2 GB before metadata. An assumed sustained 100 GB/s at the boundary carrying those weights gives at least 20 ms for a complete uncached weight sweep. That is not a token-rate prediction: some data may be cached, different operators reuse it differently, and KV reads, compute, scheduling and dequantization add costs. Measure the relevant traffic instead of dividing advertised bandwidth by a checkpoint size and calling it throughput.</p>
<p>If a trace shows 4 ms of exposed host preparation followed by 6 ms of device work per request, halving the host part changes 10 ms to 8 ms: 1.25×. If that host preparation is already fully hidden behind earlier work, shortening it may not change the critical path. Tokenizer parallelism, fewer temporary allocations, a different thread-pool policy or larger submission batches should each answer a measured bottleneck.</p>
<p>For a useful report, state processor and topology, memory configuration, compiler/library versions, thread placement, model format, batch and sequence lengths, warm-up and timing boundary. Keep first-token latency, later-token latency and throughput separate. Return to the <a href="#framework-benchmark-boundary">timing-boundary workbench</a> and <a href="#runtime-foundations">runtime foundations</a> when CPU and device timelines appear to disagree.</p>
${check('CPU utilization is 100%, but output throughput does not rise with more threads. What would you investigate?', 'Whether threads are sharing execution ports or saturating memory bandwidth, contending on locks/cache lines, oversubscribing nested pools, or doing work that does not shorten the critical path. Utilization proves that resources are busy, not that useful progress scales.')}
${ref(arm, 'Arm Neoverse performance analysis · connect PMU evidence to a bottleneck')}
`)}
`);
