import { chapterMarkup, sourceLink as ref, workedCheck as check, escapeCode } from "./lesson-template";
import memorySource from "../examples/c-basics/tensor_memory.c?raw";
import cudaSource from "../examples/cuda/row_primitives.cu?raw";
import tritonSource from "../examples/cuda/triton_softmax.py?raw";

const code = (title: string, text: string) => `<div class="lesson-code"><div><h4>${title}</h4></div><pre><code>${escapeCode(text)}</code></pre></div>`;
const listing = (title: string, text: string) => `<details class="lesson-code"><summary>${title}</summary><pre><code>${escapeCode(text)}</code></pre></details>`;

export const programmingChapter = chapterMarkup("programming", "From a C program to tensor storage",
  "Learn enough C, memory, compilation and numerical reasoning to explain every address in a GPU kernel. These exercises run on a CPU before CUDA enters the picture.", `
<section class="lesson" id="c-values-bytes" data-lesson="C values and types"><header><span>Start with a single value</span><h3>A tensor element occupies bytes; a type explains how to use them</h3></header>
<p>A program manipulates values stored in memory. A byte is an addressable storage unit; on the machines in this atlas it has eight bits. An unsigned eight-bit integer represents 0 through 255. Floating point uses a different encoding: sign, exponent and significand. Identical bits interpreted through different types can mean different values. Casting a numeric value and reinterpreting its representation are different operations.</p>
<p>In C, <code>float x = 1.5f;</code> declares an object named x and initializes it. <code>float</code> is its type; <code>1.5f</code> is a float literal. <code>x = x + 2.0f;</code> reads the old value, computes a new value, and stores it. The trailing semicolon ends the statement. A function groups statements and can receive inputs and return a result. <code>float square(float x) { return x * x; }</code> passes x by value: assigning to that local parameter does not overwrite the caller's variable.</p>
${code("Read a small C function", `#include <stddef.h> // size_t: an unsigned type for sizes

float dot(const float *a, const float *b, size_t count) {
    float sum = 0.0f;
    for (size_t i = 0; i < count; ++i) {
        sum += a[i] * b[i];
    }
    return sum;
}`)}
<p><code>i = 0</code> initializes the loop counter; <code>i &lt; count</code> decides whether to continue; <code>++i</code> advances it. <code>a[i]</code> reads one element. The pointers a and b identify storage belonging to the caller. <code>const</code> makes this access path read-only; it does not allocate data or prove that another pointer cannot change it. The function requires at least count valid elements in each input. C does not automatically carry that length with a pointer.</p>
<p>Use <code>sizeof</code> to ask for the size of a type or object. Do not assume <code>int</code>, <code>long</code> or a pointer has the same size everywhere. A matrix with 3×5 FP32 elements occupies 60 bytes when each element is four bytes; a pointer to that matrix occupies only the bytes needed to represent an address. Shapes describe meaning, and storage describes representation.</p>
${ref("https://www.open-std.org/jtc1/sc22/wg14/www/docs/n1570.pdf", "C committee draft: types, expressions and storage duration")}
${check("Check: does passing a 1 GB tensor to a function necessarily copy 1 GB?", "No. Passing a pointer and shape can copy only the small descriptor. Whether the data is copied depends on the implementation and ownership contract. A pointer alone also does not tell the function that the allocation contains 1 GB.")}
</section>

<section class="lesson" id="c-arithmetic-contracts" data-lesson="Integer and floating-point arithmetic"><header><span>Before optimizing arithmetic</span><h3>The representation changes which operations are valid</h3></header>
<p>Unsigned arithmetic wraps modulo its representable range. Signed integer overflow in C is undefined behavior: the compiler is allowed to assume it does not happen. These are different contracts. Tensor offsets should be calculated in an appropriate size type, and the products used for allocations must be checked before multiplication. Checking after an overflow cannot reconstruct the intended size.</p>
${code("Guard the multiplication before allocating", `if (count > SIZE_MAX / sizeof(float)) {
    /* reject: count * sizeof(float) would overflow */
    return NULL;
}
float *data = malloc(count * sizeof(float));
if (data == NULL) {
    /* handle allocation failure before dereferencing data */
}`)}
<p>Floating-point addition is not associative. In FP32, around 100,000,000, a change of 1 is too small to represent. <code>(100000000 − 100000000) + 1</code> produces 1, while <code>100000000 + (−100000000 + 1)</code> can produce 0. Parallel reductions change the addition tree, so a correct GPU result need not match a serial CPU sum bit for bit. Fused multiply-add also rounds a multiply plus add once, which can differ from two separately rounded instructions.</p>
<p>Define a comparison such as <code>|actual − reference| ≤ atol + rtol × |reference|</code>. Absolute tolerance matters near zero; relative tolerance scales with magnitude. Reject unexpected NaNs explicitly because <code>abs(NaN) &gt; tolerance</code> is false. A single tolerance suitable for a seven-element FP32 row may be inappropriate for a million-element reduction, a low-precision matrix instruction or a numerically ill-conditioned input.</p>
<p>Distinguish accumulation precision from storage precision. Inputs may be 16-bit, products may feed a wider accumulator, and the output may round back down. Ask which exact conversion happens at each boundary. The <a href="#mixed-precision">training numerics lesson</a> connects these choices to loss scaling and update state.</p>
${ref("https://docs.nvidia.com/cuda/floating-point/index.html", "NVIDIA: floating-point order, FMA and accuracy")}
${check("Check: a test uses only relative error. What happens when the correct gradient is zero?", "There is no meaningful nonzero relative scale. Use an absolute error allowance as well, and report the actual difference. Also test invariants, such as the sum of a softmax input gradient being approximately zero.")}
</section>

<section class="lesson" id="c-compile-run" data-lesson="Compile and run C"><header><span>A program becomes machine instructions</span><h3>Compilation and execution solve different problems</h3></header>
<p>Your source file is text. The compiler parses that text, checks language rules, transforms operations into an intermediate representation, optimizes them, and selects machine instructions. An assembler encodes instructions into an object file. The linker combines objects and resolves references such as calls to library functions. When the operating system starts the executable, the process gets an address space, and the loader makes code and data available.</p>
<figure class="textbook-lab cuda-lab"><figcaption><span>Figure C.1</span><strong>Follow one program through the toolchain</strong></figcaption><div class="cuda-pipeline"><span><code>tensor_memory.c</code><br>Declarations and loops</span><b>→</b><span>Compiler<br>IR → machine assembly</span><b>→</b><span>Assembler / linker<br>Objects → executable</span><b>→</b><span>Running process<br>Instructions access storage</span></div><p class="figure-boundary">Logical toolchain stages, not measured elapsed time. A compiler driver can perform several stages in one command.</p></figure>
${code("Build, run and inspect the companion", `mkdir -p /tmp/atlas-c
cc -std=c17 -O1 -g -Wall -Wextra -Wpedantic -Werror \\
  -fsanitize=address,undefined -fno-omit-frame-pointer \\
  examples/c-basics/tensor_memory.c -lm -o /tmp/atlas-c/tensor_memory
/tmp/atlas-c/tensor_memory
cc -std=c17 -O2 -S examples/c-basics/tensor_memory.c \\
  -o /tmp/atlas-c/tensor_memory.s`)}
<p>The first command builds with warnings and runtime instrumentation. <code>-g</code> records debugging information; optimization changes the relationship between source and instructions. <code>-S</code> stops at assembly. On an Apple Silicon machine this is ARM assembly; on an x86 host it is x86 assembly. The C logic is the same while the instruction set differs. A successful compile does not mean an out-of-bounds access is safe, and a successful test does not mean a loop is fast.</p>
<p>Compilation errors identify rejected source or unsupported constructs. Linker errors identify missing definitions or incompatible objects. Runtime errors occur after the executable starts. Keep these categories separate: reinstalling a runtime will not repair a mathematically incorrect index.</p>
${ref("https://clang.llvm.org/docs/CommandGuide/clang.html", "Clang: compiler stages and command options")}
</section>

<section class="lesson" id="c-pointers-arrays" data-lesson="Pointers and array bounds"><header><span>Make an address concrete</span><h3>A pointer gives access; it does not prove that access is valid</h3></header>
<p><code>float a[6];</code> reserves an array of six float objects. <code>&amp;a[0]</code> obtains the address of the first, and <code>*p</code> accesses the object at pointer p. For a pointer to float, <code>p + 1</code> advances by one float, not one byte. <code>a[i]</code> means <code>*(a + i)</code> within the same valid array. Many expressions convert an array to a pointer to its first element; the size of the array does not travel with that pointer.</p>
<p>If a begins at byte address 1000 and floats occupy four bytes, a[3] begins at 1012. The pointer expression <code>a + 6</code> may designate one position beyond this six-element array for iteration and comparison; dereferencing it is invalid. A pointer to an expired local variable is invalid even when its numeric address still looks plausible.</p>
<p>A flat row-major <code>float *</code> with shape [M,N] is not a <code>float **</code>. The latter describes pointers to pointers, often with separately allocated rows. Treating one as the other makes the machine interpret numeric data as addresses. A flat tensor needs a base pointer plus metadata such as shape and stride, then explicit address arithmetic.</p>
<p>Alignment is another obligation: an address must meet the requirements of the accessed type. Allocating enough bytes does not justify reading arbitrary shifted addresses as any type. Avoid pointer casts as a way to silence a type error; first determine the actual representation.</p>
${check("Worked check: what is the byte offset of FP32 A[2,4] in a contiguous [3,5] array?", "The element offset is 2×5+4=14. At four bytes per element, the byte offset is 56. The allocation contains 15 elements, so this is the start of its last element, not a 56-element offset.")}
</section>

<section class="lesson" id="tensor-strides" data-lesson="Tensor storage and strides"><header><span>Tensor metadata becomes address arithmetic</span><h3>Transpose can move the interpretation without moving the bytes</h3></header>
<p>A strided view computes an element address as <code>base + r×row_stride + c×col_stride</code>, with strides measured in elements here. Contiguous [3,5] row-major storage has strides (5,1). A transpose view with shape [5,3] uses strides (1,5) over the same allocation. A contiguous copy of that transpose rearranges the elements into a new allocation and usually has strides (3,1). These operations share mathematical values but have different costs and lifetimes.</p>
<figure class="textbook-lab cuda-lab" id="tensor-address-lab"><figcaption><span>Interactive C.2</span><strong>Point to a tensor element; find its actual word</strong><p>Every address below is a byte offset relative to an illustrative base. No process address is assumed.</p></figcaption><div class="cuda-toolbar"><label>Layout<select data-address-layout><option value="contiguous">Contiguous 3×5</option><option value="transpose">Transpose view 5×3</option><option value="padded">Padded 3×5 · stride 8</option></select></label><label>Logical row, column<select data-address-cell></select></label></div><div data-address-grid></div><p class="cuda-result" data-address-result aria-live="polite"></p><p class="figure-boundary">Original address model: FP32 elements, nonnegative strides, no device paging or cache behavior. The padded example allocates three full eight-word rows, including trailing padding.</p></figure>
<p>Padding separates the logical row length from the distance between row starts. With shape [3,5] and strides (8,1), A[2,4] is word 20, not word 14. Such a layout can arise from alignment requirements or a slice of a larger matrix. A slice can also shift the base pointer. Keep the original owning pointer: a borrowed pointer into the middle of an allocation must not be passed to <code>free</code>.</p>
<p>Broadcasting can use a zero stride: multiple logical coordinates then name the same physical element. Reads are useful; writes require a policy for aliasing. A kernel that assumes one independent output location per coordinate would race if the output were such a broadcast view. Some libraries also support negative strides; this exercise restricts them so every address is simple to inspect.</p>
${ref("https://numpy.org/doc/stable/reference/generated/numpy.ndarray.strides.html", "NumPy: strides are byte steps in its array interface")}
<p>Be precise at an API boundary: this chapter measures strides in elements; NumPy's exposed strides are in bytes. A GPU kernel that receives a library stride must use the library's units. The factor of four for FP32 is small enough to look plausible and large enough to corrupt every access.</p>
${check("Check: does a transpose view necessarily cost a complete tensor copy?", "No. It can change only shape and strides. A later operation requiring contiguous storage may materialize a copy, and a strided kernel may access memory less efficiently. The total cost belongs to the actual execution path, not the name of the view operation.")}
</section>

<section class="lesson" id="c-storage-ownership" data-lesson="Memory ownership and lifetime"><header><span>Who keeps the bytes alive?</span><h3>Storage must outlive every consumer</h3></header>
<p>Automatic local storage commonly lives in a stack frame. It stops being usable when its lifetime ends, although the compiler may keep some values in registers or remove them entirely. Allocated storage from <code>malloc</code> lives until released with <code>free</code>. The owner is the part of your program responsible for releasing it; a view borrows access without taking that responsibility. C provides the mechanisms but does not enforce this ownership convention.</p>
<p>The companion has one owning pointer and two descriptors referring to it: a normal matrix and its transpose. Freeing the owner invalidates both views. Freeing each view would attempt to release the same allocation twice. Returning a view over a local array would leave the caller with a dangling pointer. Passing a view to an asynchronous GPU copy adds a timing condition: its source storage must remain valid until that copy finishes.</p>
${listing("Read the complete owning-allocation and borrowed-view exercise", memorySource)}
<p>The harness uses double accumulation as a reference, checks padded rows remain untouched, and checks transpose coordinates resolve to identical addresses. It includes 1×1, 3×5 and 7×33 inputs. Its view descriptors are constructed from small known dimensions; a reusable untrusted-input API also needs overflow-safe validation of the maximum addressed offset against capacity.</p>
<p>CUDA C++ often uses a destructor-based owner: construction allocates device memory, destruction releases it, and copying is disabled or explicitly defined. This is called RAII, meaning the lifetime of an object controls acquisition and release of a resource. It prevents ordinary cleanup omissions, but cannot by itself prove that a different stream has finished using the buffer.</p>
${ref("https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rr-raii", "C++ Core Guidelines: managing resources with RAII")}
${check("Check: two tensors share storage. Can you update either in place safely?", "Only if the algorithm allows all affected aliases to observe that update and no consumer still needs the old values. Sharing storage is a dependency, not merely a memory saving. Autograd and asynchronous execution make those old-value lifetimes especially important.")}
</section>

<section class="lesson" id="c-debug-contract" data-lesson="Debugging with a reference"><header><span>Build evidence before speed</span><h3>A tiny independent reference makes a large kernel tractable</h3></header>
<p>Start with deterministic values whose answers you can inspect. Test a single element, odd dimensions, dimensions just below and above a block boundary, and values near numerical failure modes. A random large matrix is useful later, but can hide an indexing pattern that a 3×5 example exposes immediately. Test transposed and padded layouts only if the kernel promises to accept them; otherwise reject them explicitly at its boundary.</p>
<p>AddressSanitizer instruments CPU memory accesses and can identify issues such as out-of-bounds accesses and use after free. UndefinedBehaviorSanitizer adds checks for selected language violations. Neither is a proof of correctness. They do not establish that every tensor has the intended shape, that an optimizer divides by the right token count, or that the GPU accesses are valid.</p>
${ref("https://clang.llvm.org/docs/AddressSanitizer.html", "Clang: AddressSanitizer instrumentation and limits")}
<p>Change one thing at a time. First establish the scalar calculation, then the strided layout, then parallel ownership, then precision, then performance. Keep expected results independent of the optimized address helper; otherwise both sides of a comparison can repeat the same error. Record compiler version, flags, source revision, input shape and tolerance with any result you intend to rely on.</p>
<h4>Readiness exercise</h4><p>Without copying the companion, implement matrix-vector multiplication for a padded [3,5] matrix. Explain the exact address used for every operand, which object owns each allocation, and when every view expires. Compile with instrumentation. Then implement the transpose view and verify its dot products against a separately written nested-loop reference. Once those obligations are comfortable, <a href="#cuda-kernels">Writing CUDA kernels</a> applies the same reasoning to GPU threads.</p>
</section>
`);

export const cudaChapter = chapterMarkup("cuda-kernels", "Write, differentiate and inspect GPU kernels",
  "Carry a mathematical operation through thread ownership, memory transactions, synchronization, gradients and profiling. The runnable companions are correctness baselines; production optimization follows explicit numerical and hardware contracts.", `
<section class="lesson" id="cuda-first-launch" data-lesson="Your first CUDA kernel"><header><span>From a loop to parallel work</span><h3>A kernel is one function executed by many logical threads</h3></header>
<p>Start with a calculation you can do by hand: <code>out[i] = 0.5 × x[i] + y[i]</code>. Each answer uses only the inputs at the same index. A CPU loop visits those indices one after another. A GPU kernel gives different indices to different <strong>threads</strong>: logical workers running the same function, each with its own index and local values. Parallelism is safe here because every output has one writer and the inputs stay unchanged.</p>
<h4>Read the launch as a work assignment</h4>
<p>The <strong>host</strong> is the CPU running your application; the <strong>device</strong> is the NVIDIA GPU. A <strong>block</strong> groups threads that can cooperate, and a <strong>grid</strong> is all the blocks in one launch. CUDA supplies each thread's block number, position within its block, and block size. For a one-dimensional grid, its overall index is <code>block number × block size + position</code>.</p>
${code("CUDA C++: one output per thread, ten inputs", `__global__ void axpy(const float *x, const float *y,
                     float *out, size_t n, float alpha) {
    size_t i = size_t(blockIdx.x) * blockDim.x + threadIdx.x;
    if (i < n) out[i] = alpha * x[i] + y[i];
}
// Fragment: d_x, d_y and d_out are allocated GPU buffers.
axpy<<<3, 4>>>(d_x, d_y, d_out, 10, 0.5f);`)}
<p><code>__global__</code> marks the GPU entry point. The launch's <code>&lt;&lt;&lt;3, 4&gt;&gt;&gt;</code> requests three blocks of four threads; the parentheses pass the ordinary function arguments. The index multiplication uses <code>size_t</code> before multiplying so it is not evaluated in a narrower integer type.</p>
${ref("https://docs.nvidia.com/cuda/cuda-programming-guide/02-basics/writing-cuda-kernels.html", "CUDA: launch indices, kernel arguments and device storage")}
<div class="method-table"><table><caption>Ten inputs, twelve logical thread positions</caption><thead><tr><th scope="col">Block number</th><th scope="col">Positions in block</th><th scope="col">Output indices</th></tr></thead><tbody><tr><td>0</td><td>0, 1, 2, 3</td><td>0, 1, 2, 3</td></tr><tr><td>1</td><td>0, 1, 2, 3</td><td>4, 5, 6, 7</td></tr><tr><td>2</td><td>0, 1, 2, 3</td><td>8, 9; skip 10 and 11</td></tr></tbody></table></div>
<p>For block 1, position 2, the index is 1×4+2=6. If x[6]=12 and y[6]=3, this thread writes out[6]=9. The final two threads fail <code>i &lt; n</code> before reading or writing an array. Four threads per block makes this example easy to trace; it is not a performance recommendation.</p>
<h4>Follow the data back to the CPU</h4>
<p>The launch fragment needs a surrounding program. The <a href="#cuda-complete-harness">complete companion</a> allocates GPU storage, copies inputs into it, launches the kernel, checks completion, copies outputs back, compares them with a CPU reference, and frees storage. A device pointer identifies that allocation; passing a pointer does not copy its array.</p>
<p>A launch is asynchronous: the CPU can continue while GPU work is pending. The companion checks <code>cudaGetLastError()</code> after launch and uses <code>cudaDeviceSynchronize()</code> to wait and detect execution failures. A successful launch check alone does not establish a completed, correct result.</p>
${ref("https://docs.nvidia.com/cuda/cuda-programming-guide/02-basics/asynchronous-execution.html", "CUDA: asynchronous submission and completion")}
${check("Check: why would using only threadIdx.x give the wrong result?", "Every block would reuse indices 0 through 3. Multiple blocks would write the same four outputs, while outputs 4 through 9 would remain unwritten. Include the block offset; then explain the bounds check before optimizing the launch.")}
<details class="deep-dive"><summary>Work through larger inputs and grid-stride loops</summary>
<p>For n=1000 and 256 threads per block, four blocks provide 1024 positions. A grid-stride loop also lets a smaller grid cover a larger array: each thread advances by the total number of launched threads. With two blocks of four threads and ten inputs, thread 0 owns indices 0 and 8; thread 1 owns 1 and 9; threads 2 through 7 own one index each. These disjoint sequences preserve one writer per output.</p>
${code("CUDA C++: reuse each thread for more indices", `__global__ void axpy_strided(const float *x, const float *y,
                     float *out, size_t n, float alpha) {
    size_t i = size_t(blockIdx.x) * blockDim.x + threadIdx.x;
    size_t step = size_t(blockDim.x) * gridDim.x;
    for (; i < n; i += step) out[i] = alpha * x[i] + y[i];
}
// Device buffers must already contain valid inputs.
if (n != 0) {
    axpy_strided<<<(n + 255) / 256, 256>>>(d_x, d_y, d_out, n, 0.5f);
    CUDA_CHECK(cudaGetLastError());       // Launch configuration errors
    CUDA_CHECK(cudaDeviceSynchronize()); // Runtime execution errors
}`)}
${ref("https://developer.nvidia.com/blog/cuda-pro-tip-write-flexible-kernels-grid-stride-loops/", "NVIDIA: why a grid-stride loop covers larger arrays")}
<p>A <strong>warp</strong> groups 32 CUDA threads for execution; it is not 32 independent CPU cores. Divergent branches can execute with different lanes active. Blocks can run in any order, so block 1 must not assume block 0 has already finished. Independent thread scheduling does not make unsynchronized communication correct. The <a href="#cuda-coalescing">next lesson</a> uses warps to explain memory access; <a href="#cuda-synchronization">synchronization</a> explains safe cooperation.</p>
${ref("https://docs.nvidia.com/cuda/cuda-programming-guide/01-introduction/programming-model.html", "CUDA: blocks, warps and scheduling guarantees")}
${check("Check: can block 0 initialize a flag and every other block spin until it changes?", "That is not a safe general grid barrier. Other resident blocks may occupy all available resources while waiting for a block that has not run. Use separate dependent kernel launches, a supported cooperative launch with its requirements, or another explicitly valid synchronization protocol.")}
</details>
</section>

<section class="lesson" id="cuda-coalescing" data-lesson="Warps and memory access"><header><span>Inspect the addresses, not just the loop</span><h3>Nearby threads should usually request nearby words</h3></header>
<p>Coalescing combines a warp's global-memory accesses into requests for the memory regions they touch. Consider 32 active lanes each reading one four-byte word. With adjacent aligned words, the address set covers four 32-byte sectors. Shifting the first word by four bytes touches five sectors. Reading every second word touches eight sectors, although only half the bytes are useful distinct words. This is an address accounting model; caches and the architecture determine the eventual lower-level traffic.</p>
<figure class="textbook-lab cuda-lab" id="warp-address-lab"><figcaption><span>Interactive K.1</span><strong>One instruction, 32 addresses</strong><p>Read the byte address, 32-byte sector and hypothetical shared-memory bank for each active lane.</p></figcaption><div class="cuda-toolbar"><label>Word stride<select data-warp-stride><option value="1">1 · neighboring words</option><option value="2">2 · every other word</option><option value="8">8 · one word per sector</option><option value="32">32 · one shared bank</option><option value="33">33 · padded column</option><option value="0">0 · broadcast</option></select></label><label>Starting word<select data-warp-offset><option value="0">0 · sector aligned</option><option value="1">1 · four bytes shifted</option><option value="7">7 · end of a sector</option></select></label></div><div data-warp-diagram></div><p class="cuda-result" data-warp-result aria-live="polite"></p><details><summary>Read every address</summary><div class="cuda-scroll" data-warp-table></div></details><p class="figure-boundary">Original model: 32 active lanes, one aligned FP32 word per lane, 32-byte sectors, and a separate 32-bank/4-byte shared-memory interpretation. Global sectors and shared banks describe different memory spaces. Counts are neither measured HBM transactions nor elapsed cycles.</p></figure>
<p>Shared memory has a different issue: bank conflicts. Under the illustrative 32-bank, four-byte-word model, word w maps to bank <code>w mod 32</code>. If lanes access distinct words in the same bank, the bank must service multiple words. If they all read the same word, a broadcast is possible; counting lanes alone would falsely call that a 32-way conflict. A column of a shared array with row stride 32 hits the same bank, while stride 33 rotates through banks.</p>
${ref("https://docs.nvidia.com/cuda/cuda-c-best-practices-guide/index.html#coalesced-access-to-global-memory", "CUDA Best Practices: coalescing and shared-memory banks")}
<p>The padding change that helps a shared-memory transpose can make a global-memory load pattern worse. These are different boundaries. A production tiled kernel often cooperatively loads global memory using one pattern, rearranges data in shared memory, then feeds compute instructions using another. Trace the actual addresses at each stage before declaring a layout efficient.</p>
${check("Worked check: all 32 lanes read the same word. How many useful distinct bytes are fetched?", "Four in this model. There are 32 logical consumers, but one distinct FP32 word. Useful-distinct-byte utilization is 4/32 for its single sector. That ratio does not mean broadcast is slow: many consumers reuse the same retrieved value.")}
</section>

<section class="lesson" id="cuda-synchronization" data-lesson="Synchronization and data races"><header><span>Communication requires an ordering proof</span><h3>A completed producer is useful only when the consumer can observe it</h3></header>
<p>Two threads accessing the same location, with at least one unsynchronized write, can race. A block barrier waits for the block's participating work and establishes visibility for the memory accesses covered by its contract. It does not synchronize all blocks. A memory fence orders memory operations under its specified scope; it is not automatically an execution barrier. An atomic read-modify-write protects that operation on its location; it does not automatically complete all surrounding work.</p>
<p>For a shared tile, write the input operands, synchronize before peers read them, calculate from the tile, then synchronize before reusing that shared storage. The two barriers protect two different transitions. The existing <a href="#tiled-matmul">matrix-tile workbench</a> shows them separately. Moving a barrier inside a condition that differs across threads is not a valid way to skip empty outputs. An out-of-range output thread may still need to stage inputs and join barriers.</p>
<div class="cuda-scroll"><table class="cuda-contract-table"><caption>Choose the synchronization scope required by the dependency</caption><thead><tr><th>Dependency</th><th>Typical mechanism</th><th>Obligation</th></tr></thead><tbody><tr><td>Within one thread</td><td>Program data dependence</td><td>Keep operands alive and obey memory semantics.</td></tr><tr><td>Participating lanes of one warp</td><td>Warp intrinsic / synchronization mask</td><td>Every named lane participates; source lanes are valid.</td></tr><tr><td>Threads in one block</td><td><code>__syncthreads()</code></td><td>Compatible barrier participation across the block.</td></tr><tr><td>Dependent ordinary kernels</td><td>Same-stream order</td><td>Produce buffers before the later launch consumes them.</td></tr><tr><td>Work across streams</td><td>Record event, wait on event</td><td>The event covers the actual producer work.</td></tr></tbody></table></div>
<p>For a host-to-device transfer followed by compute, the host allocation, device allocation and stream each have a role. Pinned host memory supports asynchronous DMA behavior in supported paths; it also consumes a resource the operating system cannot page normally. An event can express completion, but does not extend the buffer's lifetime on its own. Free or reuse memory only after all intended consumers have completed.</p>
${ref("https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__STREAM.html", "CUDA Runtime: stream operations and dependencies")}
${ref("https://docs.nvidia.com/cuda/cuda-programming-guide/04-special-topics/async-copies.html", "CUDA: asynchronous copy operations")}
${check("Check: an atomic counter says that all blocks have arrived. Is every ordinary write automatically safe to consume?", "Only if the complete publication protocol supplies the required memory ordering, visibility and execution progress. The counter alone is not a substitute for specifying those conditions. Start with a separate dependent launch when that simpler boundary is sufficient.")}
</section>

<section class="lesson" id="cuda-reductions" data-lesson="Parallel reductions"><header><span>Many values become one</span><h3>Reduce locally, then reconcile the partial sums</h3></header>
<p>A sum reduction is the first cooperation pattern to master because softmax, normalization, dot products and gradient aggregation all reuse it. Each thread first sums its own assigned elements. It writes one local partial to shared memory. A tree then halves the number of writers at each stage: offset 4, then 2, then 1 for an eight-thread example. At each stage a surviving lane adds the partner value from the preceding complete state.</p>
<figure class="textbook-lab cuda-lab" id="cuda-reduction-lab"><figcaption><span>Interactive K.2</span><strong>Step through an eight-slot reduction</strong><p>Inactive inputs write zero. Inactive writers still join the barriers. Gray values remain in scratch but are no longer live partial sums.</p></figcaption><div class="cuda-toolbar"><label>Valid inputs<select data-reduce-length><option value="5">5 · padded tail</option><option value="8">8 · full block</option><option value="1">1 · single value</option></select></label><button data-reduce-back>Previous</button><button data-reduce-next>Next stage</button></div><div class="cuda-scroll" data-reduce-diagram></div><p class="cuda-result" data-reduce-result aria-live="polite"></p><details><summary>Read every stage</summary><div class="cuda-scroll" data-reduce-table></div></details><p class="figure-boundary">Original shared-memory tree with small exactly representable integers. Edges describe partners consumed from the previous state; their positions do not represent physical wires or cycle timing. A floating-point tree changes rounding order.</p></figure>
<p>The identity for a sum is zero; for a maximum it is negative infinity. An invalid input must not participate as an arbitrary uninitialized value. With five values [1,2,3,4,5] in eight slots, the first step forms [6,2,3,4], the second [9,6], and the last 15. Summing all eight scratch slots after the final step would double-count stale partials.</p>
<p>Our CUDA block reducer uses 256 threads and block barriers. Its final extra barrier prevents a later invocation from overwriting shared scratch before every thread has read the previous result. To reduce a whole input, blocks write partial sums and a second dependent kernel reduces those partials. This makes the grid-wide dependency explicit. A one-kernel atomic scheme has different contention, initialization and reproducibility considerations.</p>
<p>A faster variant reduces within warps using shuffles, writes one partial per warp, and reduces those partials using one warp. A shuffle reads a register from another participating lane; it does not make an inactive source lane valid. For a short row, have a full participating warp hold identity values for invalid elements, or implement a correct partial-warp protocol. Do not paste a full mask into divergent control flow without proving participation.</p>
${ref("https://docs.nvidia.com/cuda/parallel-thread-execution/index.html#data-movement-and-conversion-instructions-shfl-sync", "PTX: shuffle synchronization and lane contracts")}
</section>

<section class="lesson" id="cuda-stable-softmax" data-lesson="Softmax and its gradient"><header><span>The reduction becomes an LLM operation</span><h3>Normalize logits without creating unnecessary overflow</h3></header>
<p>For a finite row x of length D, let <code>m=max(x)</code>, <code>eᵢ=exp(xᵢ−m)</code>, <code>s=Σeᵢ</code> and <code>yᵢ=eᵢ/s</code>. Subtracting the same maximum leaves the exact mathematical probability unchanged. The largest exponential becomes one, so a row such as [1000,1001] can be normalized without evaluating exp(1001) directly. This does not define behavior for an all-negative-infinity masked row: subtracting negative infinity from itself is undefined numerically, so that row needs an explicit policy.</p>
<p>The baseline assigns one block to each row. Threads make a strided pass for the maximum, another for the exponential sum, and a final pass to write probabilities. This trades repeated reads and exponentials for a simple bounded register footprint. A fused register-resident row can keep intermediate values and reduce traffic, but a wider row can increase register use, spill, or lower residency. Fusion changes both data movement and resource pressure.</p>
<h4>Derive backward without allocating a D×D Jacobian</h4>
<p>The derivative is <code>∂yᵢ/∂xⱼ = yᵢ(δᵢⱼ−yⱼ)</code>. Given an upstream gradient gᵢ=∂L/∂yᵢ, expand the chain rule: <code>∂L/∂xⱼ = Σᵢgᵢyᵢδᵢⱼ − Σᵢgᵢyᵢyⱼ = yⱼ(gⱼ − Σᵢgᵢyᵢ)</code>. Backward therefore needs one row dot product and an elementwise expression. It can reuse saved probabilities y; it does not need to store a dense Jacobian.</p>
${code("Softmax gradient contract", `dot = sum(y[i] * upstream[i] for i in range(D))
dx[i] = y[i] * (upstream[i] - dot)

# Independent finite-difference check of the scalar objective:
L(x) = sum(softmax(x)[i] * upstream[i] for i in range(D))
dx_numeric[j] = (L(x + h*unit(j)) - L(x - h*unit(j))) / (2*h)`)}
<p>The input-gradient sum should be approximately zero: adding a constant to every logit does not change softmax, so the objective has no derivative in that direction. A row of length one has probability one and input gradient zero. Both are stronger checks than seeing a plausible loss value. For small double-precision examples, the companion math tests compare this derivative with central differences of an independently evaluated scalar objective.</p>
${ref("https://triton-lang.org/main/getting-started/tutorials/02-fused-softmax.html", "Triton: row fusion, masking and resource limits")}
${check("Check: increasing all logits by 1000 changes your probabilities. Which contract failed?", "Softmax is translation-invariant in exact arithmetic. The implementation may have skipped maximum subtraction, overflowed, or lost input differences during a low-precision cast. Inspect the stored logits as well as the exponentials; stable normalization cannot recover distinctions already rounded away.")}
</section>

<section class="lesson" id="cuda-rmsnorm-backward" data-lesson="RMSNorm and parameter gradients"><header><span>Different gradients reduce over different axes</span><h3>Normalize within a row; accumulate weights across rows</h3></header>
<p>RMSNorm uses the root mean square without subtracting a mean. For a row x of width D, weight w and positive epsilon, define <code>r=(Σxⱼ²/D + ε)<sup>−1/2</sup></code> and <code>yᵢ=wᵢxᵢr</code>. The forward kernel sums squares, calculates r, stores that one scalar per row, and writes y. LayerNorm has a centered variance and a different derivative; substituting one implementation for the other changes the model.</p>
<h4>Carry the chain rule through the normalization statistic</h4>
<p>Given upstream g, define <code>uᵢ=gᵢwᵢ</code>. The direct path from xᵢ to yᵢ contributes <code>r uᵢ</code>. The statistic contributes <code>∂r/∂xᵢ=−xᵢr³/D</code>, multiplied by <code>Σⱼuⱼxⱼ</code>. Thus <code>dxᵢ=r uᵢ − xᵢr³(Σⱼuⱼxⱼ)/D</code>. Leaving out this second term differentiates a function that incorrectly treats its own normalization factor as constant.</p>
<p>The weight derivative from one row is <code>dwᵢ=gᵢxᵢr</code>. If the same w is used for every token row, sum that contribution over all rows. This is a different axis from the per-row reduction used for dx. Our baseline stores per-row contributions into disjoint locations, then launches a separate column reduction. It spends extra memory to make ownership explicit and avoid a concurrent update race.</p>
<figure class="textbook-lab cuda-lab"><figcaption><span>Figure K.3</span><strong>Two reduction axes in one backward pass</strong></figcaption><div class="cuda-pipeline"><span>Each token row<br>reduce Σ(g·w·x) over features</span><b>→</b><span>Write dx[row, feature]<br>each element has one owner</span></div><div class="cuda-pipeline"><span>Each row emits g·x·r<br>partial dw[row, feature]</span><b>↓</b><span>Reduce across token rows<br>one dw[feature] for shared w</span></div><p class="figure-boundary">Dependency diagram. Production implementations may fuse or partition these reductions differently while preserving the same derivative.</p></figure>
<p>Zero input is a useful test. With positive epsilon, y and dw are zero while <code>dx=g·w/√ε</code>; the derivative need not be zero. Saving r avoids recomputing it in backward, but r must correspond to the same x, weights and epsilon used by forward. In-place mutation or mixed conventions can make a mathematically correct formula differentiate the wrong execution.</p>
${ref("https://arxiv.org/abs/1910.07467", "RMSNorm: root mean square layer normalization")}
${ref("https://triton-lang.org/main/getting-started/tutorials/05-layer-norm.html", "Triton: normalization backward and weight-gradient reduction")}
${check("Check: a weight gradient is correct for batch size one but wrong for three rows. What is a likely missing operation?", "The shared weight receives a contribution from every row. Keeping only one row's partial, overwriting the same location from many blocks, or averaging when the objective requires a sum changes dw. Compare the complete gradient with the declared loss normalization.")}
</section>

<section class="lesson" id="cuda-complete-harness" data-lesson="Build and test CUDA"><header><span>Runnable code with explicit boundaries</span><h3>Validate the binary, then connect it to a training framework</h3></header>
<p>The companion contains grid-stride AXPY, a two-launch sum, stable softmax and backward, RMSNorm and backward, a separate weight-gradient reduction, device-memory owners, launch/error checks and CPU reference comparisons. It uses FP32 device inputs and double CPU arithmetic with tolerance <code>3×10⁻⁴ + 3×10⁻⁴|reference|</code>. Rows include widths 1, 7, 31, 32, 33, 255, 256, 257 and 1025, plus zero input and large finite logits.</p>
${code("Build on an NVIDIA CUDA host", `mkdir -p /tmp/atlas-cuda
nvcc -std=c++17 -O2 -lineinfo -Xptxas=-v \\
  examples/cuda/row_primitives.cu -o /tmp/atlas-cuda/row_primitives
/tmp/atlas-cuda/row_primitives
compute-sanitizer --tool memcheck --error-exitcode 1 /tmp/atlas-cuda/row_primitives
compute-sanitizer --tool racecheck --error-exitcode 1 /tmp/atlas-cuda/row_primitives
compute-sanitizer --tool synccheck --error-exitcode 1 /tmp/atlas-cuda/row_primitives
compute-sanitizer --tool initcheck --error-exitcode 1 /tmp/atlas-cuda/row_primitives`)}
${listing("Read the full CUDA kernels and correctness harness", cudaSource)}
<p><strong>Execution boundary:</strong> CUDA compilation, GPU execution, Compute Sanitizer and GPU timing have not been verified on the development Mac. The CPU C executable and JavaScript mathematical tests are separate checks. They do not establish that the CUDA binary is correct. All listings are imported directly from the companion files so the page and source agree.</p>
<p>Memcheck checks classes of device memory misuse; racecheck targets shared-memory hazards; synccheck diagnoses selected synchronization errors; initcheck checks uninitialized device global-memory reads. Run all relevant tools, because one clean report does not imply another tool's property. A numerical mismatch with clean sanitizer output can still be an algebra, shape or normalization error.</p>
${ref("https://docs.nvidia.com/compute-sanitizer/ComputeSanitizer/index.html", "Compute Sanitizer: the distinct tool contracts")}
<h4>Connect the kernel to a complete training update</h4><p>A custom operation needs an input contract (shape, layout, dtype, device), a forward result, saved backward state, a backward implementation and stream-correct integration. Compare both forward and backward with the framework reference before using it in a decoder. Next replace one operation in the <a href="#capstone-training">tiny language-model exercise</a>, fix the initialization and input batch, and compare loss, every changed gradient, optimizer state and updated weights for several steps. Include the original implementation as a switchable reference.</p>
<p>An optimizer applies the gradients to model parameters; a kernel itself is a program implementing an operation. You train the model using kernels. If a fused operation changes saved activations, RNG consumption or accumulation order, its integration must preserve the intended objective and numerical contract. A loss that decreases is insufficient evidence.</p>
</section>

<section class="lesson" id="cuda-gemm-hierarchy" data-lesson="Matrix multiplication tiling"><header><span>Continue from the existing matrix laboratory</span><h3>A production GEMM tiles the work at several levels</h3></header>
<p>The <a href="#tiled-matmul">existing tiled-matmul companion</a> assigns one scalar output to each thread and cooperatively stages operands in shared memory. Now give a thread a small register tile of outputs. A loaded A scalar can update several columns of that tile, and B values can update several rows. Reuse increases, but each accumulator consumes a register. Larger register tiles can reduce residency or spill, so increasing tile size is not an unlimited optimization.</p>
<p>A full GEMM decomposes the output into thread-block tiles, warp tiles and instruction tiles. A loop over K brings successive operand slices into those tiles. An epilogue transforms accumulators into output: scaling, adding bias, applying an activation, quantizing or writing a specified layout. Fusing a bias and activation can avoid a separate read and write of the complete output. It also changes which data backward needs and how precision is rounded.</p>
<figure class="textbook-lab cuda-lab"><figcaption><span>Figure K.4</span><strong>One mathematical multiply, several ownership levels</strong></figcaption><div class="cuda-pipeline"><span>Grid<br>independent output tiles</span><b>→</b><span>Block tile<br>cooperative operand staging</span><b>→</b><span>Warp tile<br>instruction participation</span><b>→</b><span>Instruction tile<br>register / tensor accumulators</span><b>→</b><span>Epilogue<br>final layout and stores</span></div><p class="figure-boundary">Algorithm hierarchy. Instruction participation, accumulator storage and legal tile shapes depend on architecture and kernel family.</p></figure>
<p>Double buffering stages upcoming operands into a different buffer while computation consumes the current one. It needs a readiness condition before consuming a buffer and a release condition before reusing it. More pipeline stages hide some latency but consume shared-memory capacity and complicate lifetimes. The <a href="#gpu-resources">GPU residency chapter</a> supplies the resource accounting; a faster arithmetic instruction cannot remove an exposed producer dependency.</p>
<p>GEMM tails exist in all three dimensions. M/N tails guard output ownership; K tails must supply correct reduction identities and respect instruction alignment or padding rules. A kernel supporting only aligned dimensions should reject other inputs or dispatch to a supported fallback. Benchmark ragged shapes as well as large convenient multiples.</p>
${ref("https://docs.nvidia.com/cutlass/latest/media/docs/cpp/efficient_gemm.html", "CUTLASS: hierarchical tiling, pipelining and epilogues")}
<h4>Implement the next step</h4><p>Extend the scalar tiled companion with a 2×2 register output tile per thread. Derive the four accumulator updates, keep both shared-memory barriers, and test M=3, N=5, K=7 before larger matrices. Then add bias in the epilogue and compare the fused output with an independently computed reference. Count useful FLOPs separately from padded arithmetic, and compare measured device time with a tuned library under the same shape, layout and accuracy contract.</p>
</section>

<section class="lesson" id="cuda-tensor-cores" data-lesson="Tensor Core instructions"><header><span>Use the matrix engine deliberately</span><h3>Tensor Cores accelerate a specific matrix instruction contract</h3></header>
<p>A tensor instruction performs a structured matrix multiply-accumulate, not an arbitrary scalar loop. It specifies operand types, accumulator type, shape, participating threads and register or memory layout. An instruction fragment is not generally a simple contiguous array where each thread owns one intuitive row. All participating lanes must satisfy the instruction's execution contract.</p>
<p>PTX is NVIDIA's virtual instruction-set representation. Instructions such as <code>mma</code> describe operations and constraints that compile to target-specific machine instructions. Inspect the target architecture and ISA support before choosing an instruction. An FP16-input/FP32-accumulation instruction and a lower-precision block-scaled instruction have different numerical and metadata obligations even if both are described as Tensor Core compute.</p>
${ref("https://docs.nvidia.com/cuda/parallel-thread-execution/index.html#warp-level-matrix-instructions-mma", "PTX: matrix-instruction operands and participation")}
<h4>Hopper and Blackwell add new storage and scheduling obligations</h4><p>Modern kernels can combine Tensor Memory Accelerator transfers, asynchronous matrix work, warp specialization and architecture-specific accumulator storage. A producer warp group can stage operands while consumer groups execute matrix instructions. Separating those roles changes barriers and buffer ownership; it does not remove them. Blackwell SM100 GEMM families expose Tensor Memory and new matrix-instruction paths, so porting an older tuned kernel is more than selecting a newer compiler flag.</p>
${ref("https://docs.nvidia.com/cutlass/latest/media/docs/cpp/blackwell_functionality.html", "CUTLASS: Blackwell SM100 GEMM functionality")}
<p>Read a specific CUTLASS example by answering six questions: which thread group owns the instruction, where each operand lives, which event makes an operand ready, where the accumulator resides, who may release its storage, and which epilogue writes the final output. Record toolkit, architecture and source revision. A published peak FLOP/s number describes a supported operation under stated conditions; it is not a prediction for your ragged normalization kernel.</p>
${check("Check: does replacing FP32 scalar multiplication with a faster low-precision MMA preserve the original computation exactly?", "No. Operand rounding, product format, accumulation behavior, scaling and output conversion can change the numerical result. Establish an accuracy contract against the original operation, then compare training or inference behavior where that operation is used.")}
</section>

<section class="lesson" id="cuda-triton-compiler" data-lesson="Triton and generated code"><header><span>Choose the level where you express the algorithm</span><h3>A compiler manages layouts; you still own correctness</h3></header>
<p>In ordinary CUDA, you commonly write the work of a logical thread. In Triton, you describe operations over blocks of values and let the compiler distribute them across execution resources. For a row softmax, one program identifies a row, creates a vector of column offsets, masks invalid columns, reduces a maximum, normalizes exponentials and masks stores. The high-level vector is not a promise that one hardware thread owns the entire row.</p>
${listing("Read the full Triton forward/backward and autograd comparison", tritonSource)}
<p>The companion rounds the program's column block to a power of two. Invalid logits load negative infinity for the maximum/exponential calculation; invalid probabilities and upstream gradients load zero in backward. It compares with PyTorch softmax and autograd at odd widths through 4097. It is a contiguous FP32, finite-logit exercise. It does not accept arbitrary strides, prove performance or define fully masked rows.</p>
<p>Compilation can specialize on constants such as row width and block size. First invocation can include compilation work. Different shapes can trigger different specializations, and automatic tuning can run several candidates. Separate those costs from steady-state timing while keeping them visible in cold-start latency. A graph compiler may fuse operators or generate kernels, but the resulting executable still has register usage, memory transactions and synchronization requirements.</p>
<h4>Inspect what the toolchain actually emitted</h4>
${code("Save virtual instructions and inspect the executable", `nvcc -std=c++17 -O2 -ptx examples/cuda/row_primitives.cu \\
  -o /tmp/atlas-cuda/row_primitives.ptx
cuobjdump --dump-sass /tmp/atlas-cuda/row_primitives
# For a target-specific build, select a supported -arch=sm_XX.
# Keep -Xptxas=-v resource reports with your measurements.`)}
<p>NVCC separates host and device compilation and can package target machine code plus PTX in a binary. PTX can be compiled into machine instructions for an appropriate target; SASS is the actual NVIDIA machine-instruction representation you inspect in the resulting executable. Source loops, PTX operations and issued machine instructions are different levels. A variable called “local” in source can spill to device-backed local memory rather than staying in an on-chip register.</p>
${ref("https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html", "NVCC: compilation trajectories, targets and embedded device code")}
${ref("https://docs.nvidia.com/cuda/cuda-binary-utilities/index.html", "CUDA binary utilities: cuobjdump and disassembly")}
<p>Use generated code to resolve a hypothesis: did vector loads appear, did a reduction spill, did the intended tensor instruction survive, or did an epilogue introduce expensive conversions? Reading disassembly without a question is less useful than connecting one changed instruction or memory path to a measured result.</p>
</section>

<section class="lesson" id="cuda-profile-iterate" data-lesson="Profile and improve kernels"><header><span>Correctness is the entry ticket to optimization</span><h3>Measure a defined workload at a defined boundary</h3></header>
<p>CPU wall time around an asynchronous launch usually measures submission rather than completion. For device elapsed time, warm the path, record a start CUDA event in the measured stream, enqueue repeated launches, record a stop event in that stream, wait for the stop, and divide elapsed time by the number of repetitions. If transfers, allocations, compilation or synchronization are part of the product path, report those separately and include them in the appropriate end-to-end measurement.</p>
${code("Timing sketch after correctness checks and warmup", `cudaEventRecord(start, stream);
for (int repeat = 0; repeat < repetitions; ++repeat) {
    kernel<<<grid, block, 0, stream>>>(/* device buffers */);
}
cudaEventRecord(stop, stream);
cudaEventSynchronize(stop);
float milliseconds = 0;
cudaEventElapsedTime(&milliseconds, start, stop);
// Report milliseconds / repetitions; check every API and launch in real code.`)}
<p>The sketch omits event creation/destruction and error handling for readability; the executable companion is a correctness harness with frequent synchronization, not this benchmark. Test more than one input shape and report variability. Avoid comparing a warmed single stream against a cold end-to-end framework invocation under one number called “latency.”</p>
<p>Nsight Systems gives a timeline of launches, transfers and dependencies; use it to locate exposed idle time and the critical path. Nsight Compute investigates selected kernels using hardware counters and replay. Replay can perturb caches and execution, so its collected counters and timing need their documented context. Find the right kernel first; a full detailed profile of every launch can be slow and misleading.</p>
${ref("https://docs.nvidia.com/nsight-systems/UserGuide/index.html", "Nsight Systems: execution timeline and tracing")}
${ref("https://docs.nvidia.com/nsight-compute/ProfilingGuide/index.html", "Nsight Compute: metrics, replay and measurement context")}
<h4>Follow one hypothesis through an experiment</h4><p>Suppose a row kernel appears bandwidth-limited. Predict the byte reduction from retaining exponentials, implement that change, re-run numerical and sanitizer checks, inspect registers and spills, then compare representative widths. If time gets worse at 4097 columns, investigate register pressure and residency. The failed speedup is evidence about the limiting resource; it is not a reason to discard the measurement.</p>
<p>For GEMM, report useful <code>2MNK</code> FLOPs and the actual dtype/accumulation path. For AXPY, an ideal input/output accounting reads two FP32 vectors and writes one: <code>12N</code> bytes. Actual device traffic can differ through caching and stores. Operational intensity must name the byte boundary used in its denominator. Occupancy is a residency metric, not a utilization or speed score.</p>
<h4>Exit project: one operation in a trained and served model</h4><p>Choose RMSNorm. First explain its pointer and stride contract, then validate forward, dx and shared dw, including zero and odd-width cases. Integrate it into a tiny training step and compare several updates with the reference. Profile it at realistic prefill and decode shapes. Keep a dispatch fallback for unsupported layouts or architectures. Finally compare the serving model's complete latency and throughput: a faster normalization kernel matters only to the extent that it shortens the exposed application path.</p>
<p>Continue with <a href="#gpu-resources">GPU residency</a>, <a href="#performance">profiling and kernel reasoning</a>, and <a href="#inference">the inference engine</a>. The same ownership, lifetime and numerical contracts recur when a kernel becomes part of a multi-request, multi-device service.</p>
</section>
`);
