import { chapterMarkup, sourceLink as ref, workedCheck as check, escapeCode } from "./lesson-template";
import referenceSource from "../examples/inference/speculative_sampling.py?raw";

export const decodingChapter = chapterMarkup("decoding", "Choose tokens without losing the contract",
  "Separate the distribution you intend to sample from the machinery that produces it. Then account for speculative work, rejected state, and latency.", `
<section class="lesson" id="sampling-contract" data-lesson="Greedy, temperature, top-k and top-p"><header><span>Inference methods</span><h3>Logits are scores; a sampler turns them into a decision</h3></header>
<p>At one decoding position, the model produces a vector of vocabulary scores z. For positive temperature τ, a distribution can be formed as <code>pᵢ = exp((zᵢ−max z)/τ) / Σⱼ exp((zⱼ−max z)/τ)</code>. Subtracting the common maximum improves numerical stability without changing the ideal distribution. Reducing τ sharpens differences; increasing it flattens them. Neither operation adds factual knowledge to the model.</p>
<div class="method-table"><table><caption>Declare the token-selection rule</caption><thead><tr><th scope="col">Rule</th><th scope="col">Operation</th><th scope="col">What must be specified</th></tr></thead><tbody><tr><th scope="row">Greedy</th><td>Choose the largest score</td><td>Tie handling; do not literally divide by zero temperature</td></tr><tr><th scope="row">Categorical</th><td>Draw according to normalized probabilities</td><td>Random-number stream and sampling policy</td></tr><tr><th scope="row">Top-k</th><td>Keep k highest-scoring tokens, then normalize</td><td>k, tie order and processor order</td></tr><tr><th scope="row">Top-p / nucleus</th><td>Keep a sorted prefix reaching probability mass p</td><td>Threshold, boundary inclusion and prior filtering</td></tr><tr><th scope="row">Beam search</th><td>Track several sequence hypotheses</td><td>Sequence scoring, length treatment and pruning</td></tr></tbody></table></div>
${ref("https://huggingface.co/docs/transformers/main/en/generation_strategies", "Transformers: generation strategies and sequence search")}
<h4>Filtering order is observable</h4><p>Suppose probabilities are (0.50,0.30,0.15,0.05). Top-k with k=2 removes the last two entries and renormalizes to (0.625,0.375,0,0). Applying top-p=0.6 now keeps only the first token. Applying that threshold to the original distribution would keep the first two. A response configuration needs an exact processor order, not an unordered bag of parameter names.</p>
<p>The repository's <code>samplingDistribution</code> declares temperature → top-k → renormalize → top-p, with stable token-index tie breaks. Its tests cover large logit offsets, greedy ties, masked negative-infinite scores and invalid settings. This is an educational reference, not a promise that every serving engine uses identical processor ordering.</p>
<h4>Sampling exactness is relative to the chosen target distribution</h4><p>If the target uses a grammar mask, penalties, top-p, or a temperature, its effective distribution changes. A speculative acceptance calculation must use the actual target policy and the actual proposal probabilities at the same prefix. A rule that preserves raw softmax probabilities may not preserve a differently filtered distribution. Token IDs must also refer to the same events; cross-tokenizer speculation requires additional mapping machinery.</p>
${check("Worked check: two systems generate different strings from the same random seed. Does that disprove distributional equivalence?", "Not by itself. They may consume random numbers in different orders or execute numerically different kernels. Distributional equality is a statement about probabilities, not identical paths through one random-number stream. Test the declared contract: exact arithmetic on small distributions, statistical checks, and separately greedy equality where appropriate.")}
</section>

<section class="lesson" id="speculative-exactness" data-lesson="Exact speculative sampling and residual repair"><header><span>Speculative decoding</span><h3>Accept overlapping mass; repair the remainder</h3></header>
<p>Let p be the target distribution and q a cheaper proposal distribution at the same prefix. Draw candidate x from q. Accept it with probability <code>min(1,p(x)/q(x))</code>. If rejected, draw a replacement from normalized <code>max(p−q,0)</code>. A sampled candidate necessarily has positive q(x). When p=q, rejection has zero probability and the residual distribution is never needed.</p>
${ref("https://arxiv.org/abs/2211.17192", "Leviathan et al.: speculative decoding and acceptance")}
<figure class="textbook-lab probability-lab" id="speculation-lab"><figcaption><span>Interactive 15.1</span><strong>Where does every unit of probability go?</strong><p>Four abstract tokens, two distributions, and one exact accounting identity. Step through the construction or inspect the table.</p></figcaption>
<div class="method-toolbar"><label>Proposal quality<select data-spec-preset><option value="unequal">Unequal distributions</option><option value="close">Close proposal</option><option value="identical">Identical distributions</option><option value="disjoint">Disjoint support</option></select></label><label>Candidate<select data-spec-candidate></select></label><label>Acceptance variate u<input type="range" min="0" max="99" value="50" data-spec-uniform/><output data-spec-uniform-value>0.50</output></label><button data-spec-reset>Reset stages</button><button data-spec-next>Next stage</button></div>
<div class="probability-stage" data-spec-explanation aria-live="polite"></div><div class="probability-chart" data-spec-chart></div><div class="method-table probability-table" data-spec-table></div><p class="figure-boundary">The bars are probability masses, not token speed or confidence in factual correctness. Repair bars are unconditional mass; the replacement sampler normalizes them only after rejection. The displayed replacement draw uses a fixed residual variate of 0.65.</p></figure>
<h4>Check the identity by hand</h4><p>For p=(0.1,0.4,0.2,0.3), q=(0.4,0.1,0.3,0.2), accepted output mass is (0.1,0.1,0.2,0.2). Its sum is 0.6. The missing mass is (0,0.3,0,0.1), so a rejection uses residual probabilities (0,0.75,0,0.25). Combining accepted and repaired mass restores p. Sampling a fresh replacement from p itself would generally overcount already accepted mass.</p>
<div class="derivation"><p><code>P(output=i by acceptance) = qᵢ min(1,pᵢ/qᵢ) = min(pᵢ,qᵢ)</code></p><p><code>P(output=i by repair) = max(pᵢ−qᵢ,0)</code></p><p><code>min(pᵢ,qᵢ) + max(pᵢ−qᵢ,0) = pᵢ</code></p><p>The total acceptance probability is <code>α = Σᵢ min(pᵢ,qᵢ) = 1 − ½Σᵢ|pᵢ−qᵢ|</code>. This expresses overlap of distributions, not just agreement of their most likely tokens.</p></div>
${ref("https://arxiv.org/abs/2302.01318", "Chen et al.: modified rejection sampling")}
<p>Node tests enumerate 2,025 pairs of three-token rational distributions, including zero probabilities, and verify reconstruction. A separate Python reference tests conditional two-token generation using a tiny Markov model. The mathematical identity is stronger than an empirical histogram; the histogram checks that the program's conditional control flow agrees with that identity.</p>
${check("Worked check: p assigns positive probability to a token that q never proposes. Can the output still have distribution p?", "Yes. That token's accepted mass is zero, but its positive p−q difference appears in the repair distribution. Disjoint support is an extreme case: every proposal is rejected and repair samples the target. Correctness survives, but the draft work provides no acceleration.")}
</section>

<section class="lesson" id="speculative-state" data-lesson="Draft verification, bonus tokens and KV rollback"><header><span>Stateful inference</span><h3>A rejected prefix invalidates its descendants</h3></header>
<p>A round proposes γ tokens autoregressively with the draft. The target scores the known proposal sequence, yielding the conditional distributions needed to verify the draft and, if all proposals pass, sample a bonus token. Verification accepts a contiguous prefix. After the first rejection, later scores conditioned on that rejected token do not describe the accepted history.</p>
<figure class="textbook-lab method-lab"><figcaption><span>Figure 15.2</span><strong>Three proposed tokens, one rejection</strong><p>An original state diagram. The correction can be any token permitted by the residual distribution.</p></figcaption><ol class="method-flow"><li><strong>Committed prefix: P</strong><span>Target and draft state correspond to the same accepted token history.</span></li><li><strong>Draft: a → b → c</strong><span>Provisional positions extend P. Their state is not yet committed.</span></li><li><strong>Accept a; reject b</strong><span>Keep the valid prefix P,a. Scores and KV descendants depending on b or c cannot be reused as that prefix's future.</span></li><li><strong>Sample correction d</strong><span>The accepted token sequence becomes P,a,d. d was not necessarily processed into KV by the verification pass.</span></li><li><strong>Reconcile before continuing</strong><span>Truncate logical provisional state and process the correction as needed. Both models must agree on the next prefix.</span></li></ol></figure>
<p>“Rollback” can mean adjusting logical lengths and block ownership, not physically erasing every byte. A stale KV entry must be unreachable by the next valid attention operation, even if its storage has not been cleared. Shared prefix blocks remain protected by reference ownership. Fixed-capacity buffers may be reused only with correct position indices and masks.</p>
<p>EOS and maximum-output limits are commit boundaries too. Stop at the first accepted EOS rather than streaming later speculative tokens. A correction or bonus token may need a subsequent model step before its KV exists. Separate the count of emitted tokens, the valid KV length and the number of provisional positions; assuming those counters are always equal is a common source of off-by-one errors.</p>
<div class="lesson-code"><div><h4>Read the executable conditional reference</h4></div><pre><code>python examples/inference/speculative_sampling.py
python -m unittest discover -s examples/inference -p 'test_*.py' -v</code></pre><details><summary>Complete speculative round and toy-model checks</summary><pre><code>${escapeCode(referenceSource)}</code></pre></details></div>
<p>The Python program uses two abstract tokens and serial function calls, not a Transformer executor. It checks proposal, acceptance, correction and bonus control flow; it implements no KV cache, EOS or GPU batching. Read it alongside <a href="#paged-kv">paged KV ownership</a>, then add state reconciliation tests before implementing the same idea in an engine.</p>
</section>

<section class="lesson" id="speculation-economics" data-lesson="Speculation cost and method selection"><header><span>Hardware meets inference</span><h3>High acceptance is necessary evidence, not a speedup measurement</h3></header>
<p>Under a deliberately simple independent, constant-acceptance model, a γ-token draft yields <code>E[tokens] = 1 + α + α² + … + αᵞ</code>, counting the correction or bonus. Let d be per-token drafting time, v the verification-round time and b ordinary target decode time. The illustrative speed ratio is <code>b E[tokens] / (γd + v)</code>. This omits launch overhead, queuing, cache management and resource contention.</p>
<div class="derivation"><h4>An original break-even calculation</h4><p>Take γ=4, α=0.8, d=1 ms, v=8 ms and b=8 ms. Expected emitted tokens are 3.3616, the round costs 12 ms, and the ratio is about 2.24. If drafting instead costs 6 ms per token, the same acceptance yields a 32 ms round and a ratio of 0.84: slower than the baseline. These are hypothetical inputs, not measurements from vLLM or a GPU.</p></div>
<p>In real traffic, acceptance depends on the prefix, position, proposal method and decoding policy. Verification cost depends on draft length, batch shape, attention state, precision and hardware. A target already operating near its useful compute capacity may have little spare capacity for extra verification. A memory-bound target can sometimes exploit that additional parallel work.</p>
<h4>Different proposal methods move the cost elsewhere</h4><p>A separate draft model adds its own weights, execution and cache state. Learned auxiliary predictors need compatible target features and training. N-gram or suffix proposals use repetition rather than another model. Native multi-token prediction uses architecture-specific support. None removes the need to test the actual acceptance implementation and output contract.</p>
<p>vLLM's current documentation lists multiple proposal families and explicitly discusses numerical limitations of lossless claims. Treat those pages as versioned implementation evidence: pin the engine revision, target/draft artifacts and decoding policy when reproducing a result. Do not transfer a method name or speedup from one model family to another without testing.</p>
${ref("https://docs.vllm.ai/en/latest/features/speculative_decoding/", "vLLM: proposal methods and lossless guarantees · checked September 9, 2026")}
<p>A useful report includes accepted-prefix-length distribution, draft and verification time, target executions per emitted token, peak KV/weight memory, TTFT, inter-token latency and goodput under the same offered load. Continue with <a href="#serving-lab">serving under load</a>; an isolated low-concurrency win is not automatically a fleet-level capacity improvement.</p>
</section>`);
