import { chapterMarkup, sourceLink as ref, workedCheck as check, escapeCode } from "./lesson-template";
import ripple from "../examples/rtl/ripple_adder.sv?raw";
import mac from "../examples/rtl/elastic_mac.sv?raw";
import dot from "../examples/rtl/dot4.sv?raw";
import testbench from "../examples/rtl/tb_elastic_mac.sv?raw";
import systolicRtl from "../examples/rtl/systolic3.sv?raw";
import runScript from "../examples/rtl/run.sh?raw";
const code = (title: string, source: string) => `<div class="lesson-code"><h4>${title}</h4><pre><code>${escapeCode(source)}</code></pre></div>`;
const file = (name: string, source: string) => `<details class="digital-source-code"><summary>Read ${name}</summary><div class="lesson-code"><pre><code>${escapeCode(source)}</code></pre></div></details>`;
const lesson = (id: string, label: string, title: string, body: string) => `<section class="lesson" id="${id}" data-lesson="${label}"><header><span>${label}</span><h3>${title}</h3></header>${body}</section>`;

export const digitalChapter = chapterMarkup(
  "digital-logic", "From a number to a synchronous circuit",
  "Begin with bits and voltages. Build an adder, represent a quantized weight, describe registers in Verilog, and follow a token through a circuit that can stall. These are the foundations beneath CUDA instructions, tensor cores and custom accelerators.",
  lesson("digital-abstraction", "Bits, transistors and wires", "A digital circuit makes a promise about an analog world", `
<p>A neural-network weight is a number in your mathematical model. In a machine, an encoding maps that number to a finite sequence of bits. A bit is represented by a physical state: for example, a voltage stored in a memory cell. A wire carries a changing voltage, and a receiver interprets a sufficiently low or high range as zero or one. Intermediate voltages during a transition do not become a third useful arithmetic value.</p>
<p>The useful abstraction is a contract: if inputs have valid levels and remain stable long enough, the circuit produces valid outputs implementing a specified Boolean function. Noise margins leave separation between the levels a gate produces and the levels another gate accepts. Propagation delay tells us when we can trust the result. Both electrical and timing assumptions are part of correctness.</p>
${ref("https://computationstructures.org/notes/digitalabstraction/notes.html", "Computation Structures: digital abstraction, noise margins and delay")}
<h4>Why a transistor can implement a decision</h4>
<p>A MOS transistor uses its gate voltage to control a conducting channel. In a CMOS inverter, complementary pull-up and pull-down networks connect the output toward the supply or ground depending on the input. Networks of these switches implement NAND and NOR; composing such gates gives adders, comparators and control logic. Real transistors have capacitance, leakage and finite resistance. Charging a long wire or many gate inputs takes energy and time.</p>
${ref("https://computationstructures.org/notes/cmos/notes.html", "Computation Structures: MOS switches and CMOS gates")}
<p>Follow one multiplication down the stack: a framework requests a matrix operation; a compiler selects device instructions; arithmetic units transform encoded operands; control and storage circuits schedule those transformations; transistors and wires implement their state changes. This chapter enters at the last two layers. You do not need transistor sizing to write your first kernel, but you need this physical picture to understand why a larger arithmetic array can be starved by memory or slowed by wiring.</p>
${check("Explain it back: a gate produces the correct Boolean result in a simulator. What is still missing before that gate is useful on a chip?", "A physical implementation must meet voltage, loading and timing requirements across the intended conditions. Functional simulation checks the logical relation for tested inputs; it does not establish noise margins, actual wire delay, power integrity or manufacturing correctness.")}
`) +
  lesson("binary-and-signed", "Binary and signed numbers", "Eight bits do not tell you whether the number is negative", `
<p>For an unsigned W-bit word, bit i has weight 2<sup>i</sup>. The bit at index zero is the least significant bit. Thus <code>00101101₂ = 32+8+4+1 = 45</code>. Hexadecimal groups four bits into a digit: <code>0010 1101 = 0x2D</code>. The same pattern could be an integer, an instruction field, four two-bit values or part of a floating-point number. The consuming operation supplies the interpretation.</p>
<p>Two's complement changes the weight of the top bit to −2<sup>W−1</sup>. An eight-bit signed word represents −128 through 127. Decode <code>11110011</code> as −128+64+32+16+2+1 = −13. Equivalently, decode it unsigned as 243 and subtract 256 because the sign bit is set. To encode −13, start with 13 = <code>00001101</code>, invert all eight bits, then add one: <code>11110011</code>.</p>
<div class="derivation"><h4>One encoding, two meanings</h4><p>The word <code>10000000</code> is 128 unsigned and −128 signed. Negating the most negative eight-bit signed value cannot produce +128 in eight signed bits. Modular negation returns the same pattern; a mathematical result and its finite-width representation are different objects.</p></div>
<p>When widening a signed value, repeat its sign bit: −13 becomes <code>11111111 11110011</code> at sixteen bits. Zero extension would turn the old eight-bit pattern into +243. Widen an unsigned value with zeros. Endianness is a separate convention about byte order in memory: little endian stores the least significant byte first; it does not reverse the weights of bits inside the arithmetic definition.</p>
${ref("https://computationstructures.org/notes/information/notes.html", "Computation Structures: binary information and number representations")}
${check("Worked conversion: decode 0xD6 as unsigned and as signed eight-bit. Widen the signed value to sixteen bits.", "0xD6 = 13×16+6 = 214 unsigned. With the high bit set, the signed value is 214−256 = −42. Sign extension gives 0xFFD6. Zero extension gives 0x00D6 and therefore +214.")}
${check("Worked storage check: four signed INT8 weights occupy how many payload bits? Does that include the quantization scale?", "Four times eight is 32 payload bits, or four bytes. A scale, zero point, alignment padding and packing metadata are additional storage when the representation requires them. INT8 alone does not specify that metadata.")}
`) +
  lesson("full-adder-circuit", "Build a binary adder", "A carry is information that the next bit needs", `
<p>A full adder consumes a bit from each operand plus a carry from the less significant position. Its sum bit is <code>s = a XOR b XOR cin</code>. Its outgoing carry is <code>cout = (a AND b) OR ((a XOR b) AND cin)</code>. When two or three input bits are one, the next position must receive a carry. Joining W full adders creates a ripple-carry adder: the carry can travel through all W slices before the most significant result settles.</p>
<p>Multiplexers select which signal reaches an output: <code>y = select ? b : a</code>. A comparator chooses a Boolean relation between words. Decoders activate a selected destination. Together these structures turn a mathematical algorithm into a datapath: muxes choose operands, arithmetic computes results, and control selects which result to store. Synthesis may replace your ripple structure with the target's dedicated carry chain or another optimized implementation.</p>
${ref("https://computationstructures.org/notes/combinational_logic/notes.html", "Computation Structures: combinational composition, muxes and arithmetic")}
<figure class="textbook-lab method-lab digital-lab" id="digital-bits-lab"><figcaption><span>Bit workbench</span><strong>Follow every carry and separate unsigned carry from signed overflow</strong><p>Type signed eight-bit operands. The diagram evaluates the exact Boolean equations of all eight full adders; it does not simulate physical delay.</p></figcaption><div class="method-toolbar"><label>Operand a<input data-bit-a type="number" min="-128" max="127" step="1" value="127"></label><label>Operand b<input data-bit-b type="number" min="-128" max="127" step="1" value="1"></label></div><div data-bit-output class="digital-result" aria-live="polite"></div><div data-bit-svg class="digital-diagram"></div></figure>
<h4>Overflow is about interpretation</h4>
<p>At eight bits, 127+1 produces <code>10000000</code>. There is no unsigned carry out, but the signed result wraps to −128: two positive inputs produced a negative encoding. Conversely, −1+1 adds <code>11111111 + 00000001</code>, producing a carry out and an eight-bit zero. The signed sum fits. Signed overflow for addition occurs when equally signed operands yield a result of the opposite sign; for this adder it also equals the carry into the sign bit XOR the carry out.</p>
${file("examples/rtl/ripple_adder.sv", ripple)}
${check("Worked circuit check: add 01111111 and 00000001. Why does bit 7 change even though both bit-7 inputs are zero?", "The carry from the lower seven positions reaches bit 7. Its inputs are a=0, b=0, cin=1, so the sum is 1 and the outgoing carry is 0. The pattern is correct modulo 256 and overflows signed eight-bit arithmetic.")}
`) +
  lesson("fixed-point-rtl", "Fixed-point arithmetic", "Move the binary point without changing the wires", `
<p>A signed fixed-point format is an integer encoding plus a shared scale. We will specify total width W and fractional-bit count F explicitly, avoiding the inconsistent conventions sometimes hidden in names such as Qm.n. Decode the signed stored integer q as <code>x = q × 2<sup>−F</sup></code>. With W=8 and F=4, adjacent values differ by 1/16 and the interval is −8 through 7.9375.</p>
<p>For x=1.3125, multiply by 16 to get q=21, or <code>00010101</code>. For −1.3125, q=−21, whose eight-bit encoding is <code>11101011</code>. The binary point is a software/hardware agreement; no extra point wire appears in a multiplier. General affine neural quantization instead uses a scale and possibly a zero point, <code>x ≈ s(q−z)</code>; s need not be a power of two.</p>
<figure class="textbook-lab method-lab digital-lab" id="fixed-point-lab"><figcaption><span>Representation workbench</span><strong>Trade range against fractional resolution</strong><p>Eight total bits, signed two's complement. This model rounds ties to even, then saturates to the representable endpoints.</p></figcaption><div class="method-toolbar"><label>Real input<input data-fixed-value type="number" min="-128" max="128" step="any" value="1.3125"></label><label>Fractional bits<select data-fixed-fraction><option>0</option><option>2</option><option selected>4</option><option>6</option><option>7</option></select></label></div><div data-fixed-output class="digital-result" aria-live="polite"></div><div data-fixed-table class="method-table"></div></figure>
<h4>Keep the product's scale and width</h4>
<p>Multiply signed eight-bit operands with F=4 each. A full product needs sixteen bits and has F=8. The stored integers 24 and −8 represent 1.5 and −0.5; their product −192 represents −0.75 at scale 1/256. To return to F=4, requantize −192/16 = −12. If discarded bits are nonzero, choose and implement a rounding rule. An arithmetic right shift of a negative signed value rounds toward negative infinity; it is not nearest/even rounding.</p>
<p>An accumulator needs headroom. For K full-range signed W-bit products, <code>2W + ceil(log₂ K)</code> bits is a conservative sufficient signed width for the sum, without an extra bias. With W=8 and K=4, eighteen bits cover four products of (−128)×(−128) = 16,384, whose sum is 65,536. An INT16 accumulator would overflow. Add a bias only after accounting for its scale and range; differing fractional counts require alignment first.</p>
<p>Wraparound keeps the low W bits. Saturation clamps to the endpoints. Rounding selects a nearby grid point. These are separate policies, and a model's numerical accuracy depends on the combination. The worked converter is an explicit teaching policy, not the universal behavior of GPU INT8 instructions.</p>
${check("Worked rounding: in W=8, F=4, encode 0.15625 with nearest/even rounding. What if the value is 8.5?", "0.15625×16 = 2.5, a tie between integers 2 and 3; choose even 2, reconstructing 0.125. For 8.5, the target integer is 136, above 127, so saturation stores 127 and reconstructs 7.9375. Wrapping instead would produce a negative value.")}
`) +
  lesson("verilog-combinational", "Verilog and SystemVerilog", "Describe connected hardware, then specify when state changes", `
<p>Verilog is a hardware description language; SystemVerilog extends it with stronger declarations and verification features. A <code>module</code> defines ports and internal structure. <code>[7:0]</code> declares an eight-bit packed word. <code>signed</code> changes arithmetic interpretation. A continuous assignment describes a driven combinational signal, not an instruction executed once. Multiple assignments and modules operate concurrently.</p>
${code("A mux and an explicitly widened sum", `module choose_add (
    input  logic signed [7:0] a, b,
    input  logic choose_b,
    output logic signed [7:0] selected,
    output logic signed [8:0] total
);
    always_comb begin
        selected = choose_b ? b : a;
        total = $signed({a[7], a}) + $signed({b[7], b});
    end
endmodule`)}
<p>A procedural combinational block must assign every output on every path. Writing only <code>if (enable) selected = a;</code> asks the circuit to retain the old output when enable is false; that implies storage, often an unintended latch. Provide a default and override it, or assign both branches. Use blocking <code>=</code> for these local combinational calculations. <code>always_comb</code> expresses the intent and enables tool checks; it does not repair an incomplete assignment.</p>
${ref("https://docs.amd.com/r/en-US/ug901-vivado-synthesis/Always-Procedures", "Vivado synthesis: always_comb, always_latch and always_ff")}
<p>Width and signedness deserve the same attention as tensor shapes. A bit slice or concatenation can change expression signedness; use explicit casts and extension at arithmetic boundaries. Unsized literals may introduce unexpected widths. A shift does not automatically allocate extra result bits. If an expression must preserve an eight-by-eight product, give it a signed sixteen-bit destination and inspect the elaborated result.</p>
<p>A synthesizable loop with a constant bound generally creates repeated circuit structure. It does not promise to reuse one multiplier across clock cycles. Time sharing requires registers and a controller that selects operands over time. Conversely, a loop in a testbench can generate stimuli sequentially because the testbench describes simulation activity. Keep the design and its testbench as separate top modules.</p>
${check("Design exercise: replace the two-input mux with a four-input selector. What must every branch establish?", "All paths must drive the entire selected output. A combinational case on a two-bit selector can select a, b, c or d, with a defined default for simulation unknowns. Four hardware data alternatives exist concurrently; the control chooses one path. Inspect synthesis to learn how many LUTs or mux cells implement that choice.")}
`) +
  lesson("registers-and-fsm", "Registers and state machines", "Registers remember; a controller decides when to replace their contents", `
<p>A CPU program uses instructions to change values over time. Register-transfer level, or <strong>RTL</strong>, describes the storage and connections of a circuit. Its adders and wires keep responding to their inputs between clock edges. Its <strong>registers</strong> remember values: each word is stored in a bank of flip-flops. The rising clock edge tells those registers when to capture their next values.</p>
<p>Read clocked RTL in two passes: first calculate every next value from the current state; then advance the clock and replace that state together. This mental model is the bridge from a software loop to a pipeline. Physical wires and registers still take time to respond; the <a href="#setup-hold-timing">timing lesson</a> checks whether they settle soon enough.</p>
${ref("https://computationstructures.org/notes/sequential_logic/notes.html", "Computation Structures: current state, next state and clocked storage")}
<h4>Trace two registers through three edges</h4>
${code("SystemVerilog: a complete two-register pipeline", `module two_stages (
    input  logic clk, rst,
    input  logic [7:0] in_data,
    output logic [7:0] stage0, stage1
);
always_ff @(posedge clk) begin
    if (rst) begin
        stage0 <= 0;
        stage1 <= 0;
    end else begin
        stage0 <= in_data;
        stage1 <= stage0;
    end
end
endmodule`)}
<p><code>posedge clk</code> means the transition from a low clock level to a high one. The <code>rst</code> input clears both words on an edge where it is high: this is a synchronous reset. Nonblocking assignment <code>&lt;=</code> schedules the new register value while allowing later statements to read the old one. It is not a comparison in this assignment context.</p>
${ref("https://csg.csail.mit.edu/6.375/6_375_2007_www/papers/cummings-nonblocking-snug99.pdf", "Cummings, SNUG 2000: nonblocking assignments and simulation scheduling")}
<div class="method-table"><table><caption>All register values shown after the named edge</caption><thead><tr><th scope="col">Rising edge</th><th scope="col">Input before edge</th><th scope="col">stage0 after</th><th scope="col">stage1 after</th></tr></thead><tbody><tr><td>Reset</td><td>Ignored; rst=1</td><td>0</td><td>0</td></tr><tr><td>First data edge</td><td>7; rst=0</td><td>7</td><td>0</td></tr><tr><td>Second data edge</td><td>9; rst=0</td><td>9</td><td>7</td></tr><tr><td>Third data edge</td><td>4; rst=0</td><td>4</td><td>9</td></tr></tbody></table></div>
<p>At the second edge, stage1 captures the 7 that stage0 already held. It cannot see stage0's new 9 until a later edge. Replacing both <code>&lt;=</code> assignments with blocking <code>=</code> lets the second statement see the first statement's immediate update in simulation, losing the intended two-stage behavior.</p>
<p>The pipeline accepts a new word at every data edge: input 9 enters while 7 advances. That is <strong>throughput</strong>. The wait for one word to reach the output is <strong>latency</strong>. Here a word captured into stage0 reaches stage1 at the following rising edge. Counting from its capture avoids ambiguity about whether “two stages” means two elapsed clock periods.</p>
${check("Check: swap the order of the two nonblocking data assignments. Does stage1 get the new input sooner?", "No. Both right-hand sides still use the pre-update state, so the table stays the same. These are different registers, each with one assignment on the selected branch. Source order alone does not add a clock edge.")}
<details class="deep-dive"><summary>Work through a dot product that pauses between inputs</summary>
<p>A clock enable lets a register keep its old value on an edge. Use the device's supported enable or clock-gating infrastructure; manually ANDing the clock with arbitrary logic can introduce unwanted edges. A <strong>finite state machine</strong> stores which step a circuit is in and uses that state plus current inputs to decide what happens next.</p>
<p>The supplied dot4 has three states: WAIT accepts the first product; RUN accumulates the next three; RESULT holds the answer until it is consumed. A transfer occurs only when <code>in_valid &amp;&amp; in_ready</code> is true at the edge. Valid says the input is meaningful; ready says the circuit can accept it. The next lesson develops this <a href="#ready-valid-pipeline">handshake</a>.</p>
${ref("https://computationstructures.org/notes/fsms/notes.html", "Computation Structures: state registers, next-state logic and outputs")}
<p>Try accepted pairs (2,3), (1,4), (−1,5), (3,2). The partial sums are 6, 10, 5, 11. A five-cycle pause after the second pair leaves the sum at 10 and the accepted-pair count at two. Elapsed cycles do not add mathematical terms. On the fourth acceptance, the code stores <code>acc + wide_product</code> into y. Writing only <code>y &lt;= acc</code> there would capture the old sum 5 and omit the final product 6.</p>
<p>Moore-style outputs depend only on state; Mealy-style outputs also depend on current inputs. Either can implement a valid controller, but combinational dependencies affect timing and can create loops when modules connect. The supplied dot4 uses state-derived ready and valid. It deliberately leaves a result-transfer cycle between vectors; optimizing that bubble requires a revised, tested protocol.</p>
${file("examples/rtl/dot4.sv", dot)}
${check("Trace exercise: a dot4 has accepted two input pairs, then in_valid stays low for five cycles. What changes?", "Neither the partial sum nor the accepted-pair count changes. The controller remains in RUN. Five elapsed cycles are not five additional mathematical terms. Once two more pairs are accepted, RESULT presents the completed four-term dot product.")}
</details>
`) +
  lesson("ready-valid-pipeline", "Ready and valid handshakes", "A token moves only when both sides agree at the edge", `
<p>A streaming interface has payload, valid and ready. The producer asserts valid when it presents a meaningful payload. The consumer asserts ready when it can accept that payload. A transfer occurs on a clock edge where both are asserted. Once the producer presents an unaccepted valid token, it must keep valid and payload stable until acceptance. A producer must not wait for ready before deciding to assert valid: a consumer that waits for valid could otherwise deadlock with it.</p>
${ref("https://developer.arm.com/-/media/Arm%20Developer%20Community/PDF/IHI0022H_amba_axi_protocol_spec.pdf", "Arm AMBA AXI: valid/ready dependencies and stable payload rules")}
<p>Our teaching channel uses these transfer rules but is not a complete AXI interface. A ready signal going high is permission for that edge's transfer, not permission to overwrite a stalled output in advance. Backpressure is the propagation of unavailable capacity toward the source. A FIFO absorbs a finite burst; it cannot solve a permanent mismatch where the average arrival rate exceeds the departure rate.</p>
<div class="derivation"><h4>Derive an elastic register's readiness</h4><p>A one-slot stage can accept if it is empty, or if its current token will leave on this edge: <code>ready_here = !valid_here || ready_next</code>. If neither is true, hold both its valid bit and payload. In a chain, calculate readiness from downstream capacity. Every register still updates from pre-edge values, so an old token can leave as a new one replaces it without duplication.</p></div>
<figure class="textbook-lab method-lab digital-lab" id="elastic-pipeline-lab"><figcaption><span>Cycle workbench</span><strong>Stall the consumer and watch the two slots fill</strong><p>Each input computes a×b+c independently. The product and its matching addend occupy the first stage; the sum occupies the second. Start with the consumer stalled, then release it after three clock edges.</p></figcaption><div class="method-toolbar"><label><input data-elastic-ready type="checkbox"> Consumer ready</label><button data-elastic-next>Advance clock edge</button><button data-elastic-reset>Reset circuit</button></div><div data-elastic-output class="digital-result" aria-live="polite"></div><div data-elastic-svg class="digital-diagram"></div><div data-elastic-table class="method-table"></div><p class="figure-boundary">Exact transaction-level register model for this two-stage circuit. Combinational ready propagation has zero modeled delay. A large physical chain needs timing analysis and may require skid buffers or registered flow control.</p></figure>
<p>Latency counts time until one input's result appears or is consumed; define which. In this design a token accepted at edge 1 occupies the product stage afterward, reaches the result stage after edge 2, and can be consumed at edge 3. Under continuous readiness, successive tokens can be consumed every cycle once the pipeline is filled. An initiation interval of one cycle does not mean zero latency.</p>
${check("Worked stall: both stages are full and the consumer becomes ready. Can input, internal advance and output transfer all happen on one edge?", "Yes. The consumer takes the old result; the old product becomes the new result; a new input becomes the new product. Every operation uses pre-edge values, and both storage slots remain occupied afterward. The scoreboard must compare the consumed old result before counting newly accepted work.")}
`) +
  lesson("setup-hold-timing", "Setup and hold timing", "Slow paths threaten setup; fast paths threaten hold", `
<p>A launching register takes clock-to-Q delay before its new output emerges. The combinational path adds gate and wire delay. The receiving register needs its data stable for a setup interval before the capture edge and a hold interval after that edge. Analyze the latest possible arrival for setup and the earliest possible arrival for hold; a single typical delay cannot establish both.</p>
<p>Let capture-clock skew s be capture arrival minus launch arrival: positive s means the capture clock arrives later. Our simplified constraints are <code>setup slack = T + s − tsetup − u − tcq,max − tlogic,max</code> and <code>hold slack = tcq,min + tlogic,min − s − thold − u</code>. The uncertainty u is a deliberately symmetric budget in this model. Production tools use the appropriate clock edges, uncertainty, derating and path exceptions for each analysis.</p>
${ref("https://computationstructures.org/notes/sequential_logic/notes.html", "Computation Structures: synchronous timing and setup/hold constraints")}
<figure class="textbook-lab method-lab digital-lab" id="digital-timing-lab"><figcaption><span>Timing workbench</span><strong>Change clock period and skew; watch two different constraints respond</strong><p>Teaching delays in nanoseconds: clock-to-Q max/min 0.12/0.04, setup 0.08, hold 0.05, minimum logic delay 0.08, uncertainty 0.03. The maximum logic delay includes an imagined routed path.</p></figcaption><div class="method-toolbar"><label>Period, ns<input data-timing-period type="range" min="0.5" max="5" step="0.05" value="1"></label><label>Max logic delay, ns<input data-timing-delay type="range" min="0.1" max="4" step="0.05" value="0.7"></label><label>Capture skew, ns<input data-timing-skew type="range" min="-0.25" max="0.25" step="0.01" value="0"></label></div><div data-timing-output class="digital-result" aria-live="polite"></div><div data-timing-svg class="digital-diagram"></div><div data-timing-table class="method-table"></div><p class="figure-boundary">Illustrative single-cycle register path. The hold row uses an expanded horizontal scale. No actual device library, process/voltage/temperature corners or extracted routing parasitics are modeled.</p></figure>
<p>Increasing the clock period can fix this setup violation. It does not fix the modeled same-edge hold violation, because T is absent from the hold equation. Positive capture skew improves setup slack while reducing hold slack. Hold repair often inserts delay or changes routing, and that repair can affect other constraints. Adding a pipeline stage shortens combinational depth per cycle but costs registers, clock load, latency and another set of paths to check.</p>
${check("Worked timing: for the default 1 ns period and 0.7 ns maximum logic delay, calculate both slacks. Then add 0.1 ns positive capture skew.", "Default setup slack is 1−0.08−0.03−0.12−0.70 = 0.07 ns. Hold slack is 0.04+0.08−0.05−0.03 = 0.04 ns. Positive skew of 0.10 gives setup slack 0.17 ns and hold slack −0.06 ns. Lowering frequency alone does not repair that hold failure.")}
`) +
  lesson("metastability-cdc-reset", "Clock domains and reset", "A second clock creates a protocol problem", `
<p>An input from an unrelated clock can transition inside a receiver's setup/hold window. The receiving flip-flop can become metastable: its internal analog state takes longer to resolve into a valid digital level. Ordinary RTL simulation cannot faithfully predict that analog event. A synchronizer gives the state more time to settle before downstream logic observes it; it reduces the probability of failure without making it mathematically zero.</p>
<p>A common single-bit level synchronizer uses two or more receiving-domain registers. Use the target's supported synchronizer primitive or attributes, constrain it correctly and inspect placement and metastability reports. More settling time generally improves mean time between failures; the estimate also depends on clock rate, input toggle rate and device-specific characterization.</p>
${ref("https://www.intel.com/content/www/us/en/docs/programmable/683068/18-1/metastability-analysis.html", "Intel Timing Analyzer: synchronization chains and MTBF analysis")}
<h4>Why synchronizing every bit separately breaks a bus</h4>
<p>Suppose a binary counter changes from 0111 to 1000. All four bits change, and independent synchronizers may expose a combination the source never held. Multi-bit ownership needs a protocol. A request/acknowledge scheme can hold a data bus stable while synchronized control transfers its ownership. A sustained stream commonly uses an asynchronous FIFO, with local read/write ports and synchronized occupancy information.</p>
<p>Gray-coded FIFO pointers change one bit per adjacent increment; this helps transfer pointer progress across domains. It does not mean arbitrary Gray-coded buses need no constraints. Correct full/empty detection, pointer wrap bits, synchronizer structure, reset sequencing and physical skew assumptions still matter. A short pulse may vanish entirely when sampled by a slower clock; use pulse stretching with a stated timing contract, a toggle protocol or a handshake that preserves the event.</p>
${ref("https://docs.amd.com/r/en-US/ug949-vivado-design-methodology/Clock-Domain-Crossing", "AMD UG949: CDC circuits, synchronizers and XPMs")}
<p>Reset also crosses timing boundaries. The supplied single-clock examples use a synchronous active-high reset: an edge is needed to clear state. Designs using asynchronous reset assertion usually need a controlled deassertion strategy in each domain. Resetting a pipeline flushes transactions; a host must know whether outstanding commands were discarded. A false-path constraint changes what timing analysis checks; it cannot turn an unsafe crossing into a safe circuit.</p>
${check("Design diagnosis: an eight-bit data bus passes through eight independent two-flop synchronizers and occasionally produces impossible values. What would you change?", "Choose a bus-transfer protocol. For infrequent data, hold all bits stable at the source until a synchronized request/acknowledgment exchange completes. For streaming traffic, use a properly designed asynchronous FIFO. Independently reducing each bit's metastability risk does not ensure coherent multi-bit sampling.")}
`)
);

export const fpgaChapter = chapterMarkup(
  "fpga-asic", "Build an accelerator, then account for its wires",
  "Turn the circuits into runnable RTL, map them onto FPGA resources, and carry the design through memory scheduling, systolic execution and ASIC implementation. Correct outputs, valid protocols, timing closure and system integration are separate pieces of evidence.",
  lesson("fpga-fabric-resources", "Inside an FPGA", "An FPGA configures a circuit from resources that already exist", `
<p>A field-programmable gate array contains configurable logic, registers, programmable interconnect and fixed-function resources. Loading a bitstream configures how these resources connect and behave. It does not fabricate a new transistor for every operation in your source. A CPU normally executes an instruction sequence on an existing datapath; an FPGA can configure many datapaths to operate concurrently, with the amount of parallelism limited by the fabric and the design.</p>
<h4>LUTs are small truth tables</h4>
<p>A k-input lookup table stores 2<sup>k</sup> output bits for a Boolean function; the current inputs select one entry. A six-input, one-output LUT can therefore represent any Boolean function of six inputs using 64 configuration bits. It is not six arithmetic processors. AMD UltraScale LUT6_2 primitives expose six inputs and two outputs with documented restrictions on how the functions share inputs and table contents.</p>
${ref("https://docs.amd.com/r/en-US/ug574-ultrascale-clb/LUT-Primitives", "AMD UltraScale UG574: LUT6_2 functions and configuration bits")}
<p>Nearby flip-flops store state. Dedicated carry circuitry accelerates appropriate addition/comparison structures. DSP blocks implement common multiply/add datapaths more efficiently than building every multiplier from general LUT logic. AMD's UltraScale DSP48E2 includes a signed 27×18 multiplier; matching widths, pipeline controls and arithmetic patterns influence whether the tool can use it.</p>
${ref("https://docs.amd.com/r/2022.2-English/ug1483-model-composer-sys-gen-user-guide/DSP48E2", "AMD: DSP48E2 ports, multiplier and datapath configuration")}
<p>Block RAM is on-chip memory with a defined number of ports, aspect ratios, latency and read/write collision behavior. UltraScale 36 Kb blocks can be divided into two independently controlled 18 Kb blocks. A declaration of a large array does not guarantee efficient BRAM inference: asynchronous reads, reset-every-element logic or unsupported port behavior can force registers and LUTs instead.</p>
${ref("https://docs.amd.com/r/en-US/ug573-ultrascale-memory-resources/Block-RAM-Introduction", "AMD UltraScale UG573: block RAM organization")}
${check("Resource exercise: a six-input function has 64 possible input combinations. How many table bits define one Boolean output, and how many bits define eight unrelated outputs?", "One output requires 64 truth-table bits. Eight unrelated outputs require 512 truth-table bits in the abstract. Physical packing, shared inputs and device LUT modes determine the actual primitive count; a truth table does not imply a free eight-bit arithmetic operation.")}
`) +
  lesson("rtl-simulation-synthesis", "From RTL to hardware", "Elaborate, simulate, synthesize, place, route and check", `
<p>Elaboration resolves parameters, hierarchy and generated structures. Simulation evaluates behavior over the testbench's events and times. Synthesis transforms the supported RTL into a netlist of logic and storage, then maps that netlist to target resources. A passing simulation and a successful synthesis answer different questions: what did the tested behavior do, and what circuit did the tool infer?</p>
${ref("https://yosyshq.readthedocs.io/projects/yosys/en/v0.53/getting_started/", "Yosys: synthesis workflow and inspecting a design")}
<ol class="method-flow"><li><strong>State the contract</strong><span>Widths, signedness, rounding, accepted-input conditions, output ordering, reset and latency.</span></li><li><strong>Simulate and compare</strong><span>Drive corner cases and stalls; compare every consumed output with a reference calculation.</span></li><li><strong>Synthesize</strong><span>Check inferred registers, latches, arithmetic, RAMs and DSPs. Resolve warnings deliberately.</span></li><li><strong>Place and route</strong><span>Choose legal physical resources and wire them. Congestion and distance now shape delay.</span></li><li><strong>Analyze timing</strong><span>Check clocks, I/O delays, setup, hold and CDC assumptions. Inspect the actual worst paths.</span></li><li><strong>Program and observe</strong><span>On a compatible board, configure the device and compare measured outputs and throughput with the model.</span></li></ol>
<p>Do not hide missing constraints with a high maximum-frequency number. A design with no meaningful clock or I/O requirements can appear unconstrained rather than fast. Vendor FPGA flows need a concrete part, clock definition and board-specific pin/electrical constraints. This repository does not invent a pin map for a board you have not selected.</p>
${code("Optional generic synthesis inspection with Yosys", `yosys -p 'read_verilog -sv examples/rtl/elastic_mac.sv; hierarchy -check -top elastic_mac; proc; opt; check; stat'
# Generic synthesis can continue with: synth -top elastic_mac; stat
# A device-specific synth command, constraints, and place/route are separate steps.`)}
<p>Generic netlist statistics cannot establish FPGA DSP use, routed frequency or ASIC area. A target technology's libraries and mapping rules are needed for those claims. Keep the RTL revision, tool version, constraints, reports and command lines together so someone else can reproduce the result.</p>
`) +
  lesson("rtl-self-checking", "Test your RTL", "A waveform helps you inspect; a scoreboard tells you when you are wrong", `
<p>The supplied examples have executable testbenches. The adder test enumerates all 65,536 eight-bit operand pairs, checking both the nine-bit unsigned result and signed overflow. The elastic-MAC test applies deterministic pseudorandom operands, source bubbles, sustained consumer stalls, simultaneous transfers and an in-flight reset. A reference queue records expected values when inputs are accepted, then compares values when outputs are consumed.</p>
<p>The systolic-array test checks all nine accumulators after every cycle for 18 tiles, including signed extremes and deliberately nonzero invalid padding. The dot-product test sends 64 four-term vectors with pauses between operands and holds each result under backpressure. Its all-−128 vector checks accumulator headroom. The harness drives inputs on falling edges and observes transfers on rising edges, avoiding a testbench race with register updates. The code intentionally separates simulation delays from synthesizable modules.</p>
${code("Run all RTL examples from the repository root", `# Install Icarus Verilog using your platform's package manager first.
# macOS with Homebrew: brew install icarus-verilog
# Debian/Ubuntu: sudo apt-get install iverilog
sh examples/rtl/run.sh
# Each test prints PASS or exits with a failing status through $fatal.
# With Yosys installed, also synthesize and re-simulate all four netlists:
sh examples/rtl/synth.sh
# YoWASP alternative: RTL_YOSYS=yowasp-yosys sh examples/rtl/synth.sh`)}
${file("examples/rtl/run.sh", runScript)}
${file("examples/rtl/tb_elastic_mac.sv", testbench)}
<h4>Checks that test the protocol, not only arithmetic</h4>
<p>Count accepted inputs and consumed outputs within a reset epoch. Their difference must equal valid work still stored in the pipeline. Assert that <code>out_valid &amp;&amp; !out_ready</code> keeps payload and valid stable across the next edge. Check ordering and duplicates, not merely the final sum of all results: swapping two answers can leave that sum unchanged. A reset flush means global lifetime counts need not match across reset boundaries.</p>
<p>A useful next step is a formal property such as “output remains stable while stalled,” under an explicit source-stability assumption. Bounded checking explores only its configured horizon unless extended by an induction argument. Assertions cannot prove a missing specification, and a passing event-driven simulation does not establish metastability reliability or routed timing.</p>
${check("Break-and-repair exercise: remove the result_ready guard around the output register update. Which test should fail and why?", "When the consumer stalls, the result can be overwritten by another token. The output-stability assertion or queue comparison should fail. A test that only runs with out_ready=1 could miss this bug entirely. Restore the guard, rerun the harness, and retain the failure log as evidence that the check detects the defect.")}
`) +
  lesson("pipelined-mac-rtl", "Pipeline a multiply-add", "Carry the addend and the validity alongside the product", `
<p>The two-stage module below computes an independent <code>y=a×b+c</code> transaction. The first register stores the signed product and its corresponding addend; the second stores the widened sum. It is a pipelined multiply-add, not a recurrent running accumulator. The separate dot4 design shows a recurrence where the previous partial sum is an operand.</p>
<p>Eight-bit signed a and b need a sixteen-bit full product. The addend c has twenty signed bits. We sign-extend both to twenty-one bits before addition, preserving the full mathematical result for all input encodings. For example, a=b=−128 and c=524,287 produce 540,671, which exceeds the largest signed twenty-bit value but fits in twenty-one bits.</p>
${file("examples/rtl/elastic_mac.sv", mac)}
<p>Why store c beside the product? Suppose transaction 0 has c=5 and transaction 1 has c=−2. Reading the current input c when adding yesterday's registered product would combine operands from different requests. The token consists of data plus any metadata needed later: bias, scale, destination address, packet boundary and validity can all need matching delay.</p>
<p>The elastic readiness logic permits one accepted transaction per cycle under continuous downstream readiness after filling. A longer ready chain can become the critical path even if multiplication is well pipelined. Registering ready without adding storage changes the acceptance contract and can lose a token; a skid buffer provides capacity for a token already permitted before the stop signal arrives.</p>
<p>On an FPGA, the synthesis report must show whether the arithmetic and registers map into DSP resources or general fabric. Reset styles, clock enables, width and packing can affect mapping. On an ASIC, synthesis selects standard cells or arithmetic structures from the target flow. The same RTL therefore does not imply the same frequency, area or energy across targets.</p>
${check("Worked width audit: why is a twenty-bit c plus a sixteen-bit product given a twenty-one-bit output?", "The sum can exceed the twenty-bit signed range. For example, 524287 + 16384 = 540671, above 524287. Sign-extension to twenty-one bits preserves both operands and leaves enough headroom for every legal pair. Narrowing after addition requires a specified saturation or wrap policy.")}
`) +
  lesson("fpga-memory-banking", "Memory banks and ports", "Capacity is not a promise of enough read ports", `
<p>Suppose sixteen multipliers each need one new activation and one new weight every cycle. At eight bits per operand, their unreused demand is 32 bytes per cycle. At a declared 200 MHz, that is 6.4 GB/s of operand delivery. This arithmetic is a port-bandwidth requirement at the chosen boundary; it is not a measured board bandwidth or an HBM specification.</p>
<p>A memory can have enough total bits and still fail this requirement because its ports cannot deliver the required independent addresses. Banking partitions storage into multiple independently accessed memories. Replication provides extra read copies while increasing storage and write-update obligations. Broadcasting delivers one common value to many consumers, reducing reads but increasing fanout and wiring.</p>
<div class="derivation"><h4>Bank mapping is an address function</h4><p>Use four single-read teaching banks with <code>bank(address)=address mod 4</code>. Addresses 0,1,2,3 can be read together. Addresses 0,4,8,12 all target bank zero and require serialization or a different organization. Padding or a different layout changes the mapping; it does not create extra ports in the original bank.</p></div>
${code("A synchronous read has a cycle boundary", `reg [7:0] memory [0:255];
reg [7:0] read_data;
always @(posedge clk) begin
    if (write_enable) memory[write_address] <= write_data;
    if (read_enable)  read_data <= memory[read_address];
end
// Specify read-during-write behavior before relying on a particular RAM mode.
// Also pipeline read-valid and any tag needed to interpret read_data.`)}
<p>A register array, distributed RAM, block RAM and external DRAM have different latency/port contracts. Do not infer a hardware memory model from a software array's indexing syntax. Check what the tool inferred, including whether a reset loop prevented RAM mapping. For read/write collisions, use the device's documented mode or explicit forwarding; do not depend on a simulator's accident of statement ordering.</p>
${ref("https://docs.amd.com/r/en-US/conversion-methodology/Internal-Memory?contentId=tgTcDKZtDiSqpQypuWKcbg", "AMD: distributed RAM, block RAM and UltraRAM organizations")}
<p>Double buffering separates a tile being consumed from the next tile being filled. It requires two storage lifetimes and a completed-transfer signal before swapping roles. If the fill takes 900 cycles and compute takes 500, the steady-state pipeline still exposes at least 400 cycles of fill pressure unless reuse, bandwidth or work organization changes. The same logic applies to GPU shared-memory staging.</p>
${check("Worked banking: can four single-read banks serve addresses 2,6,10,14 in one cycle with address mod 4 mapping? Propose two ways to change the design.", "No: every address maps to bank 2. Change the layout/bank mapping so the simultaneous access pattern spreads over banks, or duplicate the read-only data across memories and route each read to a different copy. Time-multiplexing the reads is another option if the throughput contract permits four cycles.")}
`) +
  lesson("systolic-array-cycles", "Trace a systolic array", "Make matching operands arrive together, then keep the partial sum local", `
<p>For C=A×B, output C[i,j] is a sum over k of A[i,k]×B[k,j]. A systolic array places processing elements, or PEs, in a regular grid. In this output-stationary example, A moves right one PE per cycle, B moves down one PE per cycle, and each PE keeps its own C accumulator. Neighbor communication replaces repeatedly reading both operands from a distant memory.</p>
<p>Injection must be skewed. Delay A row i by i cycles and B column j by j cycles. Then term k reaches PE(i,j) at zero-based cycle <code>t=k+i+j</code>. Both operands refer to the same k. Sending every row and column without that skew would align the wrong terms at interior PEs. Valid signals distinguish a missing operand from a legitimate arithmetic zero.</p>
<figure class="textbook-lab method-lab digital-lab" id="digital-systolic-lab"><figcaption><span>Array workbench</span><strong>Step an exact 3×3 matrix product through seven cycles</strong><p>Every active cell shows the operand pair, k index and partial sum after that cycle. Complete cells retain their output while the far corner finishes.</p></figcaption><div class="method-toolbar"><button data-systolic-prev>Previous cycle</button><button data-systolic-next>Next cycle</button><button data-systolic-reset>Reset array</button></div><div data-systolic-output class="digital-result" aria-live="polite"></div><div data-systolic-svg class="digital-diagram"></div><div data-systolic-table class="method-table"></div><p class="figure-boundary">Logical cycle model, one hop and one multiply-accumulate per active PE per cycle. It does not model DSP internal latency, output drain traffic, finite SRAM ports, flow-control stalls or routed frequency.</p></figure>
${file("examples/rtl/systolic3.sv", systolicRtl)}
<p>The runnable array stores separate operand-valid bits and clears accumulators between tiles. Its testbench checks every PE after every cycle for the displayed matrix and additional signed cases. The feeder must supply the specified skew: matching valid bits alone cannot prove that two arriving operands share the same k index. There is no backpressure in this array, so the feeder and result reader must obey the fixed schedule.</p>
<h4>Fill and drain change utilization</h4>
<p>For an N×N array and K reduction terms, this single isolated tile occupies K+2(N−1) cycles from the first computation to the last. It performs N²K useful MACs. With N=3 and K=3, that is 27 MACs across 7 cycles and 9 PEs, so average arithmetic-slot use is 27/63 ≈ 42.9%. The active counts are 1,3,6,7,6,3,1. A deep reduction or overlapping tiles can amortize edge effects if buffering and the output protocol permit it.</p>
<p>For a visual companion, read <strong>TinyTPU: the why and how</strong>. Its cycle-by-cycle diagrams follow a small educational accelerator from a multiply-accumulate PE through staggered inputs, pipelining, double-buffered weights and a neural network's forward and backward passes. Compare its weight-stationary array with the output-stationary workbench above: TinyTPU keeps weights in the PEs while partial sums move down the array; our workbench keeps each output sum local while both operands move. The project documents the authors' own learning design, rather than a replica of Google's TPU.</p>
${ref("https://www.tinytpu.com/", "TinyTPU: illustrated accelerator architecture walkthrough")}
<p>The original Google TPU study provides a real example of an ASIC using a large matrix multiply unit and software-managed data movement. Its organization and workload results are specific to that generation; our nine-cell output-stationary teaching schedule is not a cycle reconstruction of a TPU. Use the paper to compare where weights, activations and accumulators reside.</p>
${ref("https://research.google/pubs/in-datacenter-performance-analysis-of-a-tensor-processing-unit/", "Google / ISCA 2017: in-datacenter TPU architecture and measurements")}
${check("Worked schedule: when does the k=2 term reach PE(2,1), and what value does that PE hold after all three terms?", "The term arrives at zero-based t=2+2+1=5, the sixth displayed cycle. C[2,1] = 7×1 + 8×2 + 9×0 = 23. The zero product is still a valid third term and must advance the completion count.")}
`) +
  lesson("accelerator-dataflows", "Accelerator data reuse", "Choose which operand stays close, then count what still moves", `
<p>A dataflow specifies where values live and when they move. Output stationary keeps a partial sum local while k advances. Weight stationary retains weights while multiple activation rows pass through. Input stationary retains activations while reusing them across outputs. These descriptions are incomplete without tile sizes, memory hierarchy, loop order and the ownership of reductions between tiles.</p>
<p>For a tiled GEMM with M=N=K=16, INT8 inputs and INT32 outputs, one complete input pair has 256+256 bytes. Holding all output accumulators takes 256×4 = 1,024 bytes. The tile performs 16³ = 4,096 MACs, or 8,192 arithmetic operations if a multiply and add count separately. If each input is fetched once and each output written once, off-chip payload is 1,536 bytes and intensity is 8,192/1,536 ≈ 5.33 operations/byte. This excludes addresses, scale metadata and protocol overhead.</p>
<p>Change the boundary and the byte count changes. Inside the array, operands still traverse links and accumulators update repeatedly. Split K into two chunks and spill partial outputs between them, and additional accumulator reads/writes appear. Sharing A across adjacent output tiles can reduce external reads while requiring more live outputs or additional scheduling. State the reuse assumption before using the arithmetic intensity to choose hardware.</p>
${ref("https://research.nvidia.com/publication/2016-06_eyeriss-spatial-architecture-energy-efficient-dataflow-convolutional-neural", "Eyeriss: a measured architecture organized around reducing data movement")}
<h4>The model compiler makes a schedule that the hardware can execute</h4>
<p>An accelerator compiler lowers operators into supported arithmetic, assigns layouts, chooses tiles, plans memory, schedules DMA transfers and emits commands. Unsupported shapes need padding or fallback kernels; padding can consume physical work without increasing useful model FLOPs. Sparse or mixture-of-experts traffic may create irregular work and load imbalance that a uniform dense schedule handles poorly. A fixed-function datapath needs an explicit policy for those cases.</p>
<p>For an LLM, dense projections are only part of execution. Norms, reductions, nonlinear functions, softmax, positional transformations, KV addressing and sampling also need hardware, microcode or a host fallback. Moving a tiny operation off chip between every layer can erase a fast GEMM's benefit. Quantized arithmetic additionally requires compatible scale handling and a validated approximation error budget.</p>
${check("Worked traffic revision: for the 16×16 tile, split K into two phases and spill/reload the INT32 partial C once. What happens to the ideal byte count?", "The original 1536-byte count gains one 1024-byte partial-output write and one 1024-byte read, for 3584 bytes. Useful work stays 8192 operations, so ideal off-chip intensity falls to about 2.29 operations/byte. Keeping partial sums on chip avoids that particular traffic at the cost of live accumulator storage.")}
`) +
  lesson("asic-physical-design", "ASIC physical design", "The netlist must fit, route, meet timing and receive power", `
<p>An application-specific integrated circuit fixes its circuit implementation in manufactured silicon. It can replace programmable switches and general fabric with purpose-built datapaths, memories and interconnect. That creates opportunities for efficiency while committing the project to implementation cost, verification effort and a workload/programmability contract. An FPGA prototype can validate parts of that contract, but its frequency and resource count are not ASIC predictions.</p>
<ol class="method-flow"><li><strong>Technology mapping</strong><span>Map logic into available standard cells; integrate characterized SRAM macros and other hard IP.</span></li><li><strong>Floorplanning</strong><span>Reserve die/core area, place large macros, plan pins, channels and power distribution.</span></li><li><strong>Placement</strong><span>Assign legal cell locations while balancing wire length, density, congestion and timing.</span></li><li><strong>Clock-tree synthesis</strong><span>Distribute clocks with controlled skew and latency; account for the clock network's load.</span></li><li><strong>Routing and extraction</strong><span>Connect nets on legal metal layers, then estimate or extract wire resistance and capacitance.</span></li><li><strong>Signoff checks</strong><span>Check timing corners, physical rules, connectivity, power integrity and the project's verification requirements.</span></li></ol>
${ref("https://openroad-flow-scripts.readthedocs.io/en/latest/tutorials/FlowTutorial.html", "OpenROAD flow tutorial: floorplan, placement, clock tree, routing and reports")}
<p>Placement can make an elegant dataflow physically expensive. A central SRAM feeding hundreds of PEs creates long, high-fanout paths. Duplicating buffers can reduce fanout and increase area/power. Routing congestion may force detours, worsening delay. A larger array can increase local throughput while lowering achievable frequency or exhausting memory delivery. The critical path can run through ready logic, address generation or reduction control rather than a multiplier.</p>
<h4>Power and package limits belong in the design</h4>
<p>A first-order switching model is <code>Pdynamic ≈ αCV²f</code>, where α captures switching activity, C switched capacitance, V voltage and f frequency; the exact event-count convention determines any constant factor. It explains why extra wiring and clock load matter, but it omits leakage and many physical effects. Lower voltage can save energy while slowing gates; raising clock frequency can increase demand beyond cooling or power-delivery limits.</p>
<p>Static timing analysis checks path constraints over characterized conditions instead of enumerating input waveforms. Process, voltage and temperature variation change delay. Voltage drop through the power network can slow cells; excessive current density threatens interconnect reliability. Design-rule checking verifies geometric constraints, while layout-versus-schematic checks extracted connectivity against the intended circuit. These checks are distinct from proving the neural network's numerical outputs correct.</p>
${check("Design review: generic synthesis reports fewer cells after a change, but routed frequency falls. Is that contradictory?", "No. Sharing logic can reduce cell count while increasing fanout, mux depth or wire length. A physical implementation pays for locations and connections. Compare the worst routed paths, congestion and constraints before attributing the result solely to the arithmetic unit count.")}
`) +
  lesson("hardware-examples-and-interfaces", "Devices and interfaces", "Different devices expose different useful resources", `
<div class="method-table"><table><caption>Examples to compare by mechanism, not a vendor ranking</caption><thead><tr><th scope="col">Example</th><th scope="col">Useful architectural question</th><th scope="col">Exercise</th></tr></thead><tbody><tr><th scope="row">Lattice iCE40 UltraPlus</th><td>A small FPGA combines LUT fabric, embedded memories and DSP blocks.</td><td>Fit a serial dot product, then count the resource cost of parallel copies.</td></tr><tr><th scope="row">AMD UltraScale / UltraScale+</th><td>LUTs, DSP48E2 slices, RAM columns and routing constrain pipelined arithmetic.</td><td>Compare inferred DSP use and timing for two register placements.</td></tr><tr><th scope="row">Agilex 7</th><td>Variable-precision DSP configurations change how arithmetic packs.</td><td>Match operand formats to a documented supported DSP mode.</td></tr><tr><th scope="row">Google TPU v1</th><td>A matrix unit is coupled to explicit buffering and an execution schedule.</td><td>Trace one layer's weights, activations and accumulated outputs.</td></tr><tr><th scope="row">Eyeriss research ASIC</th><td>Data reuse is designed around movement through a hierarchy.</td><td>Compare a convolution mapping with an LLM matrix projection.</td></tr></tbody></table></div>
<p>The iCE40 UltraPlus family datasheet documents concrete multiplier and memory resources. The Agilex variable-precision DSP guide describes configurations such as two 18×19 multipliers or one 27×27 multiplier for the covered generation. Those are resource examples, not interchangeable peak-performance units. Check the exact part, mode, clock and tool version before extrapolating a design.</p>
${ref("https://www.latticesemi.com/-/media/LatticeSemi/Documents/DataSheets/iCE/FPGA-DS-02008-1-9-iCE40-UltraPlus-Family-Data-Sheet.ashx?document_id=51968", "Lattice: iCE40 UltraPlus family datasheet")}
${ref("https://cdrdv2-public.intel.com/666477/ug-ag-dsp-683037-666477.pdf", "Intel Agilex: variable-precision DSP blocks user guide")}
<h4>A host-facing accelerator is a system</h4>
<p>The host needs a command protocol: buffer addresses, shapes, strides, dtype, completion and error status. A DMA engine moves data under a memory-ownership contract. PCIe or another link has transfer overhead and finite bandwidth; device memory may not be coherent with a CPU cache. Software must use the platform's proper allocation, mapping and synchronization APIs rather than treating a device address as a normal host pointer.</p>
<p>At minimum, define who owns each buffer before enqueue, while DMA operates, while compute reads or writes, and after completion. An interrupt or completion queue announces an event; it does not erase the need for memory ordering. Include timeouts, invalid-command handling and reset recovery. These details connect a correct standalone MAC to a reliable model-serving path.</p>
<p>Measure application latency as host preparation + transfer + queueing + compute + result handling, subtracting only overlap actually observed. A fast on-chip loop can remain a slow application when commands are tiny or weights repeatedly cross a narrow host link. Persistent device-resident weights and batched commands can amortize those costs if the workload's latency and memory constraints allow them.</p>
`) +
  lesson("fpga-asic-capstone", "Build a small accelerator", "Build a small accelerator whose claims can be reproduced", `
<p>The target is a signed INT8 dot-product engine with an explicit accumulator width, a ready/valid interface and a reference program. Start with the four-term implementation, then parameterize K and add storage. Keep the result numerically exact before introducing quantization or approximate arithmetic. The project is complete when another person can reproduce the behavior and inspect the evidence for each claimed property.</p>
<ol class="method-flow"><li><strong>Write the specification</strong><span>State operand range, K limit, output width, whether bias exists, transfer rule, reset behavior, and whether requests may overlap.</span></li><li><strong>Build a golden model</strong><span>Use wide integer arithmetic, produce adversarial vectors, and include minimum-negative products and mixed signs.</span></li><li><strong>Validate the serial engine</strong><span>Test bubbles, stalls, vector boundaries, reset mid-vector, duplicate/lost outputs and malformed commands.</span></li><li><strong>Pipeline or parallelize</strong><span>Compare one reused multiplier, several multipliers with a reduction tree, and an elastic pipelined datapath under the same contract.</span></li><li><strong>Feed the arithmetic</strong><span>Choose banks, model read latency, count bytes and ports, and add valid tags to delayed memory responses.</span></li><li><strong>Target a real device</strong><span>Record synthesis resources, clock and I/O constraints, routed setup/hold reports, and on-board observations if a board is available.</span></li><li><strong>Connect a tiny model</strong><span>Map one linear layer, compare the software output, then account for transfer and nonlinear-operation costs.</span></li></ol>
<h4>Make the result useful to a reviewer</h4>
<p>Publish source, tool versions, exact commands, test seeds, failure conditions and measured units. Report accepted inputs per cycle, end-to-end latency and resource use separately. A cycle-level simulator supports a schedule claim. An RTL scoreboard supports tested functional and protocol behavior. A placed-and-routed report supports timing under its constraints and models. A physical measurement supports only the actual board, clock, temperature and workload tested.</p>
<p>For an ASIC extension, synthesize against a stated library, integrate a real SRAM macro model, produce a floorplan and examine how routing changes the predicted critical path. Do not label a generic gate count a fabricated chip. For the software route, return to the <a href="#tiled-matmul">GPU tile workbench</a>: shared-memory banks, valid boundaries, occupancy and pipelining are different abstractions of several of the same resource problems.</p>
${check("Final oral check: why can doubling the number of multipliers fail to improve served tokens per second?", "The added multipliers may lack operand bandwidth, increase routing delay or require more transfer/queueing overhead. The model can also spend most time in other operations or KV traffic. Trace the workload's critical path, port demand and data reuse; compare end-to-end measurements under the same numerical and latency contract.")}
`)
);
