import { sourceLink as ref, workedCheck as check, escapeCode } from "./lesson-template";
import handoffSource from "../examples/inference/kv_handoff.py?raw";

export const disaggregationLessons = `
<section class="lesson" id="pd-disaggregation" data-lesson="Separate prefill and decode">
<header><span>Serving architecture</span><h3>One request can use two different worker pools</h3></header>
<p class="figure-boundary">This extension's research and implementation references were checked September 16, 2026. Versioned commands elsewhere retain their stated versions.</p>
<p><strong>Prefill</strong> reads the known prompt and builds its attention state. Its final prediction can supply the first output token. <strong>Decode</strong> repeatedly consumes the latest token and predicts another. Prefill/decode disaggregation assigns these phases to different model replicas and moves the request's state between them. It separates execution roles; it does not split the model's layers between the two pools.</p>
<p>A large prompt can interrupt a stream of small decode iterations. Separating the roles can isolate that interference and let each pool choose its own batch sizes, hardware and parallelism. Both pools still need the weights required to execute their phase. State transfer and duplicated capacity have costs. Decode with a large batch can become compute-heavy; long-context attention can become a bandwidth bottleneck. “Prefill is compute-bound, decode is memory-bound” is a useful starting case, not a law.</p>
${ref("https://www.usenix.org/system/files/osdi24-zhong-yinmin.pdf", "DistServe · OSDI 2024: phase isolation, placement and goodput")}
<figure class="textbook-lab pd-architecture"><figcaption><span>Request and state flow</span><strong>The weights stay; the request's KV moves</strong><p>Follow one ordinary decoder request. P and D name roles, not tensor-parallel ranks.</p></figcaption>
<div class="pd-route"><div><strong>Client and router</strong><span>Prompt IDs · request identity<br/>Admission and destination choice</span></div><b aria-hidden="true">↓</b><div><strong>Prefill pool · P</strong><span>Model weights resident<br/>Process prompt → KV + first token</span></div><b aria-hidden="true">↓</b><div><strong>Handoff</strong><span>Reserve · transfer · validate · publish<br/>Keep source buffers pinned</span></div><b aria-hidden="true">↓</b><div><strong>Decode pool · D</strong><span>Model weights resident<br/>Consume first token → more tokens</span></div></div>
<p class="figure-boundary">The router also returns streamed output to the client. Real implementations can pipeline layer transfers, recompute a boundary token or use shared cache storage; this diagram states a simpler complete-prompt handoff.</p></figure>
<div class="method-table"><table><caption>Three designs to compare on the same workload and fleet budget</caption><thead><tr><th scope="col">Design</th><th scope="col">Where work runs</th><th scope="col">Tradeoff to measure</th></tr></thead><tbody>
<tr><th scope="row">Colocated phases</th><td>One replica handles a request's prompt and output</td><td>Local KV; prompt bursts can delay active decodes</td></tr>
<tr><th scope="row">Chunked prefill</th><td>A replica interleaves prompt chunks with decodes</td><td>Smaller interruptions; more scheduling steps, context-dependent iteration cost</td></tr>
<tr><th scope="row">Separate P and D</th><td>Independent role pools plus a state-transfer path</td><td>Independent tuning; network, staging buffers and imbalance can dominate</td></tr>
</tbody></table></div>
<p>Sarathi-Serve makes chunked prefill a serious colocated baseline. It limits prompt work per iteration and combines it with decode work. A token budget counts scheduled positions, not milliseconds: existing context, kernels and batch composition still affect the iteration. Compare a tuned colocated baseline before assigning more replicas to a split deployment.</p>
${ref("https://www.usenix.org/system/files/osdi24-agrawal.pdf", "Sarathi-Serve · OSDI 2024: chunking and iteration scheduling")}
${check("Does splitting phases automatically increase tokens per second?", "No. A fixed fleet now divides capacity between roles and moves KV. It may satisfy more latency-constrained requests by avoiding interference, yet lose raw throughput or waste idle workers on a different request mix. Declare whether the comparison optimizes raw throughput, request goodput, cost, TTFT or inter-token latency.")}
<p class="figure-boundary">The vLLM 0.22.0 guide treats this feature as experimental and cautions against interpreting disaggregated prefill itself as a throughput improvement. Research goodput claims and this warning concern different configurations and objectives.</p>
${ref("https://docs.vllm.ai/en/v0.22.0/features/disagg_prefill/", "vLLM 0.22.0: disaggregated-prefill scope")}
</section>

<section class="lesson" id="pd-handoff" data-lesson="Transfer a valid cache">
<header><span>State ownership</span><h3>A copied buffer is not yet a usable request</h3></header>
<p>After a four-token prompt at positions 0–3, prefill can sample output token y₀ for position 4. Its cache still covers positions 0–3. The decoder receives that cache <em>and</em> y₀, consumes y₀ to write position-4 KV, and predicts y₁. A sampled token and a cached token are different events—the same distinction matters after a speculative correction or bonus token.</p>
<div class="method-table"><table><caption>One prompt, two output tokens</caption><thead><tr><th scope="col">Event</th><th scope="col">Valid KV positions</th><th scope="col">Next input / output</th></tr></thead><tbody>
<tr><th scope="row">Prefill finishes</th><td>0, 1, 2, 3</td><td>y₀ is sampled; it has no KV yet</td></tr>
<tr><th scope="row">Handoff publishes</th><td>0, 1, 2, 3 at D</td><td>y₀ and position 4 are pending</td></tr>
<tr><th scope="row">First decode finishes</th><td>0, 1, 2, 3, 4 at D</td><td>y₁ is sampled; position 5 is pending</td></tr>
</tbody></table></div>
${ref("https://arxiv.org/html/2311.18677v2", "Splitwise · ISCA 2024: handoff and first-to-second-token latency")}
<figure class="textbook-lab"><figcaption><span>Ownership protocol</span><strong>When may the decoder read, and the sender release?</strong><p>Step through an illustrative transfer. This is a protocol sketch, not an implementation of a particular connector.</p></figcaption>
<div class="method-toolbar"><button type="button" data-pd-handoff-back>Previous event</button><button type="button" data-pd-handoff-next>Next event</button><button type="button" data-pd-handoff-reset>Reset</button></div><div class="pd-handoff-state" data-pd-handoff-state aria-live="polite"></div>
<p class="figure-boundary">Cancellation must drain or fence in-flight writes before destination slots can be reused. Leases and retries need a real distributed failure model beyond this local example.</p></figure>
<p>Reserve destination capacity before initiating movement. Match model/checkpoint, adapter, token/position semantics, layer and head layout, cache dtype and any scales. Tag the transfer with request identity and an attempt number; a delayed write from an earlier attempt must not overwrite a later request. Wait for all required ranges and the device-visible readiness event before scheduling attention.</p>
<p>In particular, a transport notification is not a transaction commit. NIXL's backend contract does not impose ordering across transfer requests or lock each memory region for the caller. The surrounding engine must establish ordering, protect buffers and handle conflicting writes. vLLM's lease design keeps producer state available while a decoder is queued or reading it.</p>
${ref("https://github.com/ai-dynamo/nixl/blob/main/docs/BackendGuide.md", "NIXL backend contract · reviewed September 16, 2026")}
${ref("https://docs.vllm.ai/en/latest/design/nixl_kv_cache_lease/", "vLLM KV leases · reviewed September 16, 2026")}
<div class="lesson-code"><h4>Run the ownership sketch on a CPU</h4><pre><code>python3 examples/inference/kv_handoff.py
python3 -m unittest discover -s examples/inference -p test_kv_handoff.py -v</code></pre></div>
<details class="manual-code-details"><summary>Read the complete handoff reference</summary><pre><code>${escapeCode(handoffSource)}</code></pre></details>
<p>The reference accepts out-of-order and identical repeated chunks, rejects conflicting writes atomically, and refuses early publication or acknowledgement. Its placeholder state is not a real model cache. It assumes a trusted transport and validates only the manifest fields shown; it has no network, GPU events, lease clock or complete model-compatibility system.</p>
${check("The last chunk arrived, but an earlier chunk is missing. Can a decoder start because the transfer has a completion notification?", "Only if the engine's completion contract establishes that every required range is ready. Arrival order alone says nothing about coverage. The reference explicitly checks all slots, and keeps the source pinned until the completed attempt is acknowledged.")}
</section>

<section class="lesson" id="pd-transfer-budget" data-lesson="KV bytes and the handoff gap">
<header><span>Quantitative model</span><h3>Put the transfer on the request's critical path</h3></header>
<p>For ordinary full attention with equal K/V widths, one request's logical cache payload is <code>2 × L × S × Hkv × dh × s</code> bytes: two tensors, L layers, S cached positions, Hkv key/value heads, dh channels per head and s bytes per value. Use KV heads, not query heads. For L=32, S=8,192, Hkv=8, dh=128 and BF16, that is exactly <strong>1 GiB</strong>. At an assumed effective 25 GB/s, payload transfer alone takes about <strong>42.95 ms</strong>.</p>
<p>Effective bandwidth includes the actual path's limiting rate. NIC line rate, NVLink bandwidth and a host-staged transfer are different measurements. Packing, copying to staging memory, installation, contention and allocation can add time. Reusing complete compatible blocks at the destination removes those blocks from the transfer; a similar text prefix is not sufficient evidence of compatibility.</p>
<figure class="textbook-lab" id="pd-transfer-lab"><figcaption><span>Interactive byte and latency ledger</span><strong>Move delay between TTFT and the first output gap</strong><p>All times and bandwidths here are assumed inputs. Changing when token one is emitted changes the displayed metric, not when the full answer finishes.</p></figcaption>
<div class="method-toolbar pd-controls">
<label>Prompt positions<select data-pd-tokens><option>512</option><option>2048</option><option selected>8192</option><option>32768</option></select></label>
<label>KV heads<select data-pd-heads><option>1</option><option selected>8</option><option>32</option></select></label>
<label>Already cached at D<select data-pd-cached><option value="0">None</option><option value="0.5">First half</option><option value="1">All prompt blocks</option></select></label>
<label>Effective link · GB/s<select data-pd-bandwidth><option>5</option><option selected>25</option><option>50</option></select></label>
<label>Overlap allowance<select data-pd-overlap><option value="0">0 ms</option><option value="10">10 ms</option><option value="20">20 ms</option></select></label>
<label>Send token one<select data-pd-emission><option value="early">When prefill finishes</option><option value="late">When D is ready</option></select></label>
</div><div class="pd-results" data-pd-transfer-results aria-live="polite"></div><div class="pd-timeline" data-pd-transfer-timeline></div>
<p class="figure-boundary">Fixed: 32 layers, 128 channels/head, two bytes/value, 16-token blocks, P queue 10 ms, prefill 400 ms, serial handoff overhead 2 ms, D queue 30 ms, decode 20 ms/step, 101 output tokens. Times are held fixed to isolate accounting; they are not predictions for changing prompt length or hardware. No speculative decoding in this model.</p></figure>
<div class="derivation"><p><code>wire bytes = ceil(missing positions / block size) × block size × bytes per position</code></p><p><code>exposed handoff = serial overhead + max(0, payload time − overlap allowance)</code></p><p><code>first output gap = exposed handoff + D queue + one decode step</code> when P emits token one immediately.</p></div>
<p>The overlap control is an optimistic allowance, capped by the payload time. A real layer pipeline must prove when each chunk becomes available and how transfers overlap later computation. Do not subtract a percentage merely because a transfer is asynchronous. The constant 2 ms overhead remains even when the prompt is already cached in this teaching model.</p>
<p>With no overlap or cache reuse, the default first token arrives at 410 ms; token two at about 504.95 ms. The first gap is about 94.95 ms, while average TPOT across 100 intervals is only 20.75 ms. Delaying token one until D is ready worsens TTFT but hides that stall inside TTFT. Always report the first-to-second gap and the remaining ITL distribution as well as the average.</p>
<details class="deep-dive"><summary>MLA, hybrid state and different tensor-parallel layouts</summary>
<p>The two-tensor formula does not apply unchanged to compressed MLA. If each position stores a joint KV latent of width dc plus a positional-key component of width dRoPE, the compressed payload is <code>L × S × (dc + dRoPE) × s</code>. The joint latent already represents both K and V; multiplying it by two double-counts it. An illustrative 32-layer, 8,192-position, BF16 cache with dc=512 and dRoPE=64 is 288 MiB. Expanded kernels and workspaces may store more.</p>
${ref("https://arxiv.org/html/2405.04434v5", "DeepSeek-V2 v5: compressed MLA state")}
<p>For hybrid attention/recurrent models, sum each layer's actual state. A sliding window, full-history attention, recurrent matrix and convolution history have different sizes. Changing the architecture to reduce state requires its own quality and training evidence; it is not a transport setting.</p>
${ref("https://docs.vllm.ai/en/latest/design/hybrid_kv_cache_manager/", "vLLM hybrid cache allocation · reviewed September 16, 2026")}
<p>With eight KV heads, a four-way prefill partition might own two heads per rank, while a two-way decode partition needs four. For the 1 GiB example, each P rank owns 256 MiB and each D rank needs 512 MiB. Each D rank must receive the correct two source shards, and physical page layouts must agree or be converted. Replication changes this calculation. A connector's documented gather/scatter support determines which layouts are actually available.</p>
${ref("https://docs.sglang.io/docs/advanced_features/pd_disaggregation", "SGLang: PD transfer paths and sharding support · checked September 16, 2026")}
</details>
</section>

<section class="lesson" id="pd-capacity" data-lesson="Balance the pools and fabric">
<header><span>From one request to a fleet</span><h3>The slowest required resource limits admission</h3></header>
<p>For a fixed request mix, divide measured aggregate phase work by work per request. If a P replica processes 40,000 prompt tokens/s and every prompt has 8,000 tokens, its capacity is 5 requests/s. If a D replica delivers 1,600 output tokens/s and each request needs 400 tokens after the first, its capacity is 4 requests/s. The fabric has its own bytes-per-request constraint. These rates must come from the chosen batching and latency regime.</p>
<figure class="textbook-lab" id="pd-capacity-lab"><figcaption><span>Interactive capacity screen</span><strong>Which resource would another replica help?</strong><p>Move workers between pools and change offered load. A capacity bound does not predict p99 latency.</p></figcaption>
<div class="method-toolbar"><label>Prefill replicas<input type="range" min="1" max="8" value="2" data-pd-p-workers/><output data-pd-p-value>2</output></label><label>Decode replicas<input type="range" min="1" max="8" value="2" data-pd-d-workers/><output data-pd-d-value>2</output></label><label>Arrivals · requests/s<input type="range" min="1" max="30" value="9" data-pd-arrivals/><output data-pd-arrivals-value>9</output></label><label>Shared link · GB/s<select data-pd-capacity-link><option>3</option><option selected>25</option><option>50</option></select></label></div>
<div class="pd-capacity-result" data-pd-capacity-results aria-live="polite"></div>
<p class="figure-boundary">Independent assumed workload: 8,000 prompt tokens, 401 output tokens, 40,000 prompt tokens/s/P replica, 1,600 post-first output tokens/s/D replica, 1 decimal GB transferred/request. Rates do not change with scaling in this optimistic model. It omits burstiness, staging limits, resident/growing KV, retries, compute/network contention and service-level objectives.</p></figure>
<p>A necessary steady-state screen is <code>arrival rate &lt; min(P capacity, D capacity, fabric capacity)</code>. Equality leaves no margin for variability. With two workers of each role and 9 arrivals/s, D limits capacity to 8 requests/s. If requests are never rejected and these capacities hold, unfinished work accumulates by at least one request each second. Another P replica does not fix that bottleneck.</p>
<p>Extra transfer buffers need separate reservations. Four GiB of staging space can hold at most four 1 GiB handoffs; it does not imply space for four complete requests with growing output KV. Split pools can also strand capacity when input/output lengths change. Track queue age and bytes outstanding per role before dynamically reassigning workers; weight loading and cache draining take time.</p>
<h4>Recent systems change what gets moved</h4>
<div class="method-table"><table><caption>Mechanisms and evidence boundaries · reviewed September 16, 2026</caption><thead><tr><th scope="col">Work</th><th scope="col">What it adds</th><th scope="col">How to read it</th></tr></thead><tbody>
<tr><th scope="row">Mooncake · FAST 2025</th><td>KV-centric placement and reuse across a distributed memory/storage fabric</td><td>Study topology, cache-aware admission and transfer stages; a warm reusable prefix differs from a cold request</td></tr>
<tr><th scope="row">NIXL in vLLM</th><td>Asynchronous KV transfer with connector-specific compatibility and recovery</td><td>Pin model, backend, dtype, scales and parallel layout; transport alone is not a scheduler</td></tr>
<tr><th scope="row">Prefill-as-a-Service · April 2026</th><td>Selective offload of long prefills, motivated by smaller hybrid-model state</td><td>Its throughput/bandwidth case study uses measured profiling inside a model, not an end-to-end production speedup proof</td></tr>
</tbody></table></div>
${ref("https://www.usenix.org/system/files/fast25-qin.pdf", "Mooncake · FAST 2025: KV-centric serving")}
${ref("https://arxiv.org/html/2604.15039v2", "Prefill-as-a-Service v2 · April 22, 2026, evaluation §4.1")}
<p>The NIXL compatibility matrix checked on September 16 describes restrictions for dynamic KV scales and hybrid-model sharding. Those are versioned engine constraints, not universal limits of the architecture. A compatible layout does not prove that two replicas loaded identical weights. Failure policy is also observable: recomputing lost KV on D introduces prefill work into a supposedly isolated decode pool.</p>
${ref("https://docs.vllm.ai/en/latest/features/nixl_connector_compatibility/", "vLLM NIXL compatibility matrix · checked September 16, 2026")}
${ref("https://docs.vllm.ai/en/v0.22.0/features/nixl_connector_usage/", "vLLM 0.22.0: roles, transfer setup and load-failure policy")}
<details class="deep-dive"><summary>A reproducible experiment that combines speculation and disaggregation</summary>
<p>Measure four cases: colocated/plain decode, colocated/speculative decode, split/plain decode and split/speculative decode. Hold total devices, model/draft revisions, dtype, output policy and offered request trace fixed. Include both repeated and unique prompts and several output-length regimes. Confirm the engine actually supports the combined features before interpreting a launch command as proof.</p>
<p>Log client TTFT, first-to-second gap, every stream gap, completion/errors, P/D queue delay, transfer bytes and time, accepted draft-prefix length, and peak memory by role. Count compliant requests under the same latency definition. Speculation changes D's work per emitted token and may require draft features/cache state that the P/D connector does not transfer. Therefore multiply neither two reported speedups nor two isolated capacity ratios to predict the combination.</p>
<pre><code>case,arrival_rps,prompt_tokens,output_tokens,ttft_ms,first_gap_ms,tpot_ms
colocated_plain,9,8000,401,...,...,...
colocated_speculative,9,8000,401,...,...,...
split_plain,9,8000,401,...,...,...
split_speculative,9,8000,401,...,...,...</code></pre>
<p>These are report columns, not invented results. Include an overload run and a failed-transfer run. Choose fail or recompute deliberately, inspect retry amplification, and compare quality/effective sampling distributions before measuring speed.</p>
</details>
${check("If isolated speculation is 2× faster and isolated disaggregation is 1.5× better on a goodput metric, is the combination 3× faster?", "No. The denominators and workloads may differ, and the changes share resources. Verification can change compute saturation, batching, transfer contents and draft memory. Measure the combination against the same baseline, quality contract, fleet cost and offered load.")}
</section>`;
