import { chapterMarkup, sourceLink as ref, workedCheck as check } from "./lesson-template";

export const foundationsChapter = chapterMarkup("first-principles", "From text to a trainable function",
  "Start here if you know what an LLM does but cannot yet explain its equations. Build the vocabulary, calculate a prediction, and follow one weight update before opening the machine.", `
<section class="lesson" id="what-a-model-is" data-lesson="What a model computes"><header><span>Start from zero</span><h3>A model assigns probabilities to the next token</h3></header>
<p>Type “the cat” into a language model. The model converts that text into integer IDs, processes those IDs through learned numerical operations, and produces one score for every possible next ID. Those scores become a probability distribution. A decoding rule chooses an ID, appends it to the input, and repeats. The network does not return a complete sentence in one indivisible act.</p>
<p>The parameters, also called weights, are numbers adjusted during training. The architecture is the recipe that uses them: look up embeddings, mix information between positions, transform features, and project to vocabulary scores. A checkpoint stores parameter values and associated metadata. An inference engine runs those operations while managing memory and requests. A chat interface adds message formatting, conversation history, tools and product rules.</p>
<p>The model learns which continuations fit the text it trains on. A fluent continuation can still be false: likelihood of text is a different objective from verifying a claim about the world.</p>
<details class="deep-dive"><summary>Read the probability notation</summary><p>Write <code>pθ(xₜ | x₀, …, xₜ₋₁)</code>: the probability of token x at position t given its prefix, under parameters θ. The subscript t labels a position; θ names the full collection of weights. The vertical bar means “conditioned on,” not division. A sequence probability factors into a product of such conditional probabilities. Taking its logarithm changes that product into a sum, which is easier to optimize numerically.</p></details>
<figure class="textbook-lab"><figcaption><span>Figure 1.1</span><strong>One generated token crosses four contracts</strong><p>The output becomes input on the next iteration.</p></figcaption><div class="manual-sequence"><div><strong>Text → IDs</strong><span>Tokenizer and chat template determine the exact prefix.</span></div><div><strong>IDs → features</strong><span>Embedding rows and decoder layers build context-dependent vectors.</span></div><div><strong>Features → scores</strong><span>A vocabulary projection produces logits.</span></div><div><strong>Scores → next ID</strong><span>A sampling rule chooses the token; append it and continue.</span></div></div><p class="figure-boundary">Conceptual decoder-only flow. Retrieval, multimodal encoders, tool execution and request scheduling sit around this numerical core.</p></figure>
${check("Explain it back: what changes when you train a model, and what changes when you prompt it?", "Training updates parameters using an objective and an optimizer. Ordinary prompting supplies a different input and creates different activations and cache state while leaving the weights fixed. Fine-tuning is training; a longer prompt is not a parameter update.")}
${ref("https://arxiv.org/abs/1706.03762", "Vaswani et al.: attention-based model architecture")}
</section>
<section class="lesson" id="tokens-and-bytes" data-lesson="Tokens and embeddings"><header><span>Representation</span><h3>A token ID is an address, not a meaning</h3></header>
<p>A byte has 256 possible values. UTF-8 encodes text as a sequence of bytes; one displayed character can occupy several bytes. A byte tokenizer maps those bytes directly to IDs 0 through 255. The capstone uses that simple mapping, so you can inspect every conversion without an external tokenizer file.</p>
<p>Practical text tokenizers often combine recurring byte or character sequences into vocabulary entries. Their training data, normalization and special-token rules matter. “One token is one word” is unreliable, especially for code, non-English text and whitespace. Token counts from different tokenizers are not directly comparable units of linguistic content. To reproduce an experiment, record the tokenizer revision along with the weights.</p>
<p>For vocabulary size V and feature width D, an embedding table E has shape <code>[V,D]</code>. Looking up token ID 7 retrieves row 7, a vector of D learned numbers. The ID itself does not imply similarity: IDs 7 and 8 can represent unrelated strings. Similarity develops through the learned vectors and the computations that use them.</p>
<div class="derivation"><h4>A lookup is a matrix operation with a shortcut</h4><p>For V=4 and D=2, let E contain rows [1,0], [0,1], [1,1], [−1,2]. Token 3 yields [−1,2]. Multiplying the one-hot row [0,0,0,1] by E yields exactly the same vector. Implementations use a gather instead of materializing a large one-hot tensor.</p></div>
${check("If V=256 and D=64, how many embedding parameters and FP32 bytes exist?", "There are 256×64=16,384 parameters. At four bytes each, that is 65,536 bytes or 64 KiB. A tied output projection reuses this same parameter matrix; it does not add a second independent copy of the weights.")}
${ref("https://www.unicode.org/versions/Unicode17.0.0/core-spec/chapter-3/", "Unicode: character encoding and UTF-8")}
${ref("https://github.com/huggingface/tokenizers", "Hugging Face Tokenizers: tokenizer implementations")}
</section>
<section class="lesson" id="math-reading-kit" data-lesson="Tensor shapes and multiplication"><header><span>Mathematical prerequisites</span><h3>Read the shapes before reading the formula</h3></header>
<p>Keep three questions separate: which example are we processing, which position in it, and which numbers describe that position? The three axes of <code>X[B,T,D]</code> answer those questions. Shape is an agreement about meaning as well as a list of lengths.</p>
<div class="method-table"><table><caption>Picture two three-byte sequences, “cat” and “dog,” with four features per position</caption><thead><tr><th>Axis</th><th>What it selects</th><th>In this example</th></tr></thead><tbody><tr><th>B · batch</th><td>One sequence in the group processed together</td><td>2 sequences</td></tr><tr><th>T · time / sequence</th><td>A token position within that sequence</td><td>3 positions each</td></tr><tr><th>D · features</th><td>A component of that position’s numerical representation</td><td>4 numbers per position</td></tr></tbody></table></div>
<p>The IDs start as a <code>[2,3]</code> integer array. An embedding lookup produces <code>[2,3,4]</code>: 24 computed feature values. With zero-based indexing, <code>X[1,2,:]</code> selects all four features for the “g” position in the second sequence. A feature is a coordinate in a learned representation; it need not have a tidy human label. The two batch sequences do not attend to each other in this ordinary decoder.</p>
<p>A scalar is one number. A vector is an ordered list. A matrix is an array with two axes. A tensor extends the array idea to any number of axes. The 24 values above are <strong>activations</strong>, produced for these inputs. The embedding table is a separate set of <strong>parameters</strong>: for a 256-byte vocabulary and width 4, it contains 1,024 learned values shared across all examples and positions.</p>
<h4>What makes a matrix trainable?</h4>
<p>A matrix is simply an arrangement of numbers. We make it a parameter by storing its values as part of the model and letting an optimizer update them from gradients. Computed outputs are also arrays, but their changing values do not make them separate learned weights. A frozen parameter is still model state; its values are deliberately excluded from updates.</p>
<p>The dot product of [a,b] and [c,d] is ac+bd. It combines matching components and sums the products. Matrix multiplication repeats dot products: if A is [M,K] and B is [K,N], then C is [M,N] and <code>Cᵢⱼ = Σₖ AᵢₖBₖⱼ</code>. The Σ symbol means “add the indicated terms.” K disappears because it is summed; M and N remain. This is the same operation you will later tile in shared memory and map onto a systolic array.</p>
<div class="derivation"><h4>Do one output by hand</h4><p>A row [2,−1,3] dotted with a column [4,5,−2] gives 8−5−6=−3. That is three multiplies and two additions as written. Engineering FLOP estimates often count a multiply-accumulate as two operations and use 2MNK for a large GEMM, with the convention stated explicitly.</p></div>
<div class="derivation"><h4>Six weights turn two features into three</h4><p>Let the input row be x=[3,4] and the two rows of W be [1,0,−1] and [2,1,0]. Then <code>xW = [3×1+4×2, 3×0+4×1, 3×(−1)+4×0] = [11,4,−3]</code>. W has six parameters; the result has three activations. Increasing only W’s first entry from 1 to 1.1 increases the first output by 0.3. This dependence is what a derivative measures.</p><p>Apply this same W to every position of a <code>[B,T,2]</code> input and obtain <code>[B,T,3]</code>. The parameter count stays six when B or T grows. Gradients from the positions using a shared weight accumulate into that weight’s update; a mean loss also scales them by its denominator.</p></div>
<details class="deep-dive"><summary>Match the notation to PyTorch’s stored weights</summary><p>Here rows are input features, so W has shape [input features, output features] and the expression is xW. PyTorch’s <code>nn.Linear</code> stores its weight with shape [output features, input features] and uses its transpose: <code>y = x @ weight.T + bias</code>. Transpose exchanges the two axes. These conventions describe the same operation. The six-weight interactive lesson below writes a feature vector as a column and uses <code>z=Wx</code>, with one stored row per output token.</p></details>
<p>A function maps inputs to outputs. Composition means applying one function after another. If z=f(x) and y=g(z), y=g(f(x)). A neural network is a composition with trainable coefficients. A nonlinear activation such as GELU matters because repeated linear maps alone collapse into a single linear map; extra layers would otherwise not provide the same representational flexibility.</p>
<p>Always carry units. Capacity is bytes; bandwidth is bytes per second; latency is seconds; compute rate is operations per second. GB is 10⁹ bytes and GiB is 2³⁰ bytes. Eight bits make a byte, so a 400 Gb/s link has a raw rate of 50 GB/s before protocol and other overhead. These conversions will recur in every hardware comparison.</p>
${check("A [2,5,64] tensor is projected by [64,128]. What is the result shape and FP32 output size?", "The result is [2,5,128]: 1,280 numbers, or 5,120 bytes. The 64-feature axis contracts. No batch or time dimension disappears.")}
${check("Doubling the batch doubles the computed activations. Does it double the learned matrix?", "No. Every sequence uses the same parameter matrix. A larger batch creates more activations and more loss contributions, while the stored parameter count stays fixed.")}
${ref("https://docs.pytorch.org/docs/2.8/generated/torch.nn.Linear.html", "PyTorch 2.8: linear-map shapes and stored weight convention")}
${ref("https://docs.pytorch.org/docs/2.8/generated/torch.nn.parameter.Parameter.html", "PyTorch 2.8: model parameters and temporary tensors")}
</section>
<section class="lesson" id="probability-and-loss" data-lesson="Loss and training targets"><header><span>Learning signal</span><h3>A wrong answer needs a measurable penalty</h3></header>
<p>During training, the text supplies the answer: at each position, ask the model to predict the next recorded token. Measure how much probability it gave that answer, combine the penalties, and use that single loss to update the shared weights. First make the input–answer pairing explicit.</p>
<h4>One text window provides several training questions</h4>
<p>Take the bytes for “cat” followed by a newline: <code>[99,97,116,10]</code>. A four-token window provides three questions. The input is <code>[99,97,116]</code>; its targets are <code>[97,116,10]</code>, shifted one position ahead.</p>
<div class="method-table"><table><caption>Each row predicts the next byte using only its permitted prefix</caption><thead><tr><th>Output position</th><th>Prefix it may use</th><th>Target byte</th></tr></thead><tbody><tr><th>0</th><td>c · [99]</td><td>a · 97</td></tr><tr><th>1</th><td>ca · [99,97]</td><td>t · 116</td></tr><tr><th>2</th><td>cat · [99,97,116]</td><td>newline · 10</td></tr></tbody></table></div>
<p>The model returns <code>[1,3,256]</code> scores: one batch item, three prediction positions, 256 possible bytes at each position. It can calculate these rows together because the recorded input is available. The <a href="#attention-by-hand">causal mask</a> prevents a row from reading later input positions, even though those bytes already exist elsewhere in memory. Targets are used to score the outputs, not passed in as an extra feature that reveals the answer.</p>
<p>Generation uses the same next-token rule with an unknown answer. Given “ca,” take the output at its final position and select a token. If it selects byte 116, append “t,” then predict again from “cat.” This dependence makes successive generated tokens sequential. During training, the recorded prefixes supply every row; the model does not have to sample “a” before learning from the “ca” row.</p>
<details class="deep-dive"><summary>Locate the shift in the runnable decoder</summary><p>In <a href="#capstone-forward">the companion decoder</a>, <code>loss(sequence)</code> sends <code>sequence[:, :-1]</code> into the model and uses <code>sequence[:, 1:]</code> as targets. The colon selects every batch item; the slices omit the last and first position respectively. Pass the complete window to that method: shifting it again in the caller would teach a different alignment. Other APIs can place this shift elsewhere, so inspect their contract.</p><p>The companion flattens logits from [B,T,V] to [B×T,V] and targets from [B,T] to [B×T] before cross-entropy. Each score row remains paired with its target. These windows have no padding or excluded labels; the <a href="#packing-loss">training objective lesson</a> adds those cases and their loss denominator.</p></details>
${check("If you use [99,97,116] as both input and target, what task have you accidentally created?", "You reward copying the token already visible at the same position. To learn next-token prediction from this window, the targets must be [97,116,10]. A causal mask alone cannot repair a label shift error: it intentionally permits each position to see its own input token.")}
<h4>Turn each answer’s probability into a loss</h4>
<p>Logits are unrestricted real-valued scores. Softmax turns them into probabilities: <code>pᵢ=exp(zᵢ)/Σⱼexp(zⱼ)</code>. Here zᵢ is the score for vocabulary entry i, pᵢ is its probability, and the denominator sums over every vocabulary entry j. Exponentiation makes the unnormalized values positive; division makes the probabilities sum to one.</p>
<p>For target class y, cross-entropy is <code>L=−ln(pᵧ)</code>, where ln is the natural logarithm (the inverse of exp). If the target receives probability 0.5, the penalty is about 0.693 nats; at 0.1, about 2.303. Predicting the correct class with argmax (choosing the highest score) and assigning it a high probability are different tests. A model can keep the same top prediction while substantially improving its loss.</p>
<div class="derivation"><h4>Combine three predictions into one learning signal</h4><p>Suppose the correct bytes in the table receive probabilities ½, ¼ and ⅛. Their losses are approximately 0.693, 1.386 and 2.079. The mean is <code>(0.693+1.386+2.079)/3 ≈ 1.386</code>. Lowering this mean encourages the model to assign more probability to the recorded next bytes. These are illustrative probabilities, not measurements from a trained model.</p></div>
<details class="deep-dive"><summary>Compute the loss safely and read its gradient</summary><p>Adding the same constant to every logit leaves softmax unchanged. Numerically, subtract the maximum score before exponentiating to avoid overflowing on large positive logits. A stable implementation computes <code>L=logsumexp(z)−zᵧ</code>, avoiding the logarithm of a probability that underflowed to zero. Here <code>logsumexp(z)</code> means the logarithm of the sum of the exponentiated scores, evaluated with that stable rearrangement.</p><p>The loss derivative with respect to a logit is <code>∂L/∂zᵢ=pᵢ−1[i=y]</code>, where the indicator is one for the target and zero otherwise. The target score receives a negative derivative; gradient descent increases it. The <a href="#first-weight-update">next lesson</a> follows that derivative back into individual weights.</p></details>
<p>Perplexity is exp(mean negative log-likelihood), using the same tokenization, masking and averaging convention. A uniform distribution over four tokens has loss ln(4) and perplexity 4. Perplexity is not a percentage correct, and comparing it across vocabularies or datasets without context is misleading.</p>
${check("Why must cross-entropy receive logits if the API says it performs log-softmax internally?", "The operation already performs the required normalization. Applying softmax first changes the numbers treated as logits and therefore changes both loss and gradients. Read the API contract and keep the stable logit-to-loss path.")}
${ref("https://docs.pytorch.org/docs/2.8/generated/torch.nn.CrossEntropyLoss.html", "PyTorch 2.8: cross-entropy input and target contract")}
${ref("https://arxiv.org/abs/1706.03762", "Vaswani et al.: shifted predictions and causal decoder masking")}
</section>
<section class="lesson" id="first-weight-update" data-lesson="A weight update"><header><span>Interactive derivation</span><h3>Follow the error back to six weights</h3></header>
<p>A derivative describes how an output changes under a tiny input change. For f(w)=w², the derivative is 2w. For a composed function, multiply local derivatives along a path; when several paths contribute, add them. Reverse-mode automatic differentiation starts at a scalar loss and accumulates these contributions backward through the computation graph.</p>
<p>Here the features are x=[1,2], the vocabulary has three tokens, and W has one row per token. Compute z=Wx, p=softmax(z), then L=−ln(pᵧ). The gradient is <code>∂L/∂Wᵢⱼ=(pᵢ−1[i=y])xⱼ</code>. Gradient descent uses <code>W ← W−η∂L/∂W</code>, where η is the learning rate. This is a deliberately small vocabulary projection, not a full Transformer.</p>
<figure class="textbook-lab" data-first-update><figcaption><span>Interactive 1.2</span><strong>Make the target more likely</strong><p>Step through an update, inspect every derivative, then change the target.</p></figcaption><div class="method-toolbar"><label>Target token<select data-first-target><option value="0">cat</option><option value="1" selected>sat</option><option value="2">ran</option></select></label><label>Learning rate<select data-first-rate><option>0.01</option><option selected>0.1</option><option>1</option></select></label><button data-first-step>Apply one update</button><button data-first-reset>Reset weights</button></div><div class="manual-diagram" data-first-bars></div><div class="method-table" data-first-table></div><p class="manual-status" aria-live="polite" data-first-status></p><p class="figure-boundary">Exact double-precision browser arithmetic for one linear projection and one example. It omits context, embeddings, attention, optimizer history and stochastic batches. The gradient is checked independently with finite differences.</p></figure>
<p>Initially z=[0.1,0.7,0]. The second token has probability about 0.489 and loss about 0.716. Its row gradient is about [−0.511,−1.021]; with η=0.1, [0.1,0.3] becomes approximately [0.151,0.402]. The other rows move in the opposite direction. Learning changes a distribution through all affected weights, not by setting a single “correct-answer” switch.</p>
<p>A finite-difference check estimates a derivative by <code>(L(w+ε)−L(w−ε))/(2ε)</code>. Compare it with backpropagation on a small smooth problem in FP64. ε must be small enough to approximate a local change but large enough to avoid cancellation. Passing one check does not establish every shape, dtype or distributed reduction; it establishes the derivative tested.</p>
${check("Why can an excessive learning rate make a training run unstable?", "A derivative describes local behavior. A large update can move far beyond the region where that local approximation predicts the loss. Curvature, optimizer history and noisy batches all matter. A simple one-example projection does not model the full stability problem.")}
${ref("https://docs.pytorch.org/tutorials/beginner/basics/autogradqs_tutorial.html", "PyTorch: computation graphs and automatic differentiation")}
<p>Next, use the same reasoning through <a href="#framework-same-update">PyTorch, JAX and TensorFlow APIs</a>. That exercise holds inputs and initial weights fixed, then checks the loss, gradient and complete update. It makes the difference between a mathematical derivative and a framework's gradient storage explicit.</p>
</section>
<section class="lesson" id="attention-by-hand" data-lesson="Attention by hand"><header><span>From features to context</span><h3>A position builds a weighted mixture of earlier information</h3></header>
<p>Each position projects its features into a query q, a key k and a value v. A query–key dot product produces a compatibility score. Divide by √d for head width d, apply a causal mask, normalize across allowed keys, and mix values with those weights. The result is a new feature vector, not a chosen vocabulary token.</p>
<div class="derivation"><h4>Two positions, one-dimensional values</h4><p>At the second position, let the allowed scores be [0,ln(3)] and values [2,6]. Softmax gives weights [¼,¾], so the mixture is ¼×2+¾×6=5. At the first position, the second key is in the future and must be masked before normalization; its only allowed value contributes with weight one.</p></div>
<p>Training can calculate all positions together because the entire training sequence is available. The mask still prevents each prediction from using its future target. Teacher forcing means supplying the recorded prefix during training, rather than feeding the model’s own sampled mistakes back at every position. At generation time, the next ID is unknown until selected, creating a serial dependence between output positions.</p>
<p>A KV cache retains earlier keys and values for each layer. It saves recomputing earlier representations at every decode step. It does not make the next query independent of the prefix, and standard dense attention must still read appropriate historical state. In cached decode, query position zero of a one-token input might be absolute position 100; the causal mask must use that offset.</p>
${check("If a score for a forbidden future key is set to zero instead of negative infinity, is it masked?", "No. exp(0)=1, so that key can receive positive probability after softmax. A forbidden entry must contribute zero probability under the chosen masking implementation.")}
${ref("https://arxiv.org/abs/1706.03762", "Scaled dot-product attention and masking")}
</section>
<section class="lesson" id="learning-practice" data-lesson="Check your understanding"><header><span>How to use this manual</span><h3>Advance when you can reconstruct the mechanism</h3></header>
<p>Read an explanation, close it, calculate a small example, then run or modify the companion. Predict the output before touching a control. When a prediction fails, locate whether the error is in the mathematics, the program, the memory layout or the measurement. That habit scales from six weights to a distributed training job.</p>
<div class="method-table"><table><caption>Concrete gates along the complete learning path</caption><thead><tr><th>Before advancing to</th><th>Demonstrate this without copying a solution</th><th>Practice</th></tr></thead><tbody><tr><th>Tensors and Transformers</th><td>Calculate a dot product, softmax and one gradient; label every axis</td><td><a href="#first-weight-update">Weight update lab</a></td></tr><tr><th>Training systems</th><td>Explain shifted labels, causal masking, and the global loss denominator</td><td><a href="#packing-loss">Token objective</a></td></tr><tr><th>CUDA kernels</th><td>Compute a row-major address and distinguish a pointer from its allocation</td><td><a href="#programming">C programming</a></td></tr><tr><th>FPGA and ASIC design</th><td>Separate combinational logic from clocked state; explain backpressure</td><td><a href="#digital-logic">Digital logic</a></td></tr><tr><th>Efficient serving</th><td>Prove cache equivalence and account for weights, KV and temporary memory</td><td><a href="#end-to-end">Build, train and serve</a></td></tr><tr><th>Frontier research</th><td>Reproduce a baseline and identify what a paper’s comparison holds fixed</td><td><a href="#frontier">Research mechanisms</a></td></tr></tbody></table></div>
<p>Use the chapter prerequisites and focused paths to revisit missing foundations. The complete route includes both software and circuit design. GPU runtime, FPGA board timing, large-scale training and real serving throughput require their respective hardware; browser simulations teach the mechanism and cannot establish those measurements.</p>
</section>`);
