import { chapterMarkup, sourceLink as ref, workedCheck as check } from "./lesson-template";

export const foundationsChapter = chapterMarkup("first-principles", "From text to a trainable function",
  "Start here if you know what an LLM does but cannot yet explain its equations. Start with text, token IDs and learned numbers. The next chapters introduce the mathematics before asking you to calculate a prediction or a weight update.", `
<section class="lesson" id="what-a-model-is" data-lesson="What a model computes"><header><span>Start from zero</span><h3>A model assigns probabilities to the next token</h3></header>
<p>Type “the cat” into a language model. The model converts that text into integer IDs, processes those IDs through learned numerical operations, and produces one score for every possible next ID. Those scores become a probability distribution. A decoding rule chooses an ID, appends it to the input, and repeats. The network does not return a complete sentence in one indivisible act.</p>
<p>The parameters, also called weights, are numbers adjusted during training. The architecture is the recipe that uses them. It converts each ID to a list of numbers, combines information from the preceding text, and calculates the next-token scores. The following chapters name and derive each operation. A checkpoint stores parameter values and associated metadata. An inference engine runs those operations while managing memory and requests. A chat interface adds message formatting, conversation history, tools and product rules.</p>
<p>The model learns which continuations fit the text it trains on. A fluent continuation can still be false: likelihood of text is a different objective from verifying a claim about the world.</p>
<details class="deep-dive"><summary>Read the probability notation</summary><p>Write <code>pθ(xₜ | x₀, …, xₜ₋₁)</code>: the probability of token x at position t given its prefix, under parameters θ. The subscript t labels a position; θ names the full collection of weights. The vertical bar means “conditioned on,” not division. A sequence probability factors into a product of such conditional probabilities. Taking its logarithm changes that product into a sum, which is easier to optimize numerically.</p></details>
<figure class="textbook-lab"><figcaption><span>Figure 1.1</span><strong>One generated token crosses four contracts</strong><p>The output becomes input on the next iteration.</p></figcaption><div class="manual-sequence"><div><strong>Text → IDs</strong><span>Tokenizer and chat template determine the exact prefix.</span></div><div><strong>IDs → features</strong><span>The model turns each ID into a list of numbers and incorporates the available context.</span></div><div><strong>Features → scores</strong><span>The model calculates a score, called a logit, for each possible next ID.</span></div><div><strong>Scores → next ID</strong><span>A decoding rule chooses the token; append it and continue.</span></div></div><p class="figure-boundary">Conceptual decoder-only flow. Retrieval, multimodal encoders, tool execution and request scheduling sit around this numerical core.</p></figure>
${check("Explain it back: what changes when you train a model, and what changes when you prompt it?", "Training adjusts stored weights to reduce a numerical penalty for unwanted predictions. Ordinary prompting changes the input and the temporary computed values while leaving those weights fixed. Fine-tuning is training; a longer prompt is not a parameter update.")}
${ref("https://arxiv.org/abs/1706.03762", "Vaswani et al.: attention-based model architecture")}
</section>
<section class="lesson" id="tokens-and-bytes" data-lesson="Tokens and embeddings"><header><span>Representation</span><h3>A token ID is an address, not a meaning</h3></header>
<p>A bit is a value that can be 0 or 1. Eight bits form a byte, giving 2⁸=256 possible bit patterns. UTF-8 encodes text as a sequence of bytes; one displayed character can occupy several bytes. A byte tokenizer maps those bytes directly to IDs 0 through 255. The capstone uses that simple mapping, so you can inspect every conversion without an external tokenizer file.</p>
<p>Practical text tokenizers often combine recurring byte or character sequences into vocabulary entries. Their training data, normalization and special-token rules matter. “One token is one word” is unreliable, especially for code, non-English text and whitespace. Token counts from different tokenizers are not directly comparable units of linguistic content. To reproduce an experiment, record the tokenizer revision along with the weights.</p>
<p>An array is an ordered collection of numbers; a vector is a one-dimensional list and a matrix is a table of rows and columns. For vocabulary size V (the number of possible IDs) and feature width D (numbers per ID), an embedding table E is a matrix with V rows and D columns, written <code>[V,D]</code>. Looking up token ID 7 retrieves row 7, a vector of D learned numbers. The ID itself does not imply similarity: IDs 7 and 8 can represent unrelated strings. Similarity develops through the learned vectors and the computations that use them.</p>
<div class="derivation"><h4>A lookup is a matrix operation with a shortcut</h4><p>For V=4 and D=2, let E contain rows [1,0], [0,1], [1,1], [−1,2]. Token 3 yields [−1,2]. Multiplying the one-hot row [0,0,0,1] by E yields exactly the same vector. This multiplication will be derived in <a href="#math-reading-kit">the shape lesson</a>. For now, picture selecting one row directly: the zeros leave the other rows out.</p></div>
${check("If V=256 and D=64, how many learned values exist, and how much space do they need at four bytes per value?", "There are 256×64=16,384 parameters. At four bytes each, that is 65,536 bytes or 64 KiB. Here KiB means 1,024 bytes. Four-byte floating-point storage is called FP32; we will study its numerical limits after introducing the arithmetic.")}
${ref("https://www.unicode.org/versions/Unicode17.0.0/core-spec/chapter-3/", "Unicode: character encoding and UTF-8")}
${ref("https://github.com/huggingface/tokenizers", "Hugging Face Tokenizers: tokenizer implementations")}
</section>




<section class="lesson" id="learning-practice" data-lesson="Check your understanding"><header><span>How to use this manual</span><h3>Advance when you can reconstruct the mechanism</h3></header>
<p>Read an explanation, close it, calculate a small example, then run or modify the companion. Predict the output before touching a control. When a prediction fails, locate whether the error is in the mathematics, the program, the memory layout or the measurement. That habit scales from six weights to a distributed training job.</p>
<div class="method-table"><table><caption>Concrete gates along the complete learning path</caption><thead><tr><th>At this checkpoint</th><th>Demonstrate this without copying a solution</th><th>Practice</th></tr></thead><tbody><tr><th>Before the Transformer</th><td>Calculate a dot product, softmax and one gradient; label every axis</td><td><a href="#first-weight-update">Weight update lab</a></td></tr><tr><th>Training systems</th><td>Explain shifted labels, causal masking, and the global loss denominator</td><td><a href="#packing-loss">Token objective</a></td></tr><tr><th>CUDA kernels</th><td>Compute a row-major address and distinguish a pointer from its allocation</td><td><a href="#programming">C programming</a></td></tr><tr><th>FPGA and ASIC design</th><td>Separate combinational logic from clocked state; explain backpressure</td><td><a href="#digital-logic">Digital logic</a></td></tr><tr><th>After building a small service</th><td>Prove cache equivalence and account for weights, KV and temporary memory</td><td><a href="#end-to-end">Build, train and serve</a></td></tr><tr><th>Frontier research</th><td>Reproduce a baseline and identify what a paper’s comparison holds fixed</td><td><a href="#frontier">Research mechanisms</a></td></tr></tbody></table></div>
<p>Use the chapter prerequisites and focused paths to revisit missing foundations. The complete route includes both software and circuit design. GPU runtime, FPGA board timing, large-scale training and real serving throughput require their respective hardware; browser simulations teach the mechanism and cannot establish those measurements.</p>
</section>`);
