import { sourceLink as ref, workedCheck as check, escapeCode } from "./lesson-template";
import executionSource from "../examples/frameworks/execution_contract.py?raw";

const torchGrad = "https://docs.pytorch.org/docs/2.14/notes/autograd.html";
const torchBreak = "https://docs.pytorch.org/docs/2.14/user_guide/torch_compiler/compile/programming_model.graph_breaks_index.html";
const torchRecompile = "https://docs.pytorch.org/docs/2.14/user_guide/torch_compiler/compile/programming_model.recompilation.html";
const jaxGrad = "https://docs.jax.dev/en/latest/automatic-differentiation.html";
const jaxJit = "https://docs.jax.dev/en/latest/jit-compilation.html";
const tfGrad = "https://www.tensorflow.org/guide/autodiff";
const tfFunction = "https://www.tensorflow.org/guide/function";
const kerasGuide = "https://keras.io/guides/migrating_to_keras_3/";

export const frameworkExecutionLessons = `
<section class="lesson" id="framework-same-update" data-lesson="The same numerical update">
<header><span>Establish the contract</span><h3>Different frameworks should agree on the calculation you actually specified</h3></header>
<p class="figure-boundary">Sources checked September 16, 2026 for these four execution lessons. PyTorch documentation is pinned to edition 2.14; JAX, TensorFlow, Keras, Flax and Optax guides are living sources. Companion runtime pins are separate and recorded with the execution evidence. The browser computes original arithmetic; it does not run Python frameworks or measure GPU performance.</p>
<p>A framework supplies arrays, automatic differentiation, model state and execution tools. Start with a tiny calculation whose answer you can inspect. The <a href="#math-reading-kit">matrix reading kit</a>, <a href="#probability-and-loss">probabilities and loss</a>, and <a href="#first-weight-update">first weight update</a> provide the prerequisites. Here we connect those ideas to real APIs before adding compilation or a transformer.</p>
<p>Three examples each have two input channels. A classifier maps each row to two class scores: <code>Z = XW + b</code>. Rows of X are [1,2], [2,−1], [−1,1]; W is [[0.2,−0.3],[0.4,0.1]] and b is [0.1,−0.2]. Our convention stores input channels along W's first axis and output classes along its second. The scores are [[1.1,−0.3],[0.1,−0.9],[0.3,0.2]]. Targets are class IDs [0,1,0].</p>
<p>Softmax turns each score row into class probabilities. A row's cross entropy is <code>ℓₜ = logsumexp(Zₜ) − Zₜ,targetₜ</code>. The mask [1,1,0] includes the first two rows and excludes the last. For a mean, divide by <strong>two valid targets</strong>: <code>L = Σₜ mₜℓₜ / Σₜmₜ</code>. For a sum, the denominator is one. This explicit rule avoids depending on a loss function's default reduction.</p>
<p>Here <code>logsumexp(z)=log(Σc exp(zc))</code>. Compute it stably as <code>zmax+log(Σc exp(zc−zmax))</code>; subtracting the maximum keeps each exponential at most one. The indicator <code>1[c=target]</code> in the derivative below is 1 for the correct class and 0 for every other class. It subtracts probability mass from the model's predicted class distribution to form the error signal.</p>
<figure class="textbook-lab framework-workbench" id="framework-update-lab"><figcaption><span>Interactive · original arithmetic</span><strong>Inspect the loss, every derivative and the resulting weights</strong><p>Each control starts again from the stated W and b. It changes one update's contract; it does not run repeated training steps.</p></figcaption>
<div class="method-toolbar"><label>Included targets<select data-fw-mask><option value="110">Rows 0 and 1</option><option value="111">All three rows</option><option value="001">Only row 2</option><option value="000">No valid targets</option></select></label><label>Loss reduction<select data-fw-reduction><option value="mean">Mean over valid targets</option><option value="sum">Sum over valid targets</option></select></label><label>Learning rate η<select data-fw-lr><option value="0">0 · inspect gradients</option><option value="0.125" selected>0.125</option><option value="0.5">0.5</option></select></label></div>
<p class="framework-result" data-fw-update-summary aria-live="polite"></p><p class="framework-scroll-hint">Scroll wide tables sideways to compare all columns.</p><div class="method-table" data-fw-update-rows tabindex="0" role="region" aria-label="Classifier rows and gradients; scroll horizontally if needed"></div><div class="method-table" data-fw-update-weights tabindex="0" role="region" aria-label="Parameter gradients and updated values; scroll horizontally if needed"></div>
<p class="figure-boundary">Two-class linear classifier, binary mask, finite valid class IDs, plain SGD without momentum or weight decay. An empty valid-target batch explicitly skips the update. Every displayed derivative is tested independently with finite differences.</p></figure>
<p>At the default setting, L≈0.766840. With probabilities p, the score derivative is <code>∂L/∂Zₜc = mₜ(pₜc − 1[c=targetₜ])/2</code>. Multiplication's chain rule then gives <code>∂L/∂W = Xᵀ(∂L/∂Z)</code> and <code>∂L/∂b = Σₜ ∂L/∂Zₜ</code>. Finally, SGD subtracts the learning rate times the derivative: <code>W′=W−η∂L/∂W</code>. Changing mean to sum doubles the default loss and gradients; keeping η fixed also doubles the parameter displacement.</p>
<details class="deep-dive"><summary>Why a masked target still needs a valid class ID here</summary><p>The companion first evaluates sparse cross entropy for every row, then multiplies by the mask. An out-of-range target can fail before masking. Use valid placeholder IDs for excluded rows in this contract. Other APIs offer explicit ignore indices, with their own normalization rules. Similarly, multiplying a previously computed NaN by zero does not repair the invalid operation. Prevent invalid work before it enters the differentiated graph.</p></details>${ref(torchGrad, "PyTorch 2.14 autograd mechanics · masking after an invalid operation does not remove its derivative")}
${check("If you duplicate this entire batch, should the learning step double?", "The mean over valid targets has the same loss and gradient, so plain SGD makes the same step. A summed loss doubles its gradient and the step at a fixed learning rate. This is why batch size, accumulation and reduction must be specified together.")}
</section>

<section class="lesson" id="framework-autodiff-state" data-lesson="Autodiff and training state">
<header><span>Follow the derivative</span><h3>Automatic differentiation computes gradients; an optimizer changes parameters</h3></header>
<p>Return to the <a href="#autodiff">chain-rule lesson</a> if the derivative path is unfamiliar. Reverse-mode automatic differentiation carries a derivative from a scalar loss back through the operations that produced it. It does not choose the loss, fix incorrect target alignment or infer the intended normalization. The optimizer update is another operation with its own state and semantics.</p>
<div class="method-table"><table><caption>Equivalent responsibilities in the CPU companion</caption><thead><tr><th scope="col">Responsibility</th><th scope="col">PyTorch</th><th scope="col">JAX</th><th scope="col">TensorFlow / Keras</th></tr></thead><tbody>
<tr><th scope="row">Represent parameters</th><td>Floating tensors with requires_grad=True</td><td>A tuple or other pytree of floating arrays</td><td>tf.Variable or tracked Keras layer weights</td></tr>
<tr><th scope="row">Find derivatives</th><td>loss.backward() accumulates into leaf .grad fields</td><td>jax.value_and_grad(loss_fn) returns value and gradient tree</td><td>GradientTape records operations; tape.gradient returns derivatives</td></tr>
<tr><th scope="row">Apply this SGD rule</th><td>SGD.step() after zero_grad and backward</td><td>tree.map((p,g) → p−ηg); retain the returned parameters</td><td>Keras SGD.apply_gradients pairs derivatives with variables</td></tr>
<tr><th scope="row">Persistent state</th><td>Parameters, buffers, optimizer slots and random state</td><td>Explicit parameter / optimizer / random-key state in this functional loop</td><td>Variables, layer state, optimizer slots and random state</td></tr>
</tbody></table></div>
<p>PyTorch normally rebuilds its autograd graph as eager operations run. Clear gradients at the start of the intended accumulation window; otherwise backward adds to existing gradients. Calling a module's <code>eval()</code> changes behaviors such as dropout and batch normalization but does not itself disable gradients. Freezing parameter gradients, changing training mode, and entering a no-gradient context have distinct effects.</p>${ref(torchGrad, "PyTorch 2.14 autograd mechanics · graph recording, gradient accumulation and evaluation mode")}
<p>JAX differentiates a function with respect to chosen array arguments and returns the result. The companion keeps parameters explicit, then retains the updated tree. Flax supplies neural-network modules and state conventions on top of JAX; its NNX interface can present mutable object state while its transformations manage that state. Optax supplies composable gradient transformations and optimizer state. Neither is required to derive our single SGD update.</p>${ref(jaxGrad, "JAX automatic differentiation · grad, value_and_grad and parameter containers")}${ref("https://flax.readthedocs.io/en/latest/why.html", "Flax NNX guide · modules, state and JAX transformations")}${ref("https://optax.readthedocs.io/en/latest/getting_started.html", "Optax getting started · gradient transformations and optimizer state")}
<p>A <strong>leaf tensor</strong> in the PyTorch example is a directly created trainable tensor, rather than an intermediate produced by another tracked operation. A <strong>pytree</strong> is a nested container of arrays, such as a dictionary of layer names containing weight and bias arrays; its derivative has the same container structure. An optimizer <strong>slot</strong> is saved state associated with a parameter, such as Adam's first moment. The vocabulary differs, but each path must identify the same parameters and preserve the corresponding update history.</p>
<p>TensorFlow's tape automatically watches trainable variables used while the tape is active. Plain tensors may need <code>tape.watch</code>. An unconnected source commonly yields None; a connected derivative can instead be exactly zero. Leaving the framework for a NumPy calculation can sever the path even if the resulting numbers look correct. Check which variables the tape watched and which operations happened inside it before diagnosing an optimizer.</p>${ref(tfGrad, "TensorFlow autodiff guide · watched sources, unconnected gradients and leaving TensorFlow")}
<details class="deep-dive"><summary>What a checkpoint must preserve beyond weights</summary><p>A resumed training trajectory also depends on optimizer accumulators, scheduler position, precision scaling where used, random-generator state, and data progress. Saving only W and b is enough to reproduce this deterministic one-step example, but not a general continuation of Adam training with shuffled data and dropout. Parameter names, order and shape must match the optimizer's saved state; silently attaching a momentum buffer to a different tensor is not a valid migration.</p></details>
${check("The loss has a plausible number, but one parameter has no gradient. Is a smaller learning rate the first fix?", "First inspect whether the parameter participates in the differentiated function, is watched or requires gradients, and remains connected through framework operations. A disconnected path is different from a connected zero derivative. A learning-rate change cannot reconnect it.")}
</section>

<section class="lesson" id="framework-tracing-boundaries" data-lesson="Tracing and graph boundaries">
<header><span>Execution is another layer</span><h3>A derivative graph, a compiler graph and a GPU launch graph answer different questions</h3></header>
<p><strong>Eager execution</strong> dispatches framework operations as Python runs; device work may still complete asynchronously. <strong>Tracing</strong> records a supported computation using information about arguments. A compiler can then transform that representation into executable work. Automatic differentiation describes dependencies for derivatives. None of these statements implies that the whole training step becomes one GPU kernel.</p>
<figure class="textbook-lab framework-workbench" id="framework-execution-map"><figcaption><span>Interactive · original execution schematic</span><strong>Locate Python, differentiation and graph execution</strong><p>Choose an API and a situation. Rectangles show responsibilities, arrows show the order in this example, and the explanation identifies the boundary that matters.</p></figcaption>
<div class="method-toolbar"><label>Framework path<select data-fw-engine><option value="torch">PyTorch</option><option value="jax">JAX</option><option value="tensorflow">TensorFlow</option></select></label><label>Situation<select data-fw-phase><option value="eager">Differentiate without whole-function compilation</option><option value="first">First graph call</option><option value="reuse">Reuse a compatible graph</option><option value="branch">Python if on a tensor value</option></select></label></div>
<p class="framework-scroll-hint">Scroll the diagram sideways to follow every boundary.</p><div class="framework-map" data-fw-execution-map tabindex="0" role="region" aria-label="Execution stages; scroll horizontally on narrow screens"></div><p class="framework-result" data-fw-execution-description aria-live="polite"></p>
<p class="figure-boundary">Conceptual API paths, not a trace from a GPU. Backend lowering can produce multiple library calls, kernels and synchronization points. The companion separately records actual CPU capture or trace counts.</p></figure>
<p><strong>PyTorch:</strong> torch.compile uses Dynamo to capture supported regions and checks guards before reuse. A graph break can execute intervening Python and resume capture; it does not necessarily end the whole call. Data-dependent Python control flow is a common boundary. <code>fullgraph=True</code> makes an unsupported break fail, which is useful when checking that a chosen region really is captured.</p>${ref(torchBreak, "PyTorch 2.14 compiler programming model · graph breaks and fullgraph")}
<p><strong>JAX:</strong> jax.jit traces a function with abstract values and then compiles it. Array shape and dtype are available during tracing; ordinary array contents are not concrete Python values. A Python <code>if x.sum() &gt; 0</code> therefore cannot simply choose a branch from a traced value. Express runtime branching with an appropriate JAX operation such as <code>jax.lax.cond</code>. Ordinary Python print or list mutation happens during tracing and must not be used as the training-state update.</p>${ref(jaxJit, "JAX JIT guide · tracing, Python effects, control flow and compilation")}
<p><strong>TensorFlow:</strong> tf.function traces a graph. AutoGraph can convert supported Python control flow when the source is available and convertible; otherwise use explicit TensorFlow control-flow operations. Python effects occur while tracing, whereas a TensorFlow operation such as tf.print can execute in the graph. A tf.function graph is not automatically proof of XLA compilation; the companion explicitly uses <code>jit_compile=False</code>.</p>${ref(tfFunction, "TensorFlow function guide · tracing, AutoGraph and Python effects")}
<p>The <a href="#framework-cuda-replay">CUDA Graph replay lesson</a> adds another boundary: captured device launches and memory addresses. Compilation, differentiation and replay can cooperate, but success at one layer does not establish correctness or speed at another. Follow <a href="#framework-benchmark-boundary">the benchmark boundary</a> before timing asynchronous work.</p>
${check("A graph capture counter reports one graph. Does that prove one kernel or a speedup?", "No. A captured graph can lower to many kernels or library calls, and our PyTorch counting backend deliberately executes the captured graph eagerly. Inspect generated work and measure completed execution against a stated baseline after checking numerical parity.")}
</section>

<section class="lesson" id="framework-shapes-and-migration" data-lesson="Shapes, reuse and migration">
<header><span>Make specialization visible</span><h3>Changing values is different from changing the program signature</h3></header>
<p>A cached executable is valid under assumptions. These may include shape, dtype, device, static arguments, object identity, layout and guards. A new batch's numerical values need not require a new graph. Conversely, an unchanged Python function name does not ensure reuse when those assumptions change.</p>
<figure class="textbook-lab framework-workbench" id="framework-trace-cache-lab"><figcaption><span>Interactive · declared cache policy</span><strong>Replay six calls and account for every new signature</strong><p>The teaching cache keys on input shape, dtype and a static training flag. Choose whether its batch dimension is fixed or variable. This is an explicit model, not a predictor of all three frameworks.</p></figcaption>
<div class="method-toolbar"><label>Batch-dimension contract<select data-fw-signature><option value="exact">Exact batch size</option><option value="variable">Variable batch dimension B</option></select></label><label>Show calls through<select data-fw-call><option>1</option><option>2</option><option>3</option><option>4</option><option>5</option><option selected>6</option></select></label></div><p class="framework-result" data-fw-cache-summary aria-live="polite"></p><p class="framework-scroll-hint">Scroll the call ledger sideways to inspect signatures and reuse.</p><div class="method-table" data-fw-cache-table tabindex="0" role="region" aria-label="Call signatures and cache reuse; scroll horizontally if needed"></div><p class="figure-boundary">Only the declared keys are modeled. Real systems have additional guards, limits, specialization rules, optimization passes and compilation costs; the figure assigns no latency.</p></figure>
<p>With fixed shapes this ledger creates four entries. Allowing B to vary creates three because the six-row call can reuse the three-row call's shape contract. Dtype and static mode still differ. “Variable batch” is a permission to reuse compatible work; it does not make incompatible widths, operations or dtypes valid.</p>
<p>In the pinned CPU companion, PyTorch explicitly requests <code>dynamic=False</code>, JAX uses an ordinary shape-specialized jit, and TensorFlow compares exact tensor signatures against <code>TensorSpec([None,2], float64)</code>. Those choices expose different policies. PyTorch's automatic dynamic-shape behavior and recompilation limits should be inspected under the actual configuration; forcing every framework into one generic caching story would hide the point of the experiment.</p>${ref(torchRecompile, "PyTorch 2.14 compiler guide · guards, dynamic shapes and recompilation")}${ref(tfFunction, "TensorFlow function guide · explicit input signatures and variable dimensions")}
<details class="deep-dive"><summary>Porting a model requires more than changing import names</summary><p>Confirm weight layout first: our W has shape [input,output], matching the usual Dense kernel convention, while a PyTorch Linear weight is stored [output,input]. The companion uses explicit x@W to avoid a hidden transpose. Then check target shift, mask placement, mean denominator, dtype, train/evaluation behavior, random state and optimizer defaults. Compare forward outputs, scalar loss, each parameter's gradient and the update separately. A matching scalar loss can conceal wrong parameter mapping.</p><p>Keras 3 supports multiple backends, but portable model code must use compatible operations and state construction. Build tracked weights in the proper lifecycle; a TensorFlow GradientTape training loop remains tied to TensorFlow even when the model could run elsewhere. The companion's Keras Dense check deliberately uses its TensorFlow backend.</p>${ref(kerasGuide, "Keras 3 migration guide · backend-compatible operations and state construction")}</details>
<details class="deep-dive" id="framework-executable-contract"><summary>Run the CPU parity and real tracing companion</summary><p><code>examples/frameworks/execution_contract.py</code> runs five mask/reduction/batch cases per framework and then three calls through each selected graph path. It checks loss, every weight/bias derivative, and every updated parameter against an independent scalar reference within absolute/relative tolerance 1e−10. The Keras Dense path checks the default case too. See <code>examples/frameworks/execution_README.md</code> for dependencies, commands, execution evidence and limits.</p><p><strong>Executed September 16, 2026:</strong> native arm64 Python 3.11.5, CPU float64, PyTorch 2.8.0 and JAX 0.6.2. Both passed all five numerical cases and three graph calls; maximum absolute discrepancy was 2.22×10⁻¹⁶. Each recorded two graph captures or traces: changed values reused the three-row signature, while six rows created another. The TensorFlow 2.20 / Keras 3.11.3 paths are supplied but remain unexecuted because the temporary installation exceeded available disk space.</p><div class="code-block"><div class="code-caption"><span>Python · executable companion</span><strong>One contract across PyTorch, JAX and TensorFlow / Keras</strong></div><pre><code>${escapeCode(executionSource)}</code></pre></div><p>The PyTorch compiler check counts Dynamo captures with an eager backend; it does not validate Inductor code generation. JAX exercises XLA CPU compilation. The TensorFlow path requests tf.function with XLA disabled. No GPU, distributed training, model-quality or throughput result follows from these checks.</p></details>
${check("A TensorFlow signature allows a variable batch. Can a different feature width reuse it?", "Not when the signature fixes that width at two. Variable dimensions are specific permissions. The operation, parameter shapes, dtype and remaining signature constraints still have to agree.")}
</section>`;
