import { sourceLink as ref, workedCheck as check, escapeCode } from "./lesson-template";
import stopReference from "../examples/frameworks/serving_contract.py?raw";

export const servingFrameworkBridgeLesson = `
<section class="lesson" id="framework-token-boundary" data-lesson="Messages, tokens and stops"><header><span>The serving boundary</span><h3>A chat message, a model token and a streamed chunk are different objects</h3></header>
<p>A user submits a list of role-labelled messages. A <strong>chat template</strong> serializes those messages into the sequence the model was trained to continue. A tokenizer maps that sequence to integer IDs. The model consumes IDs and predicts IDs; a detokenizer and response formatter produce the text the user sees. Each boundary can introduce a difference even when the weight files match.</p>
<p>Consider an invented teaching vocabulary: <code>[BOS]=1, [USER]=2, Hi=10, [END]=3, [ASSISTANT]=4</code>. A one-turn template might produce <code>[1,2,10,3,4]</code>. Sending only <code>[10]</code> asks the model to continue a different context. Adding a second BOS yields <code>[1,1,2,10,3,4]</code>; the token count, positions and prefix identity all change. These are illustrative IDs, not a real model's vocabulary.</p>
<p>In Transformers 4.57.1, <code>apply_chat_template(..., tokenize=True)</code> performs template rendering and tokenization together. If rendering text first, the documentation instructs the later tokenization to use <code>add_special_tokens=False</code> to avoid duplicating special tokens. Starting a new assistant turn and continuing a partially written final message are different template operations. Inspect the resulting IDs for your exact tokenizer and template revision.</p>
${ref("https://huggingface.co/docs/transformers/v4.57.1/chat_templating", "Transformers 4.57.1 · chat templates and special-token ownership")}
<h4>Stopping occurs at more than one boundary</h4>
<p>An EOS or configured <strong>stop token ID</strong> ends generation when that ID is selected. A <strong>stop string</strong> matches decoded text and can span several tokens or lie inside a token's decoded piece. An output-length limit counts tokens according to the endpoint's contract. A connection closing is transport state: it does not by itself explain whether the model finished, hit its limit or failed.</p>
<p>SGLang's sampling reference separates <code>stop</code>, <code>stop_token_ids</code>, <code>ignore_eos</code> and stop trimming. Those distinctions are real configuration choices; the toy below specifies its own string-matching rule so the behavior is reproducible.</p>
${ref("https://docs.sglang.io/docs/basic_usage/sampling_params", "SGLang sampling parameters · live documentation checked September 16, 2026")}
<figure class="textbook-lab framework-serving-lab" id="framework-stop-lab"><figcaption><span>Interactive</span><strong>Hold a possible delimiter until the next text arrives</strong><p>Step through decoded text. Change chunking while keeping the generated text fixed; the final visible text must stay the same.</p></figcaption>
<div class="method-toolbar"><label>Generated text<select data-serving-stop-scenario><option value="match">Hello &lt;END&gt;ignored</option><option value="unfinished">Hello &lt;EN · then normal EOF</option><option value="false-alarm">Hello &lt;ENO&gt; · no stop</option></select></label><label>Text delivery<select data-serving-stop-chunks><option value="pieces">Illustrative token pieces</option><option value="characters">One character per chunk</option><option value="whole">One coalesced chunk</option></select></label><label>Arrivals processed<input type="range" min="0" max="5" value="3" data-serving-stop-step/><output data-serving-stop-step-value></output></label></div>
<div class="framework-stop-state" aria-live="polite"><div><span>Newly released text</span><strong data-serving-stop-emitted></strong></div><div><span>Held possible delimiter</span><strong data-serving-stop-held></strong></div><div><span>Total visible text</span><strong data-serving-stop-visible></strong></div></div>
<p class="framework-serving-result" data-serving-stop-result></p><div class="method-table" data-serving-stop-trace tabindex="0" role="region" aria-label="Text stop trace; scroll horizontally on narrow screens"></div>
<p class="figure-boundary">Original text adapter, not an engine emulator. Stop is the literal string &lt;END&gt;, excluded from output. The first completed stop wins; simultaneous matches prefer the longest. Inputs are decoded strings, not raw UTF-8 packets. EOF releases an incomplete delimiter. No latency or model-token count is estimated.</p></figure>
<p>After <code>"Hello &lt;EN"</code>, the adapter can safely release <code>"Hello "</code> but must retain <code>"&lt;EN"</code>. If the next piece is <code>"D&gt;"</code>, releasing the retained text earlier would have leaked a delimiter that the API promised to exclude. If normal EOF arrives first, the incomplete suffix is ordinary output and can be released. This buffering can delay a visible text event without delaying model token production.</p>
<details class="deep-dive"><summary>Run the complete CPU stop-filter reference</summary><p>The file below is imported directly from <code>examples/frameworks/serving_contract.py</code>. It needs only Python's standard library. Tests enumerate every partition of short input strings and include overlapping stops and repeated terminal calls.</p><div class="lesson-code"><span>Python · complete text-stop reference</span><pre><code>${escapeCode(stopReference)}</code></pre></div><div class="lesson-code"><span>Shell · run and verify locally</span><pre><code>python3 examples/frameworks/serving_contract.py
python3 -m unittest discover -s examples/frameworks -p 'serving*_test.py' -v</code></pre></div><p>A real client must incrementally decode UTF-8 bytes and parse its event framing before feeding text into an adapter. Do not equate one socket read, one server-sent event, one text delta and one token. Client-side trimming also does not cancel upstream generation; cancellation requires the server's request-lifetime protocol.</p></details>
${check("Check: the text stream contains five chunks. Did the model generate five tokens?", "You cannot infer that. A chunk may combine several decoded tokens, contain only protocol metadata, or withhold a partial stop or Unicode sequence. Count model tokens using the engine's token IDs or documented usage field, and measure visible text events separately.")}
</section>`;

export const frameworkServingLessons = `
<section class="lesson" id="framework-model-artifacts" data-lesson="Engines and model artifacts"><header><span>Serving implementations</span><h3>Loading a model requires an executable interpretation of its files</h3></header>
<p class="figure-boundary">Research check: September 16, 2026. vLLM links use version 0.22.0; Transformers uses 4.57.1. SGLang, llama.cpp and MLX LM links are dated live documentation. TensorRT-LLM's cited migration snapshot was generated from commit c295dd9 on September 4, 2026. These sources establish documented interfaces, not a locally reproduced model or speed comparison.</p>
<p>A checkpoint is a collection of parameter values and metadata. An <strong>engine</strong> supplies the executable model, kernels, state allocation and generation loop. A tensor container does not tell you that every architecture, quantization scheme or feature combination can execute. An HTTP API describes how requests and responses are exchanged. A deployment coordinator places and routes engine instances. Keep those responsibilities distinct even when one project offers several of them.</p>
<div class="method-table framework-engine-table" tabindex="0" role="region" aria-label="Serving engines, model interpretation and interface responsibilities"><table><caption>Concrete responsibilities to inspect when moving the same application between implementations</caption><thead><tr><th scope="col">Implementation</th><th scope="col">Model and execution responsibility</th><th scope="col">Input/output boundary to verify</th></tr></thead><tbody>
<tr><th scope="row">vLLM<br><small>0.22.0</small></th><td>Native model implementations and a documented Transformers modeling backend. A Hugging Face model directory still needs a compatible architecture and feature combination.</td><td><code>vllm serve</code> supplies HTTP serving. Chat requests require a template; inspect which implementation actually loaded. ${ref("https://docs.vllm.ai/en/v0.22.0/models/supported_models/", "vLLM · model implementations and support")}</td></tr>
<tr><th scope="row">SGLang<br><small>Dated live docs</small></th><td>The server runtime accepts model requests and controls generation. Its server chat-template system is separate from the SGLang language frontend's template system.</td><td>The server defaults to the model tokenizer's Hugging Face template; a launch override can change the input. Verify native sampling parameters separately from API field names. ${ref("https://docs.sglang.io/docs/references/custom_chat_template", "SGLang · server template ownership")}</td></tr>
<tr><th scope="row">TensorRT-LLM<br><small>c295dd9 docs</small></th><td>The cited migration guide specifies a PyTorch execution backend that loads supported Hugging Face checkpoints directly; AutoDeploy remains built on that backend.</td><td><code>trtllm-serve</code> wraps generation in an API. Old checkpoint-conversion and <code>trtllm-build</code> recipes describe a removed backend. ${ref("https://nvidia.github.io/TensorRT-LLM/latest/legacy/tensorrt-backend-removal.html", "TensorRT-LLM · dated backend migration")}</td></tr>
<tr><th scope="row">llama.cpp<br><small>Dated server README</small></th><td>C/C++ inference with model files commonly packaged as GGUF. The executable must implement the architecture and tensor types carried by the file.</td><td><code>llama-server</code> offers native and compatibility endpoints; its native <code>/completion</code> is a different interface from <code>/v1/completions</code>. ${ref("https://github.com/ggml-org/llama.cpp/blob/master/tools/server/README.md", "llama.cpp · server interface reference")}</td></tr>
<tr><th scope="row">MLX LM<br><small>Apple silicon</small></th><td>A Python model package on MLX, with model loading, quantization/conversion and generation. MLX-compatible weights and model implementations are the relevant boundary.</td><td><code>generate</code> and <code>stream_generate</code> expose local generation; inspect tokenizer templating and sampler/logits-processor settings. ${ref("https://github.com/ml-explore/mlx-lm", "MLX LM · model loading and generation")}</td></tr>
</tbody></table></div>
<h4>Read an artifact as a manifest</h4>
<p>Record the model's immutable revision, architecture/configuration, tensor names and shapes, weight dtype or quantization metadata, tokenizer revision, special-token IDs and template. If adapters are loaded separately, record their base-model revision, weights and scaling. A friendly API model name such as <code>assistant-prod</code> is a routing alias; it need not identify an immutable checkpoint.</p>
<p>GGUF illustrates the difference clearly: it is a tensor-and-metadata format and can include <code>tokenizer.chat_template</code>. Its specification describes an embedded computation graph as a future extension. A valid GGUF header therefore does not establish that an arbitrary runtime knows how to compute that model. Equally, a <code>.safetensors</code> extension alone does not specify architecture, quantization axes or a chat template.</p>
${ref("https://github.com/ggml-org/ggml/blob/master/docs/gguf.md", "GGUF specification · metadata, template and computation-graph boundary; checked September 16, 2026")}
<p>Conversion may rename and reshape tensors, pack integer codes, attach scales, or alter numerical values through quantization. Separate <em>can the loader read this artifact?</em> from <em>does this execution preserve the intended model behavior?</em> A successful load answers the first question. Validate the second at fixed token inputs before comparing complete generations.</p>
<details class="deep-dive"><summary>Why the TensorRT-LLM version label matters</summary><p>The migration snapshot says the TensorRT engine backend and separate conversion/build commands were removed. Its release notes place that breaking change under Release 1.2. Older retained pages still explain engine construction. Follow the documentation matching your installed version; do not infer that a current wheel accepts a legacy engine directory from the project's name.</p>${ref("https://nvidia.github.io/TensorRT-LLM/release-notes.html#tensorrt-llm-release-1-2", "TensorRT-LLM release notes · Release 1.2 API changes, checked September 16, 2026")}<p>The current command reference exposes tokenizer, revision, generation-defaults and response-parser options. Some options are explicitly prototype or deprecated. An option's presence is not proof that every model, device and other option can be combined with it.</p>${ref("https://nvidia.github.io/TensorRT-LLM/latest/commands/trtllm-serve/trtllm-serve.html", "TensorRT-LLM · command reference at documentation commit c295dd9")}</details>
${check("Check: both engines accept the same HTTP request and both weight files say four bits. Have you established model equivalence?", "No. Check immutable weights, quantizer scales and grouping, tokenizer/template, executable architecture, special tokens and the numerical execution path. Four bits describes only part of the representation; API acceptance describes only part of the request contract.")}
</section>

<section class="lesson" id="framework-api-contract" data-lesson="Compatible request contracts"><header><span>Application portability</span><h3>An accepted JSON request can still mean something different</h3></header>
<p>“OpenAI-compatible” identifies an interface family. It is useful for reusing clients, but individual engines document their supported endpoints, fields and behavior. For example, vLLM 0.22.0 documents that completions do not support <code>suffix</code> and that chat ignores <code>user</code>. Its chat endpoint also requires a template. Application portability is a field-by-field contract.</p>
${ref("https://docs.vllm.ai/en/v0.22.0/serving/online_serving/", "vLLM 0.22.0 · supported endpoints, field limitations and chat templates")}
<p>An omitted field is also a choice. SGLang's cited reference says its default sampling source is the model's <code>generation_config.json</code> under <code>--sampling-defaults model</code>; its alternative source is selected separately. Two servers with an identical short JSON request can therefore resolve different defaults. Record the resolved settings, including temperature, top-p/top-k, penalties, stop IDs and length limits.</p>
${ref("https://docs.sglang.io/docs/basic_usage/sampling_params", "SGLang · sampling defaults and per-request overrides, checked September 16, 2026")}
<div class="lesson-code"><span>JSON · small request specimen, not a universal compatibility test</span><pre><code>{
  "model": "YOUR_SERVED_MODEL_ALIAS",
  "messages": [{"role": "user", "content": "Return one short sentence."}],
  "temperature": 0,
  "max_tokens": 24,
  "stream": false
}</code></pre></div>
<p>Send this only after confirming that the chosen endpoint supports these fields and the alias. Its visible text is a basic integration result. It does not expose the rendered prompt IDs, the entire sampling chain, or which kernel produced the logits. The <a href="#framework-token-boundary">messages, tokens and stops lesson</a> shows why even text length and token count differ.</p>
<h4>Define what must agree</h4>
<div class="method-table" tabindex="0" role="region" aria-label="Serving contract comparison layers"><table><thead><tr><th scope="col">Layer</th><th scope="col">Concrete comparison</th><th scope="col">What it establishes</th></tr></thead><tbody>
<tr><th scope="row">Prompt construction</th><td>Exact rendered token IDs, positions, mask and any nontext inputs</td><td>Both executions received the same effective model input</td></tr>
<tr><th scope="row">Model computation</th><td>Next-token logits on fixed teacher-forced prefixes</td><td>Numerical agreement at those inputs, under a declared tolerance</td></tr>
<tr><th scope="row">Sampling policy</th><td>Ordered penalties, masks, temperature/filtering, seed and random-number implementation</td><td>The intended distribution and sampling procedure are comparable</td></tr>
<tr><th scope="row">Response formatting</th><td>Text trimming, finish reason, tool/reasoning fields and usage accounting</td><td>The application receives the contract it expects</td></tr>
</tbody></table></div>
<p>For a tool-using model, supplying a tool schema, generating the model's tool-call syntax, and parsing that syntax into a structured response are three operations. A grammar can constrain syntax; it does not execute the tool or establish that its arguments are correct. Keep a small golden fixture for each behavior the application uses: ordinary chat, a multi-turn continuation, a stop across text pieces and any supported structured output.</p>
<h4>Close logits can still yield different greedy tokens</h4>
<p>Suppose the two largest reference logits are 3.0000 and 2.9999. Errors of −0.0001 on the first and +0.0001 on the second reverse the winner. Temperature zero does not remove numerical differences. Once a different token enters the history, later logits are conditioned on different inputs, so comparing only long free-running answers hides the first cause.</p>
<details class="deep-dive"><summary>A useful margin bound for greedy agreement</summary><p>Let z be the reference logits and ẑ the candidate logits for the same prefix. If <code>maxᵢ|ẑᵢ−zᵢ|≤ε</code> and the unique reference winner exceeds the runner-up by <code>Δ&gt;2ε</code>, the winner cannot change: its score can fall by at most ε while any competitor rises by at most ε. At a tie or smaller margin, this bound makes no promise. This is an arithmetic statement at one fixed input, not a guarantee for an entire generated sequence.</p><p>Report the maximum absolute logit difference, reference top-two margin and selected token at the first mismatch. A tolerance test on all observed prefixes is stronger evidence than matching one answer, but it still covers only the tested inputs. Identical seeds also do not align different random-number generators or sampling implementations.</p></details>
<p>llama.cpp's server README specifically warns that cached and uncached prompt processing can produce non-bit-identical logits on some backends because batch shapes differ. Treat token equality, numerical tolerance and task-level quality as separate measurements. An HTTP-only endpoint that exposes text alone cannot prove logit parity.</p>
${ref("https://github.com/ggml-org/llama.cpp/blob/master/tools/server/README.md", "llama.cpp · cache_prompt numerical caveat; checked September 16, 2026")}
${check("Check: the output differs only after token 37. Where should the parity investigation begin?", "At the first divergent decision, using the same fixed prefix on both engines. Confirm input IDs and resolved sampling settings, then compare logits and the top-two margin. Later free-running positions already have different histories and cannot isolate the original discrepancy.")}
</section>

<section class="lesson" id="framework-cache-identity" data-lesson="Cache identity across requests"><header><span>What a prefix means</span><h3>Cached state belongs to a computation, not to a matching text fragment</h3></header>
<p>In a dense causal decoder, a later layer's key and value for a token depend on the token's preceding context. Reusing a matching sentence from the middle of a different prompt generally reuses the wrong state. Exact prefix reuse requires the same effective prefix and the same model computation. A template change matters when it changes the IDs, positions or other inputs; a template filename alone is not the tensor computation.</p>
<p>vLLM 0.22.0's prefix-cache design chains each block's identity to its parent and exact block tokens. Extra identity includes adapters, multimodal inputs and cache-isolation salts. It documents caching full blocks. The diagram models that full-block rule with direct equality checks so the mechanism remains inspectable; it is not vLLM's production hash or cache allocator.</p>
${ref("https://docs.vllm.ai/en/v0.22.0/design/prefix_caching/", "vLLM 0.22.0 · prefix identity, parent hashes and full blocks")}
<figure class="textbook-lab framework-serving-lab" id="framework-cache-lab"><figcaption><span>Interactive</span><strong>Find the last complete block the new request may reuse</strong><p>Both rows contain explicit token IDs. A changed prefix token invalidates the blocks after it even if their local IDs match. Identity changes can invalidate every block. Scroll the rows sideways on narrow screens.</p></figcaption>
<div class="method-toolbar"><label>Incoming request<select data-serving-cache-case><option value="same">Same prompt and context</option><option value="token">Template changes token index 3</option><option value="adapter">Same IDs, different adapter</option><option value="weights">Same IDs, new model weights</option><option value="positions">Same IDs, shifted positions</option><option value="format">Same IDs, different cache format</option><option value="namespace">Same IDs, different cache namespace</option><option value="sampling">Same prompt, new temperature</option></select></label><label>Tokens per cache block<select data-serving-cache-block><option value="2">2</option><option value="4" selected>4</option></select></label></div>
<p class="framework-serving-result" data-serving-cache-result aria-live="polite"></p><div class="framework-cache-diagram" data-serving-cache-diagram tabindex="0" role="region" aria-label="Cached and incoming prefix blocks; scroll horizontally on narrow screens"></div><p class="framework-cache-legend">Blue border: eligible complete block · dashed border: incomplete tail · orange token: changed ID. Block and position indices begin at zero.</p><p data-serving-cache-explanation></p>
<p class="figure-boundary">Same-engine, dense causal, text-only reference with immutable evaluated KV. Only complete blocks are eligible; residency is assumed. Context includes weights, adapter, attention configuration, representation and namespace. It omits eviction, multimodal embeddings, hybrid recurrent state and cross-engine layout conversion. Eligible tokens do not directly equal saved milliseconds.</p></figure>
<h4>Separate semantic eligibility, representation and policy</h4>
<p><strong>Semantic eligibility:</strong> the prefix state must represent the same computation, including weights, adapter, positions and attention rules. <strong>Representation:</strong> the consumer must interpret dtype, scales, layer/head ordering and layout correctly. <strong>Policy:</strong> a namespace can deliberately prohibit sharing even when the numerical state would match. A resident, authorized and compatible entry is required for a real hit.</p>
<p>Changing only temperature does not change the already evaluated prompt KV in this fixed model: temperature acts on output logits. It can change the newly sampled continuation, whose cache then follows that new history. Conversely, identical prompt IDs do not preserve state after a weight or adapter update. A block hash scoped inside one model instance is not automatically a portable identity for another engine.</p>
<p>The lab's ten-token prefix has eight reusable tokens with four-token blocks: the two-token tail is incomplete. If token index 3 changes, no full four-token block matches. With two-token blocks, the first two tokens remain eligible. Moving an otherwise identical sentence to another prompt position cannot restore the missing ancestor prefix.</p>
<p>KV state alone also does not contain the final vocabulary logits. Even an eligible prefix may need boundary work to produce the next decision, depending on what the engine retains. Thus the diagram counts eligible state, not an exact number of model operations skipped.</p>
<details class="deep-dive"><summary>A reproducible identity record for a serving experiment</summary><p>Store immutable artifact and tokenizer revisions, exact rendered prompt IDs, position/mask configuration, adapter revision/scales, precision settings, engine version and cache layout. Record template and generation settings as provenance even when some are not direct inputs to the KV function. Multimodal placeholders need the identity of the actual encoded inputs; identical placeholder IDs alone are insufficient.</p><p>Separate a <em>request record</em> used to reproduce behavior from a minimal <em>cache key</em> used for reuse. A request record includes stop strings and sampling settings; a minimal prompt-KV key need not include settings that only transform the later output distribution. Over-keying wastes reuse; omitting a true dependency can return incorrect state.</p></details>
${check("Check: the system prompt is unchanged, but an adapter was updated in place under the same friendly name. Can the old KV be reused?", "No under this model. The adapter weights participate in the computation that created the cache. A name is not an immutable weight identity. Advance the adapter revision and invalidate or separate entries; merely keeping the same text and name does not preserve their numerical meaning.")}
</section>`;
