import { sourceLink as ref, workedCheck as check, escapeCode } from "./lesson-template";
import trainingReference from "../examples/frameworks/training_reference.py?raw";
import hfSmoke from "../examples/frameworks/training_hf_smoke.py?raw";

const chat = "https://huggingface.co/docs/transformers/v4.57.1/en/chat_templating";
const tokenizer = "https://huggingface.co/docs/transformers/v4.57.1/en/main_classes/tokenizer";
const model = "https://huggingface.co/docs/transformers/v4.57.1/en/main_classes/model";
const gpt2 = "https://huggingface.co/docs/transformers/v4.57.1/en/model_doc/gpt2";
const accelerate = "https://huggingface.co/docs/accelerate/v1.11.0/en/quicktour";
const accumulation = "https://huggingface.co/docs/accelerate/v1.11.0/en/usage_guides/gradient_accumulation";
const peft = "https://huggingface.co/docs/peft/v0.17.0/en/developer_guides/checkpoint";
const lora = "https://huggingface.co/docs/peft/v0.17.0/package_reference/lora";
const trl = "https://huggingface.co/docs/trl/v0.24.0/en/sft_trainer";

export const trainingFrameworkBridgeLesson = `
<section class="lesson" id="framework-label-ownership" data-lesson="Who shifts the labels?">
<header><span>From objective to API</span><h3>Shift a prediction exactly once, and mask padding by position</h3></header>
<p>The <a href="#post-training-loss">SFT alignment lesson</a> shows what each position must predict. An implementation adds another question: <strong>which component performs that shift?</strong> Some loops explicitly pair <code>logits[:,:-1]</code> with <code>targets[:,1:]</code>. The pinned Transformers GPT-2 API instead accepts labels aligned with input IDs and shifts them inside its loss calculation. Its ignore label is −100, a loss sentinel rather than a token ID.</p>
${ref(gpt2, "Transformers 4.57.1 · GPT2LMHeadModel labels: internal shift and ignore index")}
<p>For the illustrative sequence [BOS,user,question,assistant,answer,EOS,PAD,PAD], response-only API labels are <code>[−100,−100,−100,−100,answer,EOS,−100,−100]</code>. The model pairs the assistant-marker logit row with the answer label at the next position. Pre-shifting that label array again makes the question position predict the answer, before the assistant marker has been read.</p>
<figure class="textbook-lab framework-workbench" id="framework-label-lab"><figcaption><span>Interactive · original token example</span><strong>Follow the labels across the collator/model boundary</strong><p>Column numbers are physical array positions. Diagonal lines show the model's single i→i+1 alignment. Change the collator behavior to see the actual prediction pairs and denominator.</p></figcaption>
<div class="method-toolbar"><label>Target mask<select data-framework-mask><option value="assistant">Assistant answer + real EOS</option><option value="all">Every nonpadding target</option><option value="token-id">Assistant, then ignore every EOS ID</option></select></label><label>Collator label handling<select data-framework-shift><option value="once">Keep labels aligned</option><option value="twice">Pre-shift labels again</option></select></label><label>Retained sequence length<select data-framework-length><option value="8">8 · includes two padding positions</option><option value="6">6 · ends at real EOS</option><option value="5">5 · EOS truncated</option><option value="4">4 · entire answer truncated</option></select></label></div>
<div class="framework-readout" data-framework-label-result aria-live="polite"></div><div class="architecture-scroll" data-framework-label-chart tabindex="0" role="region" aria-label="Token, attention and label alignment diagram; scroll horizontally on narrow screens"></div><div class="method-table" data-framework-label-table tabindex="0" role="region" aria-label="Scored targets and losses; scroll horizontally if needed"></div>
<p class="figure-boundary">Eight illustrative tokens, six vocabulary IDs, Float64 arithmetic and assigned probabilities. EOS and padding deliberately share ID 5 but have different positions. This diagram does not run a tokenizer or model; the separate local framework companion exercises those APIs.</p></figure>
<h4>The same ID can mean a real target or a padded slot</h4>
<p>Suppose an application reuses its EOS ID to fill padded slots. The predicate <code>input_ids == eos_token_id</code> cannot distinguish a genuine end token from padding. Build labels from the known padding positions and declared assistant spans. Here the correct answer/EOS losses are 0.4 and 0.8, giving 0.6. Deleting every EOS-valued label leaves loss 0.4 and removes the direct training signal for ending the response. A lower reported loss can therefore expose a masking bug.</p>
<div class="lesson-code"><h4>PyTorch · aligned labels for the pinned model-owned shift</h4><pre><code>labels = input_ids.clone()
# assistant_mask describes target-token positions, before any shift.
labels[(attention_mask == 0) | ~assistant_mask.bool()] = -100
assert labels[:, 1:].ne(-100).any(), "no valid next-token targets"
outputs = model(input_ids=input_ids, attention_mask=attention_mask,
                labels=labels, use_cache=False)
# Equivalent explicit pairing for this API: logits[:, :-1], labels[:, 1:].
# Do not apply both that explicit shift AND the model's labels loss.</code></pre></div>
<p>An assistant span should come from the template/tokenization contract, not a guessed number of characters or a substring search for “assistant.” In TRL 0.24.0, <code>assistant_only_loss=True</code> requires a conversational dataset and a template that can return assistant-token masks through generation blocks. Prompt/completion masking is a separate supported setting. Inspect the rendered IDs and masks after template application and truncation; include or exclude assistant control/end tokens deliberately.</p>
${ref(trl, "TRL 0.24.0 · assistant-only versus completion-only loss and template-mask requirement")}
${check("The padding mask and loss mask are correct. Does that establish isolation between packed conversations?", "No. Their attention and position boundaries still need the intended packed-sequence contract. Removing direct loss on a prompt does not prevent responses from attending to it; removing a padding target is also separate from blocking cross-example attention.")}
<p>Continue to <a href="#framework-model-contract">model and tokenizer contracts</a> for the local API example and <a href="#framework-distributed-objective">wrapper normalization</a> for preserving this target count across workers.</p>
</section>`;

export const frameworkTrainingLessons = `
<section class="lesson" id="framework-model-contract" data-lesson="Models, tokenizers and batches">
<header><span>Names become numerical inputs</span><h3>A model object is only one part of a reproducible training example</h3></header>
<p class="figure-boundary">Training ecosystem source check: September 16, 2026. API examples deliberately cite Transformers 4.57.1, Accelerate 1.11.0, PEFT 0.17.0 and TRL 0.24.0. They define a concrete teaching contract, not the newest releases or a validated combined GPU environment. Native runtime references identify their own versions or inspection date.</p>
<p><strong>Hugging Face Transformers</strong> provides model implementations, configuration objects, tokenizer interfaces and training/generation utilities. <code>AutoModelForCausalLM</code> selects a compatible implementation from the configuration; it does not make unrelated architectures or token vocabularies interchangeable. A weight tensor has dimensions. A complete model also assigns those dimensions a meaning: layer ordering, attention heads, position treatment, normalization and vocabulary rows.</p>
${ref(model, "Transformers 4.57.1 · model loading, configuration, resizing and serialization")}
<h4>Follow one batch across the boundary</h4>
<div class="method-table"><table><caption>Decoder-only batch contracts; B=batch, T=positions, V=vocabulary</caption><thead><tr><th scope="col">Object</th><th scope="col">Shape or role</th><th scope="col">What to verify</th></tr></thead><tbody><tr><th scope="row">Tokenizer + chat template</th><td>Messages → exact token sequence</td><td>Vocabulary identity, role/end markers and special-token insertion</td></tr><tr><th scope="row">input_ids</th><td>Integer [B,T]</td><td>Every ID addresses the intended embedding row</td></tr><tr><th scope="row">attention / positions</th><td>API-specific masks and position metadata</td><td>Padding, causality and packed-example boundaries</td></tr><tr><th scope="row">labels</th><td>Integer [B,T] for the pinned internal-shift API</td><td>One shift, target roles, ignored positions and valid count</td></tr><tr><th scope="row">logits</th><td>Floating [B,T,V]</td><td>Vocabulary-axis meaning and the exact rows scored by the loss</td></tr></tbody></table></div>
<p>A tokenizer with the same vocabulary size can still map “answer” to a different row. Loading weights without a shape error cannot detect that semantic mismatch. Conversely, adding a token changes the vocabulary contract: resize the model's embeddings through its supported API, account for the output head and tied weights, and preserve the new tokenizer with the resulting model. Record the newly initialized rows and whether they are trained.</p>
${ref(tokenizer, "Transformers 4.57.1 · tokenizer vocabulary, added tokens, masks and serialization")}
<p>A chat template serializes roles and content into that token stream. Training on complete conversations normally omits a new generation prompt at the end. If a template has already inserted its special tokens, a later tokenization pass that adds them again can duplicate boundaries. Use the template's tokenizing path, or explicitly manage special-token insertion in the two-stage path.</p>
${ref(chat, "Transformers 4.57.1 · chat serialization, special tokens and training preprocessing")}
<h4>A local test with no model download</h4>
<p>The companion constructs a seven-token WordLevel tokenizer and an original chat template, then creates a random one-layer GPT-2 with width 16 and two attention heads. It compares the model-owned loss against explicit shifted cross entropy, every parameter gradient and three SGD updates. It also saves and reloads the model and tokenizer, and exercises a PEFT adapter. These are API and arithmetic checks on tiny random weights, not language training or model-quality evidence.</p>
<div class="lesson-code"><h4>Python · local framework contract test</h4><pre><code>python examples/frameworks/training_hf_smoke.py</code></pre></div>
<details class="deep-dive"><summary>Read the full local Transformers + PEFT check</summary><p>Dependencies and execution evidence are recorded in <code>examples/frameworks/training_README.md</code>. The script uses temporary local artifacts, disables Hub access and does not launch distributed workers.</p><pre><code>${escapeCode(hfSmoke)}</code></pre></details>
${check("Two checkpoints have matching [V,d] embeddings. Can either tokenizer be used?", "No. Matching dimensions establish capacity, not token identity. Verify exact vocabulary mapping, normalization and special-token behavior, then the chat template. A vocabulary permutation would require the corresponding model-row transformation and its complete output/input contract.")}
</section>

<section class="lesson" id="framework-training-stack" data-lesson="Which tool owns which job?">
<header><span>Compose responsibilities</span><h3>Separate the model, training recipe and execution runtime</h3></header>
<p>Framework names often appear together because they solve different problems. Begin with a concrete update: construct a batch, evaluate the chosen loss, differentiate the trainable parameters, combine distributed contributions, update once and save the resulting state. Ask which component owns each step before adding a wrapper.</p>
<figure class="textbook-lab"><figcaption><span>Original responsibility diagram</span><strong>One update crosses four interfaces</strong><p>Read in order; checkpoint and evaluation paths observe the same contracts. This is a responsibility map, not a claim that every stack calls these packages.</p></figcaption><ol class="framework-responsibility-flow"><li><strong>Data → model inputs</strong><span>Tokenizer, template, collator, positions and label mask determine the exact examples.</span></li><li><strong>Model → loss</strong><span>Architecture and adapters produce logits; the recipe declares SFT, preference or rollout objectives.</span></li><li><strong>Loss → update</strong><span>Autograd, precision, accumulation, collectives and optimizer ownership determine the update.</span></li><li><strong>Update → artifact</strong><span>Export weights or adapters; separately preserve the state needed to resume training.</span></li></ol></figure>
<div class="method-table"><table><caption>Common Hugging Face components and the boundary they leave to the experiment</caption><thead><tr><th scope="col">Component</th><th scope="col">Typical responsibility</th><th scope="col">Still declare and check</th></tr></thead><tbody><tr><th scope="row">Transformers / Trainer</th><td>Model/tokenizer interfaces and a general training-loop abstraction</td><td>Architecture, data, labels, objective and callback behavior</td></tr><tr><th scope="row">Accelerate</th><td>Prepare model/optimizer/dataloader; adapt placement and backward to a selected execution setup</td><td>Backend configuration, reduction and accumulation semantics</td></tr><tr><th scope="row">PEFT</th><td>Inject and manage parameter-efficient adapters; expose their trainable state</td><td>Target modules, frozen versus trainable tensors, rank/scaling and base identity</td></tr><tr><th scope="row">TRL</th><td>Specialized post-training trainers and recipe configuration</td><td>Dataset format, response masking, reduction and the particular algorithm's semantics</td></tr></tbody></table></div>
${ref(accelerate, "Accelerate 1.11.0 · prepare, backward and dataloader responsibilities")}${ref(lora, "PEFT 0.17.0 · LoRA target modules, rank, scaling and variants")}${ref(trl, "TRL 0.24.0 · SFTTrainer configuration and PEFT integration")}
<p>For example, a Transformers causal model can receive PEFT adapters and be trained by TRL's SFTTrainer with its chosen runtime integration. This is not four independent optimizers. Inspect who creates the optimizer and which parameters it contains. A frozen base parameter should not accidentally become trainable; an added embedding or explicitly saved module should not disappear merely because the run is called “LoRA.”</p>
<h4>Choose the distributed ownership layer deliberately</h4>
<div class="method-table"><table><caption>Runtime responsibilities; mechanisms are explained in the linked earlier chapters</caption><thead><tr><th scope="col">Runtime family</th><th scope="col">What it supplies</th><th scope="col">Integration boundary</th></tr></thead><tbody><tr><th scope="row">Native PyTorch DDP</th><td>Replicated model, gradient synchronization across its data-parallel process group</td><td>Your loop still owns data partitioning, objective and update timing</td></tr><tr><th scope="row">Native PyTorch FSDP2</th><td>Sharded parameter state with group materialization and gradient reduction</td><td>Build sharding and optimizer setup in the supported order; inspect live tensors and checkpoint APIs</td></tr><tr><th scope="row">DeepSpeed</th><td>An engine controlling backward/update, precision and configured optimizer/state sharding</td><td>Its engine APIs and configuration own those operations; duplicated outer stepping changes the run</td></tr><tr><th scope="row">Megatron Core</th><td>Transformer-oriented distributed components, parallel layers, schedules and optimizer/checkpoint machinery</td><td>Architecture, mesh and tensor layouts must match its modules and conversion paths</td></tr></tbody></table></div>
${ref("https://docs.pytorch.org/docs/2.14/generated/torch.nn.parallel.DistributedDataParallel.html", "PyTorch 2.14 · DDP synchronization and caller-owned input sharding")}${ref("https://docs.pytorch.org/docs/2.14/distributed.fsdp.fully_shard.html", "PyTorch 2.14 · FSDP2 fully_shard and optimizer setup")}${ref("https://www.deepspeed.ai/getting-started/", "DeepSpeed · engine forward/backward/step and client checkpoint state; checked September 16, 2026")}${ref("https://docs.nvidia.com/megatron-core/developer-guide/latest/user-guide/index.html", "Megatron Core · model components and parallelism guide; checked September 16, 2026")}
<p>These are overlapping capabilities, not a universal nesting order. Use a documented integration when a higher-level trainer delegates to a runtime. Manually wrapping the same model in several independent distribution engines does not automatically compose their process groups, accumulation rules or checkpoint formats. For tensor ownership, return to <a href="#parallel-training">distributed training</a> and <a href="#sharded-state-ownership">FSDP/ZeRO ownership</a>; for generated training data, see <a href="#rollout-pipeline">actor/learner scheduling</a>.</p>
${check("A TRL run uses PEFT and DeepSpeed. Who owns the meaning of an assistant token?", "The experiment's dataset and tokenizer/template/masking contract still does. PEFT controls adapter parameters; the selected trainer/runtime executes the update. None of those names establishes that the correct response spans reached the loss.")}
</section>

<section class="lesson" id="framework-distributed-objective" data-lesson="Preserve one global objective">
<header><span>Compare updates across abstractions</span><h3>A convenience wrapper can introduce another division</h3></header>
<p>The <a href="#packing-loss">global token objective</a> is unchanged by a framework migration: sum the losses of all declared targets in one optimizer update, then divide by their count. What changes is where normalization occurs. An internal token mean, an accumulation helper and a data-parallel reducer can each divide. Audit the complete path once, including empty local microbatches and the final short accumulation window.</p>
<p>Let Sᵣₘ be a local <em>summed</em> loss on rank r and microstep m, N the valid-target count across the whole update, K the actual division applied by a backward helper, and R the rank divisor if the reducer averages. Then submitting <code>(RK/N)Sᵣₘ</code> gives <code>(1/R)ΣᵣΣₘ(1/K)∇[(RK/N)Sᵣₘ] = (1/N)ΣᵣΣₘ∇Sᵣₘ</code>. If one layer sums instead of averaging, its divisor is 1.</p>
<p>Here K names the helper's effective division, not an assumption that every library always divides by the number of observed microbatches. The pinned Accelerate guide explicitly compensates both its accumulation scaling and DDP's rank averaging in its variable-size example. That compensation must be rechecked for another backend, plugin, trainer loss hook or accumulation policy.</p>
${ref(accumulation, "Accelerate 1.11.0 · variable-size accumulation: sum loss, global count and wrapper divisions")}
<figure class="textbook-lab framework-workbench" id="framework-reduction-lab"><figcaption><span>Interactive · original derivative ledger</span><strong>Preserve the update while changing who divides</strong><p>Two ranks and two microsteps have target counts [1,2] and [0,3]. Their scalar derivative sums are [1,5] and [0,15]. Track the contribution submitted at each interface.</p></figcaption><div class="method-toolbar"><label>Data-parallel reducer<select data-framework-reducer><option value="mean">Average rank gradients</option><option value="sum">Sum rank gradients</option></select></label><label>Automatic backward division<select data-framework-divisor><option value="1">None · divisor 1</option><option value="2" selected>Divide by 2</option><option value="4">Divide by 4</option></select></label></div><div class="framework-readout" data-framework-reduction-result aria-live="polite"></div><div class="architecture-scroll" data-framework-reduction-chart tabindex="0" role="region" aria-label="Local sums through automatic backward and rank divisions; scroll horizontally"></div><p class="figure-boundary">Algebraic execution model, not an Accelerate/DDP launch. Scalar derivative contributions are assigned teaching values. The Python reference independently checks partitioned gradients against finite differences of a scalar objective and compares repeated updates.</p></figure>
<p>At R=2, K=2 and N=6, the submitted multiplier is 2/3. After the two automatic divisions, the final derivative is <code>21/6=3.5</code>. Forgetting either factor 2 gives 1.75. A smaller learning rate could hide that fixed mistake in one batch; it cannot generally repair changing target counts or a changing final accumulation window.</p>
<h4>Use a migration comparison that can locate the first disagreement</h4>
<p>Freeze a tiny model revision, token IDs, label mask, RNG policy and optimizer configuration. Compare the unwrapped and wrapped paths in this order: valid counts and loss sums; logits; named parameter gradients; gradient clipping norm and clipping result; updated weights and optimizer state. Repeat several steps, then save and resume. Matching only a scalar average loss can conceal a wrong mask, a transposed tensor conversion or a duplicated update.</p>
<p>Expected equivalence means the same mathematical objective within a stated numerical tolerance. Different reduction order, mixed precision and kernels can prevent bitwise equality. Dropout, data shuffling, duplicated distributed-sampler examples and different update boundaries can change the actual experiment. Resolve those differences before attributing a training curve change to a faster runtime.</p>
<details class="deep-dive"><summary>Where a custom loss attaches to a model API</summary><p>When an API returns an already averaged loss, multiplying it by a count is valid only if that count is precisely its denominator. For the explicit causal cross entropy in the CPU framework check, use <code>reduction="sum"</code> and count the nonignored shifted labels. A real trainer may inject a global item count or apply its own loss scaling; use its documented hook and verify the resulting update instead of adding compensation blindly.</p><p>A globally empty update has no token mean. A locally empty microbatch may still need to participate in the rank's execution/synchronization protocol. Its gradient contribution is zero, but removing the entire call path without a supported uneven-input protocol can violate collective ordering.</p></details>
${check("Can the nominal product batch × context × accumulation be used as N for assistant-only training?", "Only when it equals the actual number of scored next-token targets. Prompt positions, padding, truncation and ignored boundaries reduce that count. Aggregate the actual shifted target mask over every rank and microstep in the update.")}
</section>

<section class="lesson" id="framework-adapter-artifacts" data-lesson="Adapters, exports and resume state">
<header><span>Make artifacts mean the same computation</span><h3>A small adapter file needs a specific base and a defined execution path</h3></header>
<p>The <a href="#adapters-rollouts">LoRA introduction</a> explains the low-rank branch. A framework adds a serialization contract. In the usual <code>torch.nn.Linear</code> orientation, W is [out,in], A is [rank,in], B is [out,rank], and a column vector obeys <code>y=Wx+(α/r)B(Ax)</code>. This is the transpose convention of the earlier row-vector derivation; tensor names alone do not establish their orientation.</p>
<p>In real arithmetic, for an ordinary linear LoRA branch with dropout inactive, <code>Wmerged=W+(α/r)BA</code> produces the same output on the same input. PEFT supports additional conventions and variants, including different scaling and orientation settings. Read the saved adapter configuration rather than assuming every adapter uses α/r, every target is an ordinary linear layer, or every method supports merging.</p>
${ref(lora, "PEFT 0.17.0 · lora_alpha, rank, fan_in_fan_out, scaling variants and target modules")}
<h4>Work one merge all the way to the output</h4>
<p>Let <code>W=[[1,2],[−1,0.5]]</code>, <code>A=[[1,−1]]</code>, <code>B=[[0.5],[1]]</code>, α=r=1 and x=[2,1]. The base output is [4,−1.5], the adapter adds [0.5,1], and the result is [4.5,−0.5]. Merging gives <code>[[1.5,1.5],[0,−0.5]]</code>, with the same result. Changing just W₀₀ from 1 to 1.25 changes the first output to 5.0 although every tensor shape still matches.</p>
<figure class="textbook-lab framework-workbench" id="framework-adapter-lab"><figcaption><span>Interactive · original adapter arithmetic</span><strong>Separate algebraic merging from base identity and rounding</strong><p>Follow the two branches, then compare the merged path. A changed base is shown as a deliberately incompatible attachment; a strict loader would reject it.</p></figcaption><div class="method-toolbar"><label>Adapter α<input type="range" min="0" max="2" step="0.25" value="1" data-framework-alpha/><output data-framework-alpha-value>α=1, rank=1, scale=1</output></label><label>Base weights<select data-framework-base><option value="same">Declared base revision</option><option value="changed">Incompatible W₀₀ += 0.25</option></select></label><label>Additional merged conversion<select data-framework-round><option value="no">None</option><option value="yes">Round weights to integer grid</option></select></label></div><div class="framework-readout" data-framework-adapter-result aria-live="polite"></div><div class="architecture-scroll" data-framework-adapter-chart tabindex="0" role="region" aria-label="Adapter branches and merged computation; scroll horizontally"></div><div class="method-table" data-framework-adapter-table tabindex="0" role="region" aria-label="Base, update and merged matrices; scroll horizontally if needed"></div><p class="figure-boundary">Float64 linear algebra, fixed input, rank one, no dropout. Integer-grid rounding is a declared counterexample, not a PEFT quantization backend. No device latency or model-quality gain is inferred.</p></figure>
<p>Rounding the merged matrix to an integer grid with ties to even yields [[2,2],[0,0]], giving [6,0]. Merging followed by a new quantization is a different numerical path. A quantized base plus an unquantized adapter can also differ from first merging into an unquantized base and then quantizing. Validate the deployed path with the actual base representation, scaling, accumulator and output conversion.</p>
<h4>Distinguish three artifacts before handing one to another tool</h4>
<div class="method-table"><table><caption>Artifacts answer different loading questions</caption><thead><tr><th scope="col">Artifact</th><th scope="col">Enough information for</th><th scope="col">Additional dependency</th></tr></thead><tbody><tr><th scope="row">Adapter export</th><td>Restoring the saved adapter parameters/configuration</td><td>Exact compatible base, target modules and tokenizer/template; any separately trained saved modules</td></tr><tr><th scope="row">Full or merged model export</th><td>Loading the declared forward model in a compatible implementation</td><td>Configuration, vocabulary/template and execution format; conversion parity</td></tr><tr><th scope="row">Training resume checkpoint</th><td>Continuing the optimization process from a declared boundary</td><td>Optimizer, scheduler, random/data state and distributed layout in addition to trainable/model state</td></tr></tbody></table></div>
<p>PEFT's saved adapter format contains adapter weights and configuration; its base-model identifier or optional revision is not the base weight payload. A mutable model name is not an immutable identity. In the original CPU reference, an application-level manifest checks a base-content digest plus tokenizer, template and target-module identity before merging. That is a deliberately small teaching schema, not PEFT's own file format or a claim that its loader enforces those checks.</p>
${ref(peft, "PEFT 0.17.0 · saved adapter files, base/revision fields and merge limitations")}
<p>Save the tokenizer/template explicitly with your deployable model bundle. Keep resume state in the runtime's supported checkpoint path; a <code>save_pretrained</code> weight export does not establish that optimizer moments, consumed data or RNG state can be recovered. For distributed state conversion, continue with <a href="#sharded-checkpoint-reshard">logical tensor identity and resharding</a>.</p>
<div class="lesson-code"><h4>Python · dependency-free boundary reference</h4><pre><code>python3 examples/frameworks/training_reference.py
python3 -m unittest discover -s examples/frameworks -p 'training*_test.py' -v</code></pre></div>
<details class="deep-dive"><summary>Read the full arithmetic and adapter-manifest reference</summary><pre><code>${escapeCode(trainingReference)}</code></pre></details>
${check("An adapter loads without a shape error and its merged outputs match the separate path. Is it attached to the intended model?", "Not necessarily. Both paths can agree on the same wrong base. Establish base, vocabulary, template and target identity first; then verify numerical conversion. Resume equivalence also needs the optimization and data state, not just forward outputs.")}
</section>`;
