import { sourceLink as ref, workedCheck, escapeCode } from "./lesson-template";

import replayCode from "../examples/frameworks/cuda_replay.py?raw";

export const frameworkReplayLesson = `
<section class="lesson" id="framework-cuda-replay" data-lesson="CUDA graph replay">
<header><span>Connect kernels to repeated execution</span><h3>Replay device work while preserving its storage contract</h3></header>
<p class="figure-boundary">Source check: September 16, 2026; PyTorch APIs pinned to 2.14. The listing remains an unexecuted CUDA exercise on this CPU-only test environment.</p>
<p>A <a href="#framework-tracing-boundaries">framework compiler graph</a> represents operations to transform or compile. A <strong>CUDA Graph</strong> records device operations and their dependencies for repeated submission. Compilation may change the kernels; replay changes how a compatible sequence is submitted. Both can be used in one execution path.</p>
<p>CUDA separates graph definition, instantiation and launch. Stream capture records operations into a graph rather than running that captured work immediately. An executable graph can then be launched repeatedly. Capture and replay have constraints; the simple example below deliberately keeps operations and tensor storage fixed.</p>
${ref("https://docs.nvidia.com/cuda/cuda-programming-guide/04-special-topics/cuda-graphs.html", "CUDA Programming Guide · graph definition, capture, instantiation and replay")}
<figure class="textbook-lab fw-map" id="framework-replay-diagram"><figcaption><span>Original storage diagram</span><strong>The pointer stays; its contents change</strong><p>Trace the fixed captured input and output buffers for y = x² + 1. A new Python name is not an update to recorded device arguments.</p></figcaption>
<ol class="fw-layers"><li><span class="fw-role">Before replay</span><strong>Copy [2, 3, 4, 5] into input buffer A</strong><p>The incoming tensor can have different storage. copy_ writes its values into the persistent captured buffer.</p></li><li><span class="fw-role">Captured work</span><strong>Read A → square → add 1 → write B</strong><p>The graph reads and writes its captured storage. Expected B is [5, 10, 17, 26].</p></li><li><span class="fw-role">Next replay</span><strong>Copy [−1, 0, 1, 2] into A → write B again</strong><p>B becomes [2, 1, 2, 5]. Clone or consume the previous result before its storage is overwritten.</p></li></ol>
<p class="figure-boundary">A storage/lifetime illustration. The framework determines the actual kernels and temporary buffers; this diagram does not promise a fused kernel, physical addresses or faster execution.</p></figure>
<details class="code-disclosure"><summary>Python / PyTorch: fixed-buffer CUDA replay with output checks</summary><pre><code>${escapeCode(replayCode)}</code></pre></details>
<p>The code warms the operation on a side stream, preserves its input/output tensors and checks two different inputs. Copies, replay and output cloning are ordered on the current stream. The explicit synchronization makes this a correctness exercise, not an optimized benchmark. CPU execution cannot establish that CUDA capture succeeds; this listing still needs its compatible GPU run.</p>
${ref("https://docs.pytorch.org/docs/2.14/generated/torch.cuda.graph.html", "PyTorch 2.14 · stream capture context")}
${ref("https://docs.pytorch.org/docs/2.14/generated/torch.cuda.CUDAGraph.html", "PyTorch 2.14 · captured graph lifecycle and replay")}
<h4>Why an inference engine uses graph buckets</h4>
<p>A changing batch can require a different execution shape. One approach keeps several captured shapes and pads current work to a compatible bucket. The inactive rows must be masked, and persistent buffers, cache indices and positions must still describe the intended requests. More buckets can consume more memory and capture time; padding adds work. Dynamic request state does not become constant just because the submission pattern is reused.</p>
${ref("https://docs.vllm.ai/en/v0.22.0/design/cuda_graphs/", "vLLM 0.22.0 · graph modes, batch descriptors and compatible attention paths")}
<p>The exact graph modes and supported attention/parallel features belong to the engine version. Start with <a href="#framework-benchmark-boundary">completed-work timing</a>, compare warm eager and replay execution, and include input copies, padding and capture amortization when the workload pays for them. A replay improvement should appear in the measured submission bottleneck.</p>
<details class="deep-dive"><summary>Fixed-buffer capture is a teaching case, not the entire CUDA Graph API</summary><p>The CUDA API also provides explicit graph construction, node updates, conditional nodes and other mechanisms. Their rules do not imply that rebinding a Python tensor changes an already captured PyTorch graph. Custom streams must preserve capture dependencies, and operations that synchronize with the host cannot simply be placed into this capture region.</p></details>
${workedCheck("A new input has the same values and shape but a different allocation. Does replay automatically read it?", "No for this fixed-buffer capture. Copy it into the captured input buffer with the required ordering, or use a supported update/recapture path. A Python assignment does not change the graph's recorded device pointer.")}
</section>`;
