import { sketchArrow, sketchBox } from "./inference-sketch";
import { chapterMarkup, sourceLink as ref, workedCheck as check, escapeCode } from "./lesson-template";

export const frontierChapter = chapterMarkup(
  "frontier", "The frontier is a set of changing constraints", "Follow the current research from attention state and sparse experts to low-precision training, asynchronous kernels and disaggregated serving. Distinguish a mathematical change, a reported result and a deployment you have measured. Evidence checked September 16, 2026.", `
<section class="lesson" id="frontier-map" data-lesson="A map of frontier mechanisms"><header><span>Reading research</span><h3>Ask which cost moves, and which contract changes</h3></header>
<p>Read this chapter after the ordinary <a href="#attention">attention operation</a>, <a href="#quantization-codebook">integer quantization</a>, <a href="#sampling-contract">token sampling</a> and <a href="#load-test">serving measurements</a>. Its purpose is to explain mechanisms behind research claims. We first identify what is stored and computed, derive a small example, and only then attach a dated model or implementation name. You do not need to memorize those names to understand the mechanism.</p>
<p>A faster kernel can preserve the model's mathematical operation. A compressed attention state can change the architecture and require training. A serving scheduler can preserve token probabilities while changing queueing. A low-precision format changes numerical behavior and may require calibration or training. Putting these changes into one “efficiency” category hides their different validation requirements.</p>
<div class="method-table"><table><caption>Mechanisms and the evidence each needs</caption><thead><tr><th scope="col">Mechanism</th><th scope="col">Cost it targets</th><th scope="col">Required check</th></tr></thead><tbody><tr><th scope="row">FlashAttention kernels</th><td>Memory traffic, on-chip scheduling, non-matmul bottlenecks</td><td>Forward/backward numerical agreement and matched kernel shapes</td></tr><tr><th scope="row">MLA / hybrid recurrent attention</th><td>State size and access cost at long contexts</td><td>Architecture-specific quality, retrieval, cache and kernel behavior</td></tr><tr><th scope="row">Mixture of experts</th><td>Active arithmetic relative to total parameter capacity</td><td>Routing balance, communication, total residency and quality</td></tr><tr><th scope="row">FP8 / FP4 / microscaling</th><td>Storage, movement and low-precision matrix work</td><td>Rounding, scales, outliers, accumulation and training stability</td></tr><tr><th scope="row">Prefill/decode separation</th><td>Phase interference and resource mismatch</td><td>KV transfer, placement, tail latency and goodput</td></tr><tr><th scope="row">Test-time computation</th><td>Quality from additional inference effort</td><td>Verifier reliability, compute budget, latency and correlated failures</td></tr></tbody></table></div>
<p>This chapter is a research map with dated examples, not a claim that every proprietary frontier system is disclosed. Architecture reports, released configurations, implementation repositories and vendor measurements provide different evidence. A repository's moving <code>main</code> branch is not a permanent specification: record a commit when reproducing an experiment.</p>
</section>
<section class="lesson" id="frontier-mla" data-lesson="Latent attention"><header><span>Compress the state</span><h3>Store a latent representation instead of every expanded key and value</h3></header>
<p>Conventional attention caches key and value vectors for each past token. Multi-head latent attention (MLA) instead learns a lower-dimensional latent vector from which head-specific keys and values can be derived. DeepSeek-V3 describes joint KV compression and a separate positional-key path. This reduces cached state; it does not make the number of past tokens disappear.</p>${ref("https://arxiv.org/html/2412.19437v2#S2.SS1.SSS1", "DeepSeek-V3 §2.1.1: MLA and decoupled positional attention")}
<p>A <strong>latent vector</strong> is a learned intermediate representation. “Lower-dimensional” means it has fewer coordinates: for example, storing two numbers and applying a fixed 3×2 matrix can reconstruct a three-coordinate vector. That reconstruction can express only the vectors allowed by those two coordinates. MLA trains around such a representation; it does not losslessly compress arbitrary previously trained keys and values into fewer numbers.</p>
<h4>Derive the content-only absorption trick</h4><p>Use column vectors: hidden state <code>hₜ∈Rᵈ</code>, compressed state <code>cₜ=W_D hₜ∈Rʳ</code>, key <code>kₜ=W_K cₜ∈Rᵈᵏ</code> and value <code>vₜ=W_V cₜ∈Rᵈᵛ</code>. The score is <code>qᵀkₜ=qᵀW_Kcₜ=(W_Kᵀq)ᵀcₜ</code>. Transform the current query once, then compare it directly with cached latents. The weighted value sum is <code>ΣₜpₜW_Vcₜ=W_V(Σₜpₜcₜ)</code>. Linearity lets expansion move after the weighted sum. Each head has its own projections and attention weights.</p>
<figure class="architecture-figure"><figcaption><span>Hand-drawn derivation · content-only attention</span><strong>Move a matrix through a dot product, then through a sum</strong></figcaption><div class="architecture-scroll"><svg viewBox="0 0 840 285" role="img" aria-labelledby="mla-figure-title mla-figure-desc"><title id="mla-figure-title">Latent attention keeps the cached sequence compressed</title><desc id="mla-figure-desc">A hidden token is compressed into c and appended to a latent cache. The query is transformed by the transpose of the key projection. Scores are computed against the cache; softmax weights form a weighted latent sum, then the value projection expands the final output. The positional path is excluded from this teaching diagram.</desc><g fill="none" stroke="currentColor" stroke-width="1.4">${sketchBox(15, 25, 180, 65)}${sketchBox(260, 25, 230, 65)}${sketchBox(565, 25, 250, 65)}${sketchBox(15, 160, 180, 65)}${sketchBox(260, 160, 230, 65)}${sketchBox(565, 160, 250, 65)}${sketchArrow(195, 58, 260, 58)}${sketchArrow(490, 58, 565, 58)}${sketchArrow(690, 90, 690, 160)}${sketchArrow(195, 192, 260, 192)}${sketchArrow(375, 90, 375, 160)}${sketchArrow(490, 170, 600, 90)}</g><g font-size="16"><text x="30" y="55">New token hₜ</text><text x="30" y="77" font-size="13">cₜ = W_D hₜ</text><text x="275" y="55">Cache C = [c₁ … cₜ]</text><text x="275" y="77" font-size="13">r values per past token</text><text x="580" y="55">Weighted latent u = Cp</text><text x="580" y="77" font-size="13">No expansion of every vₜ</text><text x="30" y="190">Current query q</text><text x="30" y="212" font-size="13">q′ = W_Kᵀq</text><text x="275" y="190" font-size="13">p = softmax(a Cᵀq′ + mask)</text><text x="275" y="212" font-size="13">a is the scalar score scale</text><text x="580" y="190">Output = W_V u</text><text x="580" y="212" font-size="13">Expand after the sum</text><text x="15" y="260" font-size="13">The content identity is exact in real arithmetic; rounding and positional terms need separate treatment.</text></g></svg></div></figure>
<p>For a numerical check, let cached latents be c₁=(1,0), c₂=(0,1), let W_K have rows (1,0), (0,1), (1,1), and let q=(ln 3,0,0). Both the expanded and absorbed score paths give (ln 3,0). With score scale 1, softmax gives p=(3/4,1/4). If W_V=(2,6), expanding values first gives (3/4)×2+(1/4)×6=3. Combining latents first gives u=(3/4,1/4), then W_Vu=3. The memory optimization follows from distributivity, before any claim about GPU speed.</p>
<p>Rotary position transforms generally obstruct this simple absorption when applied inside the key expansion: the transform depends on token position, so one fixed projected query is insufficient for that entire path. MLA separates a positional component instead. Never implement the content-only diagram as though it were the complete DeepSeek operator. Query scaling, positional scores, masks, head layout and output projection belong to the full contract.</p>
<div class="lesson-code"><div><h4>Numerical thought experiment: verify the identity before optimizing it</h4></div><pre><code>${escapeCode(`# NumPy-style reference; one content-only head, no positional path.
# C: [tokens, rank], Wk: [key_dim, rank], Wv: [value_dim, rank]
# q: [key_dim]. Use the SAME mask and scalar score scale in both paths.
expanded_scores = (C @ Wk.T) @ q
latent_scores = C @ (Wk.T @ q)
p = softmax(latent_scores * score_scale + additive_mask)
expanded_output = p @ (C @ Wv.T)
latent_output = (p @ C) @ Wv.T
# Compare both score vectors and outputs with dtype-appropriate tolerance.
# This establishes an algebraic reference, not a production MLA kernel.`)}</code></pre></div>
<p>A deliberately matched teaching comparison uses 64 key/value heads, head dimension 128, 32 layers, 32,768 tokens and two-byte cache scalars. Expanded K+V takes 32 GiB. A latent cache with rank 512 plus 64 positional scalars per token uses 1.125 GiB. The 28.44× ratio follows from the declared representations. It does not predict an equally large speedup or a model-quality equivalence; against an 8-head GQA baseline the original cache is only 4 GiB.</p>
${check("Exercise: after compression, is MLA decode independent of context length?", "No. This latent-attention representation still retains one latent entry per past token and reads or otherwise processes the relevant history. Its state grows with sequence length, with a smaller coefficient. Fixed recurrent state and sparse selection are different mechanisms.")}
</section>
<section class="lesson" id="frontier-moe" data-lesson="Mixture of experts"><header><span>Conditional computation</span><h3>Active weights reduce arithmetic; all experts still need a home</h3></header>
<p>A conventional feed-forward layer applies the same learned function to every token vector. A <strong>mixture of experts (MoE)</strong> supplies several such functions plus a learned <strong>router</strong> that chooses which to use for this token. An expert is a parameterized function, not a person or a guaranteed named specialty. The output usually combines selected expert results with numerical weights called gates.</p>
<p>A mixture-of-experts layer sends a token to a small subset of feed-forward networks. Let E be the number of experts, k the selected experts per token, N the token rows in a batch and d the activation width. The expert computation scales with approximately Nk evaluations, while the complete parameter storage includes all E experts. The router, shared layers, gating and communication remain.</p>
<p>DeepSeek-V3 reports 671B total parameters and 37B active per token, using MLA, routed/shared experts and an auxiliary-loss-free balancing strategy with an additional sequence-wise balancing term. The title of that strategy does not mean the entire training objective contains no auxiliary losses. Read the actual objective and routing rule.</p>${ref("https://arxiv.org/html/2412.19437v2#S2.SS1.SSS2", "DeepSeek-V3: expert selection, balancing biases and complementary loss")}
<ol class="method-flow"><li><strong>Score and select</strong><span>The router selects expert IDs and weights. Capacity limits or load-balancing mechanisms can affect routing.</span></li><li><strong>Pack by owner</strong><span>Reorder token rows into buffers for the devices that own the chosen experts; retain a reverse map.</span></li><li><strong>Dispatch</strong><span>Send activations to expert owners. Many-to-many traffic can have small uneven messages.</span></li><li><strong>Run grouped expert matrices</strong><span>Experts with few assigned tokens create small GEMMs; one popular expert can determine completion time.</span></li><li><strong>Return and combine</strong><span>Restore original token order and combine outputs with their routing weights.</span></li></ol>
<h4>Count a dispatch payload</h4><p>For N=4,096 tokens, k=2 experts, d=4,096 and BF16 activation scalars, a no-deduplication dispatch representation contains <code>Nkd×2 = 67,108,864 bytes = 64 MiB</code>. Returning same-width expert outputs adds another 64 MiB. This is logical payload before metadata, backward communication or replication. Some routes stay local; some implementations avoid repeated sends to experts on one device. Actual network bytes require the ownership map.</p>
<p>At a declared useful 100 GB/s across the bottleneck boundary, 128 MiB of non-overlapped dispatch-plus-return payload alone costs about 1.34 ms. A large aggregate port sum does not guarantee that throughput for the busiest expert owner. Larger token batches can improve grouped-GEMM utilization while increasing queueing delay.</p>
${check("Exercise: every expert receives 128 tokens except one receiving 1,024. Does average load prove balance?", "No. A synchronized layer waits for the slowest required outputs. Measure the maximum assigned tokens, expert service times, payload destinations and the exposed communication tail. Balanced routing can also affect model quality, so changing the router is more than a scheduler adjustment.")}
</section>
<section class="lesson" id="frontier-hybrid" data-lesson="Linear and hybrid attention"><header><span>Different memory semantics</span><h3>A summary state cannot retain an unlimited addressable history</h3></header>
<p>Begin with a running sum: after observing 2, then 5, storing 7 is enough to report their sum, but not to recover each observation. A <strong>recurrent state</strong> similarly updates a fixed collection of numbers as tokens arrive. It can summarize the past without retaining a separate record for every token. To obtain content-dependent reads, replace the scalar sum with a matrix of key/value associations.</p>
<p>A simple linear-attention recurrence stores a matrix <code>Sₜ=Sₜ₋₁+vₜφ(kₜ)ᵀ</code> and optionally a normalizer <code>zₜ=zₜ₋₁+φ(kₜ)</code>; a query reads <code>Sₜφ(qₜ)</code>, with a suitable denominator in normalized formulations. Fixed-size state avoids an ever-growing token cache in that layer, but it compresses many associations into a finite representation. Decay, gating and delta updates control interference; they do not give exact arbitrary retrieval of every historical token.</p>
<h4>Derive one fixed-state read</h4><p>Let φ map a key or query to m nonnegative features, and let each value have dᵥ coordinates. Then S has shape [dᵥ,m] and z has m coordinates. Starting from zero, each outer product vₜφ(kₜ)ᵀ adds one association. The normalized read is <code>oₜ = Sₜφ(qₜ) / (zₜᵀφ(qₜ))</code> when the denominator is positive. Expanding the numerator gives <code>Σᵢ≤ₜ vᵢ[φ(kᵢ)ᵀφ(qₜ)]</code>: the brackets supply a similarity weight. This replaces the ordinary exponential dot-product similarity; it is not automatically the same softmax attention.</p>
<p>Take scalar values 2 and 6 and feature keys (1,0) and (0,1). The state becomes S=(2,6), z=(1,1). Query features (1,0) read 2; features (1,1) read 8/2=4. If both keys instead use (1,0), the state becomes S=(8,0), z=(2,0): a query at that address reads 4 and cannot distinguish the two original values. A finite feature space can have useful associations while also suffering interference.</p>
${ref("https://arxiv.org/abs/2006.16236v3", "Katharopoulos et al. · linear attention from associative products and recurrent state")}
<h4>Correct a stored association instead of only adding another</h4><p>For a separate, unnormalized delta-rule example, use a key k in the state’s address space. In our column-vector convention, let S̄ be the previous state after decay; this example does not use the preceding normalizer z. A simple delta update is <code>Snew = S̄ + β(v − S̄k)kᵀ</code>. The vector S̄k is the old read at key k; v−S̄k is its prediction error; β controls the write strength. For a unit-length key and β=1, multiplying the update by k gives Snew k=v. With another gate or a non-unit key, it need not overwrite exactly. Writes can also change reads at nonorthogonal keys. KDA adds learned channel-wise decay and other architecture details to this idea.</p>
<p>Kimi Linear develops Kimi Delta Attention (KDA), which uses channel-wise forgetting and a delta-style correction when writing a key/value association. It combines three KDA layers with one global MLA layer. The source's 6.3× TPOT comparison at one-million-token context uses the increased batch capacity; its batch-one comparison reports 2.3× there. Those are author results under specified setups, not a universal speedup from the recurrence alone.</p>${ref("https://arxiv.org/html/2510.26692v1#S5.SS6", "Kimi Linear §5.6 and Figure 1: batch-sensitive efficiency results")}
<figure class="architecture-figure"><figcaption><span>Hand-drawn schematic · a repeating teaching block</span><strong>Three compressed memories, then an addressable history</strong></figcaption><div class="architecture-scroll"><svg viewBox="0 0 840 220" role="img" aria-labelledby="hybrid-figure-title hybrid-figure-desc"><title id="hybrid-figure-title">Hybrid recurrent and attention layers have different state costs</title><desc id="hybrid-figure-desc">Three recurrent layers each maintain a fixed matrix state. A global attention layer keeps a history that grows with context. Every layer processes the same current token in sequence. Fixed state in some layers does not make the entire hybrid constant-memory.</desc><g fill="none" stroke="currentColor" stroke-width="1.4">${sketchBox(15, 45, 175, 70)}${sketchBox(225, 45, 175, 70)}${sketchBox(435, 45, 175, 70)}${sketchBox(645, 45, 175, 70)}${sketchArrow(190, 80, 225, 80)}${sketchArrow(400, 80, 435, 80)}${sketchArrow(610, 80, 645, 80)}<path d="M100 115Q98 132 100 150M310 115Q308 132 310 150M520 115Q518 132 520 150M730 115Q728 132 730 150"/>${sketchBox(50, 150, 100, 36)}${sketchBox(260, 150, 100, 36)}${sketchBox(470, 150, 100, 36)}${sketchBox(660, 150, 145, 36)}</g><g font-size="17"><text x="42" y="85">Recurrent 1</text><text x="252" y="85">Recurrent 2</text><text x="462" y="85">Recurrent 3</text><text x="668" y="85">Global MLA</text><text x="66" y="173" font-size="13">fixed state</text><text x="276" y="173" font-size="13">fixed state</text><text x="486" y="173" font-size="13">fixed state</text><text x="674" y="173" font-size="13">history grows ∝ S</text><text x="15" y="24" font-size="13">Current token flows through each layer; the boxes underneath show persistent state.</text></g></svg></div></figure>
<h4>State accounting for a hybrid</h4><p>Suppose a teaching model has 24 recurrent layers, each with 16 heads and 128×128 FP32 state matrices. Their main state is <code>24×16×128²×4 = 24 MiB</code> per sequence. Eight conventional attention layers with 8 KV heads, dimension 128, 32,768-token context and BF16 KV add 1 GiB. Total main state is 1,048 MiB before recurrent convolution buffers and other metadata. Fixed state removes growth only from the recurrent layers.</p>
<p>Kimi K3's currently published model summary gives 93 layers: 69 KDA and 24 Gated MLA, with 2.8T total and 104B activated parameters. That is a different checkpoint from Kimi Linear and not an exact repeated 3:1 layer count. GLM-5.3-Flash's released configuration reports 45 layers, 34 linear-attention entries and 11 deepseek_sparse_attention entries, with sparse-index selection up to 2,048. Model-family names do not substitute for reading a checkpoint configuration.</p>${ref("https://github.com/MoonshotAI/Kimi-K3", "MoonshotAI: Kimi K3 released model summary")}${ref("https://huggingface.co/zai-org/GLM-5.3-Flash/raw/main/config.json", "Z.ai: GLM-5.3-Flash configuration; audit the actual layer schedule")}
${check("Exercise: replacing 75% of attention layers with recurrent layers cuts all inference memory by 75%. True?", "No. It may greatly reduce the context-dependent cache term under the stated architecture. Model weights, remaining attention history, recurrent state, runtime buffers and allocator overhead still exist. The full memory reduction depends on their proportions and on the exact checkpoint.")}
</section>
<section class="lesson" id="frontier-flash" data-lesson="FlashAttention-3 and FlashAttention-4"><header><span>Algorithm and kernel design together</span><h3>Faster tensor units expose the work between matrix multiplies</h3></header>
<p>A <strong>kernel</strong> is the device program implementing an operation. The attention equation tells us which result to compute; the kernel decides which small matrix blocks to load, where to keep intermediate values and when to synchronize. A <strong>tile</strong> is one such block. Revisit <a href="#flashattention">the online-softmax derivation</a> before studying newer hardware pipelines: the running maximum, denominator and numerator explain what must survive each tile.</p>
<p>FlashAttention avoids writing the full score/probability matrices to HBM by tiling attention and maintaining online softmax statistics. This preserves the dense attention operation in real arithmetic; floating-point order and approximation choices require numerical validation. FlashAttention-3 targets Hopper with asynchronous tensor operations, warp specialization and low-precision techniques. One group can move data while another computes, provided barriers establish the right buffer lifetimes.</p>${ref("https://arxiv.org/abs/2407.08608", "FlashAttention-3: asynchronous execution and low precision on Hopper")}
<p>FlashAttention-4's March 2026 paper targets Blackwell's uneven resource growth: tensor throughput increases faster than shared-memory traffic capacity and exponential-function throughput. Its techniques include redesigned overlapping pipelines, software-assisted exponentials, conditional rescaling, tensor-memory intermediates and two-CTA matrix operations. The author's maintained repository now documents the CuTe-DSL implementation; a Python surface here generates GPU kernels, rather than interpreting a Python loop for every element.</p>${ref("https://arxiv.org/abs/2603.05451", "FlashAttention-4: March 2026 paper and measured comparison conditions")}${ref("https://github.com/Dao-AILab/flash-attention/blob/main/README.md", "Dao-AILab: current FlashAttention-4 implementation and installation contract")}
<h4>Make a three-resource roofline</h4><p>For a declared tile with 4 million matrix FLOPs, 16,384 exponentials and 256 KiB of shared-memory traffic, let sustainable resource rates be 8 million FLOPs/µs, 16,384 exponentials/µs and 128 KiB/µs. The independent bounds are 0.5 µs, 1 µs and 2 µs. Even perfect overlap cannot beat the largest: 2 µs. Doubling matrix throughput changes 0.5 to 0.25 µs while leaving that bound unchanged. Cutting shared traffic in half brings the bound to 1 µs. Synchronization and dependencies can make actual time exceed both estimates.</p>
<p>Do not divide total FLOPs by tensor peak and call the remainder “bad utilization.” Count exp, conversion, loads, stores, synchronization and matrix operations at their own execution boundaries. A new pipeline must also pass forward and backward tests on causal masks, varying sequence lengths, head dimensions and dtypes. An isolated favorable shape does not imply a full training-step speedup.</p>
<p>A September 3, 2026 preprint on hardware-aware FP4 FlashAttention-4 reports distinct noncausal inference and training paths. Its abstract also states that all tested distributed MXFP4 probability/value training trajectories diverged. This is an author-reported experimental boundary, not proof that all FP4 attention training is impossible. It demonstrates why an inference throughput result must not silently become a training-stability claim.</p>${ref("https://arxiv.org/abs/2609.04105", "Hardware-Aware FP4 FlashAttention-4: September 2026 preprint, including negative training results")}
${check("Exercise: a new attention kernel is twice as fast, but attention is 30% of the step. What is the best end-to-end speedup if everything else stays fixed?", "Normalize old step time to 1. The new time is 0.70 + 0.30/2 = 0.85, giving 1/0.85 ≈ 1.176×. Overlap, communication and changed shapes may alter that model; a 2× kernel improvement is not a 2× training improvement.")}
</section>
<section class="lesson" id="frontier-precision" data-lesson="Microscaling, FP4 and numerical contracts"><header><span>Precision is a representation</span><h3>A four-bit payload is only part of the number</h3></header>
<p>The earlier <a href="#quantization-codebook">uniform integer codebook</a> used equally spaced values. A floating-point codebook uses sign, exponent and fraction bits to provide spacing that varies with magnitude. For example, E2M1 names two exponent bits and one fraction bit, in addition to a sign bit. A block scale then shifts the useful range of that small codebook. <strong>Microscaling</strong> means using many local scales across a tensor, instead of one scale for the whole tensor.</p>
<p>A quantized tensor represents values using a small stored code and one or more scales. For a block, write <code>x̂ᵢ=s·qᵢ</code>. A wide scale covers outliers but can erase smaller values; a narrow scale preserves small values but may clip the outlier. Smaller blocks let the scales adapt locally, at the cost of metadata, quantization work and hardware layout constraints. Numerical format, scaling recipe and training recipe are separate decisions.</p>
<div class="method-table"><table><caption>Selected representation contracts in NVIDIA Transformer Engine documentation</caption><thead><tr><th scope="col">Format</th><th scope="col">Element</th><th scope="col">Scale structure</th><th scope="col">Storage teaching estimate</th></tr></thead><tbody><tr><th scope="row">BF16</th><td>16 bits</td><td>No external scale in ordinary storage</td><td>2 bytes/value</td></tr><tr><th scope="row">Tensor-scaled FP8</th><td>8 bits, e.g. E4M3 / E5M2</td><td>Recipe may maintain tensor scale and amax history</td><td>1 byte/value plus recipe state</td></tr><tr><th scope="row">MXFP8</th><td>E4M3 payload</td><td>E8M0 scale per 32 values</td><td>1 + 1/32 = 1.03125 bytes/value</td></tr><tr><th scope="row">NVFP4 basic 1D layout</th><td>E2M1 payload</td><td>E4M3 scale per 16 values plus global FP32 scale</td><td>0.5 + 1/16 = 0.5625 bytes/value, plus global scale</td></tr></tbody></table></div>
${ref("https://docs.nvidia.com/deeplearning/transformer-engine/examples/fp8_primer.html", "Transformer Engine: FP8, MXFP8 and NVFP4 representations")}
<p>The NVFP4 estimate is for the basic one-dimensional representation. Training recipes can use two-dimensional weight scaling, transposed quantized copies, stochastic rounding and transforms to reduce quantization error. Do not use 0.5625 bytes/value as a complete optimizer or training-memory estimate. FP4 activations do not imply FP4 master weights, gradients, optimizer moments, reductions and softmax.</p>${ref("https://docs.nvidia.com/deeplearning/transformer-engine/api/common.html", "Transformer Engine recipes: directional quantization and NVFP4 training details")}
<h4>Why transposing quantized bytes can be wrong</h4><p>If scales group 32 consecutive values along a matrix's contraction dimension, transposing the matrix changes which values share a scale. A byte transpose does not recalculate those groups. For the transpose needed in backward, generate the required quantized orientation from the higher-precision tensor under the recipe; an extra dequantize/requantize can introduce another rounding error. Kernels must also read scales in the expected tiled layout.</p>
<p>A 1,024×1,024 matrix uses 2 MiB in BF16. Its basic MXFP8 payload plus one-byte block scales uses <code>1,048,576+32,768 = 1,081,344 bytes = 1.03125 MiB</code>. Basic NVFP4 uses <code>524,288+65,536+4 = 589,828 bytes</code>, about 0.562504 MiB. These ratios are less than 2× and 4× because scales take space. Alignment and duplicate layouts can add more.</p>
${check("Exercise: a loss curve matches BF16 for 20 steps. Is low-precision training validated?", "No. Check a sufficiently long controlled run, validation quality, rare outlier batches, gradients and optimizer state, and reproducibility across seeds. Record the exact recipe and hardware. Short runs establish local behavior; they do not establish convergence or downstream equivalence.")}
</section>
<section class="lesson" id="frontier-disaggregation" data-lesson="Separating prefill and decode"><header><span>Serving architecture</span><h3>Separate the phases only when the saved interference pays for movement</h3></header>
<p>Prefill processes a prompt with many token rows; decode repeatedly processes small increments while retaining request state. DistServe separates these phases so they can use different resource allocations and parallelism, optimizing requests served within both first-token and per-token latency requirements. State must move or become accessible at the new owner. Separation reduces one kind of interference while adding a transport and coordination boundary.</p>${ref("https://arxiv.org/abs/2401.09670", "DistServe: prefill/decode placement and goodput under latency constraints")}
<figure class="architecture-figure"><figcaption><span>Hand-drawn schematic · request ownership</span><strong>The handoff includes state and its meaning</strong></figcaption><div class="architecture-scroll"><svg viewBox="0 0 840 250" role="img" aria-labelledby="disagg-figure-title disagg-figure-desc"><title id="disagg-figure-title">Prefill to decode ownership handoff</title><desc id="disagg-figure-desc">The router assigns a request to a prefill worker. The worker produces KV pages and metadata. Transport moves the state to a compatible decode worker. Only after transfer completion and ownership confirmation does decode consume the state. The decode worker streams output tokens and eventually releases pages.</desc><g fill="none" stroke="currentColor" stroke-width="1.3">${sketchBox(15, 55, 145, 75)}${sketchBox(205, 55, 180, 75)}${sketchBox(440, 55, 165, 75)}${sketchBox(660, 55, 165, 75)}${sketchArrow(160, 92, 205, 92)}${sketchArrow(385, 92, 440, 92)}${sketchArrow(605, 92, 660, 92)}<path d="M742 130Q740 157 742 190Q403 193 85 190L85 130 M82 136L85 130L88 136"/></g><g font-size="16"><text x="30" y="85">Admission</text><text x="30" y="111" font-size="13">request + budget</text><text x="220" y="85">Prefill owner</text><text x="220" y="111" font-size="13">weights → KV pages</text><text x="455" y="85">Transfer</text><text x="455" y="111" font-size="13">bytes + metadata</text><text x="675" y="85">Decode owner</text><text x="675" y="111" font-size="13">check → generate</text><text x="172" y="181" font-size="13">Completion, cancellation and page release follow the ownership protocol</text><text x="15" y="225" font-size="13">Cache layout, token positions, model revision and precision must agree across the handoff.</text></g></svg></div></figure>
<h4>Work a transfer break-even estimate</h4><p>The <a href="#accelerator-capacity">capacity workbench</a> produces 10 GiB KV state for one 32K-context teaching request. A 400 Gb/s link equals 50 GB/s before overhead. At a declared 70% useful bandwidth, transfer takes <code>10×2³⁰ / (35×10⁹) ≈ 307 ms</code>. Suppose separation improves decode from 10 to 6 ms per token. It must save more than the unrounded transfer duration, so <code>N−1 &gt; 306.7834/4 ≈ 76.70</code> decode intervals are needed for N total output tokens when prefill supplies token one. Thus 77 decode intervals, or <strong>78 total output tokens</strong>, are the first integer case that amortizes the payload. Counting all N outputs as decode savings introduces an off-by-one error.</p>
<p>This comparison assumes unchanged prefill and no overlap; actual queueing, transport packing, parallel KV transfer, different placements and admission limits can change the result. A short answer to a large prompt can lose from the handoff even if its decode kernel is faster. A long answer under severe prefill interference can gain. Evaluate the complete latency distribution, including overloaded periods.</p>
<p>vLLM's current documentation labels disaggregated prefilling experimental and describes connector implementations under its KV-transfer layer. Connector support, cache layout compatibility and topology are runtime-version facts. Pin the implementation, validate cancellation and partial-transfer cleanup, and confirm that the consumer never reads pages before the producer's writes are visible.</p>${ref("https://docs.vllm.ai/en/latest/features/disagg_prefill/", "vLLM: disaggregated prefilling and KV connector boundary")}
${check("Exercise: two workers have identical tensor shapes but different model revisions. May they exchange cached state?", "No. KV contents depend on model weights and the token/position history, not only buffer shape. A compatible handoff must identify model revision, state representation, precision/layout, positions and ownership. Otherwise the request can return plausible-looking but incorrect output.")}
</section>
<section class="lesson" id="frontier-test-time" data-lesson="Test-time compute"><header><span>Spend computation where it improves the answer</span><h3>More generated tokens are useful only when they improve a measured outcome</h3></header>
<p>Here “test time” means using an already trained model to solve a new input. The weights stay fixed while the system spends additional inference work. A <strong>candidate</strong> is one proposed answer. A <strong>selector</strong> chooses which candidate to return; a <strong>verifier</strong> supplies evidence for that choice, such as whether generated code passes a test. This quality-oriented verifier is a different role from the target-probability verifier in exact speculative decoding.</p>
<p>Test-time compute can generate more candidates, revise a draft, search over intermediate steps or spend more effort on hard prompts. A verifier can score candidates, use a task-specific test, or judge intermediate progress. These approaches have different sequential depth, batching opportunities and failure correlations. A fast token engine increases the available work within a latency budget; it does not make the verifier correct.</p>
<p>Snell and colleagues study both searching with process-based verifiers and adapting the response distribution. Their results depend on prompt difficulty and compute allocation. The finding that extra inference can outperform a larger model in particular matched-compute settings is not a general replacement rule for pretraining.</p>${ref("https://arxiv.org/abs/2408.03314", "Snell et al.: prompt-dependent allocation of test-time computation")}
<h4>Separate candidate coverage from answer selection</h4><p>If independent candidates each succeed with probability p, the probability that at least one succeeds among n is <code>1−(1−p)ⁿ</code>. At p=0.2 and n=8, that is about 83.22%. This is a coverage probability under the stated independence assumption. To turn coverage into delivered-answer accuracy would additionally require an oracle selector that always recognizes and chooses a correct candidate when one exists. Eight correlated wrong candidates can add almost no coverage; a flawed selector can choose a wrong candidate even when a correct one exists.</p>
<p>If each candidate generates 500 tokens, eight candidates generate 4,000 tokens, plus verification work. Parallel candidates may share an immutable prompt prefix, but their generated suffixes diverge and require separate state. Sequential revision reuses history differently and can extend critical-path latency. Count candidate-generation, verifier and tool costs separately; report success within a fixed total budget and maximum latency.</p>
${check("Exercise: a system improves pass@8 but not the accuracy of the single selected answer. Is the user-facing solver better?", "Not yet on that metric. pass@8 measures whether a correct candidate exists among eight; selected-answer accuracy also measures the selector. Report both, together with total generated tokens, verifier cost, latency and the evaluation set. An oracle metric cannot stand in for the delivered answer.")}
<h4>A frontier-reading capstone</h4><ol class="method-flow"><li><strong>Freeze one claim</strong><span>Write the model revision, dataset, context distribution, dtype, hardware and software versions.</span></li><li><strong>Classify the change</strong><span>Algebra-preserving kernel, new architecture, approximate representation, scheduler or extra inference work.</span></li><li><strong>Build the budget</strong><span>Compute, storage, memory traffic, interconnect and critical-path queueing; label estimates separately from measurements.</span></li><li><strong>Try to falsify it</strong><span>Use another shape, a longer context, a less balanced batch, an outlier tensor or a harder retrieval case.</span></li><li><strong>Publish a bounded conclusion</strong><span>State where the quality and performance gain was observed, which tests failed and what remains unmeasured.</span></li></ol>
<p>For example, combine MLA state compression, expert parallelism and a prefill/decode split. Derive the correct latent-cache transfer size; place all experts; include the busiest dispatch path; then test both first-token and inter-token targets at realistic arrival rates. This connects the entire manual: the mathematical representation controls kernel shapes, hardware placement and the serving contract.</p>
</section>`);
