import {
  chapterMarkup,
  sourceLink as ref,
  workedCheck as check,
} from "./lesson-template";

export const resourceChapter = chapterMarkup(
  "gpu-resources",
  "The limits behind a resident block",
  "Count registers, shared memory, warps and bytes before interpreting utilization. A peak specification is a constraint, not the performance of your kernel.",
  `
<section class="lesson" id="occupancy-contract" data-lesson="SM residency and register allocation"><header><span>GPU execution</span><h3>A block must fit before its warps can hide latency</h3></header>
<p>A CUDA block becomes resident on an SM together with its required resources. Registers retain each resident thread's working state; shared memory supports cooperation inside the block. Hardware limits also cap threads, warps and blocks. Exhausting any one resource can prevent another block from becoming resident, even when other resources remain free.</p>
<p>Occupancy is resident warps divided by the SM's maximum supported warps. It is not instruction throughput, the fraction of useful lanes, or the fraction of wall time spent doing productive work. Many resident warps can all wait on dependencies or synchronization. Conversely, enough independent work within fewer warps can sometimes keep the relevant execution units busy.</p>
${ref("https://docs.nvidia.com/cuda/cuda-c-best-practices-guide/index.html#occupancy", "NVIDIA: occupancy, register pressure and allocation granularity")}
<figure class="textbook-lab method-lab" id="occupancy-lab"><figcaption><span>Interactive 10.1</span><strong>Find the resource that stops the next block</strong><p>Declared teaching SM: 65,536 32-bit registers, 100 KiB shared memory, 2,048 threads, 64 warps and 32 blocks. This is not a B200 specification.</p></figcaption><div class="method-toolbar"><label>Threads / block<select data-occ-threads><option>64</option><option>128</option><option selected>256</option><option>512</option><option>1024</option></select></label><label>Registers / thread<select data-occ-registers><option>16</option><option>32</option><option>48</option><option selected>64</option><option>65</option><option>96</option><option>128</option></select></label><label>Shared memory / block<select data-occ-shared><option value="0">0 KiB</option><option value="16">16 KiB</option><option value="32">32 KiB</option><option value="64">64 KiB</option><option value="128">128 KiB</option></select></label></div><div data-occ-result class="occupancy-result" aria-live="polite"></div><div data-occ-warp-grid class="occupancy-grid" role="img" aria-label="Resident versus unavailable warp slots"></div><div class="method-table" data-occ-table></div><p class="figure-boundary">Registers are rounded to 256-register units per warp; shared storage to 256-byte units. These are explicit model assumptions. Real hardware has architecture-specific partitions, allocation rules and launch limits. This calculator is not the CUDA occupancy API or a measured runtime.</p></figure>
<h4>Derive the 64-to-65-register cliff</h4><p>At 256 threads, a block has eight warps. With 64 registers per thread, each warp needs 2,048 registers, and a block needs 16,384. Four blocks fit into 65,536 registers: 32 resident warps and 50% occupancy. Requesting 65 registers yields 2,080 logical registers per warp, rounded to 2,304 under this model. The block allocation becomes 18,432; only three fit, so occupancy falls to 37.5%.</p>
<p>That arithmetic does not prove the 64-register kernel is faster. Forcing a lower register count can introduce spills, more loads/stores, or repeated computation. “Local memory” in CUDA is a per-thread address space, not a promise of on-chip register speed. Inspect compiler resource reports and kernel metrics together.</p>
<div class="lesson-code"><div><h4>Measure the compiled kernel's resources</h4></div><pre><code>nvcc -O3 -lineinfo --ptxas-options=-v \\
  examples/cuda/tiled_matmul.cu -o /tmp/atlas-tiled-matmul
# Inspect registers, shared storage and spill reports for the actual target.
# Then validate correctness before collecting a performance trace.</code></pre></div>
<p>Use the occupancy API or Nsight Compute for the real binary, GPU and launch configuration. Include dynamically allocated shared memory, not only the static array declarations. A block requiring more than the available shared storage cannot become resident in the teaching model; do not describe that as a valid kernel with merely “low occupancy.”</p>
${check("Worked check: the warp-slot diagram is half full. Is half of HBM bandwidth available to other work?", "No. Warp residency and memory bandwidth are different quantities. Those warps may saturate the memory path, or may barely use it. Measure traffic, dependency stalls and achieved throughput under the actual workload.")}
</section>
<section class="lesson" id="roofline-contract" data-lesson="Arithmetic intensity and roofline bounds"><header><span>Performance models</span><h3>Use the same byte boundary on both sides of the equation</h3></header>
<p>Let F be useful floating-point operations, Q the bytes transferred across a declared memory boundary, C sustainable compute throughput for the chosen instruction/dtype, and B sustainable bandwidth across that boundary. Arithmetic intensity is <code>I=F/Q</code>. An idealized time lower bound is <code>max(F/C,Q/B)</code>; the corresponding throughput ceiling is <code>min(C,BI)</code>. Real execution adds costs and may not achieve either resource limit.</p>
<div class="derivation"><h4>An original, deliberately round-number machine</h4><p>Use C=100 TFLOP/s and B=1 TB/s in decimal units. The ridge point is 100 FLOP/byte. A workload with F=2 TFLOP and Q=20 GB has two equal 20 ms bounds. If actual Q doubles to 40 GB while F stays fixed, the bandwidth bound becomes 40 ms. Dividing by an ideal payload size would hide that extra traffic.</p></div>
<p>Do not combine L2-cache bytes with an HBM bandwidth specification, or count scalar FP32 work against a sparsity-enabled low-precision peak. A multiply-add commonly counts as two FLOPs; document that convention. Recomputing activations raises executed work without necessarily increasing the useful mathematical work of the model. Report both when they answer different questions.</p>
${ref("https://docs.nvidia.com/nsight-compute/ProfilingGuide/index.html#roofline-charts", "Nsight Compute: roofline interpretation")}
<h4>Why batching changes dense decode</h4><p>For a dense projection with P weights and B token rows, the ideal weight-only count is approximately 2BP FLOPs and sP weight bytes, where s is bytes per stored weight. Ignoring activations and outputs, intensity is 2B/s. Batching amortizes a common weight read over more rows. It does not necessarily amortize KV reads across unrelated requests, and cache reuse or tensor-parallel communication changes the actual accounting.</p>
<p>With BF16 weights, the toy expression becomes B FLOP/byte. A batch of one and a batch of 64 are very different arithmetic shapes even on the same GPU. Neither number predicts latency without the actual kernel, memory hierarchy and traffic mix. Link this reasoning to the <a href="#tiled-matmul">tile workbench</a> and <a href="#serving-budgets">prefill/decode budgets</a>.</p>
</section>
<section class="lesson" id="async-execution" data-lesson="Streams, DMA and asynchronous execution"><header><span>Host and device</span><h3>An asynchronous launch is not completed work</h3></header>
<p>A host can enqueue device work and continue before the GPU finishes. A CPU timer around a launch may therefore measure submission overhead. CUDA events placed in the relevant stream can delimit device work, while a system timeline exposes host gaps and cross-stream dependencies. Neither substitutes for defining which operations belong to the measured interval.</p>
<p>Streams express order; independent streams can expose concurrency, but concurrency is not guaranteed. Kernels can compete for SM resources and memory bandwidth. A copy engine can overlap a transfer with compute only when the platform, memory type, dependencies and resources permit it. Pinned host memory enables appropriate asynchronous transfer paths but consumes a constrained host resource.</p>
${ref("https://docs.nvidia.com/cuda/cuda-programming-guide/02-basics/asynchronous-execution.html", "CUDA: asynchronous execution and streams")}
<h4>Follow the lifetime of an input buffer</h4><ol class="method-flow"><li><strong>CPU fills the host buffer</strong><span>Preparation must finish before a dependent host-to-device transfer begins.</span></li><li><strong>Transfer reads the host buffer</strong><span>Do not overwrite or free it while the transfer can still consume its bytes.</span></li><li><strong>GPU consumes the device buffer</strong><span>A kernel must wait for its operands, even if the host is already preparing another batch.</span></li><li><strong>Completion establishes reuse</strong><span>An event, stream dependency or other valid completion protocol makes later reuse safe.</span></li></ol>
<p>Double buffering creates two storage lifetimes, not automatic overlap. The profiler should show preparation or transfer of batch n+1 overlapping compute on batch n, without a race or hidden synchronization. CUDA Graphs can reduce repeated submission overhead for compatible execution patterns; they do not make a memory-bound kernel compute-bound.</p>
${ref("https://docs.nvidia.com/cuda/cuda-programming-guide/04-special-topics/cuda-graphs.html", "CUDA Graphs: replaying an execution graph")}
</section>`,
);

export const collectiveChapter = chapterMarkup(
  "collectives",
  "The tensor has to arrive with the right owner",
  "Collectives are data transformations with communication costs. Trace their values first, then map the logical operation onto the physical fabric.",
  `
<section class="lesson" id="collective-contracts" data-lesson="All-reduce, all-gather, reduce-scatter and all-to-all"><header><span>Distributed execution</span><h3>Name the result, not only the transport</h3></header>
<div class="method-table"><table><caption>Collective contracts across R ranks</caption><thead><tr><th scope="col">Operation</th><th scope="col">Input ownership</th><th scope="col">Output ownership</th><th scope="col">Typical connection</th></tr></thead><tbody><tr><th scope="row">All-reduce</th><td>Each rank has a same-shaped contribution</td><td>Every rank receives the elementwise reduction</td><td>Replicated gradients or row-parallel output sums</td></tr><tr><th scope="row">Reduce-scatter</th><td>Each rank has a full contribution</td><td>Each rank receives one reduced shard</td><td>Sharded gradient/optimizer ownership</td></tr><tr><th scope="row">All-gather</th><td>Each rank owns a distinct shard</td><td>Every rank receives the concatenated shards</td><td>Materializing sharded parameters or activations</td></tr><tr><th scope="row">All-to-all</th><td>Each rank has data for multiple destinations</td><td>Each rank receives its addressed pieces</td><td>Expert dispatch and return paths</td></tr></tbody></table></div>
<p>A sum is not an average. All-gather concatenates rather than adds. Rank order defines shard placement and is not necessarily device-number order. All participants must agree on the communicator and compatible operation metadata; mismatched calls can hang or corrupt an execution contract.</p>
${ref("https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/usage/collectives.html", "NCCL: collective result semantics")}
<p>In data parallelism, ranks differentiate different samples against compatible parameter versions, then combine contributions using the objective's normalization. In tensor parallelism, ranks own pieces of a layer, so intermediate activations and their gradients must be reconstructed or reduced at specific boundaries. An MoE dispatcher instead routes tokens to parameter owners, often producing unequal payload sizes.</p>
</section>
<section class="lesson" id="ring-allreduce" data-lesson="Ring all-reduce, fragment by fragment"><header><span>Communication workbench</span><h3>Reduce one shard, then distribute the reduced shards</h3></header>
<p>This synchronous four-rank teaching ring first reduces and scatters four chunks, then gathers them. Each chunk contains two FP32-sized example scalars. The diagram shows buffers <em>after</em> a step; arrows describe the sends that produced that state. The table records which original ranks contributed to every partial sum.</p>
<figure class="three-lab wide-figure" id="ring-workbench"><div class="three-head"><figcaption><span>Interactive 12.1</span><strong>One collective, six communication steps</strong><p>Select a rank or click its buffers. A blue chunk contains all four contributions; partial chunks still have missing contributors.</p></figcaption><div class="three-controls"><button data-ring-view="oblique" class="is-active" aria-pressed="true">Rank buffers</button><button data-ring-view="top" aria-pressed="false">Read the ring</button></div></div><div class="method-toolbar"><label>Inspect rank<select data-ring-rank><option value="0">Rank 0</option><option value="1">Rank 1</option><option value="2">Rank 2</option><option value="3">Rank 3</option></select></label><button data-ring-reset>Reset</button><button data-ring-back>Previous step</button><button data-ring-next>Send next chunks</button></div><div class="three-stage"><div id="ring-scene" class="scene-canvas"><p data-ring-fallback class="matmul-fallback">Loading the rank-buffer model. The numerical table also works without WebGL.</p></div><aside id="ring-inspector" class="scene-inspector" aria-live="polite"></aside></div><div class="method-table" data-ring-table></div><p class="figure-boundary">Logical, synchronous ring; not a literal NVLink cable layout, an NCCL execution trace or a timing simulation. Source contributions and sent payloads are exact for the integer example. Real collectives use architecture-dependent protocols, channels, algorithms and sometimes in-network reduction.</p></figure>
<h4>Why two phases?</h4><p>After three reduce-scatter steps, each rank owns one complete reduced chunk. The other chunks in its teaching buffer are incomplete and are not final all-reduce outputs. Three more all-gather steps distribute the complete chunks without adding them again. Every final element includes each rank exactly once; the tests assert this ownership invariant at every intermediate state.</p>
<p>The ring's chunk assignment is a convention. Here rank r finishes reduction with chunk (r+1) mod 4. Reordering ranks or choosing a different send schedule changes placement, not the sum that all-reduce promises. Ranks are logical participants; two adjacent ranks in this drawing might communicate through a switch rather than a direct cable.</p>
<h4>Count transmitted payload once</h4><p>For R ranks and an S-byte vector, this ring sends R−1 chunks in each phase, with chunk size S/R. Sent payload per rank is <code>2(R−1)S/R</code>. Our example has S=32 bytes and R=4, so each rank sends 48 bytes in six 8-byte steps. Across all ranks, sent payload is 192 bytes. Counting each receive again would measure transmit-plus-receive traffic, a different convention.</p>
<p>A simple model is <code>T ≈ 2(R−1)α + 2(R−1)S/(RB)</code>, with α per-step latency and B usable directed bandwidth. It omits reduction arithmetic, protocol overhead, contention and topology asymmetry. Small payloads emphasize the latency term; large payloads emphasize bytes. The model is not a guarantee that a ring beats a tree on a given platform.</p>
${ref("https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/usage/collectives.html", "NCCL: reduce-scatter and all-gather contracts")}
${check("Worked check: at the end of reduce-scatter, may every rank apply an optimizer to every local chunk?", "Not as though every chunk were a complete global gradient. In this schedule only the designated chunk on each rank is fully reduced. A sharded optimizer updates its owned shard, then follows the parameter-reconstruction protocol required by the next computation.")}
</section>
<section class="lesson" id="collective-topology" data-lesson="Rank placement, scale-up and scale-out"><header><span>Physical hardware</span><h3>The collective graph and the cable graph are different maps</h3></header>
<p>Place the logical participants onto devices, hosts and fabric domains. A tensor-parallel layer may communicate several times during a token step; data-parallel synchronization can have different frequency and overlap opportunities. A job configuration that minimizes per-rank memory can increase critical-path communication if tightly coupled ranks cross a slower boundary.</p>
<p>Within an NVSwitch scale-up domain, logical neighbors can traverse a switched fabric. Across domains, traffic may pass through NICs and an external network. PCIe attachment, NUMA placement, path contention, oversubscription and collective algorithm selection affect the usable bandwidth. A marketing sum of all rack ports is not the bandwidth available to one collective edge.</p>
<p>Use the <a href="#rack">rack workbench</a> to identify compute trays, scale-up switches and scale-out connections. Then annotate a real job with rank → GPU → host → NIC → switch mappings. Measure the actual message sizes and concurrency; a microbenchmark with one isolated transfer does not establish performance for overlapping training collectives.</p>
<h4>Overlap has a dependency condition</h4><p>A gradient bucket can communicate after its contents are ready, while backward computes other gradients. That does not mean every communication byte disappears from the step. The final outstanding bucket can remain exposed, and communication may slow concurrent kernels by consuming bandwidth or execution resources. Compare the measured step critical path, not only a sum of kernel and collective durations.</p>
${ref("https://docs.nvidia.com/dgx-superpod/reference-architecture-scalable-infrastructure-gb200/latest/network-fabrics.html", "NVIDIA GB200 SuperPOD: fabric domains")}
</section>`,
);
