import cudaSource from "../examples/cuda/tiled_matmul.cu?raw";
const escape = (value: string) =>
  value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;");
const source = (url: string, label: string) =>
  `<a class="lesson-source" href="${url}" target="_blank" rel="noreferrer">${label}</a>`;

export const tiledMatmulLesson = `<section class="lesson" id="tiled-matmul" data-lesson="A matrix tile, instruction by instruction">
<header><span>From tensor algebra to a kernel</span><h3>Follow one output tile through memory</h3></header>
<p>A matrix multiplication is a collection of dot products. For row-major <code>A[M,K]</code>, <code>B[K,N]</code> and <code>C[M,N]</code>, output <code>C[r,c] = Σₚ A[r,p]B[p,c]</code>. The reduction index p runs across K. M and N decide how many outputs exist; K decides how long each dot product is.</p>
<p>Start with one thread per output. Nearby outputs repeatedly need the same A rows and B columns. A block can cooperate: load a tile of A and B into shared memory, wait for those loads, accumulate a contribution, then wait before overwriting that storage. The grid below shows values from the same mathematical schedule as the CUDA companion.</p>
<figure class="three-lab wide-figure matmul-workbench" id="matmul-workbench">
<div class="three-head"><figcaption><span>Interactive 11.1</span><strong>A block owns a tile of C</strong><p>Click a C cell or use the output selector. Blue marks its operands; pale blue marks other staged values. Empty C positions belong to other blocks.</p></figcaption><div class="three-controls"><button data-matmul-view="oblique" aria-pressed="true" class="is-active">Memory layers</button><button data-matmul-view="top" aria-pressed="false">Read the values</button></div></div>
<div class="matmul-toolbar"><label>Matrix shape<select data-matmul-shape><option value="regular">4×6 @ 6×4</option><option value="edges">3×5 @ 5×3 · ragged edges</option></select></label><label>Tile width<select data-matmul-tile><option value="2">2 × 2</option><option value="4">4 × 4</option></select></label><label>Inspect output<select data-matmul-output></select></label><p>Changing the output block restarts its schedule.</p></div>
<div class="three-stage"><div class="scene-canvas" id="matmul-scene"><p class="matmul-fallback" data-matmul-fallback>Loading the 3D workbench. The numerical tables and controls below work without WebGL.</p></div><aside class="scene-inspector" id="matmul-inspector" aria-live="polite"></aside></div>
<div class="matmul-stepper"><div><span data-matmul-progress></span><strong data-matmul-phase></strong></div><div><button data-matmul-reset>Reset</button><button data-matmul-back>Previous</button><button data-matmul-next>Next stage</button></div></div>
<div class="matmul-phase-strip" aria-label="Repeated reduction-tile stages"><span data-matmul-stage="load">Load A/B</span><b>→</b><span data-matmul-stage="ready">Wait for producers</span><b>→</b><span data-matmul-stage="accumulate">Accumulate</span><b>→</b><span data-matmul-stage="release">Wait for consumers</span></div>
<div class="matmul-ledger" aria-live="polite"><div><span>Logical input loads so far</span><strong data-matmul-loads></strong></div><div><span>Useful / scheduled FLOPs</span><strong data-matmul-flops></strong></div><div><span>Valid output stores</span><strong data-matmul-stores></strong></div></div>
<details class="matmul-tables"><summary>Read the numerical tables</summary><div data-matmul-tables></div></details>
<p class="figure-boundary">Original explanatory geometry, not a physical memory layout or a clock-level simulation. This is a simple SIMT kernel, not Tensor Core MMA. Counts describe one output block and logical accesses, not cache misses or measured HBM traffic. Invalid shared operands are zero-filled; other output blocks are not computed here.</p>
</figure>
<h4>The two barriers solve different hazards</h4>
<p>The first barrier stops a consumer from reading a shared location before the thread responsible for writing it has finished. The second stops a fast thread from replacing that location with the next tile while a slower peer still needs the old value. Neither barrier means all blocks in the grid have synchronized. Blocks compute independent output tiles.</p>
<p>An edge thread must not return early merely because its output is outside M or N. It may still be responsible for loading an operand another thread needs, and the block-wide barriers require compatible participation. The companion guards global loads, substitutes zero, keeps every thread in the loop, and guards only the final store.</p>
<h4>Derive reuse before claiming bandwidth savings</h4>
<p>For a full T×T output tile and reduction length K, separate dot products request <code>2T²K</code> input scalars. Cooperative staging requests <code>2TK</code>. The ratio is T for this logical-access model. A single T-wide reduction stage performs <code>2T³</code> FLOPs and requests <code>8T²</code> FP32 input bytes: input-only arithmetic intensity is <code>T/4</code> FLOP/byte. This excludes output stores and cache behavior; it is a different accounting boundary from the whole-matrix ideal in the preceding lesson.</p>
<p>Edges weaken reuse. A block with one valid row and one valid column reuses neither operand across multiple useful outputs. Padded lanes can still execute multiply-adds that do not contribute to C. Select the ragged example and inspect C[2,2]: the arithmetic and load counters separate those costs.</p>
<details class="knowledge-check"><summary>Worked check: why is the second barrier necessary after a thread finishes its own sum?</summary><p>Its peers may not have finished reading shared memory. Without the barrier, the next loop iteration can overwrite a value they still need. Local completion is not collective completion. The hazard is between different threads and two storage lifetimes, not between two instructions in one thread.</p></details>
<div class="lesson-code"><div><h4>Read the actual CUDA companion</h4></div><p class="companion-inline">The expandable listing is imported from the repository source, so it cannot drift from the companion file. It includes a CPU-reference correctness harness. CUDA compilation and execution have not been verified on this Mac.</p><details><summary>Kernel and correctness harness</summary><pre><code>${escape(cudaSource)}</code></pre></details></div>
${source("https://docs.nvidia.com/cuda/cuda-programming-guide/02-basics/writing-cuda-kernels.html", "CUDA: cooperative work and synchronization")}${source("https://docs.nvidia.com/cuda/cuda-c-best-practices-guide/index.html", "CUDA: shared-memory reuse and performance accounting")}${source("https://github.com/djsydney04/inference_and_training_systems/tree/main/examples/cuda", "Build commands and verification boundaries")}
<h4>What changes in a production GEMM?</h4><p>The scalar accumulator becomes a register tile or instruction-specific accumulator fragment. Loads may be vectorized or asynchronous; shared buffers may alternate so the next operands arrive while current work executes. Tensor instructions impose shape, precision and layout contracts. Those optimizations preserve the dataflow obligations demonstrated here: correct ownership, valid operands, synchronized reuse, and correctly masked outputs.</p>
<p>Use this exercise to explain the <a href="#gpu">SM workbench</a>, then compare the kernel with a tuned library under the same shape and numerical contract. A mathematically correct tiling scheme alone is not evidence of high occupancy, good bank behavior, or competitive throughput.</p>
</section>`;

export const distributedRuntimeLesson = `<section class="lesson" id="replica-update" data-lesson="Verify a real replica update">
<header><span>A runnable distributed-runtime exercise</span><h3>Two replicas must mean one optimizer update</h3></header>
<p>The <a href="#packing-loss">global token objective</a> gives each valid target the same weight. Now test that contract through a framework’s actual replica runtime. The new companion configures two logical CPU devices, creates mirrored parameters and an SGD-with-momentum optimizer, and compares four updates against an unpartitioned reference.</p>
<figure class="textbook-lab replica-lab"><figcaption><span>Figure 6.1</span><strong>One update, eleven valid targets</strong><p>Both replicas process two microbatches. One local microbatch contains no valid targets, but that replica still joins the update.</p></figcaption><div class="replica-contract"><div><strong>Replica 0</strong><span>Microbatch 0 <b>2 targets</b></span><span>Microbatch 1 <b>0 targets</b></span><small>Local gradient contribution: ∇(S₀ / 11)</small></div><div><strong>Replica 1</strong><span>Microbatch 0 <b>6 targets</b></span><span>Microbatch 1 <b>3 targets</b></span><small>Local gradient contribution: ∇(S₁ / 11)</small></div></div><div class="replica-reduction"><span>Count reduction: 2 + 9 = 11</span><b>↓</b><span>Accumulate locally, then sum replica gradients</span><b>↓</b><strong>Apply the same momentum update to both copies</strong></div><p class="figure-boundary">A real TensorFlow MirroredStrategy run on two logical CPUs in one process. The illustration shows dependency order, not measured elapsed time. It does not exercise GPU kernels, NCCL, multi-host transport or worker failure recovery.</p></figure>
<h4>Three sums, three different responsibilities</h4><p><strong>Count targets:</strong> reduce local valid-target counts across replicas for the complete accumulation window. <strong>Accumulate:</strong> sum each microbatch’s gradient of its loss sum divided by that shared count. <strong>Synchronize:</strong> let the configured optimizer path sum the replica contributions once. Reducing gradients manually and then passing them through a second automatic reduction changes the update.</p>
<p>The runtime test uses a small linear token classifier so a failed equality test has few hiding places. There is no dropout, weight decay, mixed precision or clipping. Those mechanisms require additional contracts. In particular, clipping a local contribution before a global sum is generally different from clipping the final global gradient; verify the exact ordering in the stack you use.</p>
<div class="lesson-code"><div><h4>Run the equality check</h4></div><pre><code>python examples/tensorflow/distributed_update.py
python -m unittest discover -s examples/tensorflow -p 'test_*.py' -v</code></pre></div>
<p>Configure logical devices before TensorFlow initializes its runtime; run this example in a fresh process. The test suite launches a subprocess for that reason. The script checks the global loss, reduced gradient, both parameter copies, optimizer state and target count after each update. It exits with an error if the numerical tolerance is exceeded.</p>
<div class="replica-evidence"><span>Verified locally · September 8, 2026 · TensorFlow 2.20.0</span><dl><div><dt>Runtime</dt><dd>CPU:0 + CPU:1, one process</dd></div><div><dt>Updates checked</dt><dd>4, with 2 microbatches per replica</dd></div><div><dt>Largest gradient difference</dt><dd>7.45 × 10⁻⁹</dd></div><div><dt>Largest parameter difference</dt><dd>3.73 × 10⁻⁹</dd></div></dl><p>These are observed absolute differences for this tiny deterministic problem, not universal tolerances or throughput measurements. Different TensorFlow versions and hardware may change reduction order and rounding.</p></div>
<h4>Why the empty microbatch still matters</h4><p>Zero local targets means zero local objective contribution, not permission to skip the collective protocol. Replicas must agree on which operations belong to the update. Branching out of a synchronized step on only one replica can violate that agreement. An entirely empty global update should be handled by an explicit, globally consistent policy; this example rejects it.</p>
<details class="knowledge-check"><summary>Design check: you average the two local token means and the loss still goes down. Is the trainer correct?</summary><p>Not necessarily. The replica with two targets now receives the same aggregate weight as the replica with nine targets. A decreasing loss does not prove equality with the intended global objective. Compare losses, gradients and parameter updates against a single-replica reference using exactly the same targets.</p></details>
${source("https://github.com/djsydney04/inference_and_training_systems/blob/main/examples/tensorflow/distributed_update.py", "Open the complete runtime test")}${source("https://www.tensorflow.org/tutorials/distribute/custom_training", "TensorFlow: replica losses and optimizer aggregation")}${source("https://www.tensorflow.org/api_docs/python/tf/config/set_logical_device_configuration", "TensorFlow: logical-device configuration")}
<p>Next, repeat the equality check on real accelerators before measuring speed. Then add a real input pipeline, model sharding, collective traces, checkpoint coordination and failure injection one contract at a time. The laptop result establishes none of those properties by itself.</p>
</section>`;
