/** Short figure captions; explanations belong in the lesson and Notes. */
export const figureTitles: Record<string, string> = {
  "systems-mental-models": "Model, machine, system",
  "systems-scale-ladder": "From scalar to cluster",
  "training-lifecycle": "Training stages",
  "tokens-and-bytes": "Bytes, IDs, vectors",
  "math-reading-kit": "Matrix multiplication",
  "probability-and-loss": "Probability and loss",
  "attention-by-hand": "A weighted value read",
  "learning-practice": "The learning loop",
  "autodiff": "Forward and backward",
  "attention-and-mlp": "Two axes of mixing",
  "attention-primitives": "Attention operations",
  "c-values-bytes": "Bits and their meaning",
  "c-arithmetic-contracts": "Arithmetic contracts",
  "c-pointers-arrays": "Addresses and bounds",
  "c-storage-ownership": "An allocation’s lifetime",
  "c-debug-contract": "Reference and candidate",
  "data-contract": "Data provenance",
  "packing-loss": "Packing and masks",
  "pretraining-experiments": "A controlled experiment",
  "mixed-precision": "A mixed-precision update",
  "training-ledgers": "State across a training update",
  "training-state": "Training memory",
  "parallel-axes": "Three ways to partition",
  "sequence-context-experts": "Token and expert ownership",
  "rank-grid": "Rank coordinates",
  "adapters-rollouts": "Adapters and rollouts",
  "digital-abstraction": "From transistor to bit",
  "binary-and-signed": "Signed and unsigned bits",
  "verilog-combinational": "Combinational logic",
  "registers-and-fsm": "A state transition",
  "metastability-cdc-reset": "Crossing clock domains",
  "fpga-fabric-resources": "FPGA resources",
  "rtl-simulation-synthesis": "RTL to implementation",
  "rtl-self-checking": "A self-checking testbench",
  "pipelined-mac-rtl": "A pipelined MAC",
  "fpga-memory-banking": "Addresses and banks",
  "accelerator-dataflows": "Operand reuse",
  "asic-physical-design": "Netlist to silicon",
  "hardware-examples-and-interfaces": "Host and accelerator",
  "fpga-asic-capstone": "The hardware design loop",
  "roofline-contract": "Compute and memory limits",
  "async-execution": "Submission and completion",
  "cuda-first-launch": "Grid, block, thread",
  "cuda-synchronization": "A block barrier",
  "cuda-stable-softmax": "Stable softmax",
  "cuda-complete-harness": "Kernel verification",
  "cuda-tensor-cores": "Tiles and fragments",
  "cuda-triton-compiler": "Compilation layers",
  "cuda-profile-iterate": "The optimization loop",
  "network-budget": "The transfer path",
  "collective-contracts": "Collective results",
  "collective-topology": "Communication boundaries",
  "accelerator-comparison-contract": "A fair comparison",
  "accelerator-memory-atlas": "Memory locations",
  "accelerator-sram-machines": "SRAM and compute",
  "accelerator-local-systems": "A local inference system",
  "accelerator-topology-fit": "Matching work to hardware",
  "accelerator-portability-lab": "Portable kernel contracts",
  "profiling-protocol": "Measure and explain",
  "kernel-roofline": "Reuse within a tile",
  "serving-budgets": "Request latency",
  "sampling-contract": "From scores to a sample",
  "speculation-economics": "The cost of speculation",
  "load-test": "Queues and completions",
  "goodput-cost": "Throughput, goodput, cost",
  "frontier-map": "Levels of system design",
  "frontier-moe": "Routing to experts",
  "frontier-flash": "Tiled attention",
  "frontier-precision": "Codes and scales",
  "frontier-test-time": "Candidate branches",
  "capstone-forward": "Three uses of one forward pass",
  "capstone-training": "Training checks",
  "capstone-cache": "Cached and full execution",
  "capstone-profile": "A profiling comparison",
  "capstone-http": "A request’s lifecycle",
  "capstone-vllm": "Serving runtime layers",
  "capstone-assessment": "What the evidence proves",
  "project-trainer": "Save and restore",
  "project-parallel": "Partition and reconcile",
  "project-kernel": "Kernel correctness",
  "project-preference": "Preference learning",
  "project-serving": "A serving experiment",
  "engineering-report": "An engineering argument",
  "c-compile-run": "Compile, link, run",
  "h100-kernel-example": "H100 operand path",
  "mi300x-kernel-example": "MI300X operand path",
  "tpu-kernel-example": "TPU operand path",
  "trainium-kernel-example": "Trainium operand path",
  "cpu-instructions": "Source to execution",
  "cpu-dependencies": "Issue, complete, retire",
  "cpu-branches": "Prediction and recovery",
  "cpu-caches": "A cache lookup",
  "cpu-translation": "Translation and data",
  "cpu-load-store": "Publish and acquire",
  "cpu-simd": "Independent vector lanes",
  "cpu-coherence": "Cache-line ownership",
  "cpu-cores-threads": "Threads and cores",
  "cpu-numa": "Memory placement",
  "cpu-measurement": "A CPU experiment",
  "cpu-practical-lab": "Row and column traversal",
  "cpu-model-workloads": "The host’s critical path"
};
