import { figureTitles } from "./lesson-visual-titles.ts";
export type VisualKind = "flow" | "fork" | "cycle" | "memory" | "matrix" | "timeline" | "hierarchy" | "compare";
export type VisualStep = { label: string; detail: string; note: string };
export type LessonVisual = {
  id: string; kind: VisualKind; title: string; steps: VisualStep[];
  relationship: string; invariant: string; example: string;
};
export const s = (label: string, detail: string, note: string): VisualStep => ({ label, detail, note });
export const v = (id: string, kind: VisualKind, title: string, relationship: string, invariant: string, example: string, ...steps: VisualStep[]): LessonVisual => ({ id, kind, title: figureTitles[id] ?? title, relationship, invariant, example, steps });

/** Authored conceptual schematics. Geometry shows relationships, not measured timing. */
export const lessonVisuals: LessonVisual[] = [
  v("systems-mental-models", "hierarchy", "One calculation, three levels of explanation", "Implementation layers", "A mathematical operation does not specify its kernel or scheduling policy.", "A matrix multiply can use the same equation on a CPU or GPU while moving bytes very differently.", s("Model", "tensors + parameters", "Defines the transformation and the learned values."), s("Machine", "memory + execution", "Provides storage, arithmetic and communication resources."), s("System", "queues + placement", "Decides when and where requests consume those resources.")),
  v("systems-scale-ladder", "hierarchy", "Zoom from one multiply to the cluster", "Each level contains the one before it", "A larger scale introduces communication and coordination, not just more arithmetic.", "A tensor tile lives within a kernel; the kernel executes on a device; a collective joins devices.", s("Scalar", "a × b + c", "One operation has data dependencies and finite numerical precision."), s("Tensor tile", "cooperative reuse", "Many operations share operands staged in nearby memory."), s("Device", "kernels + HBM", "Execution and memory bandwidth must be scheduled together."), s("Cluster", "ranks + fabric", "Ranks exchange shards and synchronize through a network.")),
  v("training-lifecycle", "flow", "The model changes at different stages", "A checkpoint connects training stages", "Changing an objective is different from changing the runtime that executes it.", "Pre-training predicts text; supervised fine-tuning scores selected response tokens; deployment normally keeps weights fixed.", s("Pre-train", "next-token objective", "Broad data changes the model parameters through many gradient updates."), s("Adapt", "examples + preferences", "Post-training changes the objective and data distribution while retaining a checkpoint foundation."), s("Serve", "fixed weights + requests", "Inference creates activations and cache state without an optimizer update.")),
  v("tokens-and-bytes", "memory", "Text, token IDs and embeddings are different objects", "Representation changes", "A token ID is an index; its numeric magnitude is not a semantic feature.", "Four IDs and an embedding width of eight produce [4, 8] activations, regardless of the number of UTF-8 bytes in the text.", s("Text bytes", "UTF-8 sequence", "Bytes encode text; their boundaries do not have to match word boundaries."), s("Token IDs", "integer sequence", "A tokenizer maps pieces of text into vocabulary entries."), s("Vectors", "one row per ID", "Embedding lookup selects learned rows and begins the model computation.")),
  v("math-reading-kit", "matrix", "Contract the shared axis", "[M, K] × [K, N] → [M, N]", "Only the contracted K axis is summed out.", "[2, 3] × [3, 4] gives [2, 4]. Each output uses three multiply-add contributions.", s("Left matrix", "M rows × K channels", "A row supplies the features for one output row."), s("Right matrix", "K channels × N columns", "Each column supplies weights for one output feature."), s("Output", "M rows × N columns", "Entry (i, j) is the dot product of left row i and right column j.")),
  v("probability-and-loss", "flow", "Score the actual following token", "Normalize scores, then select the target probability", "The target is a vocabulary index, not a generated sample.", "If the correct token has probability 0.25, its loss is −ln(0.25) ≈ 1.386.", s("Logits", "real-valued scores", "Scores compare vocabulary entries before normalization."), s("Probabilities", "softmax over vocabulary", "Subtract the maximum before exponentiation for numerical stability."), s("Loss", "−log p(target)", "The observed next token identifies which probability contributes to cross entropy.")),
  v("attention-by-hand", "flow", "A query reads a weighted mixture of values", "Query and keys determine weights; values supply content", "Mask forbidden positions before normalizing.", "Weights [0.25, 0.75] and values [2, 6] produce 0.25×2 + 0.75×6 = 5.", s("Query + keys", "compare features", "Compare the current query with each available key to produce compatibility scores."), s("Attention weights", "scale · mask · softmax", "Scale scores, exclude forbidden positions, then normalize over the allowed keys."), s("Read values", "weighted sum of V", "Multiply each value vector by its attention weight and sum over token positions."), s("Head output", "one mixed vector", "The result has value-channel width; its channels are not vocabulary probabilities.")),
  v("learning-practice", "cycle", "Turn an explanation into a prediction", "Predict → compute → compare → revise", "A wrong prediction is useful when you can identify which assumption failed.", "Predict the output shape first, run a small example, then change one dimension and predict again.", s("Predict", "write the expected result", "State a shape, value or invariant before running the lab."), s("Compute", "use a small case", "Keep enough numbers visible to trace the calculation."), s("Compare", "locate the first mismatch", "Inspect the earliest wrong intermediate rather than only the final score."), s("Revise", "change one assumption", "Explain the correction and test a nearby counterexample.")),
  v("autodiff", "cycle", "The backward pass follows dependencies in reverse", "Forward values support local derivatives", "A parameter gradient has the same shape as its parameter.", "For y = wx, x = 2, w = 3 and target 4, half squared-error loss L = (wx − 4)² / 2 gives dL/dw = (6 − 4) × 2 = 4.", s("Forward", "x → prediction", "Save values that the derivative formulas will need."), s("Loss", "prediction → scalar", "A scalar objective starts the reverse chain of sensitivities."), s("Backward", "chain local derivatives", "Accumulate contributions when a value influences the loss through several paths."), s("Update", "w ← w − ηg", "The optimizer uses gradients; the forward graph alone does not change weights.")),
  v("attention-and-mlp", "compare", "Mix positions, then transform features", "Two complementary axes", "Both sub-layers return the residual width D.", "Attention can move information from token 1 to token 4; an FFN transforms token 4’s already-contextualized vector.", s("Attention", "mix across T", "Query–key weights combine information from allowed token positions."), s("Feed-forward", "mix across D", "The same nonlinear channel transformation runs independently at every position."), s("Residual", "preserve [B, T, D]", "Equal-width updates are added to the stream rather than concatenated.")),
  v("attention-primitives", "flow", "From QKᵀ to an attention output", "The order of masking and normalization matters", "Masked probability is zero; each allowed row sums to one.", "For one head, [T, dh] × [dh, T] gives [T, T] scores; multiplying probabilities by [T, dh] returns [T, dh].", s("Scores", "QKᵀ / √dh", "Batched multiplication compares every query with the available keys."), s("Mask + softmax", "normalize the key axis", "Apply the causal exclusion before converting scores to probabilities."), s("Value sum", "P × V", "The contraction runs over key positions, leaving query positions and head channels.")),
  v("c-values-bytes", "memory", "A type gives meaning to stored bits", "Interpretation sits above storage", "Equal byte patterns do not imply equal values under different types.", "A 32-bit object occupies four bytes; those bits may encode an integer or an IEEE floating-point value.", s("Bytes", "addressable storage", "Memory contains bit patterns with alignment and lifetime constraints."), s("Type", "size + interpretation", "The declared type controls how operations interpret those bits."), s("Operation", "defined C semantics", "Conversions and arithmetic rules determine the result, not the diagram’s appearance.")),
  v("c-arithmetic-contracts", "compare", "Choose which arithmetic contract you need", "Representations have different failure modes", "Do not assume mathematical integers or real numbers behave like finite machine types.", "Unsigned addition wraps modulo 2ⁿ; a finite floating-point sum can round away a small contribution.", s("Unsigned", "modulo 2ⁿ", "Overflow wraps by the language’s unsigned arithmetic rules."), s("Signed", "bounded integer range", "Signed overflow in C is undefined behavior; avoid relying on a wraparound result."), s("Floating point", "sign + exponent + fraction", "Rounding, infinities and NaNs require explicit numerical checks.")),
  v("c-pointers-arrays", "memory", "An address is not an array bound", "Base + index × element size", "A pointer alone does not carry the length or lifetime of the allocation.", "For a float array, p + 3 advances by three elements, normally 12 bytes when sizeof(float) is 4.", s("Base pointer", "start of an allocation", "The address identifies storage, not how many valid elements follow."), s("Index", "0 ≤ i < length", "Bounds must be checked against the actual array length."), s("Element", "*(base + i)", "Dereference only a correctly aligned address within a live object.")),
  v("c-storage-ownership", "timeline", "An allocation has a lifetime", "Acquire → use → release", "No access is valid after the owning storage has expired.", "Returning a pointer to a local stack array leaves a dangling pointer after the function returns.", s("Allocate", "establish an owner", "Record who must release the storage and what size was acquired."), s("Borrow", "temporary access", "A borrowed pointer does not extend the owner’s lifetime."), s("Release", "end the lifetime", "Free once and stop all later reads or writes through aliases.")),
  v("c-debug-contract", "compare", "Compare a fast path with a trusted small case", "Same inputs, independently computed outputs", "A benchmark is meaningful only after correctness holds for its input domain.", "Test zero, one and ragged dimensions before timing a large matrix.", s("Reference", "simple implementation", "Favor transparent arithmetic over speed so failures can be localized."), s("Candidate", "optimized implementation", "Run the same inputs, shapes and precision contract."), s("Comparison", "values + tolerances", "Check bounds, NaNs, errors and ownership before interpreting runtime.")),
  v("data-contract", "flow", "Preserve provenance through the data pipeline", "Raw records become a versioned training stream", "A checkpoint is not reproducible without the data and transformation versions.", "Changing tokenizer vocabulary or filtering rules changes the effective training distribution even if filenames stay the same.", s("Source", "license + provenance", "Track origin, consent or license constraints and dataset version."), s("Transform", "filter + deduplicate", "Document which records survive and how text is normalized."), s("Sample", "mixture + order", "Sampling weights and shuffle state determine the stream seen by the optimizer.")),
  v("packing-loss", "memory", "Token packing needs both boundaries and counts", "Physical adjacency is not permission to attend", "Normalize by eligible target tokens, not by the number of packed rows.", "Two workers with loss sums 6 and 4 over 3 and 1 tokens have global mean (6+4)/(3+1) = 2.5.", s("Pack", "several examples per row", "Packing removes padding while retaining each example’s boundary."), s("Mask", "attention + loss eligibility", "Attention boundaries and target-loss masks are separate decisions."), s("Reduce", "sum losses / sum tokens", "Unequal token counts require a globally consistent denominator.")),
  v("pretraining-experiments", "compare", "Change one variable in an equal-budget comparison", "Baseline and intervention share evaluation", "Report the compute and data budget along with the final score.", "A larger model trained on fewer tokens is not an equal-data comparison, even if total training FLOPs match.", s("Baseline", "fixed recipe", "Record tokenizer, model, data, budget and random seeds."), s("Intervention", "one declared change", "Separate the intended variable from hidden changes in batch size or evaluation."), s("Evaluation", "held-out + uncertainty", "Use the same held-out data and report variation, not a single attractive run.")),
  v("mixed-precision", "cycle", "Low-precision compute still needs an update contract", "Cast → compute → check → update", "Loss scaling does not repair an already-overflowed forward activation.", "For loss scale S, divide the accumulated scaled gradient by S before clipping the true gradient norm.", s("Parameters", "master + compute copies", "The recipe determines which values retain higher precision."), s("Forward / backward", "finite arithmetic", "Limited range and rounding affect activations and derivatives."), s("Unscale + check", "finite gradients", "Detect nonfinite values before applying an optimizer update."), s("Optimizer", "stateful update", "Update the authoritative parameters and refresh lower-precision copies as required.")),
  v("training-ledgers", "hierarchy", "One update spans several kinds of state", "A checkpoint must reconcile the ledgers", "Weights alone are not enough to reproduce the next training update.", "Restoring weights but resetting Adam moments, data position or RNG state changes the future trajectory.", s("Model", "weights + gradients", "Track authoritative parameters and how their gradients were reduced."), s("Optimizer", "moments + step", "Stateful updates depend on accumulated statistics and schedules."), s("Execution", "ranks + collectives", "Every rank must agree on ownership and update order."), s("Experiment", "data + RNG + checkpoint", "Replay requires the same next batch and the same stochastic choices.")),
  v("training-state", "memory", "Separate persistent model state from temporary activations", "Different allocations have different lifetimes", "A weights-only byte count is not a training-memory budget.", "A BF16 weight copy costs 2 bytes per parameter; gradients, moments and any master copy add separate allocations.", s("Weights", "parameter storage", "Precision and sharding determine how many bytes each rank owns."), s("Gradients + moments", "update state", "The optimizer and distribution strategy control these persistent buffers."), s("Activations", "forward to backward", "Sequence length, microbatch size and checkpointing determine temporary storage.")),
  v("parallel-axes", "compare", "Choose what each device owns", "Replication, slicing and staging are different axes", "A parallel method must define both local computation and communication.", "Data parallelism changes which examples a rank sees; tensor parallelism changes which parameter slices it computes.", s("Data parallel", "replicate model", "Ranks process different samples then reconcile gradients."), s("Tensor parallel", "split operators", "Ranks own parts of a layer and communicate to reconstruct required results."), s("Pipeline parallel", "split layers", "Microbatches cross stage boundaries while activations stay alive for backward.")),
  v("sequence-context-experts", "compare", "Three additional ownership boundaries", "Each branch partitions a different object", "Names are not interchangeable: specify the tensor axis or routed token set.", "An MoE router can send different numbers of tokens to each expert, making all-to-all sizes uneven.", s("Activations", "tokens + channels", "Begin with a tensor and identify which dimension is distributed."), s("Sequence / context", "split token work", "Attention may need remote keys and values even when query positions are local."), s("Experts", "route token subsets", "Dispatch selected tokens to expert parameter owners and combine returned outputs."), s("Reconcile", "collectives + layout", "The next layer must receive the layout and values it expects.")),
  v("rank-grid", "hierarchy", "A rank belongs to several communication groups", "Logical coordinates map to physical devices", "Parallel degrees multiply to the world size only under the declared decomposition.", "DP = 2, TP = 4 and PP = 2 use 16 ranks; each rank has one coordinate along each axis.", s("World", "all ranks", "The job assigns every process a global identity."), s("Coordinates", "DP × TP × PP", "Coordinates define which model slice and data replica a rank owns."), s("Groups", "one axis varies", "A collective group holds the other coordinates fixed."), s("Placement", "devices + links", "Map communication-heavy groups onto the appropriate physical fabric.")),
  v("adapters-rollouts", "compare", "Small trainable adapters still need a full rollout system", "Training parameters and inference work are different budgets", "Freezing base weights does not remove the forward computation through them.", "For W with shape [m, n], a rank-r adapter adds r(m+n) parameters rather than mn.", s("Base model", "frozen weights", "The checkpoint remains part of every forward pass."), s("Adapter", "low-rank update", "Only the small update matrices receive the chosen training gradients."), s("Rollouts", "generated samples", "Generation consumes inference time and cache capacity."), s("Learning signal", "scores + log probabilities", "Training must identify which policy produced each sample.")),
];
