import "./fonts.css";
import "./styles.css";
import "./textbook.css";
import "./reader.css";
import "./workbench.css";
import "./kernel.css";
import "./methods.css";
import "./manual.css";
import "./accelerator.css";
import "./cuda.css";
import "./digital.css";
import "./learning-reader.css";
import { initializeAtlasUI } from "./atlas-ui";
import { atlasMarkup } from "./content";
import { initializeNetworkLabs } from "./network-labs";
import { prepareLessonVisuals, initializeLessonVisuals, initializeFigurePopouts } from "./lesson-visuals";
import { initializeGlossary } from "./glossary";
import { initializeInteractions } from "./interactions";
import { initializeTrainingSystems } from "./training-systems";
import { initializeTextbook } from "./textbook";
import { prepareReader, initializeReader } from "./reader";
import { initializeSystemsLabs } from "./systems-labs";
import { initializeMatmulLab } from "./kernel-lab";
import { initializeMethodLabs } from "./method-labs";
import { initializeDecodingLabs } from "./decoding-labs";
import { initializeHardwareLabs } from "./hardware-labs";
import { initializeParallelLabs } from "./parallel-labs";
import { initializeFoundationsLabs } from "./foundations-labs";
import { initializeAcceleratorLabs } from "./accelerator-labs";
import { initializeCudaLabs } from "./cuda-labs";
import { initializeDigitalLabs } from "./digital-labs";

const app = document.querySelector<HTMLDivElement>("#app");

if (!app) throw new Error("Atlas root element is missing");

app.innerHTML = atlasMarkup;
prepareReader();
prepareLessonVisuals();

initializeGlossary();
initializeInteractions();
initializeNetworkLabs();
initializeTrainingSystems();
initializeTextbook();
initializeSystemsLabs();
initializeMatmulLab();
initializeMethodLabs();
initializeDecodingLabs();
initializeHardwareLabs();
initializeParallelLabs();
initializeFoundationsLabs();
initializeAcceleratorLabs();
initializeCudaLabs();
initializeDigitalLabs();
initializeLessonVisuals();
initializeReader();
initializeAtlasUI();
initializeFigurePopouts();

void import("./scenes").then(({ initializeScenes }) => initializeScenes());
