import "./fonts.css";
import "./styles.css";
import "./textbook.css";
import "./reader.css";
import "./workbench.css";
import "./kernel.css";
import "./methods.css";
import "./manual.css";
import "./accelerator.css";
import "./cuda.css";
import "./digital.css";
import "./disaggregation.css";
import "./speculation-frontier.css";
import "./rollout-training.css";
import "./serving-runtime.css";
import "./sharded-training.css";
import "./quantization.css";
import "./moe-execution.css";
import "./learning-reader.css";
import { initializeAtlasUI } from "./atlas-ui";
import { prepareBookStudies } from "./book-illustrations";
import { atlasMarkup } from "./content";
import { initializeNetworkLabs } from "./network-labs";
import { prepareLessonVisuals, initializeLessonVisuals, initializeFigurePopouts } from "./lesson-visuals";
import { prepareSystemBuildout, initializeSystemBuildout } from "./system-buildout";
import { initializePortableKernelLab } from "./portable-kernel-lab";
import { initializeGlossary } from "./glossary";
import { initializeInteractions } from "./interactions";
import { initializeTrainingSystems } from "./training-systems";
import { initializeTextbook } from "./textbook";
import { prepareReader, initializeReader } from "./reader";
import { initializeSystemsLabs } from "./systems-labs";
import { initializeMatmulLab } from "./kernel-lab";
import { initializeMethodLabs } from "./method-labs";
import { initializeDecodingLabs } from "./decoding-labs";
import { initializeHardwareLabs } from "./hardware-labs";
import { initializeParallelLabs } from "./parallel-labs";
import { initializeFoundationsLabs } from "./foundations-labs";
import { initializeAcceleratorLabs } from "./accelerator-labs";
import { initializeCudaLabs } from "./cuda-labs";
import { initializeDigitalLabs } from "./digital-labs";
import { initializeDiagramPlayback, refreshDiagramPlayback } from "./diagram-playback";
import { prepareChipAnatomy, initializeChipAnatomy } from "./chip-anatomy";
import { initializeDisaggregationLabs } from "./disaggregation-labs";
import { initializeSpeculationFrontierLabs } from "./speculation-frontier-labs";
import { initializeRolloutTrainingLabs } from "./rollout-training-labs";
import { initializeServingRuntimeLabs } from "./serving-runtime-labs";
import { initializeShardedTrainingLabs } from "./sharded-training-labs";
import { initializeQuantizationLabs } from "./quantization-labs";
import { initializeMoeExecutionLabs } from "./moe-execution-labs";

const app = document.querySelector<HTMLDivElement>("#app");

if (!app) throw new Error("Atlas root element is missing");

app.innerHTML = atlasMarkup;
prepareSystemBuildout();
prepareChipAnatomy();
prepareReader();
prepareLessonVisuals();

initializeGlossary();
initializeInteractions();
initializeNetworkLabs();
initializeTrainingSystems();
initializeTextbook();
initializeSystemsLabs();
initializeMatmulLab();
initializeMethodLabs();
initializeDecodingLabs();
initializeHardwareLabs();
initializeParallelLabs();
initializeFoundationsLabs();
initializeAcceleratorLabs();
initializeCudaLabs();
initializeDigitalLabs();
initializeChipAnatomy();
initializePortableKernelLab();
initializeDisaggregationLabs();
initializeSpeculationFrontierLabs();
initializeRolloutTrainingLabs();
initializeServingRuntimeLabs();
initializeShardedTrainingLabs();
initializeQuantizationLabs();
initializeMoeExecutionLabs();
initializeLessonVisuals();
initializeSystemBuildout();
prepareBookStudies();
initializeReader();
initializeAtlasUI();
initializeFigurePopouts();
initializeDiagramPlayback();

void import("./scenes").then(({ initializeScenes }) => {
  initializeScenes();
  refreshDiagramPlayback();
});
