import { chapterMarkup, sourceLink as ref, workedCheck as check } from "./lesson-template";
import { probabilityTree, gradientFork } from "./notebook-figures";

export const mathematicsChapter = chapterMarkup(
  "mathematical-foundations", "Mathematics for model building",
  "Read the notation, derive the probability of a sequence, and follow derivatives through shared computations. Small examples connect the equations to the model you will build.", `
<section class="lesson" id="numbers-and-functions" data-lesson="Numbers, functions and units">
<header><span>Start with ordinary arithmetic</span><h3>A model is built from operations on numbers</h3></header>
<p>Begin with one number, such as 3. A variable is a name for a number that can change: writing x=3 says which value x has in this example. An expression tells you what to calculate. For 2x+1, multiply x by 2 and add 1, obtaining 7. Parentheses set the order: 2(x+1)=8 for the same x. A minus sign can subtract two numbers or indicate a negative number; 3−5=−2.</p>
<p>A fraction is a division: 3/4=0.75=75%. Squaring multiplies a number by itself, so (−3)²=9. The square root √9 is the nonnegative number 3 whose square is 9. A negative exponent denotes a reciprocal: 2⁻³=1/2³=1/8. We will use these operations for averages, scales and storage budgets before combining them into a model.</p>
<h4>Name the input, the rule and the output</h4>
<p>A function is a rule from an allowed input to an output. Write f(x)=2x+1; then f(3)=7. The letter f names the rule, while x is its input. A parameter names a number inside the rule that we can choose: f(x;w,b)=wx+b has weight w and bias b. At w=2 and b=1, it is the same rule. Training adjusts w and b; ordinary inference holds them fixed and changes x.</p>
<div class="derivation"><h4>Follow two operations and one update</h4><p>Let z=2x+1 and y=z². At x=3, first compute z=7, then y=49. This is composition: y=g(f(x)) with g(z)=z². It does not mean multiplying the two functions. If we instead change the weight from 2 to 2.1, z becomes 7.3 and y becomes 53.29. The output depends on both the input and the parameters.</p><p>An equals sign states a relationship. A program-style arrow states an update: w←w−0.1 replaces the old w by a new value. A subscript labels an item, as in x₀, x₁, x₂; it does not multiply x by the subscript. Superscript ² usually means a square, but the superscript T on a matrix will mean transpose. Read the local definition when symbols are reused.</p></div>
<h4>Exponentials and logarithms are two directions of one conversion</h4>
<p>The exponential exp(x), also written eˣ, uses the fixed base e≈2.71828. It is positive for every finite real x: exp(0)=1, exp(1)≈2.718 and exp(−1)≈0.368. Increasing the input by 1 multiplies the output by e. The natural logarithm ln reverses this conversion: ln(exp(x))=x and exp(ln(a))=a for a&gt;0. Thus ln(1)=0 and ln(e)=1. A logarithm of a number between zero and one is negative, which is why −ln(probability) can serve as a nonnegative penalty.</p>
<p>The identities exp(a+b)=exp(a)exp(b) and ln(ab)=ln(a)+ln(b) connect products to sums. The probability lessons will use them to score a sequence without multiplying many tiny numbers. Logarithms with base 2 count information in bits; natural logarithms count it in nats. That choice changes numerical scale, not the ranking of probabilities.</p>
<h4>Keep the unit attached to the number</h4>
<p>A model with 1,000 stored numbers at 4 bytes each uses 4,000 bytes of payload. A transfer of 4,000 bytes at 2,000 bytes per second takes 2 seconds in an ideal constant-rate model. The units show why: bytes divided by bytes/second leaves seconds. Capacity, rate and elapsed time describe different quantities. A faster link does not increase how many bytes fit in memory.</p>
<p>Scientific notation writes large and small quantities compactly: 3×10⁶ is three million, and 5×10⁻³ seconds is 0.005 seconds or 5 milliseconds. The later hardware chapters use decimal prefixes such as giga (10⁹) and binary prefixes such as gibi (2³⁰); keep them distinct when checking an estimate.</p>
${check("For f(x;w,b)=wx+b with x=4, w=0.5 and b=−1, what is the output? What changes if only w becomes 0.75?", "The first output is 0.5×4−1=1. The second is 0.75×4−1=2. The input is unchanged; modifying a parameter changed the function's prediction.")}
<p>Next, arrange numbers into lists and tables. Every larger expression will still reduce to operations on individual entries. You can read the mathematical examples without knowing a programming language; the code listings are a second route to the same calculations, developed later in <a href="#programming">C and memory</a> and <a href="#frameworks">tensor frameworks</a>.</p>
${ref("https://d2l.ai/chapter_preliminaries/calculus.html", "Dive into Deep Learning: functions and change")}
</section>
<section class="lesson" id="math-reading-kit" data-lesson="Tensor shapes and multiplication"><header><span>Mathematical prerequisites</span><h3>Read the shapes before reading the formula</h3></header>
<p>A scalar is one number. A vector is an ordered list. A matrix is an array with two axes. A tensor extends the array idea to any number of axes. The 24 feature values in the example below are <strong>activations</strong>, produced for these inputs. The embedding table is a separate set of <strong>parameters</strong>: for a 256-byte vocabulary and width 4, it contains 1,024 learned values shared across all examples and positions.</p>
<p>Keep three questions separate: which example are we processing, which position in it, and which numbers describe that position? The three axes of <code>X[B,T,D]</code> answer those questions. Shape is an agreement about meaning as well as a list of lengths.</p>
<div class="method-table"><table><caption>Picture two three-byte sequences, “cat” and “dog,” with four features per position</caption><thead><tr><th>Axis</th><th>What it selects</th><th>In this example</th></tr></thead><tbody><tr><th>B · batch</th><td>One sequence in the group processed together</td><td>2 sequences</td></tr><tr><th>T · time / sequence</th><td>A token position within that sequence</td><td>3 positions each</td></tr><tr><th>D · features</th><td>A component of that position’s numerical representation</td><td>4 numbers per position</td></tr></tbody></table></div>
<p>The IDs start as a <code>[2,3]</code> integer array. An embedding lookup produces <code>[2,3,4]</code>: 24 computed feature values. With zero-based indexing, <code>X[1,2,:]</code> selects all four features for the “g” position in the second sequence. A feature is a coordinate in a learned representation; it need not have a tidy human label. The two batch sequences do not attend to each other in this ordinary decoder.</p>

<h4>What makes a matrix trainable?</h4>
<p>A matrix is simply an arrangement of numbers. We make it a parameter by storing its values as part of the model and letting an optimizer update them from gradients. Computed outputs are also arrays, but their changing values do not make them separate learned weights. A gradient measures how the loss changes when a weight changes; the derivative lessons below will calculate one. A frozen parameter is still model state; its values are deliberately excluded from updates.</p>
<p>The dot product of [a,b] and [c,d] is ac+bd. It combines matching components and sums the products. Matrix multiplication repeats dot products: if A is [M,K] and B is [K,N], then C is [M,N] and <code>Cᵢⱼ = Σₖ AᵢₖBₖⱼ</code>. The Σ symbol means “add the indicated terms.” K disappears because it is summed; M and N remain. This is the same operation you will later tile in shared memory and map onto a systolic array.</p>
<div class="derivation"><h4>Do one output by hand</h4><p>A row [2,−1,3] dotted with a column [4,5,−2] gives 8−5−6=−3. That is three multiplies and two additions as written. Engineering FLOP estimates often count a multiply-accumulate as two operations and use 2MNK for a large GEMM, with the convention stated explicitly.</p></div>
<div class="derivation"><h4>Six weights turn two features into three</h4><p>Let the input row be x=[3,4] and the two rows of W be [1,0,−1] and [2,1,0]. Then <code>xW = [3×1+4×2, 3×0+4×1, 3×(−1)+4×0] = [11,4,−3]</code>. W has six parameters; the result has three activations. Increasing only W’s first entry from 1 to 1.1 increases the first output by 0.3. This dependence is what a derivative measures.</p><p>Apply this same W to every position of a <code>[B,T,2]</code> input and obtain <code>[B,T,3]</code>. The parameter count stays six when B or T grows. Gradients from the positions using a shared weight accumulate into that weight’s update; a mean loss also scales them by its denominator.</p></div>
<details class="deep-dive"><summary>Match the notation to PyTorch’s stored weights</summary><p>Here rows are input features, so W has shape [input features, output features] and the expression is xW. PyTorch’s <code>nn.Linear</code> stores its weight with shape [output features, input features] and uses its transpose: <code>y = x @ weight.T + bias</code>. Transpose exchanges the two axes. These conventions describe the same operation. The later six-weight interactive lesson writes a feature vector as a column and uses <code>z=Wx</code>, with one stored row per output token.</p></details>
<p>A function maps inputs to outputs. Composition means applying one function after another. If z=f(x) and y=g(z), y=g(f(x)). A neural network is a composition with trainable coefficients. A nonlinear activation such as GELU matters because repeated linear maps alone collapse into a single linear map; extra layers would otherwise not provide the same representational flexibility.</p>
<p>Always carry units. Capacity is bytes; bandwidth is bytes per second; latency is seconds; compute rate is operations per second. GB is 10⁹ bytes and GiB is 2³⁰ bytes. Eight bits make a byte, so a 400 Gb/s link has a raw rate of 50 GB/s before protocol and other overhead. These conversions will recur in every hardware comparison.</p>
${check("A [2,5,64] tensor is projected by [64,128]. What is the result shape and FP32 output size?", "The result is [2,5,128]: 1,280 numbers, or 5,120 bytes. The 64-feature axis contracts. No batch or time dimension disappears.")}
${check("Doubling the batch doubles the computed activations. Does it double the learned matrix?", "No. Every sequence uses the same parameter matrix. A larger batch creates more activations and more loss contributions, while the stored parameter count stays fixed.")}
${ref("https://docs.pytorch.org/docs/2.8/generated/torch.nn.Linear.html", "PyTorch 2.8: linear-map shapes and stored weight convention")}
${ref("https://docs.pytorch.org/docs/2.8/generated/torch.nn.parameter.Parameter.html", "PyTorch 2.8: model parameters and temporary tensors")}
</section>
<section class="lesson" id="indices-and-reductions" data-lesson="Indices, sums and broadcasting">
<header><span>Reading an equation</span><h3>An index tells you which number an equation describes</h3></header>
<p>The <a href="#math-reading-kit">first shape examples</a> introduced a tensor as an array with named axes. Now use those names to read an equation without guessing. Uppercase letters below describe axis lengths; lowercase letters select positions. Let X have shape [B,T,D]: B sequences, T token positions per sequence, D features per position. Then X[b,t,d] is one scalar, and X[b,t,:] is the feature vector for a single position.</p>
<p>A summation is a loop with an accumulator. In <code>s[b,t] = Σ(d=0…D−1) X[b,t,d]</code>, hold b and t fixed, walk d from zero to D−1, and add those D values. The result has shape [B,T]. The indices b and t are <strong>free indices</strong>: the equation describes a separate result for each combination. The index d is <strong>summed over</strong>, so it disappears from the result. A mean adds a denominator: <code>μ[b,t] = s[b,t]/D</code>.</p>
<div class="derivation"><h4>Reduce the intended axis</h4><p>Let one sequence contain two vectors, [1,3,5] and [2,4,6]. Averaging over features gives [3,4], one value per token. Averaging over tokens gives [1.5,3.5,5.5], one value per feature. Averaging all six entries gives the scalar 3.5. All three are valid calculations; only one matches a particular layer’s specification.</p><p>This difference matters for normalization. A decoder usually normalizes the channels within each token. It should not accidentally mix a token’s statistics with future positions or other batch examples.</p></div>
<h4>Broadcasting means reuse along specified axes</h4>
<p>For a per-feature bias b[D], the equation <code>Y[n,t,d] = X[n,t,d] + b[d]</code> reuses the same bias at every token and batch position. It does not learn a new bias for each occurrence. Array libraries commonly compare dimensions from the right: matching lengths are compatible, and a length-one dimension can be expanded. Explicit shapes help communicate intent. A per-token mean with shape [B,T,1] subtracts cleanly from [B,T,D]; the last dimension records that its single statistic applies to all D features.</p>
<p>Shape compatibility alone cannot prove semantic correctness. If T happens to equal D, a [T] array might broadcast onto the feature axis even though you intended one offset per time position. Name the axes on paper, then use a reshape such as [1,T,1] when that is the intended meaning. The <a href="#tensor-strides">storage lesson</a> explains why a broadcast or transpose need not copy the underlying values.</p>
<h4>Read a matrix multiplication as three loops</h4>
<p>With X[N,D] and W[D,F], <code>Y[n,f] = Σ(d=0…D−1) X[n,d]W[d,f]</code>. N counts input rows, D is the input width, and F is the output width. Each output row uses the same W. Elementwise multiplication instead multiplies corresponding entries without summing; we write it as ⊙. Confusing these operations can produce plausible shapes and completely different models.</p>
${check("For X[2,4,3], what shapes should a per-token mean and a per-feature bias use when combined with X?", "Use [2,4,1] for the per-token mean and [3] or [1,1,3] for the per-feature bias. The first varies across tokens; the second varies across features. The resulting tensor keeps shape [2,4,3].")}
<p>Next, interpret the vectors themselves. An axis length tells you how many coordinates you store; linear algebra describes how those coordinates combine.</p>
${ref("https://www.deeplearningbook.org/contents/linear_algebra.html", "Goodfellow, Bengio and Courville: arrays and linear algebra")}
${ref("https://numpy.org/doc/stable/user/basics.broadcasting.html", "NumPy: broadcasting rules and compatible dimensions")}
</section>

<section class="lesson" id="vectors-and-linear-maps" data-lesson="Vectors, geometry and rank">
<header><span>What a projection does</span><h3>A learned matrix combines coordinates into new coordinates</h3></header>
<p>A vector such as x=[3,4] can describe a point, a direction, or a list of model features. Its Euclidean length is <code>‖x‖₂ = √(Σᵢ xᵢ²)</code>, which is 5 here. The subscript 2 names the norm; it is not an axis. A unit vector has length one, so x/‖x‖₂=[0.6,0.8]. Normalizing the zero vector requires separate handling because division by zero is undefined.</p>
<p>The dot product connects length and direction: <code>x·w = ‖x‖₂‖w‖₂ cos(θ)</code>, where θ is the angle between nonzero vectors. Cosine is the horizontal coordinate of a unit circle at that angle: it is 1 for the same direction, 0 at a right angle and −1 for opposite directions. For x=[3,4] and w=[4,−3], the dot product is 12−12=0: the vectors are perpendicular. For x and 2x, cosine similarity is one, but their dot product is 50. A large dot product can reflect magnitude as well as alignment. Learned attention scores therefore need not be a pure measure of semantic similarity.</p>
<div class="derivation"><h4>Describe a map by its action on a basis</h4><p>The basis vectors e₁=[1,0] and e₂=[0,1] select the two input coordinates. Write x=3e₁+4e₂. Under the row-vector convention, suppose e₁W=[1,2] and e₂W=[−1,1]. Linearity gives <code>xW = 3[1,2] + 4[−1,1] = [−1,10]</code>. W’s rows are precisely these two basis images.</p><p>More generally, a linear map satisfies f(ax+by)=af(x)+bf(y) for scalars a and b. Adding a learned bias produces an affine map: it can translate the origin. Applying a nonlinear activation after the map allows compositions that cannot be collapsed into one affine transformation.</p></div>
<h4>Width and independent directions are different quantities</h4>
<p>A matrix’s rank is the number of independent directions its output can span. If both rows of W are [1,2], every result xW equals (x₁+x₂)[1,2]. The output still stores two coordinates, but it lies on one line: rank one. Different inputs, such as [1,0] and [0,1], now produce the same output, so this map cannot be inverted to reconstruct arbitrary inputs.</p>
<p>This is the foundation of <a href="#adapters-rollouts">low-rank adapters</a>. A product A[D,r]B[r,F] has rank at most r. It represents an update through r intermediate coordinates using r(D+F) stored numbers instead of DF. That is a constraint on the update’s linear map; it does not mean every activation or the entire adapted model has rank r. The base matrix still contributes its own directions.</p>
<p>A transpose exchanges row and column roles: Wᵀ[f,d]=W[d,f]. It is not generally an inverse. Transposes appear in backpropagation because derivatives route an output sensitivity back through the coefficients that connected inputs to outputs. You will derive that relationship below instead of assuming that backward “undoes” the forward pass.</p>
${check("A [4,1] matrix A is multiplied by B[1,6]. How many parameters are stored, and what is the largest possible rank of AB?", "A and B store 4+6=10 numbers. AB is a [4,6] matrix with rank at most one. It can have rank zero if either factor is zero. An unrestricted [4,6] matrix stores 24 numbers and can have rank as large as four.")}
${ref("https://d2l.ai/chapter_appendix-mathematics-for-deep-learning/geometry-linear-algebraic-ops.html", "Dive into Deep Learning: geometry of linear operations")}
${ref("https://arxiv.org/abs/2106.09685", "Hu et al.: low-rank adaptation")}
</section>

<section class="lesson" id="conditional-sequences" data-lesson="Conditional probability and sequences">
<header><span>From one prediction to a sequence</span><h3>The probability of a continuation depends on its entire path</h3></header>
<p>A random variable assigns a value to an uncertain outcome. A token variable X can take one of V vocabulary IDs. A distribution p(x) assigns nonnegative probabilities that sum to one over those possible IDs. An event can include several outcomes: the probability of generating either of two distinct IDs is the sum of their probabilities.</p>
<p>A conditional probability <code>p(B|A) = p(A,B)/p(A)</code> describes B when A is known, assuming p(A)&gt;0. The comma denotes a joint event; the vertical bar reads “given.” Rearranging gives <code>p(A,B)=p(A)p(B|A)</code>. Independence is the special condition p(B|A)=p(B), not a default assumption. The next token in language generally depends on the preceding tokens.</p>
<p>Apply the product rule repeatedly to a token sequence of length T:</p>
<div class="derivation"><h4>The autoregressive factorization</h4><p><code>p(x₁,…,xT) = ∏(t=1…T) p(xₜ | x₁,…,xₜ₋₁)</code></p><p>Π means multiply the indicated terms, just as Σ means add them. The empty prefix at t=1 is represented by a starting context or a beginning-of-sequence convention. With a supplied prompt, hold that prompt fixed and factor only the generated continuation. The fixed-length example below generates two positions without an early-stop rule; a complete variable-length model also specifies stopping, commonly through an end token.</p></div>
${probabilityTree}
<p>In the drawing, p(Ax)=0.6×0.5=0.30, while p(Bx)=0.4×0.9=0.36. Choosing the highest-probability first token selects A, yet Bx is the most probable complete two-token sequence. <strong>Greedy decoding</strong> maximizes the next local choice; it does not generally maximize the probability of the whole response.</p>
<p>Sampling has a different purpose: draw a continuation according to the model’s distribution. Across many independent trials, the four outcomes in the drawing approach frequencies 0.30, 0.30, 0.36 and 0.04. Marginalizing means adding over an unobserved variable. If you do not care which first token was drawn, the chance that the second is x is 0.30+0.36=0.66. Do not average the two conditional probabilities equally; their prefixes have different probabilities.</p>
<h4>A probability model is not a truth oracle</h4>
<p>The distribution learned from text describes likely token continuations under that model and context. The probability of the token string “yes” is not automatically the probability that an external claim is true. A task-specific scoring rule, calibration data and an evaluation protocol are needed to make that connection. Later <a href="#evaluation-calibration">calibration examples</a> distinguish these quantities explicitly.</p>
${check("After observing that the second token is x, what is the probability that the first was B?", "Use the joint event divided by the marginal: p(B|second=x)=0.36/0.66=6/11, approximately 0.5455. Conditioning changes the relative weights of the possible prefixes.")}
${ref("https://d2l.ai/chapter_preliminaries/probability.html", "Dive into Deep Learning: joint, conditional and marginal probabilities")}
</section>



<section class="lesson" id="likelihood-and-information" data-lesson="Likelihood, entropy and KL divergence">
<header><span>Why this loss?</span><h3>Taking a logarithm turns sequence products into teachable sums</h3></header>
<p>The natural logarithm ln is the inverse of exp, and <code>ln(ab)=ln(a)+ln(b)</code> for positive a and b. A continuation’s probability is a product of conditional token probabilities. Its negative log probability is therefore a sum of token losses. This gives the objective we will apply in <a href="#probability-and-loss">the first training example</a> a statistical interpretation.</p>
<div class="derivation"><h4>Fit the probability of the recorded data</h4><p>For observed targets x₁,…,xT and their prefixes, define <code>L(θ)=−Σₜ ln pθ(xₜ|x&lt;ₜ)</code>. Here θ is the set of learned parameters, and x&lt;ₜ means all earlier tokens. Maximizing the likelihood of this fixed data is equivalent to minimizing L because ln is increasing and the minus sign reverses the objective.</p><p>If three recorded next tokens receive probabilities 0.8, 0.5 and 0.25, their joint conditional probability is 0.1. The total negative log-likelihood is −ln(0.1)≈2.3026 nats. Summing the three token losses gives the same result. Dividing by three gives 0.7675 nats per target and perplexity exp(0.7675)≈2.1544.</p></div>
<p>“Likelihood” uses the probability expression while viewing the recorded data as fixed and the parameters as the variable to be fitted. It is not a probability distribution over θ. Token probabilities may each be moderate while their long product becomes extremely small. Adding log probabilities avoids forming that tiny product, though each log probability still needs a stable implementation.</p>
<h4>Turn arbitrary scores into a probability distribution</h4>
<p>A model can produce any real-valued scores, called logits. Probabilities must instead be nonnegative and sum to one. Softmax supplies that conversion: <code>qᵢ=exp(zᵢ)/Σⱼ exp(zⱼ)</code>, where zᵢ is the score for outcome i and the denominator adds over all outcomes j. Exponentiation makes each value positive; dividing by their total normalizes the sum.</p>
<div class="derivation"><h4>Two scores, two probabilities</h4><p>For scores [0,ln(3)], exponentiation gives [1,3]. Their sum is 4, so softmax returns [1/4,3/4]. If the recorded target is the second outcome, the penalty is −ln(3/4)≈0.2877 nats. Choosing the larger score gives that second outcome deterministically; sampling draws the outcomes with these probabilities. Those are different uses of the same distribution.</p></div>
<h4>Separate uncertainty in the data from mismatch in the model</h4>
<p>For two distributions p and q over the same outcomes, entropy is <code>H(p)=−Σᵢ pᵢ ln pᵢ</code>, cross-entropy is <code>H(p,q)=−Σᵢ pᵢ ln qᵢ</code>, and KL divergence is <code>D_KL(p‖q)=Σᵢ pᵢ ln(pᵢ/qᵢ)</code>. Use the convention 0 ln 0=0 by continuity. If p assigns positive probability where q is zero, the corresponding cross-entropy and KL are infinite.</p>
<p>Substituting the definitions gives <code>H(p,q)=H(p)+D_KL(p‖q)</code>. With p fixed, minimizing cross-entropy minimizes the mismatch term. KL is nonnegative, but it is not a distance metric: reversing its arguments generally changes the value. Here p describes the target distribution and q the candidate model. Later policy objectives can use other directions; read the order rather than treating the two distributions as interchangeable.</p>
<div class="derivation"><h4>Compare a model distribution with the data distribution</h4><p>Let the true two-outcome distribution be p=[0.75,0.25], and compare q=[0.5,0.5]. Then H(p)≈0.5623 nats, H(p,q)=ln 2≈0.6931, and KL≈0.1308. Matching q to p removes that mismatch while leaving the population’s uncertainty intact.</p><p>For one observed target, the empirical target distribution is one-hot: one at the recorded ID, zero elsewhere. Its cross-entropy against q reduces to −ln q(target). An individual example provides this sparse observation even when the population has several reasonable continuations.</p></div>
<p>Changing the tokenizer changes the events and the denominator. Per-token perplexities are therefore not directly comparable across arbitrary tokenizations. A held-out evaluation must also specify its text, context windows, target masks and averaging rule. The <a href="#evaluation-generalization">evaluation lesson</a> develops those contracts.</p>
${check("If q gives the right token probability 0.9 in one case and 0.6 in another, can both have the same top-1 accuracy but different losses?", "Yes. If that token is the top choice in both cases, both predictions are correct by top-1 accuracy. Their losses are −ln(0.9)≈0.1054 and −ln(0.6)≈0.5108. Log loss records how much probability was assigned, not just the winning ID.")}
${ref("https://www.deeplearningbook.org/contents/prob.html", "Goodfellow, Bengio and Courville: entropy and KL divergence")}
${ref("https://d2l.ai/chapter_linear-classification/softmax-regression.html", "Dive into Deep Learning: likelihood and cross-entropy")}
</section>

<section class="lesson" id="chain-rule-and-sharing" data-lesson="The chain rule and shared weights">
<header><span>From local sensitivity to a model gradient</span><h3>Multiply along a dependency; add when dependencies meet</h3></header>
<p>A derivative is the limiting ratio of an output change to a small input change. For f(x)=x², expanding (x+δ)²−x² gives 2xδ+δ². Divide by δ and let δ approach zero to obtain f′(x)=2x. At x=2, the tangent predicts <code>f(2+δ)≈4+4δ</code>. The approximation omits the δ² term, which matters more for larger steps.</p>
<p>A <strong>partial derivative</strong> changes one coordinate while holding the others fixed. For f(x,w)=wx, ∂f/∂x=w and ∂f/∂w=x. The gradient of a scalar function collects its partial derivatives into the same shape as its input. If L depends on many weights, ∇θL is the collection of sensitivities to those weights at the current point.</p>
<p>For y=g(f(x)), the chain rule gives <code>dy/dx = (dy/df)(df/dx)</code>. If x influences y through several intermediates, sum the contribution from each route. Reverse-mode differentiation carries the scalar loss sensitivity backward, reusing local derivatives instead of perturbing every parameter in a separate forward run.</p>
${gradientFork}
<div class="derivation"><h4>Check the branching calculation without backpropagation</h4><p>For y=x²+3x at x=2, forward gives 4+6=10. Backward gives 1×2x from the square branch and 1×3 from the linear branch, totaling 7. Independently, <code>y(2+δ)=10+7δ+δ²</code>. The coefficient of the first-order change is 7, agreeing with the graph.</p><p>If a program overwrites the first contribution when processing the second branch, it returns 3 instead of 7. This is why gradient accumulation at shared inputs is part of correctness, not only a batching optimization.</p></div>
<h4>Backpropagation through a matrix does not require its inverse</h4>
<p>Take Y=XW with X[N,D], W[D,F], and an upstream gradient G[N,F], where G[n,f]=∂L/∂Y[n,f]. Differentiate the indexed expression for Y. A weight W[d,f] influences every row n through X[n,d], so <code>∂L/∂W[d,f]=Σₙ X[n,d]G[n,f]</code>. In matrix notation this is <code>∂L/∂W=XᵀG</code>, with shape [D,F]. Similarly, <code>∂L/∂X=GWᵀ</code>, shape [N,D].</p>
<p>For a broadcast bias b[F], every row uses the same b[f], so <code>∂L/∂b[f]=Σₙ G[n,f]</code>. Backward sums over axes on which forward reused a value. For a mean rather than a sum loss, its denominator is already part of G; do not divide a second time just because there are N rows.</p>
<div class="derivation"><h4>One projection, all three derivatives</h4><p>Let X=[2,−1], W have rows [1,3] and [4,−2], and b=[0,0]. Then Y=[−2,8]. Choose L=Y₁+2Y₂=14, so G=[1,2]. The gradients are <code>dX=[7,0]</code>, <code>dW=[[2,4],[−1,−2]]</code>, and <code>db=[1,2]</code>.</p><p>Increasing W’s second-row, first-column entry by ε changes Y₁ by −ε and L by −ε, confirming its derivative −1. Increasing X’s second coordinate changes Y by [4ε,−2ε], whose loss contributions cancel: 4ε+2(−2ε)=0. A zero gradient can arise from cancellation even when the intermediate values depend on that input.</p></div>
<p>The Jacobian of a vector-valued function contains every output’s derivative with respect to every input. For a scalar loss, backward typically needs only the Jacobian transposed times the upstream gradient, called a vector–Jacobian product under the row-vector convention. It need not materialize the full Jacobian. This keeps differentiation practical for enormous intermediate tensors.</p>
${check("The same embedding row is looked up at three positions, with backward contributions [1,2], [3,4] and [−1,0]. What reaches that parameter row?", "The sum [3,6]. All three lookups used the same learned values. Other embedding rows receive only their own contributions. Any loss averaging is already included in these stated upstream gradients.")}
${ref("https://cs231n.stanford.edu/handouts/derivatives.pdf", "Stanford CS231n: derivatives, Jacobians and backpropagation")}
</section>

<section class="lesson" id="expectation-and-batches" data-lesson="Expectation, variance and minibatches">
<header><span>Learning from samples</span><h3>A batch estimates an average over a larger population</h3></header>
<p>For a discrete random variable X and a numerical function f, the expectation is <code>E[f(X)] = Σₓ p(x)f(x)</code>. It is a probability-weighted average, not necessarily a value that any one sample can take. If a request generates 10 tokens with probability 0.75 and 50 tokens with probability 0.25, its expected length is 20 tokens. No request in this example has length 20.</p>
<p>Variance measures spread around the mean μ=E[X]: <code>Var(X)=E[(X−μ)²]=E[X²]−μ²</code>. Its units are squared units; standard deviation is its square root and has the original units. In the request example, variance is 0.75×(10−20)²+0.25×(50−20)²=300 tokens², and standard deviation is about 17.32 tokens. An average alone hides substantial variation.</p>
<div class="derivation"><h4>What averaging independent samples buys</h4><p>For B independent samples with the same mean μ and variance σ², let <code>X̄=(X₁+…+XB)/B</code>. Then E[X̄]=μ and Var(X̄)=σ²/B. The standard deviation of this estimated mean, called its standard error, is σ/√B. Quadrupling B halves that uncertainty; doubling B does not halve it.</p><p>For the invented lengths, 100 independent requests give standard error √300/√100≈1.73 tokens for their sample mean. This describes the uncertainty in an estimated mean, not a reduction in the variability of individual requests.</p></div>
<h4>The training gradient is also an estimate</h4>
<p>Let ℓ(θ;x) be the loss of example x at parameters θ. The population objective is <code>J(θ)=Eₓ[ℓ(θ;x)]</code>. Under the usual differentiability and expectation-interchange conditions, a uniformly sampled minibatch estimates its gradient with <code>ĝ=(1/B)Σᵦ ∇θℓ(θ;xᵦ)</code>. The hat indicates an estimate. With independent draws from the intended distribution, E[ĝ]=∇θJ: the estimate is unbiased even though individual steps vary.</p>
<p>Parameter sharing means all examples contribute to the same gradient coordinates. If two equally weighted examples produce scalar gradients 3 and −1, the batch mean is 1. A descent update subtracts η×1. Subtracting η×3 and then recomputing the second gradient at the new weight is a different procedure: the second derivative is evaluated at a different parameter value. Gradient accumulation reproduces a larger batch only when its weighting, parameter state and other relevant computation match.</p>
<p>The independence assumption deserves attention. Tokens within a document are correlated. Duplicating a batch four times does not create four times as much independent information. For correlated scalar estimates, <code>Var(X̄) = [Σᵢ Var(Xᵢ) + 2Σ(i&lt;j) Cov(Xᵢ,Xⱼ)]/B²</code>, where Cov measures how two deviations vary together. This is why uncertainty estimates often need to resample documents or tasks, rather than treating every token as independent.</p>
<p>The <a href="#packing-loss">token objective</a> adds one more choice: equal weight per example and equal weight per valid token are different populations. Decide which average you mean before choosing the denominator or combining workers’ local means.</p>
${check("A batch is copied ten times without changing any examples. Has its gradient estimate gained the variance reduction of ten independent batches?", "No. All ten copies have the same gradient. Averaging the copies returns exactly the original estimate. Perfect correlation cancels the variance reduction that independent sampling would provide.")}
${ref("https://d2l.ai/chapter_optimization/minibatch-sgd.html", "Dive into Deep Learning: minibatch gradient estimates")}
</section>
<section class="lesson" id="numerical-reasoning" data-lesson="Finite precision and numerical checks">
<header><span>Equations become finite arithmetic</span><h3>Equivalent real-number formulas can behave differently on a computer</h3></header>
<p>The equations so far use real arithmetic. A stored floating-point value uses a finite significand and exponent. That limits both precision and range. Near large magnitudes, representable values are farther apart, so a small update can round away. A calculation can also exceed the format’s range or lose information when nearly equal quantities are subtracted. The <a href="#c-arithmetic-contracts">C arithmetic lesson</a> and <a href="#mixed-precision">precision chapter</a> develop the concrete formats.</p>
<div class="derivation"><h4>Order matters even for addition</h4><p>Using binary32 arithmetic with rounding after each addition, set a=100,000,000, b=−100,000,000 and c=1. Then (a+b)+c=1. But b+c rounds back to b, and a+(b+c)=0. Real-number associativity would make them equal; finite arithmetic does not.</p><p>A parallel reduction changes the order in which partial sums meet. A difference in low-order bits can therefore be expected without proving a bug. A wrong mask, missing contribution or out-of-bounds read is still a bug; tolerance must not become a way to ignore those errors.</p></div>
<h4>Stable softmax follows from a mathematical invariance</h4>
<p>For any common constant c, <code>exp(zᵢ−c)/Σⱼ exp(zⱼ−c)</code> equals softmax(z) in exact arithmetic because numerator and denominator share the factor exp(−c). Choose c=max(z). The largest exponent is now zero and every other exponent is nonpositive, avoiding positive exponential overflow for finite logits.</p>
<p>For logits [1000,1001], evaluating exp directly may overflow. Subtracting 1001 gives [−1,0], with probabilities approximately [0.2689,0.7311]. For target index 1, compute the loss as <code>ln(exp(−1)+1)≈0.3133</code>. This is an original small example of why rearranging the calculation matters. A production log-softmax computes the normalized log values without first rounding tiny probabilities to zero.</p>
<p>Subtracting the maximum does not make every input meaningful. An entirely masked attention row has no permitted key; replacing all logits with −∞ and subtracting their maximum produces an undefined subtraction. Define and test the empty-row behavior in the operator contract. NaNs and positive infinities also need explicit handling, rather than an assumption that the stable finite-input identity solves every case.</p>
<h4>Test a derivative with an independent calculation</h4>
<p>The centered estimate <code>[L(w+ε)−L(w−ε)]/(2ε)</code> approximates ∂L/∂w for a smooth function. Too large an ε measures nonlocal curvature; too small an ε makes subtraction and rounding dominate. Try several ε values in higher precision, hold data and randomness fixed, and avoid a nondifferentiable point such as the corner of a ReLU when checking a smooth derivative claim.</p>
<p>Compare a candidate result a against a reference r with a rule such as <code>|a−r| ≤ atol + rtol|r|</code>. Absolute tolerance handles values near zero; relative tolerance scales with magnitude. State both tolerances and the reference’s precision. Passing a tiny derivative check is one piece of evidence; edge shapes, masks and accumulation behavior still require their own checks.</p>
${check("Why does relative error alone become unhelpful when the reference is zero?", "Dividing by |r| is undefined at zero and unstable near it. An absolute tolerance expresses the allowed error in the output’s own units. Its value should follow the operation and precision contract, rather than being enlarged until a failing result passes.")}
<p>You now have the tools to read <a href="#tensors">tensor equations and gradients</a> and reconstruct a <a href="#transformer">Transformer block</a>. Keep four habits: label the axes, identify the probability being modeled, trace every gradient contribution, and distinguish a real-number identity from its finite implementation.</p>
${ref("https://www.deeplearningbook.org/contents/numerical.html", "Goodfellow, Bengio and Courville: numerical computation")}
${ref("https://docs.pytorch.org/docs/stable/notes/numerical_accuracy.html", "PyTorch: floating-point accuracy and reduction order")}
<p>Reconstruct the probability, gradient, rotation and rounding examples with the <a href="https://github.com/djsydney04/inference_and_training_systems/tree/main/examples/foundations" target="_blank" rel="noreferrer">standard-library Python companion</a>. Predict each result before running it; the companion includes exercises for changing one assumption at a time.</p>
</section>`);
