import { chapterMarkup, sourceLink as ref, workedCheck as check, escapeCode } from "./lesson-template";
import contractSource from "../examples/tensorflow/numerical_contracts.py?raw";

export const optimizationChapter = chapterMarkup("optimization", "What makes an optimizer update valid?",
  "Before scaling a training run, understand the update itself: its state, normalization, numerical range, schedule, and saved activations.", `
<section class="lesson" id="optimizer-state" data-lesson="SGD, momentum and AdamW">
<header><span>Training methods</span><h3>The gradient is only the beginning of an update</h3></header>
<p>A loss defines what the model should improve. An optimizer defines how parameters move using the gradient and, usually, stored history. Two runs can see exactly the same tokens and gradients yet follow different trajectories because their optimizer state differs. Restoring weights alone does not restore a training run.</p>
<p>Plain SGD uses <code>θₜ = θₜ₋₁ − ηₜgₜ</code>. Here θ is a parameter vector, g is the loss gradient at the current parameters, η is the learning rate, and t counts optimizer updates. The momentum convention used below stores <code>uₜ = μuₜ₋₁ + gₜ</code> and moves by <code>−ηₜuₜ</code>. This is a direction buffer, not a second set of learned parameters. An alternative convention multiplies the new gradient by 1−μ; its learning-rate interpretation differs.</p>
<figure class="textbook-lab method-lab" id="optimizer-lab"><figcaption><span>Interactive 6.1</span><strong>One objective, different update histories</strong><p>Original two-parameter example: L(x,y) = (x² + 12y²)/2. The start is (2,1); the optimum is (0,0). This is not a language-model benchmark.</p></figcaption>
<div class="method-toolbar"><label>Method<select data-optimizer-kind><option value="sgd">SGD</option><option value="momentum">Momentum</option><option value="adamw" selected>AdamW</option></select></label><label>Learning rate<select data-optimizer-rate><option value="0.02">0.02</option><option value="0.08" selected>0.08</option><option value="0.15">0.15</option></select></label><label>Decoupled decay<select data-optimizer-decay><option value="0">0</option><option value="0.1">0.1</option></select></label><button data-optimizer-reset>Reset</button><button data-optimizer-next>Apply one update</button></div>
<div class="method-split"><div data-optimizer-plot></div><div class="method-inspector" data-optimizer-state aria-live="polite"></div></div><details class="method-table"><summary>Read the update history</summary><div data-optimizer-history></div></details><p class="figure-boundary">Deterministic JavaScript arithmetic. Each method uses its stated convention and the same fixed objective. Twenty steps do not establish convergence on a neural network or identify a universally best optimizer. Changing a setting restarts the comparison.</p></figure>
<h4>Adam stores a direction estimate and a scale estimate</h4>
<div class="derivation"><p><code>mₜ = β₁mₜ₋₁ + (1−β₁)gₜ</code><br><code>vₜ = β₂vₜ₋₁ + (1−β₂)gₜ²</code><br><code>m̂ₜ = mₜ/(1−β₁ᵗ), v̂ₜ = vₜ/(1−β₂ᵗ)</code><br><code>θₜ = (1−ηₜλ)θₜ₋₁ − ηₜm̂ₜ/(√v̂ₜ + ε)</code></p><p>The square, square root and division are elementwise. β₁ and β₂ control the moving averages, λ is decoupled decay, and ε protects the denominator. The lab uses β₁=0.9, β₂=0.999 and ε=10⁻⁸, with zero-initialized moments. Bias correction compensates for those initial zeros.</p></div>
${ref("https://arxiv.org/abs/1412.6980", "Adam: moment estimates and bias correction")}
<p>At the first step of our example, the gradient is (2,12). Bias correction gives m̂=(2,12) and v̂=(4,144). Ignoring the tiny ε, both normalized coordinates are 1. With η=0.08 and no decay, the new point is (1.92,0.92). SGD instead reaches (1.84,0.04). This calculation explains the differing first directions; it does not make one trajectory inherently preferable.</p>
<h4>Weight decay is not generally the same as adding L2 to Adam's loss</h4>
<p>A loss penalty <code>λ‖θ‖²/2</code> contributes <code>λθ</code> to g and therefore enters adaptive moment estimates. Decoupled weight decay shrinks θ separately. In this lab, enabling decay changes the parameter update but leaves m and v unchanged at the first step. With θₓ=2, η=0.08 and λ=0.1, the separate shrinkage is 0.016. Frameworks also differ in epsilon placement, parameter exclusions and update ordering: an optimizer name alone is not a complete reproducibility contract.</p>
${ref("https://arxiv.org/abs/1711.05101", "AdamW: decoupled weight decay")}
${check("Worked check: an Adam checkpoint restores θ and m but resets v. Is the next step reproducible?", "No. The denominator depends on the second-moment history and its update counter. Even identical next-batch gradients do not reconstruct the missing state. Include moments, counters, schedules, loss-scale state and the parameter-to-slot mapping in the checkpoint contract.")}
</section>

<section class="lesson" id="clipping-order" data-lesson="Accumulation, clipping and update boundaries"><header><span>Order of operations</span><h3>Clipping is nonlinear, so its position matters</h3></header>
<p>Global-norm clipping limits a complete gradient vector to norm c by multiplying every coordinate by <code>min(1, c/‖g‖₂)</code>. All parameter tensors contribute to that norm; clipping each tensor independently is another operation. A zero gradient stays zero. Clipping bounds this gradient, not necessarily the final Adam parameter displacement after moment normalization and decay.</p>
<figure class="textbook-lab method-lab"><figcaption><span>Figure 6.2</span><strong>Two contributions, two answers</strong><p>Use already-normalized, summed worker contributions a=(8,0), b=(−6,2) and clipping threshold 1.</p></figcaption><div class="contract-comparison"><div><h4>Sum, then clip</h4><code>a+b = (2,2)</code><code>‖a+b‖ = √8</code><strong>(0.7071, 0.7071)</strong></div><div><h4>Clip locally, then sum</h4><code>clip(a) = (1,0)</code><code>clip(b) ≈ (−0.9487,0.3162)</code><strong>(0.0513, 0.3162)</strong></div></div><p class="figure-boundary">Original counterexample, checked in both Node and TensorFlow. The two results differ in direction as well as magnitude. The numbers assume summed contributions, not an averaged reducer.</p></figure>
<p>The correct ordering depends on the declared objective and distributed layout. If the intended operation clips the global gradient, first obtain that global gradient or its equivalent global norm. Parameter shards need an appropriate cross-shard norm reduction. Replicated copies must not be counted repeatedly as though they were disjoint coordinates. A local call named “global norm” only knows the tensors passed to it.</p>
${ref("https://www.tensorflow.org/api_docs/python/tf/clip_by_global_norm", "TensorFlow: global norm and clipping contract")}
<h4>Accumulate at a fixed parameter version</h4><p>All microbatches in an accumulation window must differentiate with respect to the same parameter values. Normalize their loss sums using the same complete-window target count, sum their gradients, and apply one update. Updating between microbatches computes gradients at different points; no arithmetic average can undo that difference. Revisit the <a href="#packing-loss">token objective</a> and <a href="#replica-update">real replica equality test</a> before adding clipping to a distributed loop.</p>
<h4>Choose a schedule clock explicitly</h4><p>A learning-rate schedule can be indexed by updates, consumed targets, or another declared quantity. With variable packing, “1,000 steps” does not uniquely identify a token budget. A token-indexed warmup rises to the peak at a fixed consumed-target count; a cosine segment then falls toward its floor. Warmup is a recipe choice, not a correctness requirement or a universal cure for loss spikes.</p>
<div class="lesson-code"><div><h4>A declared token-count schedule</h4></div><pre><code># T = successfully consumed training targets, W = warmup targets
# N = planned target budget, peak >= floor >= 0, 0 &lt; W &lt; N
if T &lt; W:
    lr = peak * T / W
else:
    progress = min(1.0, (T - W) / (N - W))
    lr = floor + (peak - floor) * (1 + cos(pi * progress)) / 2</code></pre></div>
<p>Specify what a skipped nonfinite update does to both the sample cursor and schedule. One policy can consume the data but not advance the optimizer counter; another can retry the same batch. Both need coordinated behavior across replicas and explicit checkpoint metadata. Silently mixing the counters makes resumed runs difficult to interpret.</p>
</section>

<section class="lesson" id="mixed-precision" data-lesson="FP16, BF16 and loss scaling"><header><span>Numerical methods</span><h3>Range and precision are different resources</h3></header>
<p>A floating-point format spends bits on sign, exponent and significand. More exponent bits extend the range of magnitudes; more significand bits distinguish nearby numbers at a given magnitude. BF16 and FP16 both use 16 bits, but they make different tradeoffs. A dtype name does not specify the accumulation dtype of every matrix instruction or reduction.</p>
<div class="method-table"><table><caption>Binary formats used in this lesson</caption><thead><tr><th scope="col">Format</th><th scope="col">Sign / exponent / fraction bits</th><th scope="col">Spacing above 1</th><th scope="col">Example hazard</th></tr></thead><tbody><tr><th scope="row">FP32</th><td>1 / 8 / 23</td><td>2⁻²³</td><td>Finite precision still changes reduction order</td></tr><tr><th scope="row">FP16</th><td>1 / 5 / 10</td><td>2⁻¹⁰</td><td>100,000 exceeds the finite range</td></tr><tr><th scope="row">BF16</th><td>1 / 8 / 7</td><td>2⁻⁷</td><td>1.001 rounds to 1 in the cast example</td></tr></tbody></table></div>
<p>The companion casts the same FP32 values through both 16-bit formats on CPU. FP16 loses 10⁻⁸ to zero and overflows 100,000; BF16 retains finite nonzero values for those magnitudes but cannot preserve the small difference between 1 and 1.001. These are format demonstrations, not a statement that a complete BF16 trainer can never overflow or lose a small update.</p>
${ref("https://www.tensorflow.org/guide/mixed_precision", "TensorFlow: dtype policies and loss scaling")}
<h4>Store, compute, accumulate and update may use different dtypes</h4><p>Separate the compute copy of weights, saved activations, matrix accumulators, gradients, optimizer moments and update weights in the memory ledger. A higher-precision update representation can retain changes too small to alter a rounded compute copy immediately. This is why “16-bit training” does not imply two bytes per parameter for the complete training state.</p>
${ref("https://arxiv.org/abs/1710.03740", "Mixed Precision Training: update copies and scaling")}
<h4>Loss scaling changes intermediate magnitude, not the intended objective</h4><p>For a positive scale s, differentiating sL gives sg. Unscale before interpreting the gradient norm or applying an ordinary update. Scaling cannot recover information already lost in an unstable forward operation. Dynamic scaling also needs a nonfinite policy: changing only the scale while still applying a corrupt gradient is not protection.</p>
<div class="lesson-code"><div><h4>The current Keras 3 wrapper contract</h4></div><pre><code>inner = tf.keras.optimizers.SGD(learning_rate=0.1)
optimizer = tf.keras.mixed_precision.LossScaleOptimizer(inner)
with tf.GradientTape() as tape:
    loss = objective()
    scaled_loss = optimizer.scale_loss(loss)
scaled_gradients = tape.gradient(scaled_loss, variables)
# This wrapper unscales internally. Do not unscale a second time.
optimizer.apply_gradients(zip(scaled_gradients, variables))</code></pre></div>
<p>The runnable check uses FP32 variables to isolate the wrapper contract. A finite scaled update agrees with the unscaled SGD expectation. An injected infinite gradient leaves the inner optimizer state and weights unchanged. It does not test a low-precision decoder, distributed skip consensus, or accelerator throughput. Older TensorFlow examples may use different wrapper methods; check the installed version.</p>
${ref("https://keras.io/api/optimizers/loss_scale_optimizer/", "Keras 3: scaled gradients and skipped updates")}
${check("Worked check: the loss scale doubles. Should the effective learning rate double?", "No. Unscaling restores the original gradient magnitude before the intended update. A doubled displacement indicates missing or incorrect unscaling, changed clipping behavior, or another change in the computation.")}
</section>

<section class="lesson" id="activation-recomputation" data-lesson="Activation checkpointing and recomputation"><header><span>Training memory</span><h3>Keep boundaries; rebuild selected interiors</h3></header>
<p>Backward needs information from forward. Saving all intermediate tensors costs memory; discarding selected intermediates means recomputing them later. Activation checkpointing is this compute-for-memory tradeoff. It is unrelated to a durable training checkpoint: the former changes a step's temporary tensor lifetimes, while the latter makes a run restartable after failure.</p>
<figure class="textbook-lab method-lab"><figcaption><span>Figure 6.3</span><strong>One recomputed segment</strong><p>Read this as dependencies, not a time-scaled profiler trace.</p></figcaption><ol class="method-flow"><li><strong>Forward</strong><span>Keep the segment input x; produce its output y for downstream work.</span></li><li><strong>Later backward</strong><span>Receive ∂L/∂y from the next segment.</span></li><li><strong>Recompute</strong><span>Run the same segment from x with the same weights and random choices.</span></li><li><strong>Differentiate</strong><span>Use regenerated intermediates to calculate ∂L/∂x and parameter gradients.</span></li><li><strong>Release</strong><span>Discard those local intermediates after their consumers finish.</span></li></ol></figure>
<p>The practical memory saving depends on where checkpoints go, which activations dominate, workspace allocations and concurrent microbatches. The classical rematerialization literature gives schedules for trading storage against extra computation; it does not guarantee a fixed saving for every modern Transformer implementation.</p>
${ref("https://arxiv.org/abs/1604.06174", "Activation recomputation: memory and computation tradeoffs")}
<h4>Randomness and side effects are part of the function</h4><p>If recomputation draws a different dropout mask, it differentiates a different function from the one that produced y. The companion uses a stateless random mask with an explicit seed and compares ordinary versus recomputed outputs and both input/weight gradients. A real training loop should derive seeds from stable operation and step identities; reusing this demonstration's fixed seed for every batch is not a dropout recipe.</p>
<p>Avoid hidden mutations inside the recomputed region. Updating a running statistic or advancing an external cursor twice can violate the program even if tensor shapes still match. Test numerical equivalence before measuring memory, and use the framework's supported randomness/state handling for the model in scope.</p>
${ref("https://www.tensorflow.org/api_docs/python/tf/recompute_grad", "TensorFlow: recompute_grad boundaries")}
<div class="lesson-code"><div><h4>Run all three numerical contracts</h4></div><pre><code>python examples/tensorflow/numerical_contracts.py
python -m unittest discover -s examples/tensorflow -p 'test_numerical_contracts.py' -v</code></pre><details><summary>Read the complete executable example</summary><pre><code>${escapeCode(contractSource)}</code></pre></details></div>
<p>Continue to <a href="#training">distributed training</a> with these invariants in hand. More devices introduce communication and ownership rules; they do not remove the need for a well-defined single update.</p>
</section>`);
