import { sourceLink as ref, workedCheck as check, escapeCode } from "./lesson-template";
import referenceSource from "../examples/moe/moe_reference.py?raw";

const switchPaper = "https://www.jmlr.org/papers/volume23/21-0998/21-0998.pdf";
const gshard = "https://arxiv.org/abs/2006.16668v1";
const megablocks = "https://arxiv.org/abs/2211.15841v1";
const deepseek = "https://arxiv.org/html/2412.19437v2#S2.SS1.SSS2";

export const moeExecutionLessons = `
<section class="lesson" id="moe-route-pack-combine" data-lesson="Route, pack and combine">
<header><span>Execute conditional computation</span><h3>One token can become several expert rows, then one output again</h3></header>
<p class="figure-boundary">Sources checked September 16, 2026 for these three MoE lessons. Paper editions are identified beside their claims. The numerical examples are original CPU arithmetic, not GPU measurements or reproduced training results.</p>
<p>The <a href="#frontier-moe">MoE overview</a> names the stages. Now follow their indices and values. Read the <a href="#math-reading-kit">matrix multiplication lesson</a> first if a token row or matrix shape is unfamiliar. A <strong>router</strong> scores experts; an <strong>expert</strong> transforms a token vector. The system must preserve both the token identity and expert identity through every reorder.</p>
<p>Our original example has T=4 token rows, d=2 channels and E=3 experts. Each expert is a small linear map <code>fₑ(x)=xWₑ</code>. A real expert usually contains an expanded, nonlinear feed-forward network. The example omits attention, shared experts, normalization, biases and the residual addition so the route and combination can be checked by hand.</p>
<div class="method-table"><table><caption>Fixed inputs · row-vector convention</caption><thead><tr><th scope="col">Token t</th><th scope="col">Input xₜ</th><th scope="col">Full router probabilities pₜ</th></tr></thead><tbody><tr><th scope="row">0</th><td>[1, 2]</td><td>[0.6, 0.3, 0.1]</td></tr><tr><th scope="row">1</th><td>[2, 1]</td><td>[0.2, 0.5, 0.3]</td></tr><tr><th scope="row">2</th><td>[−1, 1]</td><td>[0.1, 0.2, 0.7]</td></tr><tr><th scope="row">3</th><td>[1, −1]</td><td>[0.5, 0.4, 0.1]</td></tr></tbody></table></div>
<p>The matrices are <code>W₀=[[1,0],[0,1]]</code>, <code>W₁=[[2,0],[0,1]]</code> and <code>W₂=[[0,1],[1,0]]</code>. Expert 0 preserves the vector, expert 1 doubles its first channel and expert 2 swaps the channels. They are different functions, even though their shapes match.</p>
<p>In this workbench a <strong>token row</strong> means its current two-coordinate hidden vector, not its vocabulary ID. An expert applies a small matrix to that vector. The router probabilities describe which expert functions to use; they are unrelated to the probabilities of vocabulary tokens in the sampling chapter. Follow token 0 through one complete weighted sum before trying the packing and gradient views.</p>
<h4>Declare which scores become mixture weights</h4>
<p>Let the router logits be Z with shape [T,E]. Apply softmax across each row to obtain p. Select k expert IDs Sₜ. In the default example, <code>gₜₑ = pₜₑ / Σⱼ∈Sₜ pₜⱼ</code> for selected experts and zero elsewhere. This is a softmax over the selected logits. Ties select the lower expert ID here; a deployment needs its own defined behavior. The controls can also retain the original full-softmax probabilities, which implements a different function.</p>
<p>For token 0 at k=2, S₀={0,1} and g=(2/3,1/3,0). Expert outputs are [1,2] and [2,2]. Therefore <code>y₀=(2/3)[1,2]+(1/3)[2,2]=[4/3,2]</code>. Keeping the original gates 0.6 and 0.3 instead gives [1.2,1.8]. Renormalization is part of the model definition.</p>
<p>Routing conventions vary. Switch uses a full-softmax top-1 gate. DeepSeek-V3 v2 uses sigmoid affinities and normalizes the selected affinities; selection also involves balancing biases and node constraints. The default workbench is neither architecture's complete router.</p>${ref(switchPaper, "Switch Transformers · JMLR 2022, section 2: gate values and top-1 routing")}${ref(deepseek, "DeepSeek-V3 v2 · February 18, 2025: affinity, selection and normalized gates")}
<figure class="textbook-lab moe-workbench" id="moe-routing-lab"><figcaption><span>Interactive · original arithmetic example</span><strong>Follow selected token rows through expert groups</strong><p>Read left to right: original token, expert work, original output position. The selected token's edges are emphasized. Below the map, packed slots reveal the inverse mapping.</p></figcaption>
<div class="method-toolbar"><label>Experts per token k<select data-moe-k><option>1</option><option selected>2</option><option>3</option></select></label><label>Gate rule<select data-moe-normalize><option value="selected">Normalize selected scores</option><option value="full">Keep full-softmax scores</option></select></label><label>Follow token<select data-moe-token><option>0</option><option>1</option><option>2</option><option>3</option></select></label></div>
<p class="moe-scroll-hint">Scroll the diagram and wide table sideways to follow the complete route.</p><div class="moe-diagram" data-moe-map tabindex="0" role="region" aria-label="Token to expert routing map; scroll horizontally on narrow screens"></div><p class="moe-summary" data-moe-routing-summary aria-live="polite"></p><div class="method-table" data-moe-packed tabindex="0" role="region" aria-label="Packed expert rows and weighted outputs; scroll horizontally if needed"></div>
<p class="figure-boundary">Four input vectors and three linear experts; no capacity limit, network traffic, GPU kernel or timing measurement. All intermediate values are computed by the same typed arithmetic helpers tested against a separate dense reference.</p></figure>
<h4>The inverse operation needs addition</h4>
<p>At k=2 there are eight <strong>assignments</strong>, although there are only four tokens. In expert order the packed token IDs are [0,3,0,1,2,3,1,2], grouped as 2 rows for expert 0, 4 for expert 1 and 2 for expert 2. First expand the selected assignments, then permute these eight rows by expert. The four-to-eight expansion itself is not a permutation.</p>
<p>For each packed slot retain (original token, expert, gate). Run each expert on its own rows; gather results back to their token IDs and <strong>add</strong> the weighted contributions. A scatter that overwrites the previous value loses one expert when k&gt;1. In exact arithmetic any packing order gives the same output; floating-point reduction order can introduce small differences.</p>
<details class="deep-dive"><summary>The dispatch matrix and its transpose explain forward and backward</summary><p>Let D be the [Tk,T] one-hot matrix that copies each token into its packed assignment row. At k=2, each column contains two ones. Let G be a diagonal [Tk,Tk] matrix of gates, and F apply the correct expert to each row. Then <code>Y = Dᵀ G F(DX)</code>. D gathers and duplicates; Dᵀ scatters and sums. The packed layout is sparse metadata in a real implementation; constructing these mostly-zero matrices is just a derivation aid.</p><p>For upstream derivative U=∂L/∂Y, the expert-output derivative is <code>G D U</code>. The expert-input derivatives return through Dᵀ and add at each original token. Gate derivatives require the dot product between that token's U and the corresponding expert output. The discrete selected IDs remain fixed in this local derivative.</p></details>
<p>Grouped matrix multiplication executes many expert matrix products with different row counts. It can reduce scheduling overhead, but it does not turn uneven expert loads into one balanced dense matrix. MegaBlocks formulates expert computation with block-sparse operations to preserve assignments without padding every expert to the largest load.</p>${ref(megablocks, "MegaBlocks v1 · November 2022: block-sparse, dropless expert computation")}
${check("Why is restoring the first four packed outputs insufficient?", "Packed slots are assignments, not token positions. Their token IDs repeat and their expert IDs differ. Multiply each expert result by its matching gate and scatter-add by the saved original token ID; only then do you have four output vectors.")}
</section>

<section class="lesson" id="moe-ownership-capacity" data-lesson="Ownership, skew and capacity">
<header><span>Communication follows selected work</span><h3>A balanced average can hide one overloaded expert</h3></header>
<p>Now place the same computation on two devices. <strong>Ownership</strong> answers where each expert’s weights reside. <strong>Dispatch</strong> moves an assigned input to that owner. <strong>Capacity</strong> limits how many assignments an expert accepts in this routing group. These decisions interact, but they are different: changing placement can preserve a function, while discarding or replacing an expert contribution changes its output.</p>
<p>In <strong>expert parallelism</strong>, different ranks own different expert weights. A rank is a participating process, commonly attached to one accelerator. Here rank 0 starts with tokens 0–1 and rank 1 with tokens 2–3. Initially rank 0 owns experts 0 and 2, and rank 1 owns expert 1. Ownership decides where an already-selected function runs. It does not decide which function the model should select.</p>
<p>Dispatch groups input rows by destination rank, then by expert on that rank. An all-to-all exchange sends each rank's destination partitions to the matching owners. The return exchange reverses those destinations, and the saved token map combines results. Variable split sizes, prefix-sum offsets and completion fences are part of the protocol; tensor-parallel reductions inside an expert are a separate communication axis.</p>${ref(gshard, "GShard v1 · June 2020: conditional computation and distributed expert sharding")}
<p>In the default top-2 example the destination matrix is [[2,2],[2,2]], with source ranks as rows. Its diagonal entries are local work; four off-diagonal assignments cross ranks. For d channels and s bytes/channel, an unpacked assignment carries d×s activation bytes. At d=2 and FP32, one-way remote payload is 4×2×4=32 bytes, and returning equal-width expert outputs adds 32 bytes. These are tiny illustrative payloads; metadata, padding, transport headers and network timing are excluded. Optimized dispatch may share a token's transfer among experts on one destination.</p>
<figure class="textbook-lab moe-workbench" id="moe-capacity-lab"><figcaption><span>Interactive · ownership and admission</span><strong>Change the route distribution, expert capacity and placement</strong><p>Each chip is one token/expert assignment. A crossed-out chip is dropped. Admission follows token order and then choice order, independently of packing.</p></figcaption>
<div class="method-toolbar"><label>Router workload<select data-moe-load><option value="example">Worked probabilities</option><option value="skew">All rows: [0.8, 0.15, 0.05]</option></select></label><label>Top-k<select data-moe-cap-k><option>1</option><option selected>2</option></select></label><label>Capacity per expert<select data-moe-capacity><option value="4">4 · all fit</option><option value="3">3 assignments</option><option value="2" selected>2 assignments</option><option value="1">1 assignment</option><option value="0">0 · no expert work</option></select></label><label>Overflow rule<select data-moe-overflow><option value="keep">Drop; keep original gates</option><option value="renormalize">Drop; renormalize survivors</option></select></label><label>Expert owners [e0,e1,e2]<select data-moe-owners><option value="010">[rank 0, rank 1, rank 0]</option><option value="001">[rank 0, rank 0, rank 1]</option></select></label></div>
<div class="moe-expert-queues" data-moe-queues></div><p class="moe-summary" data-moe-capacity-summary aria-live="polite"></p><div class="method-table" data-moe-traffic tabindex="0" role="region" aria-label="Expert loads, rank traffic and changed outputs; scroll horizontally if needed"></div>
<p class="figure-boundary">Selected-score normalization happens before admission. Dropping and optional survivor renormalization are explicit hypothetical policies. The output is only the expert contribution; a residual connection is not included. Placement changes metadata and traffic, while expert functions stay fixed. This is not a distributed runtime.</p></figure>
<h4>Capacity changes the function when assignments do not fit</h4>
<p>For our top-2 workload the average is Tk/E=8/3 assignments, but the maximum is 4 at expert 1. One commonly used planning convention is <code>C=ceil(c×Tk/E)</code>, where c is a capacity factor and T describes the routing group. Implementations differ in rounding, minimum capacity and grouping; Switch's top-1 formula uses T/E. State the convention before comparing factors.</p>
<p>With C=2, expert 1 admits tokens 0 and 1 and drops its assignments for tokens 2 and 3. Token 2's dropless output [1/3,−5/9] becomes [7/9,−7/9] when original gates survive, or [1,−1] after renormalizing its remaining gate. A dropped assignment is not the same as a dropped token. If all assignments disappear, the expert contribution is zero; any surrounding residual path is a separate operation.</p>
<div class="method-table"><table><caption>Which changes preserve the selected computation?</caption><thead><tr><th scope="col">Action</th><th scope="col">Effect</th></tr></thead><tbody><tr><th scope="row">Repack rows or run the same expert elsewhere</th><td>Preserves the mathematical function when weights, gates and token identity match; floating-point order can vary.</td></tr><tr><th scope="row">Replicate a popular expert</th><td>Can preserve the function if copies are identical. Requires extra weight residency, replica selection and training synchronization where applicable.</td></tr><tr><th scope="row">Drop overflow; renormalize surviving gates</th><td>Removes a contribution and changes other contributions. It needs a declared training/inference quality contract.</td></tr><tr><th scope="row">Send overflow to another expert</th><td>Changes the selected function unless it is an identical replica. A free buffer is not evidence of model equivalence.</td></tr><tr><th scope="row">Preserve all assignments with variable-size work</th><td>Retains the selected function but still needs memory, scheduling and a way to handle the largest expert group.</td></tr></tbody></table></div>
<p>At C=4, changing ownership to [0,0,1] changes the destination matrix to [[3,1],[3,1]]. The total remote assignment count stays four in this particular example, while the number of rows assigned to rank 0 grows from four to six. Aggregate link bytes alone therefore miss a changed compute imbalance. Observe per-expert counts, per-rank work, maximum message size, queueing and exposed communication time.</p>
${check("An expert owns four rows but the others own two each. Can you simply run its last two rows using another expert's weights?", "No. That changes the function and output. You can move or replicate the same weights, change scheduling, or adopt an explicitly trained and evaluated routing policy. The best resource fix depends on residency, interconnect and kernel sizes.")}
</section>

<section class="lesson" id="moe-router-gradients" data-lesson="Train the router and experts">
<header><span>Different paths for different derivatives</span><h3>Gradients follow selected computations; balance needs its own signal</h3></header>
<p>During training, ask how a small change in one number would change the scalar loss. The <strong>upstream derivative</strong> u tells this layer how its output affects the loss. Multiplying an expert result by gate g also multiplies its incoming derivative by g. If two selected experts contribute to the same token, their input derivatives add, just as their forward contributions add. Only after this local rule do we need the matrix notation below.</p>
<p>Use the <a href="#first-weight-update">reverse-mode differentiation lesson</a> if derivatives are new. During one backward pass, hold the chosen expert IDs fixed. For <code>yₜ=Σₑ gₜₑ fₑ(xₜ)</code> and upstream vector uₜ, the expert-output derivative is gₜₑuₜ, while the gate derivative is <code>aₜₑ = uₜ · fₑ(xₜ)</code>. Expert parameters accumulate contributions from every assigned row; token-input derivatives add across that token's selected experts.</p>
<p>For our linear row-vector expert, <code>∂L/∂Wₑ = Σₜ xₜᵀ(gₜₑuₜ)</code> and <code>∂L/∂xₜ|expert = Σₑ gₜₑuₜWₑᵀ</code>. For selected-softmax gates, a selected logit's derivative is <code>∂L/∂zₜₑ = gₜₑ(aₜₑ − Σⱼ∈Sₜ gₜⱼaₜⱼ)</code>; an unselected logit's task derivative is zero under this normalization, away from selection boundaries.</p>
<figure class="textbook-lab moe-workbench" id="moe-gradient-lab"><figcaption><span>Interactive · local derivative</span><strong>Compare the task gradient with a balancing gradient</strong><p>The scalar task objective sums the first output channel over all four tokens, so every upstream vector is [1,0]. Logits are independent inputs in this experiment.</p></figcaption>
<div class="method-toolbar"><label>Top-k<select data-moe-grad-k><option>1</option><option selected>2</option><option>3</option></select></label><label>Gate normalization<select data-moe-grad-normalize><option value="selected">Selected softmax</option><option value="full">Original full softmax</option></select></label><label>Inspect token<select data-moe-grad-token><option>0</option><option>1</option><option>2</option><option>3</option></select></label></div>
<p class="moe-summary" data-moe-grad-summary aria-live="polite"></p><div class="method-table" data-moe-grad-values tabindex="0" role="region" aria-label="Task and auxiliary gradients; scroll horizontally if needed"></div>
<p class="figure-boundary">Dropless linear experts; selection IDs held fixed. The auxiliary panel separately applies the Switch top-1 formula to the full probability matrix, regardless of the task panel's k. Values exclude its coefficient α. These are derivatives of original arithmetic examples, not a training or convergence experiment.</p></figure>
<h4>A top-1 normalization can erase the task gate gradient</h4>
<p>Normalizing one selected score gives g=1. Its selected-softmax derivative becomes 1×(a−a)=0. Retaining the original full-softmax gate is different: changing any logit can alter that selected probability through the denominator. Switch retains that gate, allowing a task-loss gradient through it. Do not transplant the selected-softmax derivative into a different router.</p>
<p>If a real router computes <code>Z=XR</code>, where R has shape [d,E], it also contributes <code>∂L/∂R=Xᵀ∂L/∂Z</code> and <code>∂L/∂X|router=(∂L/∂Z)Rᵀ</code>. Add this router path to the expert-input path. The companion intentionally treats X and Z as independent inputs and documents that boundary. Ordinary backpropagation through selected values does not differentiate the discrete top-k decision; near a tie, changing logits can switch the computation abruptly.</p>
<h4>Hard load and soft probability are different measurements</h4>
<p>Switch's top-1 auxiliary loss is <code>Lbalance=αEΣₑ fₑPₑ</code>. Here fₑ is the fraction of tokens whose winning expert is e, and Pₑ is the mean full-softmax probability of e. The hard fractions are treated as constants for differentiation; gradients flow through P. This supplies a signal involving all router probabilities. Uniform f and P give Lbalance/α=1; this is a reference value, not a quality score or convergence guarantee.</p>${ref(switchPaper, "Switch Transformers · section 2.2, equations 4–6: differentiable P and hard assignment fractions")}
<p>DeepSeek-V3 separates balancing selection biases from the original affinities used in mixture weights. Its report also includes a small sequence-wise auxiliary loss. Changing the selected set or bias-update rule during serving is a policy change, whereas relocating identical expert weights can preserve it. Batch composition, routing precision and capacity decisions can affect which work is selected, so validate those alongside placement.</p>${ref(deepseek, "DeepSeek-V3 v2 · balancing bias, complementary loss and deployment boundaries")}
<details class="deep-dive"><summary>Backward communication and optimizer ownership</summary><p>In a straightforward expert-parallel implementation, send each selected expert the weighted derivative of its output, run that expert's backward pass, and return input derivatives for scatter-add on the token owner. This adds two logical exchanges to the two forward exchanges. Fused kernels and topology can change the concrete transport pattern. Retain route indices, gates and the necessary forward values, or recompute them consistently.</p><p>A gradient for an expert weight is summed over the rows assigned to that expert. If identical experts are replicated over data-parallel groups, their parameter gradients also need the intended replica reduction before an optimizer update. This is separate from exchanging token activations. Sparse activation does not mean the remaining expert weights, optimizer state or checkpoint shards cease to exist.</p></details>
<p>A deployment stores all reachable expert weights somewhere, even though each token activates only k experts. Shared experts, dense attention/router weights and replicated copies add to that budget. Decode may produce small expert groups; prefill can produce larger groups. Choose placement and grouped kernels using the deployed workload, not the active-parameter count alone. Compare quality, exact routing contracts, memory and latency under the same request mix.</p>
<div class="lesson-code"><h4>Run the CPU route, inverse combine and derivative checks</h4><pre><code>python3 examples/moe/moe_reference.py
python3 -m unittest discover -s examples/moe -p 'test_*.py' -v</code></pre></div>
<details class="deep-dive"><summary>Python companion: complete linear-expert reference</summary><p>Python 3.10 or newer, standard library only. The dense reference independently evaluates every expert before masking. Tests use all 24 token permutations and finite differences away from top-k boundaries.</p><pre><code>${escapeCode(referenceSource)}</code></pre></details>
${check("The expert-input gradient is correct, but the real router computes Z=XR. Is the input gradient complete?", "No. Add the router contribution (∂L/∂Z)Rᵀ to the expert-path derivative, and compute the router parameter gradient Xᵀ(∂L/∂Z). The routing choices remain discrete; finite differences must avoid crossing a top-k boundary when checking this local formula.")}
</section>`;
