import {
  chapterMarkup,
  sourceLink as ref,
  workedCheck as check,
  escapeCode,
} from "./lesson-template";
import tensorParallelSource from "../examples/tensorflow/tensor_parallel.py?raw";

export const parallelChapter = chapterMarkup(
  "parallel-training",
  "Partition a computation, not just a parameter count",
  "Tensor shapes, gradient ownership and execution order determine which parallel decomposition is correct. Then memory, kernels and the fabric determine whether it is useful.",
  `
<section class="lesson" id="parallel-axes" data-lesson="Data, model and state partitioning"><header><span>Training methods</span><h3>Ask what each rank owns and what it must reconstruct</h3></header>
<p>Data parallelism gives compatible model replicas different training examples. Tensor parallelism splits operations inside a layer. Pipeline parallelism assigns groups of layers to stages. State sharding partitions persistent model/optimizer storage and materializes what computation needs. These are different answers to different bottlenecks; a single job can use several.</p>
<div class="method-table"><table><caption>Ownership questions before a framework configuration</caption><thead><tr><th scope="col">Method</th><th scope="col">Partition</th><th scope="col">Required boundary</th><th scope="col">Failure to check</th></tr></thead><tbody><tr><th scope="row">Data parallel</th><td>Examples / valid targets</td><td>Combine gradients of the declared global objective</td><td>Unequal token counts; incorrect averaging</td></tr><tr><th scope="row">Tensor parallel</th><td>Layer dimensions</td><td>Reduce or gather intermediates at the correct algebraic point</td><td>Wrong axis; duplicated bias; missing dX sum</td></tr><tr><th scope="row">Pipeline parallel</th><td>Layer groups</td><td>Send activations forward and their gradients backward</td><td>Stale weights; premature activation release</td></tr><tr><th scope="row">State sharding</th><td>Parameters, gradients, optimizer state</td><td>Materialize/reduce shards at their use/update boundaries</td><td>Peak gathered state omitted from memory budget</td></tr></tbody></table></div>
<p>Start with a full-batch correctness reference. Compare outputs, all parameter gradients, input gradients and optimizer updates before adding asynchronous communication. A finite loss is not enough: an omitted sum can produce plausible-looking but wrong updates. The earlier <a href="#replica-update">replica experiment</a> checks a data-parallel update; the next experiment checks tensor partitioning.</p>
${ref("https://docs.nvidia.com/megatron-core/developer-guide/latest/user-guide/parallelism-guide.html", "Megatron Core: supported parallelism strategies (checked September 9, 2026)")}
</section>
<section class="lesson" id="tensor-parallel-mlp" data-lesson="A tensor-parallel MLP, forward and backward"><header><span>Worked algebra</span><h3>Keep the nonlinear hidden channels local; sum the output contributions</h3></header>
<p>Use row-vector convention. Flatten batch and sequence into N token rows, with input <code>X[N,H]</code>, expansion <code>U[H,F]</code>, and down projection <code>D[F,H]</code>. The MLP is <code>Y = GELU(XU + bᵤ)D + b𝒹</code>. Split U's output columns and D's matching input rows across R ranks. Each rank computes distinct hidden channels and contributes a full-shaped partial Y.</p>
<figure class="textbook-lab parallel-mlp"><figcaption><span>Original diagram</span><strong>Two shards of one MLP</strong><p>The two branches consume the same X. They do not independently own complete copies of Y.</p></figcaption><div class="parallel-branches"><div class="parallel-shared"><strong>X [N,H]</strong><span>replicated input</span></div><div class="parallel-local"><div><span>Rank 0</span><code>U₀ [H,F/2]</code><b>↓ local GELU</b><code>A₀ [N,F/2]</code><b>↓ D₀ [F/2,H]</b><code>Z₀ [N,H]</code></div><div><span>Rank 1</span><code>U₁ [H,F/2]</code><b>↓ local GELU</b><code>A₁ [N,F/2]</code><b>↓ D₁ [F/2,H]</b><code>Z₁ [N,H]</code></div></div><div class="parallel-shared"><strong>Y = Z₀ + Z₁ + b𝒹</strong><span>sum partials, add output bias once</span></div></div><p class="figure-boundary">Logical two-way decomposition. A production implementation's communicator, output layout and backward rules must agree with its consumers; this figure is not an NCCL trace.</p></figure>
<h4>Derive the backward boundary</h4><p>Let G be dL/dY and Preᵣ=XUᵣ+bᵤᵣ. Rank r computes <code>dDᵣ=AᵣᵀG</code>, <code>dAᵣ=GDᵣᵀ</code>, and <code>dPreᵣ=dAᵣ ⊙ GELU′(Preᵣ)</code>. Then <code>dUᵣ=XᵀdPreᵣ</code> and the shared input gradient is <code>dX=Σᵣ dPreᵣ Uᵣᵀ</code>. The up-bias gradient is the token-row sum of dPreᵣ.</p>
<p>The hidden-channel weight gradients are distinct shards; do not add them elementwise as though they were replicas. The input-gradient terms refer to the same X and must be summed. The output bias gradient is the token-row sum of G, not R copies of that sum. This is why a communication operator's backward definition matters as much as its forward output.</p>
<div class="derivation"><h4>A nonlinearity is an algebraic boundary</h4><p>If a row split yields partial pre-activations a=−2 and b=3, then ReLU(a+b)=1, but ReLU(a)+ReLU(b)=3. Reducing after the nonlinear transform is not equivalent. The column-split expansion avoids this issue by giving each rank complete values for its own hidden channels.</p></div>
${ref("https://arxiv.org/abs/1909.08053", "Megatron-LM: composing column- and row-parallel projections")}
<h4>Run the single-CPU equivalence experiment</h4><p>The original TensorFlow companion uses deterministic float64 inputs and an eight-channel hidden layer. It compares the monolithic and partitioned outputs, every weight/bias gradient, and independently summed local dX contributions. It deliberately checks the duplicated-bias error. Logical shards execute in one process; there is no measured transport, multi-device overlap or GPU speedup.</p>
<div class="lesson-code"><div><h4>Four shard counts, one mathematical function</h4></div><pre><code>cd examples/tensorflow
python -m unittest test_tensor_parallel -v
python tensor_parallel.py
# Checks R = 1, 2, 4, 8 at absolute tolerance 1e-12.
# Uses float64 only to make this small algebra check precise.</code></pre></div>
<details class="code-disclosure"><summary>Read the complete executable TensorFlow reference</summary><pre><code>${escapeCode(tensorParallelSource)}</code></pre></details>
${check("Worked check: can each rank apply its own output bias before summing?", "Only if the chosen representation deliberately partitions or scales the bias so the sum equals one bias. Adding the same full b to R independent partial outputs gives ΣZᵣ + Rb. The reference instead reduces partials and adds b once.")}
</section>
<section class="lesson" id="pipeline-schedules" data-lesson="Pipeline schedules and activation lifetimes"><header><span>Execution order</span><h3>The same gradients can have different storage lifetimes</h3></header>
<p>A pipeline stage must receive a microbatch's input activation before its forward pass. Its backward pass needs its saved forward state and the next stage's input gradient. Microbatches share one parameter version during the synchronous optimizer step. The schedule decides which ready operation runs, but cannot ignore these dependencies.</p>
<figure class="textbook-lab" id="pipeline-lab"><figcaption><span>Interactive training schedule</span><strong>Follow a microbatch through forward and backward</strong><p>Compare all-forward/all-backward with non-interleaved 1F1B. Each operation costs one hypothetical time unit; no communication delay is included.</p></figcaption><div class="method-toolbar"><label>Schedule<select data-pipe-method><option value="gpipe">GPipe-style flush</option><option value="1f1b">1F1B flush</option></select></label><label>Stages<select data-pipe-stages><option>2</option><option selected>4</option><option>8</option></select></label><label>Microbatches<select data-pipe-microbatches><option>2</option><option>4</option><option selected>8</option><option>16</option></select></label><label>Highlight microbatch<select data-pipe-selected></select></label><button data-pipe-reset>Reset time</button><button data-pipe-next>Advance one tick</button></div><div class="pipeline-clock"><label>Completed time units<input data-pipe-time type="range" min="0" max="22" value="0"></label><output data-pipe-progress></output></div><div data-pipe-chart class="pipeline-chart"></div><div data-pipe-result class="pipeline-result" aria-live="polite"></div><div class="method-table" data-pipe-table></div><p class="figure-boundary">Discrete dependency model, not a profiler capture. Blue is forward, green is backward; the number identifies a microbatch. Saved-state counts are abstract per-microbatch bundles, not bytes. Optimizer time, communication buffers, recomputation and unequal stage costs are excluded.</p></figure>
<h4>Derive the fill and drain cost</h4><p>With P equal stages and M microbatches, the all-forward wave costs M+P−1 units; the reverse wave costs the same. Useful work across the machine is 2MP stage-units, while allocated slots total 2P(M+P−1). The idle fraction is <code>(P−1)/(M+P−1)</code>. For P=4 and M=8, execution takes 22 units, with 27.27% idle slots.</p>
<p>In this model, non-interleaved 1F1B reaches the same ideal elapsed time but can release early microbatches sooner. For P=4, M=8, all-forward/all-backward retains up to eight saved bundles on every stage; 1F1B peaks at four, three, two and one across stages 0–3. Less saved state is useful even when the ideal bubble does not shrink.</p>
${ref("https://arxiv.org/abs/1811.06965", "GPipe: microbatch pipeline training")}
${ref("https://arxiv.org/abs/2104.04473", "Megatron-LM: flush, 1F1B and interleaved schedules")}
<h4>Do not solve a systems problem by silently changing the experiment</h4><p>Increasing M while keeping each microbatch fixed increases the global batch and changes optimizer behavior. Holding the global batch fixed makes each microbatch smaller, potentially reducing GEMM efficiency. Unequal valid-token counts still require the <a href="#packing-loss">global normalization contract</a>. Balance actual stage time and activation memory; equal layer counts do not imply equal work when embeddings, attention lengths or experts differ.</p>
<p>Interleaving assigns multiple layer chunks to a physical rank and can reduce some idle intervals at the cost of more scheduling and communication. Schedules that separate backward-input and backward-weight work expose further choices. These are not implemented in the current lab. A real timeline must include transfers, overlap, optimizer synchronization and any stalls introduced by resource contention.</p>
${check("Worked check: after the last stage finishes one microbatch's backward, may it immediately update its weights?", "Not in the synchronous shared-version contract used here. Other microbatches may still need the old weights or saved state. Accumulate the complete intended gradient and reach the defined update boundary; an asynchronous/versioned algorithm needs a different explicit contract.")}
</section>
<section class="lesson" id="sequence-context-experts" data-lesson="Sequence, context and expert parallelism"><header><span>Beyond dense layers</span><h3>Three partitions that do not mean the same thing</h3></header>
<p>Sequence parallelism in the Megatron-style TP layout shards some tokenwise activations, reducing replicated storage around operations such as normalization and dropout. Context parallelism partitions a long sequence's work across ranks, including attention. For full attention, a query shard still needs information from remote keys and values; the implementation must exchange or stream the required state and preserve positions and masks.</p>
<p>A triangular causal mask also makes naïve equal contiguous chunks unequal in attention work: later queries can see more keys. Partitioning and communication schedules can address that imbalance. “Sequence divided by R” is therefore neither a complete compute model nor proof that attention communication disappeared.</p>
${ref("https://github.com/NVIDIA/Megatron-LM/blob/main/docs/user-guide/features/context_parallel.md", "Megatron Core: context-parallel ownership and communication")}
<p>Expert parallelism assigns different routed expert parameters to ranks. Tokens are dispatched to the selected expert owners, transformed, and returned for weighted combination. With top-k routing, one token can create k expert assignments. An assignment count is not a count of unique tokens, and a popular expert can dominate the critical path even when the average load is small.</p>
<p>Separate routing weights, dispatch metadata, padding/capacity policy and the auxiliary balancing objective. Dropping overflow assignments changes the computation; a dropless implementation preserves assignments but must handle uneven sizes. Tensor, pipeline and expert communication can compete for the same fabric, and expert replication groups need not match the dense layers' data-parallel groups.</p>
${ref("https://docs.nvidia.com/megatron-core/developer-guide/latest/apidocs/core/core.parallel_state.html", "Megatron Core: dense and expert process groups")}
</section>
<section class="lesson" id="rank-grid" data-lesson="Compose rank groups without double counting"><header><span>Systems configuration</span><h3>Write down the rank map before multiplying dimensions</h3></header>
<p>For an explicitly independent dense DP×PP×TP grid with two ranks on each axis, world size is eight. Use <code>rank=(d×PP+p)×TP+t</code>. Tensor groups vary t at fixed d,p; pipeline groups vary p at fixed d,t; data groups vary d at fixed p,t. The following mapping is generated from the same tested helper used by the lesson.</p>
<div class="method-table" data-parallel-groups></div>
<p>This three-axis product is a declared toy layout, not a formula to multiply by every framework flag. Expert groups can reorganize ranks drawn from a dense model's data-parallel dimension. Context/parameter rematerialization and newer runtime layouts add their own group rules. Validate the actual framework's world-size constraints, group membership and checkpoint shard metadata.</p>
<p>Finally map logical ranks to GPUs, nodes and communication domains. Frequent tensor collectives and pipeline point-to-point transfers have different latency sensitivity. Link the partition to <a href="#collectives">tensor ownership on collectives</a> and <a href="#rack">physical rack topology</a>, then benchmark the chosen decomposition on the target machine.</p>
</section>`,
);
