import { sourceLink as ref, workedCheck as check, escapeCode } from "./lesson-template";
import referenceSource from "../examples/quantization/reference.py?raw";

export const quantizationLessons = `
<section class="lesson" id="quantization-codebook" data-lesson="Scales and integer codes"><header><span>Numerical representation</span><h3>Store a code, then reconstruct the number it means</h3></header>
<p class="figure-boundary">Research check for these four lessons: September 16, 2026. Fixed paper versions and operator semantics are cited below. Examples are original CPU calculations, without model-quality or accelerator-performance claims.</p>
<p>Quantization replaces many possible real values with a smaller set of representable values: a <strong>codebook</strong>. In a uniform affine quantizer, adjacent reconstructed values are separated by a positive <strong>scale</strong> s. The integer <strong>zero point</strong> z is the stored code representing real zero. The code itself is not a small floating-point number.</p>
<div class="derivation"><p><code>q = clamp(round_even(x / s) + z, qmin, qmax)</code></p><p><code>x̂ = s(q − z)</code></p><p><code>error = x̂ − x</code></p></div>
<p>The reference rounds to the nearest integer, with exact halfway values going to the even integer. It rounds <code>x/s</code> before adding z. For s=0.5 and z=3, x=0.25 gives <code>round_even(0.5)+3 = 3</code>, reconstructing zero. Rounding <code>0.5+3</code> instead would choose code 4 and a different result. Negative ties follow the same rule: −1.5→−2 and −2.5→−2.</p>
${ref("https://onnx.ai/onnx/operators/onnx__QuantizeLinear.html#quantizelinear-21", "ONNX QuantizeLinear · operator version 21: scales, zero points and rounding")}
<h4>Resolution competes with range</h4>
<p>Three unsigned bits supply codes 0 through 7. With s=0.5 and z=3, the reconstructed range is −1.5 through 2.0. Input 0.6 maps to code 4, then 0.5: error −0.1. Input 3.0 saturates at code 7, then 2.0: error −1.0. The first error comes from rounding; the second includes <strong>clipping</strong>, because the value lies beyond the representable endpoints.</p>
<p>For values inside the endpoints, nearest rounding has absolute error at most s/2 in ideal arithmetic. Enlarging s covers more range but increases that bound. Moving z reallocates codes between negative and positive values without changing their spacing. A quantizer's bit count alone specifies neither its range nor its accuracy.</p>
<figure class="textbook-lab quantization-lab" id="quantization-scale-lab"><figcaption><span>Interactive</span><strong>See what the scale preserves and what it clips</strong><p>The circles connect each original input to its reconstructed value. Change sample frequencies to see how the same quantizer receives a different calibration score.</p></figcaption>
<div class="method-toolbar"><label>Unsigned code width<select data-quant-bits><option value="2">2 bits</option><option value="3" selected>3 bits</option><option value="4">4 bits</option></select></label><label>Scale s<input type="range" min="5" max="100" step="5" value="25" data-quant-scale/><output data-quant-scale-value>0.25 units/code</output></label><label>Zero point z<input type="range" min="0" max="7" step="1" value="3" data-quant-zero/><output data-quant-zero-value>code 3 represents 0</output></label><label>Observed input frequencies<select data-quant-frequency><option value="equal">Each value equally common</option><option value="central" selected>Small values dominate</option><option value="outlier">Outlier dominates</option></select></label></div>
<p class="quant-result" data-quant-result aria-live="polite"></p><div class="quant-chart" data-quant-chart tabindex="0" role="region" aria-label="Quantization codebook diagram; scroll horizontally on narrow screens"></div><div class="method-table" data-quant-values tabindex="0" role="region" aria-label="Quantized sample values and errors"></div>
<p class="figure-boundary">A uniform unsigned integer teaching format, not FP4 or a vendor-specific tensor layout. Arithmetic uses JavaScript numbers. The table reports value error; it does not estimate language-model quality.</p></figure>
${check("Check: an unsigned quantized tensor contains only nonnegative codes. Can it represent negative real values?", "Yes. With a positive zero point, codes below z reconstruct to s(q−z), which is negative. For example, code 1 at s=0.5 and z=3 reconstructs to −1. The stored code and its reconstructed value belong to different numerical spaces.")}
</section>

<section class="lesson" id="grouped-weight-quantization" data-lesson="Quantize a matrix"><header><span>Representation meets linear algebra</span><h3>A scale belongs to a particular group of weights</h3></header>
<p>Use <code>W[out,in]</code> and a column input x, so <code>y=Wx</code>. A per-tensor scale covers every weight. A per-output-channel scale covers one row. A grouped scale covers a run of input columns within a row. To reconstruct any code, a kernel must know which scale owns it; the axis, group size and memory layout are part of the format.</p>
<p>Our grouped reference uses a symmetric <strong>narrow range</strong>: <code>Q=2^(b−1)−1</code>, codes −Q through Q, zero point 0, and <code>s=max|w|/Q</code> within each group. At four bits this uses −7…7; the −8 bit pattern is deliberately unused. An all-zero group gets scale 1. This is an explicit teaching choice, not a definition of every INT4 format.</p>
<h4>Work one group by hand</h4>
<p>At four bits, weights [1,2] share <code>s=2/7</code>. Their scaled values are [3.5,7], so ties-to-even produces codes [4,7] and reconstructed weights [8/7,2]. If the next group is [7,0], its scale is 1. Multiplying every code by the first group's scale would decode that second group incorrectly.</p>
<figure class="textbook-lab quantization-lab" id="quantization-matrix-lab"><figcaption><span>Interactive</span><strong>Follow stored codes all the way to the output vector</strong><p>Compare grouping and bit width first. Then increase the first-channel transform: its weight column is multiplied and the matching input is divided before quantized execution.</p></figcaption>
<div class="method-toolbar"><label>Weight code width<select data-weight-bits><option value="2">2 bits</option><option value="3" selected>3 bits</option><option value="4">4 bits</option><option value="8">8 bits</option></select></label><label>Weights per group<select data-weight-group><option value="1">1 · separate scales</option><option value="2">2 · pairs</option><option value="4" selected>4 · entire row</option></select></label><label>Input x<select data-weight-input><option value="balanced">Balanced inputs</option><option value="first" selected>First input dominates</option><option value="last">Last input dominates</option></select></label><label>First-channel transform<input type="range" min="1" max="8" step="1" value="1" data-weight-factor/><output data-weight-factor-value>1× weight column 1; input 1 ÷ 1</output></label></div>
<p class="quant-result" data-weight-result aria-live="polite"></p><div class="method-table" data-weight-matrix tabindex="0" role="region" aria-label="Weight codes, groups and reconstructed values; scroll horizontally"></div><div class="method-table" data-weight-output tabindex="0" role="region" aria-label="Reference and quantized output vectors"></div>
<p class="figure-boundary">Two output channels and four input channels, no bias. Arithmetic and scales are evaluated in Float64. The byte count models FP32 scale metadata but does not round scales to FP32, pack the browser arrays, or model alignment. Group size 1 can reconstruct each nonzero scalar in ideal arithmetic while spending more space on scales than it saves in codes.</p></figure>
<h4>Count the metadata before claiming a compression ratio</h4>
<p>For a large tensor with four-bit codes, a four-byte scale per 128 weights adds <code>32/128=0.25</code> bits per weight. The average is 4.25 bits, before padding or other metadata. A 4,096×4,096 matrix therefore needs 8 MiB of codes plus 0.5 MiB of scales in this symmetric layout, compared with 32 MiB in BF16. The ratio is about 3.76, not four. Affine zero points, alignment, duplicate layouts and workspace can add storage.</p>
<details class="deep-dive"><summary>Read and run the actual CPU packing reference</summary><p>The Python companion packs two signed INT4 codes per byte, with the earlier code in the low nibble. For codes [−1,2,−7], the bytes are <code>2f 09</code>; the final high nibble is padding. Shape, logical count, scales and group ownership remain separate metadata. Its tests enumerate all 225 pairs of legal narrow-range codes.</p><div class="lesson-code"><h4>Python · numerical and packing reference</h4><pre><code>python3 examples/quantization/reference.py
python3 -m unittest discover -s examples/quantization -p 'test_*.py' -v</code></pre><details><summary>Complete checked companion: reference.py</summary><pre><code>${escapeCode(referenceSource)}</code></pre></details></div></details>
${check("Check: can transposing the packed codes alone produce the correct quantized transpose?", "Only if the consumer also understands the original group ownership and layout. A consumer expecting fresh groups along the transposed contraction axis generally needs a different scale assignment or requantization. Transposing bytes does not recompute scales. The same issue appears in the frontier microscaling lesson.")}
</section>

<section class="lesson" id="calibration-and-output-error" data-lesson="Measure useful error"><header><span>Calibration and activation statistics</span><h3>Preserve the computation, not just the weight histogram</h3></header>
<p><strong>Mean squared error</strong> (MSE) averages squared reconstruction errors. It is a useful local diagnostic, but a layer uses its weights through <code>y=Wx</code>. A small weight error multiplying a large activation can matter more than a larger error multiplying zero. For fixed x and <code>ΔW=Ŵ−W</code>, the exact output difference is <code>Δy=ΔW x</code>.</p>
<div class="method-table"><table><caption>Original counterexample · w=[0.49,1.04], x=[1,0], signed codes −7…7</caption><thead><tr><th scope="col">Scale</th><th scope="col">Reconstructed weights</th><th scope="col">Weight MSE</th><th scope="col">Output squared error</th></tr></thead><tbody><tr><th scope="row">0.50</th><td>[0.50,1.00]</td><td>0.00085</td><td>0.00010</td></tr><tr><th scope="row">0.52</th><td>[0.52,1.04]</td><td>0.00045</td><td>0.00090</td></tr></tbody></table></div>
<p>The second scale has lower weight MSE yet nine times the squared output error for this input. If x changes to [0,1], the second scale is exact at the output. The right error metric depends on the inputs the layer will actually see.</p>
<details class="deep-dive"><summary>Derive activation-weighted error and the role of calibration</summary><p>For one row error e and input second-moment matrix <code>C=E[xxᵀ]</code>, <code>E[(e·x)²]=e C eᵀ</code>. C includes correlations between input channels; replacing it with an identity treats directions as equally important. For a finite calibration matrix X whose columns are input examples, minimizing <code>||(Ŵ−W)X||²_F</code> directly measures layer-output reconstruction on those examples. It still does not prove that a complete autoregressive model will preserve its task behavior.</p><p>Calibration collects representative inputs to choose scales, clipping thresholds or transforms. The CPU test uses 100 observations of 0.25 and one of 3.0. Among symmetric three-bit scales {0.25,0.5,1}, scale 0.25 minimizes sample MSE despite clipping 3.0. Reversing those frequencies makes that choice worse than scale 1. Calibration measures a distribution; it is not an unconditional guarantee.</p></details>
<h4>How GPTQ, AWQ and SmoothQuant use this idea</h4>
<p><strong>GPTQ</strong> quantizes weights while compensating the remaining weights using approximate second-order information from calibration inputs. Its layer reconstruction objective accounts for the input geometry. The cited version uses batched updates and a Cholesky-based formulation to make that process practical. It is more than choosing a scale and independently rounding each weight.</p>
${ref("https://arxiv.org/html/2210.17323v2", "GPTQ · version 2, March 22, 2023 · sections 3–4")}
<p><strong>AWQ</strong> identifies important input channels from activation statistics and searches scaling choices that reduce output error. Increasing selected weight channels and inversely scaling the activations can protect those channels under grouped quantization. The matrix lab exposes that algebra using a user-selected factor; it does not implement AWQ's calibration search or clipping procedure.</p>
${ref("https://arxiv.org/html/2306.00978v6", "AWQ · version 6, April 25, 2026 · section 3.2")}
<p><strong>SmoothQuant</strong> redistributes activation outliers into the weights through an equivalent per-channel transformation before weight-and-activation quantization. In our column-vector convention, for positive diagonal S, <code>Wx=(WS)(S⁻¹x)</code>. The identity is exact before rounding. Once either side is quantized, S changes the errors and the best tradeoff must be measured.</p>
${ref("https://arxiv.org/html/2211.10438v7", "SmoothQuant · version 7, March 29, 2024 · section 3")}
<p>In the matrix lab, select three bits, whole-row groups and the first-dominant input. Increasing its first-channel factor from 1 to 8 changes output MSE from 10.900825 to 0.061825 for this one example. Those are locally checked toy results, not a measured AWQ improvement or a claim that larger scaling always helps. Change the input or grouping and inspect what happens.</p>
<h4>Training with quantization is a separate choice</h4>
<p>Post-training quantization chooses a representation for an already trained model. Quantization-aware training places quantization effects inside training so the parameters can adapt. Since exact rounding has zero derivative almost everywhere, common training recipes use a surrogate gradient, often called a straight-through estimator. Simulated quantization during training does not establish the speed or numerical behavior of the eventual packed kernel.</p>
${ref("https://arxiv.org/html/1712.05877v1", "Jacob et al. · version 1, December 15, 2017 · simulated quantization training")}
${ref("https://arxiv.org/abs/1308.3432v1", "Bengio et al. · straight-through gradient estimator · August 2013")}
${check("Check: does a good calibration loss on short English prompts validate long-context code generation?", "No. Activation magnitudes, correlations and attended positions can differ. Evaluate representative held-out prompts and output tasks, including long contexts, and compare the complete model against its reference. Keep the quantizer settings, model revision and serving implementation fixed while testing the distribution shift.")}
</section>

<section class="lesson" id="quantized-kv-and-execution" data-lesson="KV and kernel precision"><header><span>State and execution</span><h3>Storage precision, multiplication precision and accumulation precision differ</h3></header>
<p>A label such as W4A16 describes a four-bit weight representation and sixteen-bit activations; it does not fully specify the instruction sequence. One implementation may unpack and dequantize weight tiles before floating-point multiplication. Another may use a supported mixed-format matrix instruction. Accumulation and output conversion have their own types. A CPU float calculation using reconstructed weights validates the representation arithmetic, not either device path.</p>
<figure class="textbook-lab method-lab"><figcaption><span>Original schematic</span><strong>Follow the four precision contracts through one weight-only path</strong><p>A possible dequantizing implementation, not a claim about every W4A16 backend.</p></figcaption><ol class="method-flow"><li><strong>Read packed codes and metadata</strong><span>Address the correct group scale and any zero point. Low-bit payload is only part of memory traffic.</span></li><li><strong>Reconstruct a working tile</strong><span>Unpack codes and apply scales in the precision selected by the kernel. Fusion can keep this tile out of global memory.</span></li><li><strong>Multiply and accumulate</strong><span>Use the supported operand format and accumulator type. Reduction length and rounding can change the result.</span></li><li><strong>Apply the epilogue</strong><span>Add bias or other fused operations, then convert or requantize the output under its own scale and rounding contract.</span></li></ol></figure>
<p>For a simple integer dot product, <code>Σ x̂ᵢŵᵢ=sₓs_w Σ(qₓᵢ−zₓ)(q_wᵢ−z_w)</code> when both scales are constant over that sum. Nonzero zero points require the corresponding correction terms or equivalent centered operands. If scales vary by group, form and rescale each group's partial sum before combining it. Pulling one arbitrary scale outside the full sum changes the computation.</p>
<h4>Keys and values inject error through different operations</h4>
<p>For a fixed query, key error first perturbs attention scores: <code>Δa=qΔKᵀ/√d</code>. Softmax then changes which positions receive weight. Value error instead perturbs the vectors being combined. In a one-dimensional example with q=1, K=[0,1] and V=[0,10], the output is about 7.310586. Changing only K to [0,0] gives 5.0. Changing only V to [0,8] leaves the attention probabilities unchanged and gives 5.848469. The companion checks both pathways.</p>
<p><strong>KIVI</strong> studies this distinction and uses different grouping axes: keys share quantization parameters within token groups for a channel; values are quantized within token rows. It also retains a recent residual portion at higher precision. Thus a “two-bit KV cache” is not necessarily every cache byte at two bits: scales, offsets, unfilled groups and the retained portion matter.</p>
${ref("https://arxiv.org/html/2402.02750v2", "KIVI · version 2, July 25, 2024 · sections 3.2–3.3")}
<details class="deep-dive"><summary>Separate direct value error from changed attention weights</summary><p>Write the original attention output as pV. With perturbed probabilities p+Δp and values V+ΔV, the exact difference is <code>Δp·V + p·ΔV + Δp·ΔV</code>. For small score perturbations, <code>Δp ≈ (diag(p)−ppᵀ)Δa</code>. This local approximation helps diagnose errors; it does not bound repeated generation, where later queries and token histories may also change.</p></details>
<p>Measure cache bytes, scale metadata, quantize/dequantize work and end-to-end attention latency at the actual context lengths. Test long-context retrieval and generation quality. Prefill/decode handoff must transfer the cache's scales and layout contract as well as its payload. An exact speculative verifier using a quantized target preserves that target's declared policy; it does not reconstruct the unquantized model's distribution.</p>
<p>Continue with <a href="#frontier-precision">microscaling and frontier low-precision formats</a> for floating-point payloads and directional layouts, and <a href="#speculative-exactness">speculative sampling</a> for the target-policy contract. The integer codebook here is a foundation for reading those systems, not a replacement for their format specifications.</p>
${check("Check: four-bit weight files occupy one quarter the payload bytes of BF16. Must end-to-end inference run four times faster?", "No. Scales and other tensors still consume bytes; kernels add unpacking, scaling, alignment and scheduling costs. The bottleneck may be arithmetic, KV traffic, communication or queuing. Measure a supported packed kernel and the complete serving workload under the same quality and latency requirements.")}
</section>`;
