import { sourceLink as ref, workedCheck as check, escapeCode } from "./lesson-template";

const areal = "https://arxiv.org/html/2505.24298v1";
const nemo = "https://docs.nvidia.com/nemo/rl/0.7.0/guides/async-grpo.html";
const verl = "https://github.com/verl-project/verl/blob/678589299a280fac2c17a8fcc03b8839d49b823c/docs/advance/v1_async_trainer.md";
const ppo = "https://arxiv.org/abs/1707.06347";

/** Appended to the post-training chapter; section numbering belongs to the reader. */
export const rolloutTrainingLessons = `
<section class="lesson" id="rollout-runtime-records" data-lesson="Rollouts become training data">
<header><span>Inference inside training</span><h3>A rollout is a response plus the evidence needed to learn from it</h3></header>
<p>A <strong>policy</strong> is the model's distribution over the next token. An <strong>actor</strong> samples from it, perhaps calling tools between turns. A <strong>rollout</strong> records this interaction. A <strong>learner</strong> uses rewards and token probabilities to update the policy. In reinforcement learning, inference therefore creates the next training batch. The actor needs fast generation and KV storage; the learner needs saved activations, gradients and optimizer state.</p>
<p>If prefill, decode or KV storage are new terms, first follow the <a href="#inference">inference chapter's request lifecycle</a>. Here we connect that serving work to the update it makes possible.</p>
<p>For one prompt, generate a group of responses, score them, compute the chosen algorithm's advantages, and update the learner. An advantage says whether a sampled action should become more or less likely relative to the algorithm's baseline. Preserve the prompt group when the objective compares responses within that group. A queue of arbitrary finished strings is insufficient.</p>
<h4>Why can a reward teach a probability distribution?</h4>
<p>First hold one prompt x fixed and let a complete response y receive a fixed scalar reward R(y). The expected reward is <code>J(θ)=Σᵧ πθ(y|x)R(y)</code>. Using <code>∇πθ=πθ∇log πθ</code> gives <code>∇J=Eᵧ∼πθ[R(y)∇log πθ(y|x)]</code>. The response log probability is a sum of next-token log probabilities, so a sampled response supplies a gradient through the decisions that generated it. This identity assumes the reward function is held fixed during the policy update and differentiation can pass through the sum.</p>
<p>The two-response case makes the signal concrete. Give response A reward 1 and response B reward 0. If p=πθ(A|x), then expected reward is p. With p=σ(z), its derivative with respect to z is <code>p(1−p)</code>, positive whenever 0&lt;p&lt;1. Increasing z increases A's probability. For long answers there are many decisions and usually only a few scores: the difficulty is estimating which changes reliably improve expected reward from a limited sample.</p>
<p>Subtracting a baseline b(x) that does not depend on the sampled response preserves this expectation because <code>E[∇log πθ(y|x)]=∇Σᵧπθ(y|x)=0</code>. The resulting R−b measures whether a response did better than that baseline and can reduce sampling variance. A learned value estimate, a leave-one-out group mean, and a group mean including the response have different estimator details; group normalization is a specified algorithm choice, not an automatic unbiasedness guarantee.</p>
${ref("https://proceedings.neurips.cc/paper_files/paper/1999/hash/464d828b85b0bed98e80ade0a5c43b0f-Abstract.html", "Sutton et al., 1999: policy gradients and expected reward")}
<figure class="architecture-figure rollout-flow"><figcaption><span>Original schematic · two resource pools</span><strong>The response moves forward; a new policy moves back</strong></figcaption>
<div class="architecture-scroll"><svg viewBox="0 0 840 230" role="img" aria-labelledby="rollout-flow-title rollout-flow-desc"><title id="rollout-flow-title">Actor and learner data flow</title><desc id="rollout-flow-desc">A prompt enters the actor's prefill and decode stages. The response, behavior probabilities and version enter a reward service and queue, then the learner performs an update. A published weight snapshot returns to the actor for future requests. KV state belongs to the actor; optimizer state belongs to the learner.</desc><defs><marker id="rollout-arrow" markerWidth="7" markerHeight="7" refX="6" refY="3.5" orient="auto"><path d="M0 0L7 3.5L0 7" fill="none" stroke="currentColor"/></marker></defs><g fill="none" stroke="currentColor" stroke-width="1.4"><rect x="12" y="35" width="242" height="108"/><rect x="302" y="35" width="226" height="108"/><rect x="576" y="35" width="248" height="108"/><path d="M254 82H294M528 82H568" marker-end="url(#rollout-arrow)"/><path d="M700 151V192H132V152" marker-end="url(#rollout-arrow)"/></g><g fill="currentColor" font-size="16"><text x="28" y="64">Actor · snapshot v</text><text x="28" y="91">Prompt → prefill → decode</text><text x="28" y="121" font-size="13">Weights + per-request KV state</text><text x="318" y="64">Reward + ready queue</text><text x="318" y="91">Tokens · logprobs · version</text><text x="318" y="121" font-size="13">Group ID · masks · reward</text><text x="592" y="64">Learner · current policy</text><text x="592" y="91">Forward → backward → update</text><text x="592" y="121" font-size="13">Weights + gradients + optimizer</text><text x="269" y="217" font-size="14">Publish an identified snapshot after a completed update</text></g></svg></div>
<p class="figure-boundary">A logical boundary, not a prescription for GPU counts. Actor/learner separation and <a href="#pd-disaggregation">prefill/decode separation</a> are independent choices: the actor pool can itself contain separate prefill and decode workers.</p></figure>
<div class="method-table"><table><caption>What must survive the trip from actor to learner</caption><thead><tr><th scope="col">Record</th><th scope="col">Why the learner needs it</th></tr></thead><tbody>
<tr><th scope="row">Prompt, generated token IDs and masks</th><td>Reconstruct each action's exact context. Train on the intended response/tool positions, excluding padding and masked observations.</td></tr>
<tr><th scope="row">Behavior log probabilities and versions</th><td>Recover how likely each sampled action was under the distribution that actually produced it. Log probabilities are logarithms of probabilities, stored to avoid products underflowing.</td></tr>
<tr><th scope="row">Sampling and engine configuration</th><td>Temperature, truncation, model/tokenizer revision, precision and logprob convention determine which distribution was sampled and which was reported.</td></tr>
<tr><th scope="row">Group ID, reward and termination cause</th><td>Distinguish success, explicit end-of-sequence, length truncation, tool failure and cancellation; reconstruct the objective's response grouping.</td></tr>
<tr><th scope="row">Queue and update metadata</th><td>Detect duplicates, measure age, and restore pending work without quietly applying a response twice.</td></tr>
</tbody></table></div>
<p>For exact speculative sampling, the verified output follows the target policy's distribution when the algorithm and sampling transforms match its assumptions. Therefore retain the target behavior logprob for each final emitted token; the draft proposal probability is used by the acceptance algorithm and is not the learner's behavior denominator. A greedy or approximate verifier needs its own distribution contract.</p>${ref("https://proceedings.mlr.press/v202/leviathan23a.html", "Leviathan et al., 2023: distribution-preserving speculative sampling")}
<details class="deep-dive"><summary>Why changing weights can invalidate a paused response's cache</summary><p>Keys and values were computed using the old weights. Replacing the weights and continuing with those keys and values generally does not evaluate the new model on the retained prefix. One explicit protocol finishes the response with its immutable snapshot; another retains the tokens, installs a new snapshot and recomputes the prefix cache. The second response spans behavior versions, so preserve probabilities and versions for each segment. Recomputing the prefix does not rewrite the distribution that produced earlier actions.</p><p>AReaL's 2025 system describes interruptible generation with cache reconstruction and decoupled behavior/proximal policies. Its implementation uses SGLang 0.4.6 and Megatron-Core 0.11.0; those are the paper's versions, not installation advice for today's stack.</p>${ref(areal, "AReaL v1, sections 4–6: interruptible rollout, staleness and implementation")}</details>
${check("Can the learner replace recorded behavior logprobs by evaluating today's weights on the same tokens?", "No. That computes today's probability of a past action, not the probability that generated it. Retain the behavior denominator. A separate recomputed policy may be useful for a proximal-policy objective, but the two records have different meanings.")}
</section>

<section class="lesson" id="rollout-pipeline" data-lesson="Overlap generation and learning">
<header><span>Training critical path</span><h3>Overlap can hide waiting, but faster generation eventually fills the queue</h3></header>
<p>In a synchronous loop, finish generation and scoring, train, publish weights, then begin the next batch. Separate pools can overlap generation with the previous batch's update. The price is <strong>policy lag</strong>: a batch may reach the learner after the learner has already changed. Here, lag is the learner version at consumption minus the version that generated the batch.</p>
<figure class="textbook-lab method-lab rollout-workbench" id="rollout-schedule-lab"><figcaption><span>Interactive · deterministic schedule</span><strong>Follow six rollout groups through one actor and one learner</strong><p>Each group costs 1 second of prefill, 6 seconds of decode and 1 second of reward evaluation. Each update costs 4 seconds plus 1 second to publish weights. All durations are invented teaching inputs.</p></figcaption>
<div class="method-toolbar"><label>Allowed version lag<select data-rollout-lag><option value="0">0 · synchronous</option><option value="1" selected>1 · one update behind</option><option value="2">2 updates</option><option value="4">4 updates</option></select></label><label>Decode acceleration<select data-rollout-speed><option value="1" selected>1×</option><option value="2">2×</option><option value="3">3×</option><option value="6">6×</option></select></label><label>Learner compute / group<select data-rollout-train><option value="2">2 seconds</option><option value="4" selected>4 seconds</option><option value="8">8 seconds</option><option value="12">12 seconds</option></select></label></div>
<div class="rollout-readout" data-rollout-result aria-live="polite"></div><div class="architecture-scroll" data-rollout-timeline></div>
<p class="figure-boundary">G0–G5 identify groups; v identifies an actor's frozen policy snapshot. Blue bars generate and score; dark bars update; orange bars publish. White gaps are idle time. The actor snapshots weights at group start. Publication affects future groups and never modifies an active group's snapshot.</p>
<details class="deep-dive"><summary>Read every timestamp and the model's assumptions</summary><div class="method-table" data-rollout-table></div><p>Each group causes exactly one learner update. FIFO admission permits group k only when k − latest published version ≤ the selected lag. Generation/reward share one lane; update/publication share another. This bounds consumption lag without discarding samples. It excludes variable response lengths, group filtering, packing, queue memory, shared network contention, launch overhead and quality changes. Real systems can pause generation during publication or use different snapshot protocols.</p></details></figure>
<h4>Work the default timeline by hand</h4><p>Generation takes G = 8 seconds; update plus publication takes U = 5. Six synchronous groups take <code>6(G + U) = 78 seconds</code>. With one-step overlap, the first update finishes at 13 seconds; five more groups arrive every 8 seconds. Completion is <code>G + U + 5 × max(G,U) = 53 seconds</code>. This comparison keeps two identical dedicated pools in both cases. It does not claim the same result if the synchronous baseline reuses all GPUs for each phase.</p>
<p>Now choose 3× decode acceleration: generation takes <code>1 + 6/3 + 1 = 4 seconds</code>, while U stays 5. The pipeline takes 34 seconds and the learner is the slow stage. Allowing more lag adds older queued data without improving this constant-duration pipeline. Long, uneven responses can change that tradeoff; judge queue rules using the real length distribution.</p>
<details class="deep-dive"><summary>Amdahl's law: why a 3× decoder is not a 3× RL run</summary><p>For a serial critical path, <code>Tnew = Tdecode / s + Tother + Tadded</code>, where s is decode speedup and Tadded includes new exposed costs. In the default single group, decode is 6 of 13 seconds. Tripling decode gives 9 seconds, or <code>13/9 ≈ 1.44×</code>, before added overhead. Under the overlapped schedule, compare complete timelines instead: <code>53/34 ≈ 1.56×</code>. Multiplying the overlap and decoder speedup numbers counts the same saved time more than once.</p><p>Prefill/decode splitting can change prefill time, decode interference, KV transfer and queue wait. Speculation can change decode time, verifier work, draft memory and draft-update cost. Enter their measured net stage times into the schedule; a serving tokens-per-second number alone is insufficient. Keep sampling distribution, reward, evaluation set and training budget comparable, and report wall-clock time to the same held-out quality.</p></details>
<p>The source-pinned verl V1 guide documents separate and colocated async modes, retained partial rollouts, and an experimental mode that lends idle learner resources to rollout. It explicitly excludes combining that switching mode with rollout prefill/decode disaggregation in the inspected revision. Framework features that work separately do not automatically compose.</p>${ref(verl, "verl V1 async trainer · commit 6785892, guide updated August 20, 2026")}
${check("6× faster decode leaves the learner busy and the ready queue growing. What should you measure next?", "Measure learner forward/backward, optimizer, exposed communication and weight publication; compare the lag and queue-size distributions. Rebalance actor and learner capacity if useful. More rollout tokens do not help if they cannot become timely, valid training updates.")}
</section>

<section class="lesson" id="rollout-policy-freshness" data-lesson="Policy lag and probability ratios">
<header><span>Statistical correctness</span><h3>A version number bounds age; it does not bound how much the policy changed</h3></header>
<p>Two updates can be tiny or large. A lag of two therefore says nothing by itself about the probability of a particular action. At a fixed context, let μ be the behavior distribution that generated a token and π be the learner's current distribution. The action ratio is <code>r = π(a | context) / μ(a | context) = exp(log π − log μ)</code>. If the actor chose an action with probability 0.2 and today's policy assigns 0.3, its ratio is 1.5.</p>
<figure class="textbook-lab method-lab rollout-workbench" id="rollout-ratio-lab"><figcaption><span>Interactive · one token at one context</span><strong>Clipping gates an objective contribution, not every probability</strong><p>For a maximized PPO surrogate, compare rA with clip(r, 0.8, 1.2)A and take the smaller value. Training code often minimizes the negative of this quantity.</p></figcaption><div class="method-toolbar"><label>Behavior probability μ<select data-ratio-behavior><option value="0.1">0.1</option><option value="0.2" selected>0.2</option><option value="0.4">0.4</option><option value="0.8">0.8</option></select></label><label>Current probability π<select data-ratio-current><option value="0.1">0.1</option><option value="0.3" selected>0.3</option><option value="0.5">0.5</option><option value="0.8">0.8</option></select></label><label>Advantage A<select data-ratio-advantage><option value="2" selected>+2 · encourage</option><option value="-2">−2 · discourage</option></select></label></div><div class="rollout-readout" data-ratio-result aria-live="polite"></div><p class="figure-boundary">This isolates the clipped surrogate. It is not a complete PPO/GRPO loss: no value loss, reference-policy penalty, masking, sequence aggregation or off-policy state correction is modeled.</p></figure>
<p>At r = 1.5 and A = +2, the two candidates are 3 and 2.4: the contribution is 2.4. For A = −2, they are −3 and −2.4: the contribution is −3. The minimum matters. Simply clamping every ratio and multiplying by A implements a different objective.</p>${ref(ppo, "Schulman et al., PPO: the clipped surrogate objective")}
<p><strong>PPO</strong> means proximal policy optimization: it compares the trainable policy with the policy used as the update's anchor. The advantage and anchor probabilities are treated as fixed data while differentiating the surrogate. When its clipped branch is constant, that particular contribution stops rewarding further movement in the same direction. Other tokens share parameters and can still move its probability. Clipping is therefore not a hard guarantee that every final ratio stays between 0.8 and 1.2.</p>
<div class="lesson-code"><div><h4>One token's surrogate, written as a minimization loss</h4></div><pre><code>${escapeCode(`import math
behavior_logp = math.log(0.2)  # saved when the action was sampled
current_logp = math.log(0.3)   # evaluated by the learner now
advantage, epsilon = 2.0, 0.2
ratio = math.exp(current_logp - behavior_logp)
clipped = min(1 + epsilon, max(1 - epsilon, ratio))
loss = -min(ratio * advantage, clipped * advantage)
assert math.isclose(loss, -2.4)`)}</code></pre></div>
<details class="deep-dive"><summary>Three distributions, support, and why correction is not a guarantee</summary><p>A decoupled objective distinguishes the behavior policy μ, a recent frozen proximal policy πold, and the trainable current policy πθ. At one observed context, <code>πθ/μ = (πold/μ) × (πθ/πold)</code>. The first factor corrects the behavior/proximal mismatch; the second measures the update relative to its proximal anchor. A reference model used for a KL penalty is another role and need not equal any of them.</p><p>Importance sampling at one fixed context requires μ to give nonzero probability wherever the target contribution can be nonzero. Top-k or top-p truncation can remove that support. Ratios of probabilities computed from unmodified logits also need not describe a temperature-modified sampler. Record the precise distribution and algorithm convention. Multiplying token ratios gives a trajectory ratio only with matching histories and a consistent trajectory probability model; products can have extreme variance. Token-level ratios alone do not correct every change in the distribution of visited contexts.</p><p>Clipping or truncating weights trades bias against variance; it does not recover missing actions, repair an incorrect denominator or guarantee convergence. IMPALA's V-trace is an earlier actor/learner correction with its own derivation and truncation behavior. It is useful background, not a drop-in replacement for an LLM's PPO objective.</p>${ref("https://arxiv.org/abs/1802.01561", "IMPALA: distributed actor/learner lag and V-trace correction")}</details>
<h4>Make freshness observable before increasing overlap</h4>
<p>A separate reference penalty can measure distribution change with <strong>Kullback–Leibler divergence</strong>. At one fixed context, <code>KL(π||q)=Σₐπ(a)log[π(a)/q(a)]</code> when q has support wherever π does. It is nonnegative and zero only when the distributions agree on that support, but it is not symmetric. It averages over all actions under π; one sampled token's log ratio may be negative and is not the full KL. State the direction, sampling estimator and coefficient when a policy loss includes this penalty.</p>
<p>Track oldest and newest behavior versions per response, learner version at consumption, token log-ratio quantiles, clipped/rejected fractions, queue residence time and discarded prompt groups. Check differences between training-engine and rollout-engine logprobs on the same version and tokens before attributing everything to age. Changing numerical precision, kernels or sampling transforms can create a mismatch even at version lag zero.</p>
${ref("https://github.com/verl-project/verl/blob/678589299a280fac2c17a8fcc03b8839d49b823c/docs/algo/rollout_corr.md", "verl rollout correction · commit 6785892: engine mismatch, ratios and rejection")}
<p>NeMo RL 0.7.0 documents dedicated async generation resources, generation/target weight versions and age-based filtering. Its example allows a v10 trajectory at learner versions v10 or v11 when maximum age is one, then rejects it at v12. Treat its configuration as version-specific; its recommendation to enable importance correction is not a universal convergence proof.</p>${ref(nemo, "NeMo RL 0.7.0: async GRPO, weight versions and trajectory age")}
<p>Research checked September 16, 2026: <em>Stale but Stable</em> (July 2026, v3) studies a staleness-adaptive clipping interval in an asynchronous Qwen3-30B-A3B setup. Its results support a scoped lesson: sampled probability mismatch contains information that a version counter misses. They do not establish one universally safe lag, clip interval or actor-to-learner GPU ratio.</p>${ref("https://arxiv.org/abs/2607.18722v3", "Yang et al., Stale but Stable · July 24, 2026 revision")}
${check("Both actors report version 20. One uses a different temperature and reports unprocessed logits. Are their logprobs interchangeable?", "No. Equal weight versions do not imply equal sampling distributions or reporting conventions. Establish which probabilities generated the actions, which probabilities the objective expects, and whether the required support and corrections hold.")}
<p class="companion-code-note">Run the dependency-free schedule and probability checks with <code>python3 examples/training-runtime/rollout_schedule.py --self-test</code>. It models clocks and records; it does not train a model or measure a GPU runtime.</p>
</section>`;
