import { chapterMarkup, sourceLink as ref, workedCheck as check } from "./lesson-template";
import { runtimePipeline } from "./notebook-figures";

export const runtimeFoundationsChapter = chapterMarkup(
  "runtime-foundations", "Processes, memory and execution",
  "Connect a numerical program to the operating system and accelerator runtime. Follow addresses, threads, transfers and dependencies before interpreting a performance trace.", `
<section class="lesson" id="processes-and-threads" data-lesson="Programs, processes and threads">
<header><span>From a file to running work</span><h3>A program becomes a process with state and resources</h3></header>
<p>The <a href="#c-compile-run">C chapter</a> explained how source becomes an executable. The executable is a stored description of instructions and initial data. A <strong>process</strong> is a running instance: it has an address space, open resources and at least one thread of execution. Starting the same executable twice usually creates two processes with separate ordinary memory. A variable named weights in each process does not, by its name, refer to shared storage.</p>
<p>A thread carries an instruction position, register state and a stack for its function calls. Threads in one process share its address space, so they can access the same heap allocations. That makes sharing convenient and makes conflicting accesses possible. A CPU core executes instructions; an operating-system scheduler chooses which runnable threads receive processor time. A process can be alive while all its threads are waiting for input, a lock or device completion.</p>
<div class="method-table"><table><caption>The word “worker” needs a concrete owner</caption><thead><tr><th>Object</th><th>What it means here</th><th>Example in a model system</th></tr></thead><tbody><tr><th>Process</th><td>An address space and associated operating-system resources</td><td>A server replica or one distributed training rank</td></tr><tr><th>CPU thread</th><td>An instruction stream scheduled on CPU resources</td><td>A tokenizer worker or numerical library thread</td></tr><tr><th>GPU thread</th><td>A logical invocation in a device kernel</td><td>One lane’s work within a CUDA block</td></tr><tr><th>Request</th><td>An application job with its own state and lifetime</td><td>A prompt, generated tokens and cancellation state</td></tr></tbody></table></div>
<p>These counts need not match. One serving process can handle many requests, use several CPU threads and launch kernels with thousands of logical GPU threads. GPU thread scheduling is part of the device execution model; launching a GPU thread does not create an operating-system thread on the host. A distributed rank is usually associated with a process in common training launchers, but the programming contract should state that mapping explicitly.</p>
<h4>Concurrency introduces an ordering problem</h4>
<p>Concurrency means operations can be in progress over overlapping intervals. Parallelism means some work executes at the same time. Even on one CPU core, two threads can interleave a read–modify–write sequence incorrectly. Suppose a request counter starts at zero. Thread A reads zero; thread B reads zero; A writes one; B writes one. Two completions occurred, but the counter records only one.</p>
<p>A lock can protect that entire read–modify–write operation, or an atomic increment can implement an appropriate indivisible update. An atomic counter alone does not automatically publish every other field in a request. Producer and consumer also need the memory-ordering relationship appropriate to the language and API. In C and C++, an unsynchronized data race on ordinary shared memory can be undefined behavior; the interleaving above illustrates the problem, not a portable outcome to rely on.</p>
<p>The same habit applies to an optimizer: identify who owns a parameter, which updates can access it, and when a reader may observe a completed update. Later <a href="#framework-autodiff-state">framework state</a> and <a href="#collective-contracts">collective</a> lessons make those owners concrete.</p>
${check("Eight threads share one process, while eight ordinary processes each load their own model. Must the two cases have the same host memory footprint?", "No. Threads can share a single model allocation in their common address space. Separate processes can create separate copies unless an explicit sharing or mapping mechanism is used. Allocator overhead, worker state and device allocations must also be counted; a thread count alone does not predict the footprint.")}
${ref("https://pages.cs.wisc.edu/~remzi/OSTEP/cpu-intro.pdf", "Operating Systems: Three Easy Pieces — processes")}
${ref("https://pages.cs.wisc.edu/~remzi/OSTEP/threads-intro.pdf", "Operating Systems: Three Easy Pieces — threads and shared state")}
</section>

<section class="lesson" id="virtual-memory-and-locality" data-lesson="Virtual addresses, pages and locality">
<header><span>An address is part of a translation</span><h3>A pointer does not reveal where its bytes physically live</h3></header>
<p>A pointer in an ordinary user process names a <strong>virtual address</strong>. The operating system and hardware map portions of that address space to physical memory, with permissions. Two processes may use the same numerical virtual address for different physical data. A contiguous virtual array can span physical pages that are far apart. This abstraction supports isolation and flexible allocation while letting a program use a simple sequence of addresses.</p>
<p>For a teaching system with 4 KiB pages, the low 12 address bits select the byte offset within a page because 4 KiB=2¹² bytes. The remaining bits identify a virtual page to be translated. A translation lookaside buffer, or TLB, caches recent address translations. A TLB miss may require a page-table walk; it is different from a data-cache miss, which concerns the requested bytes themselves.</p>
<div class="derivation"><h4>Count pages from an address interval</h4><p>Assume an 8 KiB allocation begins at a page boundary and uses 4 KiB pages. It spans two pages. An 8 KiB range beginning 2 KiB into a page spans three pages: the final 2 KiB of the first, a complete second page, and the first 2 KiB of the third. The payload size is unchanged, but the set of translations touched is larger.</p><p>The general count for a nonempty range of S bytes, page size P and starting page offset o is <code>ceil((o+S)/P)</code>. Here ceil rounds upward, 0≤o&lt;P, and the equation assumes a uniform page size. It describes coverage, not how many page faults or physical allocations must occur.</p></div>
<h4>Keep three kinds of miss separate</h4>
<p>A data-cache miss means the requested data is absent at that cache level and must be fetched from a later level. A TLB miss means an address translation is absent from that translation cache. A <strong>page fault</strong> invokes operating-system handling because the attempted access cannot proceed with the current mapping or permissions. Some faults allocate a first-use page or resolve a copy-on-write mapping; others require storage I/O or terminate an invalid access. A page fault is not synonymous with a disk read.</p>
<p>Locality determines whether caches help. Temporal locality means reusing recently accessed data; spatial locality means accessing nearby data that arrives in the same transfer. Suppose a simplified cache uses aligned 64-byte lines and a row contains 16 FP32 values. If the row begins at a line boundary, loading all 16 consecutive values can use one line. Reading one value from each of 16 distinct uncached lines consumes 1,024 transferred bytes for 64 useful bytes, a 6.25% useful-byte ratio at this boundary. Prefetching, existing cache contents and real transaction sizes change the measurement.</p>
<p>This explains why a tensor’s <a href="#tensor-strides">strides</a> matter even when its shape is unchanged. Traversing a row-major matrix by rows walks adjacent entries. Traversing by columns can jump a row’s worth of bytes between accesses. The best layout depends on which dimensions the operation reuses; a transpose view changes indexing, while a materialized transpose pays a copy to change placement.</p>
<h4>Host and device address spaces need their own contract</h4>
<p>A runtime may present unified virtual addressing or managed allocations across host and device. That does not imply that every byte is equally fast to access, physically resident on both processors, or free of migration. Memory capacity, link bandwidth and access permissions remain real constraints. The cache blocks in <a href="#paged-kv">PagedAttention</a> are also an application-level mapping: do not assume that one KV block equals one operating-system page.</p>
${check("Does a TLB miss prove that a tensor has been swapped to disk?", "No. The translation may already exist in memory and simply be absent from the TLB. A page-table walk can resolve it without a page fault or storage access. Translation misses, data-cache misses and page faults are separate events.")}
${ref("https://pages.cs.wisc.edu/~remzi/OSTEP/vm-intro.pdf", "Operating Systems: Three Easy Pieces — address spaces")}
${ref("https://pages.cs.wisc.edu/~remzi/OSTEP/vm-tlbs.pdf", "Operating Systems: Three Easy Pieces — translation lookaside buffers")}
${ref("https://docs.nvidia.com/cuda/cuda-c-best-practices-guide/index.html#unified-virtual-addressing", "CUDA Best Practices Guide: unified virtual addressing")}
</section>

<section class="lesson" id="device-transfer-lifetimes" data-lesson="Transfers, streams and buffer lifetimes">
<header><span>Making bytes available to a kernel</span><h3>Enqueuing an operation creates work that may still be unfinished</h3></header>
<p>A host application can submit a device operation and continue before the device completes it. There are now at least three relevant events: submission, device execution and completion visible to the next consumer. An asynchronous API shortens how long the host must wait at that call; it does not remove the calculation or make dependent data ready immediately.</p>
<p><strong>Host</strong> names the CPU side running the application; <strong>device</strong> names the accelerator in this example. A runtime is the software layer that allocates device storage, submits commands and exposes completion. A <strong>kernel</strong> is a function or compiled operation submitted for device execution. A <strong>DMA</strong> engine moves bytes between memory regions without the CPU executing a load and store for every copied element; software still establishes addresses, permissions and ordering.</p>
<p>A <strong>stream</strong> describes an ordered sequence of device operations under the runtime’s rules. If a host-to-device copy and its consuming kernel are queued in the same appropriately ordered stream, the kernel waits for that copy. Across streams, record and wait on an event or use the documented dependency mechanism. Different streams allow independent work to be scheduled; they do not guarantee simultaneous execution.</p>
${runtimePipeline}
<h4>Separate the lifetime of the host buffer from the device buffer</h4>
<p>Suppose CPU code prepares input A in host memory, a copy reads it into a device allocation, and a kernel reads that allocation. The host input must remain valid and unmodified until its copy has finished reading. The device input must remain valid and unmodified until the kernel has finished reading. Reusing either too early can corrupt a later result even when every array index is in bounds.</p>
<p>Pinned, or page-locked, host memory prevents its backing pages from being paged out while registered for the relevant use. It supports the host/device transfer paths needed for many asynchronous CUDA copies. It does not mean the allocation lives in GPU HBM. Pinning consumes a constrained host resource and does not, by itself, supply the event ordering or independent device resources required for overlap.</p>
<div class="derivation"><h4>Derive the benefit of double buffering</h4><p>Assume each input copy takes 3 ms, each kernel takes 8 ms, copies run serially on one engine, kernels run serially on another, and the engines can overlap without contention. Four inputs processed serially take <code>4×(3+8)=44 ms</code>.</p><p>With two reusable device buffers and correct dependencies, copy A occupies 0–3 ms and kernel A 3–11 ms. Copy B can occupy 3–6 ms; kernel B follows at 11–19 ms. The buffer for A becomes reusable at 11 ms, allowing copy C at 11–14 ms before kernel C at 19–27 ms. The fourth kernel completes at 35 ms.</p><p>For n inputs under these assumptions, the pipelined time is <code>c+k+(n−1)max(c,k)</code>, with copy duration c and kernel duration k. For n=4 it is 3+8+3×8=35 ms: a 44/35≈1.26× speedup. This is an ideal dependency calculation, not a measured device result.</p></div>
<p>More buffers can absorb variation, but consume memory and do not raise the slowest stage’s sustainable rate. If kernels become faster than copies, transfers become the steady-state limit. If the two stages compete for a shared resource, the no-contention timing model becomes optimistic. The <a href="#framework-benchmark-boundary">framework timing lesson</a> supplies a deeper checked model of submission and completion.</p>
<p>For a measurement, choose its endpoint. Timing only the enqueue call records host submission overhead. Timing a complete request must wait for all relevant work and include any required output transfer. Warmup, compilation and prior queued work need their own stated treatment. An event recorded on an unrelated stream is not evidence that all work has completed.</p>
${check("The kernel was submitted successfully. Can the CPU immediately overwrite the pinned input used by its asynchronous copy?", "Only after the copy has finished reading that host buffer. Successful submission does not establish completion. Use the stream/event completion contract, and separately preserve the device allocation until every consuming operation finishes.")}
${ref("https://docs.nvidia.com/cuda/cuda-c-best-practices-guide/index.html#asynchronous-and-overlapping-transfers-with-computation", "CUDA Best Practices Guide: asynchronous copies and overlap")}
${ref("https://docs.pytorch.org/docs/stable/notes/cuda.html#cuda-streams", "PyTorch: stream ordering and tensor lifetimes")}
</section>

<section class="lesson" id="latency-throughput-and-scaling" data-lesson="Latency, throughput and scaling limits">
<header><span>A budget before a benchmark</span><h3>A faster component helps only the work that depends on it</h3></header>
<p><strong>Latency</strong> is elapsed time for a specified operation or request. <strong>Throughput</strong> is completed work per unit time. A pipeline can improve throughput by processing several inputs at different stages while leaving the latency of the first input unchanged. A batch can amortize a weight read across requests while making a request wait longer before it starts. Name both the work unit and the timing boundary.</p>
<p>Use units to turn capacities into time estimates. If an operation requires F floating-point operations at an attainable compute rate R operations/s, its compute time is at least F/R. If it moves Q bytes across a boundary with attainable bandwidth β bytes/s, its transfer time is at least Q/β. If these costs overlap perfectly and there is enough independent work, an optimistic lower bound is <code>max(F/R,Q/β)</code>. Dependencies, launch overhead, contention and other operations can only add constraints to that model.</p>
<div class="derivation"><h4>Calculate an arithmetic-intensity boundary</h4><p>Consider an invented device capable of 100×10¹² FLOP/s and 2×10¹² bytes/s at the chosen memory boundary. Their ratio is 50 FLOP/byte. An operation with arithmetic intensity <code>I=F/Q=10 FLOP/byte</code> has a bandwidth roof of βI=20×10¹² FLOP/s, below the compute roof. Raising only its peak compute capability cannot lift that bandwidth roof.</p><p>Intensity depends on the boundary. A value reused from registers might count once across HBM and many times across a register interface. Use the same memory boundary for both Q and β; the <a href="#roofline-contract">roofline lesson</a> carries this accounting into GPU kernels.</p></div>
<h4>Derive the limit of speeding up one part</h4>
<p>Normalize an original serial workload’s time to one. Let fraction f belong to the component being improved, and let s be that component’s speedup. If all other work is unchanged and the components are sequential, the new time is <code>(1−f)+f/s</code>. Whole-workload speedup is its reciprocal. This is Amdahl’s law for the stated fixed-work model.</p>
<p>If matrix multiplication consumes 80% of a request and becomes four times faster, the new time is 0.2+0.8/4=0.4, a 2.5× request speedup. Even making that component instantaneous leaves the 20% remainder and caps speedup at 5×. This model should not be applied blindly to overlapping trace intervals: first identify the exposed completion path in <a href="#critical-path">the profiling chapter</a>.</p>
<h4>“More devices” describes two different experiments</h4>
<p><strong>Strong scaling</strong> holds total work fixed while increasing device count p. If one device takes T₁ and p devices take Tₚ, speedup is T₁/Tₚ and parallel efficiency is <code>T₁/(pTₚ)</code>. Splitting a fixed batch can create small local matrix operations and more exposed communication. <strong>Weak scaling</strong> increases total work with device count, commonly holding per-device work fixed. Stable step time in that experiment does not prove that a fixed request became p times faster.</p>
<p>For example, a one-device fixed workload taking 100 ms and a four-device version taking 40 ms achieves 2.5× speedup and 62.5% parallel efficiency. If the four-device experiment instead processes four times the data in 100 ms, it achieves four times the throughput for that larger workload. Report which question was tested before comparing those two results.</p>
<p>Continue with <a href="#gpu-resources">GPU resource limits</a>: capacity determines which work can reside on a device, dependencies determine which work is ready, and the relevant bandwidth or execution rate limits progress. Those are the prerequisites for making sense of occupancy and utilization numbers.</p>
${check("A task spends 10% of its original serial time in tokenization. What is the largest possible whole-task speedup from improving tokenization alone?", "Let f=0.1 and let its component speedup grow without bound. The remaining time approaches 0.9, so whole-task speedup is at most 1/0.9≈1.111× under this fixed-work, sequential model.")}
${ref("https://docs.nvidia.com/cuda/cuda-c-best-practices-guide/index.html#strong-scaling-and-amdahl-s-law", "CUDA Best Practices Guide: strong scaling and Amdahl’s law")}
${ref("https://www2.eecs.berkeley.edu/Pubs/TechRpts/2008/EECS-2008-134.html", "Williams, Waterman and Patterson: the roofline model")}
</section>`);
