import { sourceLink as ref, workedCheck as check, escapeCode } from "./lesson-template";
import traceSource from "../examples/serving-runtime/trace_metrics.py?raw";

const stepper = `<div class="sr-stepper"><strong data-sr-position></strong><button type="button" data-sr-back>Previous</button><button type="button" data-sr-next>Next iteration</button><button type="button" data-sr-reset>Reset</button></div><div data-sr-state aria-live="polite"></div><div class="sr-scroll" data-sr-schedule tabindex="0" aria-label="Full iteration schedule; scroll horizontally if needed"></div><p class="sr-outcome" data-sr-outcome></p>`;
const schedulingCode = `node --experimental-strip-types --input-type=module <<'JS'
import { scheduleRequests } from './src/serving-runtime-math.ts';
const requests = ['A', 'B'].map(id =>
  ({id, prompt: 4, outputs: 6, arrival: 0}));
const config = {budget: 8, chunk: 4, blocks: 4, blockSize: 4,
  reserve: 'growing', priority: 'decode-first'};
const growing = scheduleRequests(requests, config);
console.log(growing.stalled); // true: both need a third block
console.log(growing.states.map(s => [s.cached, s.generated]));
// [[8, 5], [8, 5]]: each still owes one output token
const reserved = scheduleRequests(requests, {...config, reserve: 'maximum'});
console.log(reserved.states.map(s => s.status)); // ['complete', 'complete']
JS`;

export const servingRuntimeLessons = `
<section class="lesson" id="scheduler-iteration" data-lesson="Build a serving iteration">
<header><span>Serving runtime</span><h3>A batch is rebuilt around work that is ready now</h3></header>
<p class="figure-boundary">The four lessons below were checked against primary sources on September 16, 2026. Their simulations use declared workloads; they do not report measured GPU speed.</p>
<p>A server has waiting prompts, partially processed prompts and requests already generating answers. A <strong>scheduler</strong> chooses which of those requests participates in the next model execution. Continuous batching changes that membership at iteration boundaries. It still has to preserve each request's token order, model state and memory ownership. Review <a href="#load-test">latency and batching</a> and <a href="#paged-kv">paged cache ownership</a> before tracing the next example.</p>
<p>For ordinary autoregressive generation, prefill consumes prompt positions. Completing the prompt produces the first output token. A later decode consumes that pending token, appends its KV state, and predicts the next output. A request cannot perform both transitions in this teaching iteration: the next input depends on the previous result. Speculative verification changes that per-iteration contract; it needs the separate <a href="#speculative-state">provisional-state rules</a>.</p>
${ref("https://www.usenix.org/conference/osdi22/presentation/yu", "Orca · OSDI 2022 · iteration-level scheduling")}
<figure class="textbook-lab serving-runtime-lab" id="scheduler-iteration-lab"><figcaption><span>Interactive scheduler trace</span><strong>Make a long prompt share the next iteration</strong><p>A arrives at iteration 0 with 2 prompt and 5 output tokens. B arrives at 1 with 8 and 3. C arrives at 2 with 2 and 2. Output lengths are known only for this finite teaching trace.</p></figcaption>
<div class="sr-controls"><label>Scheduling order<select data-sr-priority><option value="decode-first">Decode first</option><option value="prefill-first">Prefill first</option></select></label><label>New positions / iteration<select data-sr-budget><option>3</option><option selected>6</option><option>12</option></select></label><label>Largest prompt chunk<select data-sr-chunk><option>2</option><option selected>6</option><option>12</option></select></label></div>
${stepper}<p class="figure-boundary">Logical iterations, not a time axis. Four positions per KV block; 16 block credits; no sharing, lookahead, swapping, recomputation, speculation or network. Arrival indices stay fixed when policies change.</p></figure>
<h4>Read one mixed batch</h4><p>With a six-position budget, A's one-token decode leaves at most five positions for B's prompt. With prefill first and a six-position chunk, B can occupy the entire next iteration and A waits. Reducing the maximum chunk to two gives more requests a chance to advance, but introduces more prompt fragments. The controls count newly processed positions; they do not count all previous keys read by attention or predict iteration duration.</p>
<p>Sarathi-Serve analyzes mixing bounded prompt chunks with ongoing decodes. The size tradeoff includes kernel efficiency, repeated reads of earlier cache state and latency objectives. Chunking preserves the causal operation when positions, masks and state are correct; it changes the execution schedule and traffic. A fixed token count is not a universal fixed-time promise.</p>
${ref("https://www.usenix.org/system/files/osdi24-agrawal.pdf", "Sarathi-Serve · OSDI 2024 · chunking and mixed batches")}
${check("At iteration 1, B processes five of its eight prompt tokens. Has it emitted five output tokens?", "No. Those are known input positions. In this ordinary decoder, the first new output is sampled only when the full prompt is processed. A partial prompt needs another prefill chunk before its first output.")}
<details class="deep-dive"><summary>What a production scheduler adds to this trace</summary><p>Work selection also includes maximum active sequences, supported execution shapes, prefix hits, multimodal encoder work, adapters and priorities. A cache block budget and a token budget are different limits. Fairness needs an explicit policy: FIFO within each phase, as used here, is not a guarantee of fair service under arbitrary streams of short or high-priority requests.</p><p>Decode-first can protect established streams while waiting prefills age; prefill-first can delay existing users. Measure both populations, include queue age, and make admission and preemption decisions explicit. A request that leaves a Python list may still have kernels or remote transfers using its buffers. Reuse requires their completion, not just a scheduling decision.</p></details>
</section>

<section class="lesson" id="kv-admission" data-lesson="Admit work that can finish">
<header><span>Memory and progress</span><h3>Fitting now does not guarantee the next token fits</h3></header>
<p>A token budget limits this iteration's work; a KV budget limits state retained across iterations. If a prompt has S positions and the answer emits O tokens, this simple cache holds up to <code>S + O − 1</code> processed positions: the final emitted token is not fed back for another prediction. With B positions per block, a conservative whole-answer reservation is <code>ceil((S + O − 1)/B)</code> blocks. Real output length is unknown in advance; an output limit can supply a conservative bound under this exact decoding contract.</p>
<p>For S=4, O=6 and B=4, one request needs three blocks at its peak. Two such requests fit their initial prompts into two blocks. As both grow to eight cached positions, they occupy all four available blocks. Each still owes one output, and each needs a third block to consume the pending token. Neither can advance under a policy that only allocates and waits.</p>
<figure class="textbook-lab serving-runtime-lab" id="kv-admission-lab"><figcaption><span>Interactive progress and memory model</span><strong>Find the iteration where all cache growth stops</strong><p>Both requests arrive together: four prompt positions and six outputs each. Change the reservation policy or cancel A at a completed-iteration boundary.</p></figcaption>
<div class="sr-controls"><label>Reservation policy<select data-sr-reserve><option value="growing">Grow when needed</option><option value="maximum">Reserve full output limit</option></select></label><label>KV block credits<select data-sr-blocks><option>3</option><option selected>4</option><option>6</option></select></label><label>Cancel request A<select data-sr-cancel><option value="no">Keep both requests</option><option value="yes">Cancel before iteration 6</option></select></label></div>
${stepper}<p class="figure-boundary">Eight scheduled positions per iteration; four-position chunks and blocks. Credits are logical capacity, not physical addresses. Processed-position counts retain history after completion; held blocks measure live reservations. Cancellation occurs after prior execution has completed. The growing policy does not evict or recompute; its stalled state is intentional.</p></figure>
<h4>Three different ways to recover capacity</h4><p><strong>Reserve more conservatively:</strong> holding three credits for A admits it first and makes B wait; A can finish and release its credits. This may leave reserved capacity temporarily unused. <strong>Preempt and rebuild:</strong> release selected cache state and later reconstruct the exact processed prefix from retained tokens, without emitting duplicate output. That repeats work and needs a progress/fairness policy. <strong>Cancel or reject:</strong> stop an attempt under a declared service contract and report it; do not count partial text as a successful answer.</p>
<p>The vLLM 0.22.0 documentation describes recomputation as its V1 default preemption mode and decode-prioritized chunking. Those are implementation details of that version, not behavior reproduced by this model. Its tuning guidance also links cache pressure, active sequence limits and batch-token limits; reducing one limit can alter both capacity and latency.</p>
${ref("https://docs.vllm.ai/en/v0.22.0/configuration/optimization/", "vLLM 0.22.0 · preemption, recomputation and chunked prefill")}
<details class="manual-code-details"><summary>Run the exact cache-progress counterexample · Node 22.13+</summary><pre><code>${escapeCode(schedulingCode)}</code></pre></details>
${check("The client disconnects halfway through a kernel. Can its cache blocks immediately return to the free pool?", "No. Record cancellation, prevent new dependent work, and release buffers after every relevant kernel or transfer has stopped using them. The simulator cancels only at a safe completed-iteration boundary; a live runtime needs device and transport completion handling.")}
<details class="deep-dive"><summary>Prefix sharing, retries and speculative reservations</summary><p>A shared prefix is retained while any valid owner still needs it. Releasing one request does not free blocks retained by another request or prefix-cache policy. Output-limit reservation here assumes no speculative lookahead, beam forks, sliding-window eviction or compressed/recurrent state. Add each mechanism's actual transient allocation and representation before applying this calculation to a real engine.</p><p>A retry is a new attempt with its own deadline and work accounting. If every timeout immediately launches another full request while the original keeps running, offered work increases precisely when capacity is already scarce. Use explicit cancellation acknowledgement, attempt identity, bounded retries and an overall deadline. For a split deployment, follow the <a href="#pd-handoff">handoff ownership contract</a> as well.</p></details>
</section>

<section class="lesson" id="serving-arrival-model" data-lesson="Offer realistic request traffic">
<header><span>Benchmark workload</span><h3>A slow server can make a closed-loop client look quiet</h3></header>
<p>Consider one server requiring an assumed 200 ms per request. It can finish five per second. An open-loop generator that offers a request every 100 ms continues to offer ten per second even when the queue grows. A single closed-loop client waits for completion before sending again; with no think time it offers only five per second in this example. Both tests are valid, but they expose different workloads.</p>
<figure class="textbook-lab serving-runtime-lab" id="arrival-pressure-lab"><figcaption><span>Interactive finite arrival trace</span><strong>Compare eight scheduled arrivals with eight sequential sends</strong><p>The service is deliberately simple so every waiting interval can be calculated. The request count stays eight; the actual arrival times change with the client model.</p></figcaption><div class="sr-controls"><label>Client model<select data-sr-arrival-mode><option value="open">Open loop · fixed arrivals</option><option value="closed">Closed loop · one client</option></select></label><label>Open-loop interval<select data-sr-interval><option>50</option><option selected>100</option><option>250</option></select></label><label>Service / request · ms<select data-sr-service><option>100</option><option selected>200</option><option>400</option></select></label></div><div data-sr-arrivals aria-live="polite"></div></figure>
<h4>Derive the queue</h4><p>For request i, let aᵢ be arrival, sᵢ start and fᵢ finish. With a single FIFO server, <code>sᵢ=max(aᵢ,fᵢ₋₁)</code> and <code>fᵢ=sᵢ+serviceᵢ</code>. Waiting is <code>sᵢ−aᵢ</code>; response latency is <code>fᵢ−aᵢ</code>. Under the default open-loop inputs, request eight arrives at 700 ms, starts at 1,400 ms and completes at 1,600 ms: 700 ms waiting and 900 ms response latency.</p>
<p>If a concurrency semaphore delays client dispatch, record both intended offer time and actual send time. Measuring only from the later send can hide the client's queue. The vLLM 0.22.0 benchmark explicitly notes that combining a concurrency limit with a requested arrival rate can lower the achieved rate. Its finite-rate generator uses a configurable stochastic arrival process; the evenly spaced teaching trace here is not that generator.</p>
${ref("https://docs.vllm.ai/en/v0.22.0/cli/bench/serve/", "vLLM 0.22.0 benchmark · request rate, burstiness and concurrency")}
${check("Both default traces finish all eight requests at 1,600 ms. Does equal aggregate throughput imply equal user latency?", "No. The server is busy for the same total service time, but the open-loop clients arrive sooner and wait. The eighth open-loop response takes 900 ms; the single closed-loop client's eighth response takes 200 ms because it was not offered until 1,400 ms.")}
<details class="deep-dive"><summary>From this trace to a defensible load test</summary><p>Preserve the joint distribution of prompt length, output limit, realized output length, prefix reuse and task type. Include burstiness and long-lived streams. Fix the model revision, quantization, tokenizer, sampling settings, fleet size and quality checks before comparing engines or scheduler policies. Separate cold start, warmup, steady traffic and final drain.</p><p>Little's law relates average in-system requests L, effective arrival rate λ and average residence time W as <code>L=λW</code> under the corresponding stable-flow conditions. It does not turn a mean into p99 or justify a steady-state calculation during indefinitely growing overload. A finite test also needs an explicit treatment of requests still queued when collection ends. Report them as outstanding/censored or drain them under a declared window; never silently remove them.</p>${ref("https://doi.org/10.1287/opre.9.3.383", "Little · 1961 · conditions for L = λW")}<p>Before a GPU run, verify the load generator's own CPU, connection pool and event scheduling. A target arrival rate is a configuration, not proof that the service received that load. Pair client records with server queue, cache, preemption and device traces to locate the delay.</p></details>
</section>

<section class="lesson" id="streaming-metrics" data-lesson="Measure complete delivered answers">
<header><span>Measurement contract</span><h3>Keep token receipts, completion and failures in the same ledger</h3></header>
<p>Start with a timestamped attempt. Record its intended arrival, actual send, token receipts and terminal result. For known token receipt times t₁…tₙ, the individual gaps are <code>tᵢ−tᵢ₋₁</code> and token-receipt TPOT is <code>(tₙ−t₁)/(N−1)</code> for N&gt;1. TTFT uses the declared arrival boundary. Terminal completion can be later than the final token if the protocol still needs to finish.</p>
<p>A and B below both deliver six tokens between 100 and 200 ms, so both have 20 ms TPOT. A spaces them evenly; B pauses for 80 ms before the last one. C produces only one token, so a between-token metric is undefined. D streams two tokens and fails; fast partial output does not make it a completed answer.</p>
<figure class="textbook-lab serving-runtime-lab" id="delivery-metrics-lab"><figcaption><span>Interactive service-objective ledger</span><strong>Count every offered attempt before judging the result</strong><p>A compliant request must complete successfully with TTFT and every token gap within the selected thresholds, plus terminal completion within 300 ms. All four attempts are observed in the fixed one-second window.</p></figcaption><div class="sr-controls"><label>TTFT limit · ms<select data-sr-ttft><option>100</option><option selected>150</option><option>200</option></select></label><label>Largest allowed gap · ms<select data-sr-gap><option>20</option><option selected>40</option><option>100</option></select></label><label>Buffer request B<select data-sr-buffer><option value="no">Original burst and pause</option><option value="yes">Delay first receipt to 180 ms</option></select></label></div><div data-sr-metrics aria-live="polite"></div><p class="figure-boundary">Invented, individually identified token receipts on one client clock. Empty protocol events are excluded. The example is too small for a meaningful population p99 and makes no server-performance claim.</p></figure>
<h4>Goodput and attainment answer different questions</h4><p>The default cohort completes three requests, but only A and C meet the full objective. In its declared one-second observation window, completion throughput is 3 requests/s and compliant-request goodput is 2 requests/s. Attainment is <code>2/4=50%</code> of all offered attempts. Keep failures, cancellations and rejected attempts visible under an explicit policy. For retries, report attempt-level work and logical-user-request outcomes separately.</p>
<p>Buffering B improves its displayed gap while delaying its first token. It does not advance the final token or terminal completion. Research on SLO metrics shows how delivery and incomplete-answer conventions can distort an apparent improvement. Use a combination of response, streaming and completion objectives, and preserve the chosen denominator when comparing systems.</p>
${ref("https://arxiv.org/html/2410.14257v1", "Revisiting SLO and Goodput Metrics in LLM Serving · v1 · metric pitfalls")}
<details class="deep-dive"><summary>HTTP chunks, percentiles and the measurement boundary</summary><p>An HTTP read or SSE event is a transport unit, not a model token. Several tokens can arrive together, an event can contain no text, and text fragments can split a tokenizer unit. If exact token membership is known, bundled tokens share their observed receipt time; their individual server generation times remain unknown. Otherwise report chunk gaps and a trustworthy output-token count separately. Do not infer per-token timing by counting chunks.</p><p>The ledger deliberately computes TPOT from first to last token receipt. Some benchmark implementations use terminal latency minus TTFT instead; a trailing usage event or connection shutdown can then enter the numerator. Both require named boundaries. Keep terminal latency separately visible and compare the same convention across runs.</p><p>A per-request mean TPOT and a pooled percentile of all token gaps are different statistics. Long answers contribute more gaps to the pooled population. Report sample counts, output lengths, percentile convention, failures and censored requests. Never average device-local p99 values and call the result the fleet p99.</p></details>
<details class="manual-code-details"><summary>Run and inspect the CPU trace evaluator · Python 3.10+</summary><pre><code>python3 examples/serving-runtime/trace_metrics.py
python3 -m unittest discover -s examples/serving-runtime -p 'test_*.py' -v</code></pre><pre><code>${escapeCode(traceSource)}</code></pre></details>
${check("A request emits tokens quickly and then fails before completion. Should it enter compliant-request goodput?", "No. It remains an offered failed attempt and contributes its actual resource cost, but not a successful compliant completion. If useful partial output is a separate product objective, define and report that metric separately rather than changing this denominator silently.")}
<p>Now apply the same timestamp and admission contract to <a href="#pd-disaggregation">separate prefill/decode workers</a> and <a href="#speculation-acceptance-depth">speculative verification</a>. Both can move waiting and memory pressure between stages. A faster local kernel helps the service only when it improves the measured critical path under the same quality and load.</p>
</section>`;
