import { escapeCode, sourceLink as ref, workedCheck as check } from "./lesson-template";
import shardedReference from "../examples/sharded-training/reference.py?raw";

const fsdp = "https://docs.pytorch.org/docs/2.14/distributed.fsdp.fully_shard.html";
const zero = "https://arxiv.org/abs/1910.02054";
const tutorial = "https://docs.pytorch.org/tutorials/intermediate/FSDP_tutorial.html";
const dcp = "https://docs.pytorch.org/docs/2.14/distributed.checkpoint.html";

export const shardedTrainingLessons = `
<section class="lesson" id="sharded-state-ownership" data-lesson="Who owns training state?">
<header><span>State sharding</span><h3>Keep one owner for each update, then reconstruct the weights computation needs</h3></header>
<p class="figure-boundary">Sources checked for the following four lessons: September 16, 2026. Framework details cite PyTorch 2.14 or a dated tutorial. The figures model declared tensor payloads and schedules; the companion runs logical ranks on a CPU.</p>
<p>A <strong>rank</strong> is one participating process. In data parallel training, ranks process different examples of the same mathematical model. A <strong>shard</strong> is the subset of a tensor assigned to one owner. Storage ownership does not tell you the shape used by a matrix multiplication: a rank can temporarily assemble complete layer weights while permanently owning only a slice.</p>
<div class="method-table"><table><caption>ZeRO's conceptual stages: retained model state and required exchange</caption><thead><tr><th scope="col">Stage</th><th scope="col">Working weights</th><th scope="col">Reduced gradients</th><th scope="col">Optimizer state</th><th scope="col">Movement</th></tr></thead><tbody>
<tr><th scope="row">0 · ordinary replication</th><td>Full</td><td>Full</td><td>Full</td><td>Combine gradients; each replica applies the same update.</td></tr>
<tr><th scope="row">1</th><td>Full</td><td>Full</td><td>Sharded</td><td>Each owner updates a slice; share updated weight slices.</td></tr>
<tr><th scope="row">2</th><td>Full</td><td>Sharded</td><td>Sharded</td><td>Reduce gradients to their owners; share updated weight slices.</td></tr>
<tr><th scope="row">3</th><td>Sharded</td><td>Sharded</td><td>Sharded</td><td>Gather needed weights, reduce gradients to owners, update locally.</td></tr>
</tbody></table></div>${ref(zero, "Rajbhandari et al., ZeRO: partitioning optimizer, gradient and parameter state")}
<p>In an <strong>all-gather</strong>, every participant contributes its slice and receives the assembled tensor. In a <strong>reduce-scatter</strong>, corresponding entries are combined across participants and each participant receives only its assigned output slice. Resharding an already assembled parameter can simply release the temporary full buffer; freeing a buffer is not another network collective.</p>
<p>For example, rank 0 owns weights [1,2] and rank 1 owns [3,4]. An all-gather gives both ranks [1,2,3,4]. Suppose their full gradient contributions are [1,2,3,4] and [10,20,30,40]. A SUM reduce-scatter forms [11,22,33,44] conceptually, returning [11,22] to rank 0 and [33,44] to rank 1. The full summed vector need not actually be stored anywhere. Gathering joins different coordinates; reducing combines contributions to the same coordinates. Neither operation decides the loss denominator.</p>
<h4>Follow one FSDP2 group through a complete update</h4>
<ol><li><strong>Before forward:</strong> gather the group's parameter shards. Each rank runs the group on its own examples.</li><li><strong>After forward:</strong> if configured to reshard, release complete weights while keeping the activations backward needs.</li><li><strong>Before backward:</strong> gather weights again if they were released. Compute local gradients from that rank's examples.</li><li><strong>After backward:</strong> release full weights, reduce-scatter gradients, and retain the reduced shard.</li><li><strong>Optimizer:</strong> each owner updates its original parameter shard and associated optimizer state. A future gather assembles the updated model.</li></ol>
<p>PyTorch 2.14's FSDP2 uses <code>fully_shard</code> and per-parameter DTensors. Its default <code>reshard_after_forward=None</code> resolves differently for root and non-root groups. Set the intended policy explicitly when studying the lifetime. <code>False</code> retains weights across forward/backward but still permits sharding outside computation; it is not identical to permanently replicated ZeRO-2 weights.</p>${ref(fsdp, "PyTorch 2.14 FSDP2: parameter lifecycle and reshard_after_forward")}
<p><strong>FSDP</strong> expands to fully sharded data parallelism. A <strong>DTensor</strong> represents a logical distributed tensor together with its process mesh and placement; the local process stores its assigned part. A module group is a set of parameters gathered together for use. The root is the outer model module; non-root groups belong to selected submodules. These software objects implement the ownership and lifetime rules above.</p>
${check("Rank 0 owns half a layer. Does its forward multiply necessarily use only half the layer's weights?", "No. Fully sharded data parallelism reconstructs that layer's complete weights for the rank's local examples. Tensor parallelism instead partitions the layer's computation. They can compose, but they are different ownership contracts.")}
</section>

<section class="lesson" id="fsdp-live-memory" data-lesson="Memory through a step">
<header><span>Persistent and temporary allocations</span><h3>The model-state total is a floor; the largest live set decides whether a step fits</h3></header>
<p><strong>Persistent state</strong> survives from one update to the next. <strong>Transient state</strong> exists only while a phase needs it. Peak memory is the largest sum of allocations alive at the same instant. Adding each allocation's separate maximum can overcount mutually exclusive buffers; counting only the storage left after a step misses gathered weights and full gradients.</p>
<figure class="textbook-lab method-lab sharded-workbench" id="sharded-memory-lab"><figcaption><span>Interactive · declared tensor payloads</span><strong>Inspect the bytes alive at every forward, backward and reduction boundary</strong><p>Four equal groups, each with 33,554,432 parameters. Original weights and Adam's two moments use FP32; gathered compute weights use BF16; gradients use FP32. Each group's saved activations use 32 MiB. Adam state is already initialized.</p></figcaption>
<div class="method-toolbar"><label>Data-parallel ranks<select data-sharded-ranks><option value="2">2</option><option value="4" selected>4</option><option value="8">8</option><option value="16">16</option></select></label><label>After forward<select data-sharded-reshard><option value="yes" selected>Release full weights</option><option value="no">Retain full weights</option></select></label><label>Prefetch<select data-sharded-prefetch><option value="no" selected>None</option><option value="yes">One future group</option></select></label></div>
<div class="sharded-readout" data-sharded-summary aria-live="polite"></div><div class="architecture-scroll" data-sharded-memory-chart></div>
<div class="sharded-phase-control"><label>Inspect phase <input type="range" min="0" max="15" step="1" value="6" data-sharded-phase></label><output data-sharded-phase-name></output></div>
<div class="sharded-readout" data-sharded-phase-result aria-live="polite"></div><div class="method-table" data-sharded-ledger></div>
<p class="figure-boundary">The horizontal axis is phase order, not elapsed time. A full gradient is counted before its group's saved activations and gathered weights are released; reduce-scatter input and output coexist. This explicit ordering is a teaching model, not a measured FSDP allocation trace. It excludes padding, allocator fragmentation, cast/copy buffers, collective workspaces, non-parameter buffers and optimizer temporaries.</p></figure>
<h4>Reconcile the default peak</h4><p>There are 134,217,728 parameters in total. On four ranks, FP32 original shards occupy 128 MiB and two FP32 moment shards occupy 256 MiB: <strong>384 MiB persists</strong>. At the first backward boundary, add 64 MiB of gathered weights, 128 MiB of full gradients and 128 MiB of saved activations. The declared peak is <strong>704 MiB</strong>. Prefetching one more weight group raises it to 768 MiB. Retaining all gathered weights across forward/backward instead raises this model's peak to 896 MiB.</p>
<p>This byte recipe differs from the earlier <a href="#training-state">classic mixed-precision state ledger</a>. Here the original FP32 parameter shard itself is the optimizer's weight storage; do not add another FP32 master copy. FSDP2's mixed-precision API separates the dtype of gathered compute weights from the original parameter dtype and gradient-reduction dtype. Different dtypes require a fresh ledger.</p>${ref(fsdp + "#torch.distributed.fsdp.MixedPrecisionPolicy", "PyTorch 2.14: original parameter storage, compute dtype and reduction dtype")}
<details class="deep-dive"><summary>Why grouping and gradient accumulation change the peak</summary><p>A single enormous communication group can require almost the whole model to materialize at once. Many small groups reduce the largest working set but increase launch count and may shorten the compute available to hide communication. Shared parameters and repeated module calls complicate release order. Disabling gradient synchronization for accumulation can retain unsharded gradient storage until a later backward; the workbench assumes a synchronized reduction for every group in one step.</p><p>FSDP2 creates communication groups bottom-up: apply <code>fully_shard</code> to desired submodules before the root. The tutorial distinguishes implicit and explicit prefetch and warns that fetching more groups ahead increases memory. Inspect the actual CUDA stream and allocation trace when selecting boundaries.</p>${ref(tutorial, "PyTorch FSDP2 tutorial: grouping, mixed precision and prefetch (checked September 16, 2026)")}</details>
<figure class="textbook-lab method-lab sharded-workbench" id="sharded-prefetch-lab"><figcaption><span>Interactive · invented milliseconds</span><strong>Move the next gather under useful computation</strong><p>Four sequential forward groups. One communication lane performs all-gathers; one compute lane performs forward work. A group cannot compute until its gather finishes.</p></figcaption><div class="method-toolbar"><label>All-gather / group<select data-prefetch-gather><option value="1">1 ms</option><option value="2" selected>2 ms</option><option value="6">6 ms</option></select></label><label>Compute / group<select data-prefetch-compute><option value="2">2 ms</option><option value="4" selected>4 ms</option><option value="8">8 ms</option></select></label><label>Schedule<select data-prefetch-enabled><option value="yes" selected>Prefetch one group</option><option value="no">Gather then compute</option></select></label></div><div class="sharded-readout" data-prefetch-result aria-live="polite"></div><div class="architecture-scroll" data-prefetch-chart></div><p class="figure-boundary">Independent fixed-rate lanes and identical groups, without bandwidth contention or CPU launch delay. The first gather remains exposed. This timeline isolates forward prefetch; it is not the time axis of the separate full-step memory diagram.</p></figure>
<p>At 2 ms per gather and 4 ms per computation, serialized work takes 24 ms. One-group prefetch takes 18 ms: the initial 2 ms gather remains visible, while the next three gathers fit under computation. If communication takes 6 ms, the prefetched pass takes 28 ms and exposes 12 ms of waiting. A faster link or a larger compute group changes the tradeoff; scheduling cannot hide more communication than the dependency graph allows.</p>
${check("Doubling data-parallel ranks halves persistent shards. Must it halve peak memory?", "No. A complete gathered group, its full local gradient and local activations do not automatically shrink. In the same local-batch configuration, those transient terms can become the dominant floor. Measure the peak and account for any changed grouping or overlap.")}
</section>

<section class="lesson" id="sharded-optimizer-update" data-lesson="Work a sharded update">
<header><span>Collective semantics and arithmetic</span><h3>Reduce contributions to the same coordinate, then update each coordinate once</h3></header>
<p>Take four weights <code>w = [1, 2, 3, 4]</code> and four examples whose input vectors are the four identity rows, with target zero. The objective is <code>L = Σ(x·w − y)² / (2N)</code>, N = 4. Its gradient is <code>[0.25, 0.5, 0.75, 1]</code>. Give rank 0 the first example and rank 1 the remaining three.</p>
<figure class="textbook-lab method-lab sharded-workbench" id="sharded-update-lab"><figcaption><span>Interactive · four-coordinate update</span><strong>Separate data contributions from optimizer ownership</strong><p>The same two data partitions contribute gradient sums. Change the number of logical update owners to repartition the reduced vector. This isolates reduce/scatter algebra; a real process group's contributors and recipients follow its collective contract.</p></figcaption><div class="method-toolbar"><label>Update owners<select data-update-owners><option value="1">1</option><option value="2" selected>2</option><option value="4">4</option></select></label><label>SGD learning rate<select data-update-rate><option value="0.01">0.01</option><option value="0.1" selected>0.1</option><option value="0.5">0.5</option></select></label></div><div class="architecture-scroll" data-update-chart></div><div class="sharded-readout" data-update-result aria-live="polite"></div><div class="method-table" data-update-table></div><p class="figure-boundary">The chart uses plain SGD so each subtraction is visible. The CPU companion additionally verifies AdamW weights, moments and bias-correction step across 1, 2 and 4 logical ranks.</p></figure>
<p>Rank 0's local gradient <em>sum</em> is [1,0,0,0]; rank 1's is [0,2,3,4]. Sum corresponding entries and divide once by four. Averaging local <em>means</em> instead gives [0.5, 1/3, 0.5, 2/3], because a rank with one example gets the same total weight as a rank with three. For language modeling, replace the example count by the objective's valid-token count when using token-mean loss.</p>
<p>A reduce-scatter with SUM does not silently normalize by examples. If a framework additionally divides by world size, arrange loss scaling and that division to realize the desired global objective exactly once. The optimizer-owner slice is determined by parameter coordinates, not by which rank supplied the largest gradient.</p>${ref("https://docs.pytorch.org/docs/2.14/distributed.html#torch.distributed.reduce_scatter_tensor", "PyTorch 2.14: reduce_scatter_tensor input/output and reduction semantics")}
<details class="deep-dive"><summary>Carry AdamW's moments along with the parameter shard</summary><p>Each owner also stores first moment m and second moment v for its coordinates. With step t, update <code>m ← β₁m + (1−β₁)g</code> and <code>v ← β₂v + (1−β₂)g²</code>; then use <code>m̂ = m/(1−β₁ᵗ)</code> and <code>v̂ = v/(1−β₂ᵗ)</code>. AdamW applies <code>w ← w(1−ηλ) − ηm̂/(sqrt(v̂)+ε)</code>. The per-coordinate rule needs the correctly reduced gradient, not remote coordinates' moments.</p><p>For w = 1, g = 0.25, zero moments, t = 1, β₁ = 0.9, β₂ = 0.99, η = 0.1, λ = 0.1 and ε = 0.01: m = 0.025, v = 0.000625, m̂ = 0.25 and v̂ = 0.0625. The new weight is <code>0.99 − 0.025/0.26 ≈ 0.893846154</code>. These deliberately visible hyperparameters are not a recommended training recipe.</p>${ref("https://docs.pytorch.org/docs/2.14/generated/torch.optim.AdamW.html", "PyTorch 2.14 AdamW: moments, bias correction and decoupled decay")}</details>
${check("Can each shard independently clip its gradient norm to the same threshold and reproduce clipping the whole model?", "Generally no. The global norm combines squared values from all owned coordinates before deriving one scale factor. Two shards each below the threshold can exceed it jointly. Per-coordinate optimizer ownership does not make global statistics local.")}
</section>

<section class="lesson" id="sharded-checkpoint-reshard" data-lesson="Restore on another mesh">
<header><span>Recovery and placement</span><h3>A checkpoint identifies the logical tensor; a rank number only identifies its current placement</h3></header>
<p>Suppose a four-coordinate tensor was saved as rank 0's [0,2) slice and rank 1's [2,4) slice. Restoring on four ranks assigns [0,1), [1,2), [2,3) and [3,4). The values and optimizer moments must follow their logical coordinates. Renaming two files to look like four rank files cannot perform that transformation.</p>
<p>The interval [a,b) includes index a and excludes index b. Thus [0,2) contains coordinates 0 and 1. The same notation appears in the update-owner table. A <strong>mesh</strong> arranges participating ranks along named parallel dimensions; changing the mesh changes placement, while the global tensor's name, shape and values should retain their meaning.</p>
<div class="method-table"><table><caption>State needed to reconstruct the next update</caption><thead><tr><th scope="col">Saved identity</th><th scope="col">What it preserves</th></tr></thead><tbody><tr><th scope="row">Tensor name, global shape, dtype and chunk offsets</th><td>Which logical coordinates each stored payload contains, independent of current rank number.</td></tr><tr><th scope="row">Parameters, moments and optimizer step</th><td>The numerical state and Adam bias correction that determine the next update.</td></tr><tr><th scope="row">Data position, RNG and training configuration</th><td>The next data and stochastic operations; loading weights alone does not replay the run.</td></tr><tr><th scope="row">Complete checkpoint metadata and version</th><td>A committed recovery point rather than a mixture of shards from different steps.</td></tr></tbody></table></div>
<p>PyTorch 2.14 Distributed Checkpoint supports load-time resharding into preallocated target state and distributed tensor/optimizer state APIs. That capability does not guarantee compatibility across arbitrary PyTorch versions, renamed tensors or changed optimizer schemas. Preserve software/configuration identity and test the next update after restoration.</p>${ref(dcp, "PyTorch 2.14 Distributed Checkpoint: resharding, target storage and compatibility boundaries")}
<h4>Run an independent CPU correctness experiment</h4><p>The reference trains a tiny linear model with uneven data partitions, saves after two updates, reconstructs four owner shards and continues. Tests compare weights and both Adam moments against uninterrupted training, independently check gradients using finite differences, and reject missing or overlapping checkpoint chunks. Small actual buffer payloads also verify the declared FP32/16-bit byte arithmetic.</p>
<div class="lesson-code"><div><h4>Python · run the reference and its correctness tests</h4></div><pre><code>python3 -m unittest discover -s examples/sharded-training -p 'test_*.py' -v
python3 examples/sharded-training/reference.py</code></pre></div>
<details class="lesson-code"><summary>Python · complete CPU sharding and recovery reference</summary><pre><code>${escapeCode(shardedReference)}</code></pre></details>
<p>This program reconstructs tiny full vectors in one CPU process to make the equivalence easy to check. It executes no FSDP hooks, process group, network collective or GPU kernel. At production scale, a checkpoint planner can read only the necessary intersections of saved chunks and destination shards; materializing every tensor on every rank can itself exceed memory. Changing a reduction order or device topology can also change floating-point rounding, so logical equivalence need not imply bitwise-identical long training trajectories.</p>
${check("A resumed run has identical weights but zero Adam moments and a reset step counter. Is it the same next update?", "No. The next update depends on accumulated first/second moments and their bias-correction step. The companion deliberately resets them and confirms that the next parameters diverge. A successful file load is only the beginning of a recovery check.")}
</section>`;
