import { sourceLink as ref, workedCheck as check, escapeCode } from "./lesson-template";

const treeExample = `node --experimental-strip-types --input-type=module <<'JS'
import { draftTreeLayout, committedTreeSlots }
  from "./src/speculation-frontier-math.ts";
// Flat storage: A, B, C, D, E, F, G. null points to prefix P.
const parents = [null, null, 0, 0, 1, 2, 4];
const tree = draftTreeLayout(parents, 4);
console.log(tree.positions);             // [4,4,5,5,5,6,6]
console.log(tree.mask[5]);               // F sees A,C,F
console.log(committedTreeSlots(parents, 4, 5)); // [4,6,9]
// A length alone cannot identify those interleaved cache entries.
JS
node --experimental-strip-types --test tests/speculation-frontier.test.ts`;

export const speculationFrontierLessons = `
<section class="lesson" id="modern-speculative-drafters" data-lesson="Modern drafters"><header><span>Research to implementation · checked September 16, 2026</span><h3>The frontier changes how proposals are produced</h3></header>
<p class="figure-boundary">Research check for the four lessons below: September 16, 2026. Paper versions and dated technical announcements are identified at each claim; this atlas has not benchmarked these drafters on a GPU.</p>
<p>A <strong>drafter</strong> cheaply proposes future tokens. A <strong>verifier</strong> evaluates those proposals with the target model and decides what may be emitted. Keep these two jobs separate as you read new methods: a better proposal changes the amount of useful work per target pass; the verifier determines the output contract. Start with <a href="#speculative-exactness">the acceptance and repair identity</a> if that distinction is unfamiliar.</p>
<h4>EAGLE-3: reuse the target's internal context</h4>
<p>EAGLE-3 combines hidden vectors from several target layers and predicts draft tokens with a small decoder. Later draft steps reuse the drafter's own state because the target has not evaluated those positions yet. It removes the earlier feature-regression constraint and learns direct token prediction. Candidate branches use the dynamic tree approach introduced by EAGLE-2. The paper's March 2025 design is the reference here; a serving engine still needs compatible feature extraction and weights.</p>
${ref("https://arxiv.org/html/2503.01840v1", "EAGLE-3 · sections 3.1–3.2 · March 2025")}
<h4>EAGLE 3.1: make repeated draft steps more stable</h4>
<p>The EAGLE, vLLM and TorchSpec teams' May 26, 2026 technical announcement describes normalization before feature fusion and feedback of post-normalization hidden states. These changes address instability as draft depth grows, including sensitivity to context length and prompt formatting. This is a documented implementation development, with author-reported evaluations; the atlas has not reproduced its performance. The concrete engineering question is whether the selected checkpoint and serving implementation agree on those normalization and feedback conventions.</p>
${ref("https://vllm-project.github.io/2026/05/26/eagle-3-1.html", "EAGLE 3.1 · joint technical announcement · May 26, 2026")}
<h4>Native multi-token prediction: train useful extra prediction modules</h4>
<p><strong>MTP</strong> means multi-token prediction. DeepSeek-V3 trains additional sequential modules: each combines an earlier representation with the next token's embedding, then predicts one position farther ahead. Its embedding and output head are shared with the main model. The auxiliary losses can improve the main model during training; the additional modules can later be discarded or used for speculation. “MTP” does not imply that every future token is predicted independently in one operation. Read the exact architecture before deciding its draft schedule.</p>
${ref("https://arxiv.org/html/2412.19437v2#S2.SS2", "DeepSeek-V3 · section 2.2: sequential MTP and inference reuse")}
<h4>DFlash: predict a block in one draft pass</h4>
<p>The February 2026 DFlash paper uses a small block diffusion drafter conditioned on target hidden features. It fills masked positions in parallel, with those features supplied through key/value projections. The target remains autoregressive and verifies the proposed continuation. One draft pass can still involve several layers and substantial work; “parallel” describes dependencies, not zero latency. Compare total draft and verification time, including the cost of extracting and retaining target features.</p>
${ref("https://arxiv.org/html/2602.06036v1", "DFlash · sections 4.1–4.2 · February 2026")}
<details class="deep-dive"><summary>August 2026 extension: what DFlash 2 adds</summary>
<p>The original authors' DFlash 2 technical post describes two additions: a small selector that scores adjacent token candidates, and short dynamic convolutions that share local information across block positions. Pair scores are computed in parallel; selecting the final path still has a sequential dependency. The proposal distribution after selection is the one the verifier must account for. The post includes experiments and implementation links, some targeting pull-request revisions when checked. Treat it as a dated author report, not evidence that an arbitrary installed engine supports the feature.</p>
${ref("https://inco.ai/blog/dflash2/", "DFlash 2 · original authors' technical post · August 18, 2026")}
</details>
<div class="method-table"><table><caption>Choose the work you can afford to add</caption><thead><tr><th scope="col">Proposal route</th><th scope="col">What to measure first</th><th scope="col">Integration question</th></tr></thead><tbody>
<tr><th scope="row">Separate small language model</th><td>Extra weights, KV and serial draft passes</td><td>Do target and draft token events line up?</td></tr>
<tr><th scope="row">Feature-conditioned draft</th><td>Feature capture, draft depth and acceptance by depth</td><td>Which target layers and normalization conventions?</td></tr>
<tr><th scope="row">Native MTP</th><td>Additional module latency and retained memory</td><td>Were compatible MTP weights included and supported?</td></tr>
<tr><th scope="row">Parallel block draft</th><td>Block cost, candidate coherence and verifier cost</td><td>What is the actual conditional proposal law?</td></tr>
<tr><th scope="row">N-gram or suffix lookup</th><td>Lookup overhead and repetition in the workload</td><td>How are deterministic proposals verified?</td></tr>
</tbody></table></div>
${ref("https://docs.vllm.ai/en/latest/features/speculative_decoding/", "vLLM · implementation families and output guarantees · checked September 16, 2026")}
${check("Check: does replacing a serial draft model with a parallel block model automatically preserve output quality?", "The proposal change alone does not establish that. A verifier must still implement the declared target policy using the actual proposal probabilities, or a correct greedy verification rule. Correlated candidate selection, filtering and rejection paths all matter. A method name and an acceptance-length plot are insufficient evidence.")}
</section>

<section class="lesson" id="training-a-drafter" data-lesson="Train the drafter"><header><span>Training serves inference</span><h3>Train for the states the drafter will actually encounter</h3></header>
<p>A frozen target can teach a smaller proposal model. At a prefix h, let p be the target distribution and q the draft distribution. One elementary distillation objective is <code>L(h) = −Σᵢ p(i|h) log q(i|h)</code>. Training on tokens sampled from p gives a stochastic estimate of that objective. This is a starting point for understanding distribution matching, not the full EAGLE or DFlash training recipe. Temperature choices, target features and multi-step losses are method-specific.</p>
${ref("https://arxiv.org/abs/1503.02531", "Hinton, Vinyals and Dean · knowledge distillation")}
<p>Consider p=(0.55,0.45). A draft q=(0.99,0.01) chooses the same greedy token but has acceptance overlap only 0.56. A less sharp q=(0.60,0.40) has overlap 0.95. Matching the target's highest-scoring token and matching its sampling distribution are different objectives. These numbers follow directly from <code>Σ min(pᵢ,qᵢ)</code>.</p>
<h4>The first draft step is easier to train than the fifth</h4>
<p>For feature-based drafting, training only on target-produced hidden vectors creates a mismatch: later inference steps consume draft-produced vectors. EAGLE-3 includes repeated draft steps during training, feeding its outputs back into subsequent steps. Its masks preserve the correct context for each training branch. This is why a good one-step validation loss can coexist with a poor accepted-prefix length.</p>
${ref("https://arxiv.org/html/2503.01840v1#S3.SS2", "EAGLE-3 · training-time test and branch masks")}
<p>DFlash instead trains masked blocks anchored at clean response tokens, with the frozen target supplying context features. Its attention masks prevent the block from reading forbidden later context. It emphasizes earlier positions in the block loss because an early rejection discards later draft work. Computing target features online trades extra target execution for less storage; precomputing them moves work into a dataset artifact.</p>
${ref("https://arxiv.org/html/2602.06036v1#S4.SS2", "DFlash · block construction, loss weights and training masks")}
<figure class="textbook-lab method-lab"><figcaption><strong>From a target checkpoint to a useful draft checkpoint</strong><p>An original workflow. Every evaluation uses the same target revision and output policy.</p></figcaption><ol class="method-flow">
<li><strong>Collect representative prefixes</strong><span>Cover the deployed domains, prompt templates, context lengths and sampling settings. Separate evaluation prompts before training.</span></li>
<li><strong>Capture only valid supervision</strong><span>Freeze the target; attach feature-layer IDs, tokenizer and checkpoint revision. Position masks must prevent future-token leakage.</span></li>
<li><strong>Train the proposal path</strong><span>Optimize only the intended parameters. Reproduce the method's feedback, masking and loss scheme instead of assuming ordinary next-token training is interchangeable.</span></li>
<li><strong>Evaluate complete rounds</strong><span>Measure conditional acceptance by depth, rejected work and draft/verify latency on held-out prompts, including template and long-context shifts.</span></li>
<li><strong>Test the integrated engine</strong><span>Check target-policy correctness, EOS and cache reconciliation, then run latency and goodput tests under offered load.</span></li>
</ol></figure>
<details class="deep-dive"><summary>Why training loss is not the final selection metric</summary><p>Cross-entropy is differentiable and useful for learning. Serving cost is determined by the accepted prefix, execution shape and traffic. A larger draft may lower loss but occupy memory needed for more active requests. A change to the target's weights, adapter, quantization or tokenizer can change both feature compatibility and proposal quality. Revalidate against the exact deployed target; do not reuse a previous target's acceptance report as a new measurement.</p><p>For an auxiliary MTP module trained jointly with a main model, also distinguish two comparisons: the quality benefit of adding the training objective, and the serving benefit of using the trained module as a proposer. The second comparison must keep the resulting main checkpoint fixed.</p></details>
${check("Check: the draft has worse loss on a held-out set. Must the served model's distribution get worse?", "With a correct exact verifier, the declared target distribution stays the same; useful accepted work may shrink and latency may rise. That conclusion assumes the implementation's probability, masking and state contracts hold. Training quality and verification correctness need separate tests.")}
</section>

<section class="lesson" id="speculative-tree-attention" data-lesson="Tree attention"><header><span>Positions, attention and ownership</span><h3>A flat buffer can hold several possible futures</h3></header>
<p>Instead of proposing only A → C → F, a drafter may also propose A → D and B → E → G. The target can evaluate all these nodes together, provided each query sees exactly its own history. <strong>Ancestor-only attention</strong> means a node reads the committed prefix, the nodes on its path and itself. It cannot read a sibling branch. EAGLE-2 describes dynamic draft trees; the tree below is an original seven-node teaching example.</p>
${ref("https://arxiv.org/html/2406.16858v1", "EAGLE-2 · context-dependent tree construction and verification")}
<figure class="textbook-lab speculation-frontier-lab" id="speculation-tree-lab"><figcaption><strong>Inspect a branch, its mask and its cache slots</strong><p>Choose the target query being computed. The highlighted ancestry determines both visibility and the state that can be retained if that path is accepted.</p></figcaption>
<div class="method-toolbar"><label>Target query<select data-tree-query><option value="0">A</option><option value="1">B</option><option value="2">C</option><option value="3">D</option><option value="4">E</option><option value="5" selected>F</option><option value="6">G</option></select></label></div>
<div class="tree-visual" data-tree-diagram tabindex="0" role="region" aria-label="Draft tree diagram; scroll horizontally on narrow screens"></div><p class="tree-explanation" data-tree-explanation aria-live="polite"></p><div class="method-table" data-tree-mask tabindex="0" role="region" aria-label="Target tree attention mask; scroll horizontally on narrow screens"></div>
<p class="figure-boundary">Letters identify nodes, not literal words. Positions and storage slots are zero-based. This lab models a causal target with a full four-token prefix; sliding-window attention needs an additional visibility constraint. It does not implement a stochastic tree sampler or execute a GPU kernel.</p></figure>
<h4>Three indices that must not be confused</h4>
<p><strong>Logical position</strong> determines where a token occurs in a sequence: A and B are both at position 4. <strong>Storage slot</strong> says where provisional KV was placed: A and B occupy different locations. <strong>Probability owner</strong> identifies the model output used to verify a candidate: the output after C predicts F; the output after F predicts what follows F. A token must never validate itself using logits conditioned on that same token.</p>
<p>If A → C → F is accepted, its provisional slots are 4, 6 and 9. Keeping the first three slots would retain A, B and C, which is a different history. An engine must gather the accepted ancestry or remap its logical ownership, protect any shared prefix and make rejected branches unreachable. A newly sampled correction or bonus may still lack KV and must be processed before that KV is used.</p>
<div class="lesson-code"><h4>Run the mask and ownership contract</h4><pre><code>${escapeCode(treeExample)}</code></pre></div>
<p>The tests compare masked packed attention with independent causal-path attention and exercise interleaved branch storage. Correct scores are only one part of tree verification. Greedy branch matching and stochastic tree acceptance require different selection logic; applying a chain rejection formula independently to every sibling is not a proof of a correct sampler.</p>
${check("Check: may a lower-triangular mask over the flat order A,B,C,D,E,F,G replace the tree mask?", "No. For example, C would read B merely because B was stored earlier, although B is an alternative to C's ancestor A. F would also read several unrelated branches. The layout order is a storage decision; causal history comes from ancestry.")}
</section>

<section class="lesson" id="speculation-acceptance-depth" data-lesson="Choose draft depth"><header><span>Measure before tuning</span><h3>A token at depth six helps only after depths one through five survive</h3></header>
<p>Let A be the number of accepted draft tokens before the first rejection. Define <code>sₖ = P(A ≥ k)</code>: the fraction of rounds that reach at least k accepted proposals. With one correction or bonus, no early stopping and maximum depth γ, <code>E[emitted tokens] = 1 + Σₖ₌₁ᵞ sₖ</code>. This <strong>survival curve</strong> captures position-dependent behavior that one overall acceptance percentage hides.</p>
<p>If <code>αₖ = P(proposal k accepted | all earlier proposals accepted)</code>, then <code>sₖ = α₁ × … × αₖ</code>. No independence assumption is needed: these are conditional probabilities. For α=(0.9,0.8,0.5), s=(0.9,0.72,0.36), so a round emits 2.98 tokens on average. The third proposal adds only 0.36 expected tokens, although its conditional acceptance is 50%.</p>
<figure class="textbook-lab speculation-frontier-lab" id="speculation-depth-lab"><figcaption><strong>Find when one more draft position stops paying</strong><p>Change the conditional acceptance curve and the cost of drafting. Every timing below is a hypothetical input, with units shown explicitly.</p></figcaption>
<div class="method-toolbar"><label>Draft schedule<select data-depth-mode><option value="serial">Serial token steps</option><option value="block">Parallel block pass</option></select></label><label>First-position acceptance<input type="range" min="0" max="100" value="90" data-depth-first/><output data-depth-first-value>90%</output></label><label>Drop per later position<input type="range" min="0" max="25" value="8" data-depth-fall/><output data-depth-fall-value>8 points</output></label><label>Draft cost parameter d<input type="range" min="1" max="80" value="10" data-depth-draft/><output data-depth-draft-value>1.0 ms</output></label></div>
<p class="tree-explanation" data-depth-result aria-live="polite"></p><div class="method-table" data-depth-table tabindex="0" role="region" aria-label="Draft depth cost comparison; scroll horizontally on narrow screens"></div><p class="figure-boundary">The comparison deliberately holds the acceptance curve constant to isolate the cost tradeoff. Actual drafters and block sizes can change that curve. These formulas do not measure a GPU, predict a named model's speed or include load-dependent queuing.</p></figure>
<details class="deep-dive"><summary>Estimate the curve from logs without hiding failed rounds</summary><p>Record every complete round's accepted draft length, including zero. For counts (2,3,1,4) at lengths (0,1,2,3), ten rounds give s=(0.8,0.5,0.4) and 2.7 emitted tokens per round. The same result comes from summing each round's actual emitted count. The tested <code>survivalFromHistogram</code> helper computes this empirical curve. Keep EOS and output-limit rounds separate: they are censored by stopping and do not satisfy the automatic “plus one” assumption.</p><p>Record total elapsed round time and emitted tokens, then use <code>Σ elapsed time / Σ emitted tokens</code>. Averaging individual round ratios gives equal weight to short and long rounds and can answer a different question. Log offered load, batch size and scheduler state so a change in traffic is not mistaken for a better drafter.</p></details>
<p>In a serving system, test short and long contexts, several concurrency levels and output policies. Report TTFT, inter-token latency, tail latency and goodput alongside acceptance depth. Increasing γ adds target verification work and provisional KV; its best value may change with load. Prefill/decode disaggregation also changes which worker has spare compute and where draft state should live. Combine the methods only after measuring their shared resource costs.</p>
${check("Check: a new draft doubles the mean accepted prefix. Is a speedup guaranteed?", "No. Divide complete round time by emitted tokens. A larger drafter, wider verification tree, extra feature traffic, or lower serving concurrency can offset the gain. Select the depth and method that satisfy the same latency and output-quality requirements under the same workload.")}
</section>`;
