const source = (url: string, title: string) => `<a class="lesson-source" href="${url}" target="_blank" rel="noreferrer">Read: ${title}</a>`;
const check = (question: string, answer: string) => `<details class="knowledge-check"><summary>${question}</summary><p>${answer}</p></details>`;

export const tensorLesson = `
<section class="lesson" id="autodiff" data-lesson="Loss and gradients">
  <header><span>1.2 / From numbers to learning</span><h3>What a gradient actually tells the optimizer</h3></header>
  <div class="lesson-reading"><div>
    <p>A model contains adjustable numbers called parameters. A forward pass uses them to compute predictions. A loss function turns prediction error into one scalar. The gradient tells us how a tiny change to each parameter would change that loss, with the current data held fixed.</p>
    <p>Start with a single prediction: <code>ŷ = wx</code>. If <code>x = 2</code>, <code>w = 3</code>, and the target is <code>y = 4</code>, then <code>ŷ = 6</code>. Using <code>L = ½(ŷ − y)²</code>, the loss is 2. The chain rule gives <code>∂L/∂w = (ŷ − y)x = 4</code>. A gradient-descent update at learning rate 0.1 changes the weight to 2.6; the new prediction is 5.2 and the loss falls to 0.72.</p>
    <p>Backpropagation applies this same chain rule across the tensor graph. For <code>Y = XW</code> and upstream gradient <code>G = ∂L/∂Y</code>, the two matrix derivatives are <code>∂L/∂X = GWᵀ</code> and <code>∂L/∂W = XᵀG</code>. That explains both the extra matrix multiplication during training and why backward needs forward values such as X.</p>
  </div><aside><h4>Follow the shapes</h4><dl><dt>X</dt><dd>[tokens, input features]</dd><dt>W</dt><dd>[input features, output features]</dd><dt>G</dt><dd>[tokens, output features]</dd><dt>XᵀG</dt><dd>[input features, output features]</dd></dl><p>The gradient of a parameter has the same shape as that parameter. A gradient is a sensitivity, not an instruction to change every weight by the same amount.</p></aside></div>
  <div class="lesson-code"><div><h4>One scalar update in TensorFlow</h4><button data-copy-target="gradient-code" class="copy-button">Copy code</button></div><pre id="gradient-code"><code>import tensorflow as tf
w = tf.Variable(3.0)
with tf.GradientTape() as tape:
    prediction = w * 2.0
    loss = 0.5 * tf.square(prediction - 4.0)
gradient = tape.gradient(loss, w)
w.assign_sub(0.1 * gradient)
print(float(gradient), float(w))  # 4.0, approximately 2.6</code></pre></div>
  <h4>Next-token prediction is a classification problem at every position</h4>
  <p>For tokens <code>[BOS, the, cat, sat, EOS]</code>, inputs are the first four tokens and labels are the last four. Position zero predicts “the”; position one predicts “cat”. Teacher forcing provides the correct preceding tokens during training. The causal mask prevents a position from reading the answer to its own prediction.</p>
  <p>The vocabulary projection produces logits, which are unnormalized scores. Cross entropy is <code>−log p(correct token)</code>; it rewards putting probability on the observed target. A probability of 0.25 gives a loss of about 1.386 natural-log units. Perplexity is <code>exp(mean token loss)</code> for this objective, and depends on the tokenizer and evaluation corpus.</p>
  ${check("Check your understanding: why can training process many positions together while decode is sequential?", "During teacher-forced training, the input tokens are known in advance. A causal mask allows their hidden states to be computed in parallel without future leakage. At inference time, the next sampled token is not known until the preceding step completes, so a single sequence has an autoregressive dependency.")}
  ${source("https://www.tensorflow.org/guide/autodiff", "TensorFlow automatic differentiation")}
</section>`;

export const attentionLesson = `
<section class="lesson" id="flashattention" data-lesson="FlashAttention, tile by tile">
  <header><span>3.2 / Algorithm meets memory</span><h3>Keep the answer. Stop storing every score.</h3></header>
  <p>For one query, attention is a weighted average of value vectors. A straightforward implementation writes every query–key score, reads it to compute softmax, writes the probabilities, then reads them for the weighted sum. Full attention still has quadratic pairwise work, but those large intermediate arrays need not live in HBM.</p>
  <p>FlashAttention visits blocks of keys and values while retaining small running statistics on chip. For each query row, keep the largest score <em>m</em>, a rescaled exponential sum <em>ℓ</em>, and a rescaled value numerator <em>u</em>. A new maximum changes the scale of every prior contribution, so rescale the old statistics before adding the new tile. Finally, output <code>u / ℓ</code>.</p>
  <figure class="textbook-lab" id="softmax-lab">
    <figcaption><span>Lab 3.B</span><strong>Compute one attention row in three tiles</strong><p>Step forward. The final tile contains a new maximum, forcing the old accumulated values to rescale.</p></figcaption>
    <div class="tile-memory-map"><div><span>HBM / six keys and values</span><div data-softmax-tiles></div></div><div class="tile-transfer" aria-hidden="true">↓<small>load one tile</small></div><div class="softmax-registers"><span>On-chip running state</span><dl><div><dt>maximum m</dt><dd data-softmax-max>−∞</dd></div><div><dt>denominator ℓ</dt><dd data-softmax-denom>0</dd></div><div><dt>numerator u</dt><dd data-softmax-num>0</dd></div></dl></div></div>
    <div class="lab-action-row"><button data-softmax-step>Load next tile</button><button data-softmax-reset>Reset</button><output data-softmax-result aria-live="polite">No scores processed yet.</output></div>
    <p class="figure-boundary">One query and one value channel; real kernels process matrix tiles, use vector accumulators, and coordinate asynchronous loads. This is an algorithm demonstration, not a hardware timing trace.</p>
  </figure>
  <div class="derivation"><h4>The online update</h4><p><code>m′ = max(m, max(tile scores))</code></p><p><code>α = exp(m − m′)</code></p><p><code>ℓ′ = αℓ + Σ exp(scoreᵢ − m′)</code></p><p><code>u′ = αu + Σ exp(scoreᵢ − m′) valueᵢ</code></p><p>All sums are over the new tile. Subtracting the common maximum prevents exponential overflow; rescaling preserves the same normalized weighted average, up to floating-point rounding.</p></div>
  ${check("Worked check: does FlashAttention make dense attention linear-time?", "No. Dense attention still evaluates a quadratic number of query–key pairs. FlashAttention changes IO and intermediate storage, and improves how work maps to hardware. Sparse attention changes which pairs are computed; recurrent attention changes the representation of history. These are different choices.")}
  ${source("https://arxiv.org/abs/2205.14135", "FlashAttention, especially the IO analysis and algorithm")}
</section>`;

export const postTrainingLesson = `
<section class="lesson" id="post-training-loss" data-lesson="SFT and preference losses">
  <header><span>4.4 / From an objective to tensors</span><h3>The loss mask defines what you teach</h3></header>
  <p>Supervised fine-tuning often trains on assistant responses while keeping the prompt as context. That needs two different masks. The attention mask controls which tokens can be read. The loss mask controls which prediction targets contribute to the objective. A prompt can be visible to attention while contributing zero direct loss.</p>
  <figure class="textbook-lab"><figcaption><span>Figure 4.E</span><strong>Shift the labels, then identify response targets</strong><p>Each column is one prediction position. The token names are schematic, not a specific chat tokenizer.</p></figcaption>
    <div class="sft-alignment" role="img" aria-label="Inputs BOS, user, question, assistant, answer predict labels user, question, assistant, answer, EOS. Only answer and EOS contribute to response-only loss.">
      <span>Input</span><b>BOS</b><b>user</b><b>question</b><b>assistant</b><b>answer</b>
      <span>Target</span><b>user</b><b>question</b><b>assistant</b><b class="learn-target">answer</b><b class="learn-target">EOS</b>
      <span>Loss mask</span><i>0</i><i>0</i><i>0</i><i class="learn-target">1</i><i class="learn-target">1</i>
    </div><p class="figure-boundary">The prediction of “answer” comes from the assistant-marker input position. Build the mask from target-token roles after shifting; an off-by-one error changes the task.</p>
  </figure>
  <p>If the two response targets have losses 0.4 and 0.8, token-mean SFT loss is <code>(0.4 + 0.8) / 2 = 0.6</code>. Dividing by all five positions would silently change the weighting to 0.24. With variable lengths, averaging each example’s mean gives equal weight to examples; averaging all valid tokens gives equal weight to tokens. Neither reduction should happen accidentally.</p>
  <p>Packed conversations need both valid loss targets and the intended attention boundaries. Padding must not become a target. If examples must be independent, their attention mask must prevent cross-example reading; concatenation alone does not guarantee that. Reject all-masked training batches instead of producing a misleading zero loss.</p>
  <h4>DPO compares two response likelihood ratios</h4>
  <p>Let <code>c</code> and <code>r</code> be the chosen and rejected responses to the same prompt. Sum the response-token log probabilities to obtain each conditional sequence log likelihood. Define <code>z = β[(log πθ(c) − log πref(c)) − (log πθ(r) − log πref(r))]</code>. The DPO pair loss is <code>softplus(−z)</code>; the frozen reference anchors this relative comparison.</p>
  <div class="derivation"><h4>A pair you can calculate by hand</h4><p>Suppose policy log likelihoods are −4 for the chosen answer and −6 for the rejected answer. Both reference log likelihoods are −5. At β = 0.1, the margin is <code>z = 0.1[(−4 + 5) − (−6 + 5)] = 0.2</code>.</p><p>The loss is <code>log(1 + exp(−0.2)) ≈ 0.5981</code>, below the equal-margin loss <code>log 2 ≈ 0.6931</code>. Increasing this relative margin lowers the loss. It does not guarantee that either answer is factually correct.</p></div>
  <div class="lesson-code"><div><h4>A numerically stable DPO loss in TensorFlow</h4><button data-copy-target="dpo-code" class="copy-button">Copy code</button></div><pre id="dpo-code"><code>import tensorflow as tf

def dpo_loss(policy_chosen, policy_rejected,
             reference_chosen, reference_rejected, beta=0.1):
    # Each argument: [batch] response-summed log likelihoods.
    reference_gap = tf.stop_gradient(
        reference_chosen - reference_rejected)
    margin = beta * (policy_chosen - policy_rejected - reference_gap)
    return tf.reduce_mean(tf.nn.softplus(-margin))

# The companion's sequence_log_probs computes these sums from
# [batch, time, vocabulary] logits and a response-only target mask.</code></pre></div>
  <p>Standard DPO uses sequence sums, not length-normalized token averages. Changing that reduction changes the objective. Keep the tokenizer, chat template, masking, and reference checkpoint fixed and versioned. A falling preference loss needs a separate held-out assessment of helpfulness, correctness, and undesirable behavior.</p>
  ${check("Check your understanding: does masking prompt loss stop gradients from flowing through the prompt?", "No. Response predictions attend to prompt representations. Their loss can backpropagate through those representations and the parameters that produced them. A loss mask removes direct prediction targets; it is not a stop-gradient operation.")}
  ${source("https://arxiv.org/abs/2305.18290", "Direct Preference Optimization")}
</section>
<section class="lesson" id="adapters-rollouts" data-lesson="LoRA and rollout systems">
  <header><span>4.5 / Which weights, which experiences?</span><h3>Adapters change storage. Rollouts change the workload.</h3></header>
  <p>Low-rank adaptation (LoRA) freezes a base matrix and learns a small update. Using row-vector conventions, <code>Y = XW + (α/r)XAB</code>, where W has shape [dᵢₙ, dₒᵤₜ], A is [dᵢₙ, r], and B is [r, dₒᵤₜ]. Only A and B need trainable optimizer state. With a 4,096 × 4,096 base matrix and rank 8, the adapter has 65,536 parameters instead of 16,777,216: 0.39% as many.</p>
  <div class="adapter-flow" role="img" aria-label="Input X takes two paths: a frozen base matrix W and trainable rank-r matrices A then B. The scaled adapter output is added to the base output."><strong>X</strong><div><span>Frozen W · wide → wide</span><span>Train A · wide → r <b>→</b> Train B · r → wide <small>scale α/r</small></span></div><strong>+ → Y</strong></div>
  <p>Initialize B to zero so the starting output equals the base model. The first step can update B even though the gradient of A initially vanishes. LoRA reduces trainable state, but the base weights still occupy memory and the backward pass still needs activations. Merging the update into W can remove the extra serving branch when the deployment format permits it.</p>
  ${source("https://arxiv.org/abs/2106.09685", "LoRA: Low-Rank Adaptation of Large Language Models")}
  <h4>A reinforcement-learning step starts by generating experience</h4>
  <p>In supervised learning the target response arrives with the dataset. In on-policy reinforcement learning the current policy first generates responses. A verifier or reward model scores them, then the learner changes the policy. Rollout generation has inference-like scheduling and KV-memory costs; the update has training-like activation and optimizer costs.</p>
  <div class="rollout-flow"><span>Version policy θₖ</span><b>→</b><span>Generate K answers</span><b>→</b><span>Verify + compute advantages</span><b>→</b><span>Optimize → θₖ₊₁</span></div>
  <p>A group-relative method can compare sampled answers to other answers for the same prompt without fitting a separate value network. As an illustrative normalization, rewards <code>[1, 0, 1, 0]</code> have mean 0.5 and population standard deviation 0.5, yielding advantages <code>[1, −1, 1, −1]</code>. An all-equal group has no relative signal; an epsilon prevents division by zero but cannot create information.</p>
  <p>That advantage calculation is only one piece of GRPO-style training. The complete objective must specify old-policy probabilities, probability ratios, clipping, KL treatment, token masking, and sequence/token reduction. Later variants alter these choices. Do not implement a policy optimizer by multiplying log probabilities by rewards and assuming all these objectives are equivalent.</p>
  ${source("https://arxiv.org/abs/2402.03300", "DeepSeekMath and the original GRPO formulation")}
  <h4>Record enough to diagnose an apparent improvement</h4>
  <p>Store the rollout policy version, prompt identity, sampled tokens, old log probabilities, termination reason, verifier version, reward, and token mask. Monitor reward alongside completion length, truncation, entropy, KL, and independent task accuracy. A reward increase caused by exploiting the verifier is a data point about the verifier, not proof of improved reasoning.</p>
  ${check("Design exercise: a code reward gives one point whenever a program prints the expected output. What is missing?", "A solution can hard-code a known answer without solving the task. Evaluate on hidden inputs, isolate execution, enforce resource limits, and distinguish syntax/runtime failures from wrong answers. Keep a held-out task set separate from the verifier feedback used for optimization.")}
  <p class="companion-inline">Runnable loss and adapter implementations, with gradient tests: <a href="https://github.com/djsydney04/inference_and_training_systems/tree/main/examples/tensorflow">examples/tensorflow/post_training.py</a>.</p>
</section>`;

export const hardwareLesson = `
<section class="lesson" id="cpu-execution" data-lesson="Inside a CPU core">
  <header><span>5.3 / The host is part of the machine</span><h3>From an instruction to a committed result</h3></header>
  <p>A CPU core fetches instructions, decodes them, locates operands, performs operations, and retires completed work into the program’s architectural state. Modern high-performance cores overlap many instructions and may execute independent operations before older stalled ones. They still preserve the observable rules of the instruction set.</p>
  <figure class="textbook-lab cpu-figure"><figcaption><span>Figure 5.C</span><strong>A conceptual out-of-order core</strong><p>Select a stage to follow the responsibilities of the hardware.</p></figcaption>
    <div class="cpu-flow"><button data-cpu-stage="fetch">Fetch<small>PC + prediction</small></button><b>→</b><button data-cpu-stage="decode">Decode<small>instructions → operations</small></button><b>→</b><button data-cpu-stage="rename">Rename<small>physical registers</small></button><b>→</b><button data-cpu-stage="issue">Issue<small>ready operands</small></button><b>→</b><button data-cpu-stage="execute">Execute<small>ALU / vector / LSU</small></button><b>→</b><button data-cpu-stage="retire">Retire<small>commit in order</small></button></div>
    <div class="cpu-cache-path"><span>Load/store unit</span><i>↔</i><span>TLB + L1</span><i>↔</i><span>L2 / shared cache</span><i>↔</i><span>DRAM controller</span></div>
    <div class="diagram-explanation" data-cpu-readout aria-live="polite"><strong>Fetch</strong><p>The program counter identifies the next instruction. Branch prediction guesses the next path early enough to keep the pipeline supplied.</p></div>
    <p class="figure-boundary">Conceptual high-performance CPU; pipeline widths, cache topology, instruction decomposition, and ordering details depend on the microarchitecture and ISA.</p>
  </figure>
  <div class="lesson-reading"><div><h4>Registers, caches, and virtual memory solve different problems</h4><p>Registers hold immediate operands and results. Caches keep nearby or recently used memory lines close to the core. The translation lookaside buffer (TLB) caches virtual-to-physical address translations. A cache miss and a TLB miss are distinct events, although either can delay a load.</p><p>Register renaming assigns physical storage to logical register names, removing false dependencies caused by reusing a name. It cannot remove a true dependency: an addition that consumes a load must wait for that load’s value. Branch misprediction can discard speculative work and redirect fetch.</p></div><aside><h4>Why an inference engineer cares</h4><p>Tokenization, request parsing, batching, driver launches, sampling setup, and networking use CPU time. A GPU timeline with gaps may indicate a host bottleneck. Measure CPU threads and GPU launches together before optimizing a kernel that is already fast.</p></aside></div>
  ${source("https://developer.arm.com/-/media/Arm%20Developer%20Community/PDF/Learn%20the%20Architecture/Armv8-A%20Instruction%20Set%20Architecture.pdf", "Arm instruction-set and CPU fundamentals")}
</section>
<section class="lesson" id="warp-memory" data-lesson="Warps, registers, and memory">
  <header><span>5.4 / A request becomes transactions</span><h3>Thirty-two loads can be cheap or expensive</h3></header>
  <p>A CUDA warp contains 32 logical threads. If neighboring lanes load neighboring four-byte values, their requests can use a compact set of memory sectors. If the addresses are far apart, each sector carries fewer useful bytes. This is why the tensor’s physical layout matters even when the mathematical operation is unchanged.</p>
  <figure class="textbook-lab"><figcaption><span>Lab 5.D</span><strong>Explore memory coalescing</strong><p>All 32 lanes load one FP32 value. The stride changes the distance between their addresses.</p></figcaption><div class="lab-action-row"><label>Stride, in floats <select data-memory-stride><option value="1">1 · adjacent</option><option value="2">2 · every other</option><option value="4">4 · spread out</option><option value="8">8 · one sector each</option></select></label><output data-memory-efficiency aria-live="polite"></output></div><div class="lane-strip" data-memory-lanes aria-label="32 lane requests"></div><div class="sector-map" data-memory-sectors aria-label="Memory sectors touched"></div><p class="figure-boundary">Aligned base, four-byte loads, ideal 32-byte sector counting. Cache hits, instruction splitting, larger transfers, ECC, and architecture-specific behavior affect actual DRAM traffic.</p></figure>
  <h4>A warp waits; the scheduler looks for another ready warp</h4><p>A dependent instruction cannot issue until its input is ready. The scheduler can issue an eligible instruction from another resident warp while that load is outstanding. Registers for those resident warps remain allocated on the SM; switching among them does not require an operating-system context switch.</p>
  <p>Occupancy measures resident work relative to a hardware maximum. Register allocation, shared-memory allocation, threads per block, and block limits constrain it. More occupancy helps only if additional independent work covers otherwise exposed latency. A kernel can be fast at moderate occupancy when it has enough instruction-level parallelism or a well-pipelined tensor-core workload.</p>
  <div class="lesson-code"><div><h4>The same operation, different lane addresses</h4><button data-copy-target="coalescing-code" class="copy-button">Copy code</button></div><pre id="coalescing-code"><code>// Demonstration kernel; x must contain at least n * stride floats.
__global__ void gather(const float* x, float* y, int n, int stride) {
    int i = blockIdx.x * blockDim.x + threadIdx.x;
    if (i &lt; n) y[i] = x[i * stride];
}
// Compare stride=1 with stride=8 using a memory profiler.
// Keep n, dtype, launch dimensions, and cache conditions fixed.</code></pre></div>
  ${check("Worked check: 32 lanes load 4 bytes each at stride 8. What is useful-sector efficiency?", "Each address is 32 bytes from the previous address, so the simplified model touches 32 sectors. It transfers 32 × 32 = 1,024 bytes for 128 useful bytes: 12.5%. At stride 1, the same payload fits into four aligned sectors, giving 100% useful-sector efficiency.")}
  ${source("https://docs.nvidia.com/cuda/cuda-programming-guide/", "NVIDIA’s current CUDA Programming Guide")}
</section>`;

export const rackLesson = `
<section class="lesson" id="hardware-photographs" data-lesson="Read the real hardware">
  <header><span>6.2 / Reference images</span><h3>Connect the cutaway to the physical system</h3></header>
  <p>Use these NVIDIA reference images as visual anchors. The rack view establishes scale; the tray view reveals serviceable components; the block diagram distinguishes the GPU fabric from host and network connections. Open any figure to inspect it at full size.</p>
  <div class="reference-gallery">
    <figure><button class="figure-open" data-figure-open="figures/gb200-racks.png" aria-label="Enlarge NVIDIA DGX GB200 rack image"><img src="figures/gb200-racks.png" alt="NVIDIA reference image showing four DGX GB200 racks with stacked compute and switch trays" loading="lazy" width="1200" height="680" /></button><figcaption><strong>Rack scale</strong><p>Four DGX GB200 racks shown; each rack is its own NVLink domain. Source: NVIDIA reference architecture, Figure 2.</p></figcaption></figure>
    <figure><button class="figure-open" data-figure-open="figures/gb200-tray.png" aria-label="Enlarge GB200 compute tray image"><img src="figures/gb200-tray.png" alt="Front of a NVIDIA GB200 compute tray showing networking and service interfaces" loading="lazy" width="1200" height="420" /></button><figcaption><strong>Compute tray</strong><p>Front access exposes service and scale-out connections. Source: NVIDIA reference architecture, Figure 3.</p></figcaption></figure>
    <figure class="reference-wide"><button class="figure-open" data-figure-open="figures/gb200-topology.png" aria-label="Enlarge official GB200 compute-tray block diagram"><img src="figures/gb200-topology.png" alt="Official block diagram locating two Grace CPUs, four B200 GPUs, and network interfaces within a GB200 compute tray" loading="lazy" width="1400" height="700" /></button><figcaption><strong>Trace an interface</strong><p>Locate a CPU–GPU connection, a GPU–GPU fabric connection, and a network adapter. They serve different communication scopes. Source: NVIDIA reference architecture, Figure 5. Images © NVIDIA; captions are original.</p></figcaption></figure>
  </div>
  ${source("https://docs.nvidia.com/dgx-superpod/reference-architecture-scalable-infrastructure-gb200/latest/dgx-superpod-components.html", "NVIDIA DGX GB200 reference architecture and full-resolution figures")}
</section>
<section class="lesson" id="network-budget" data-lesson="Fiber and communication budgets">
  <header><span>6.3 / Bytes across distance</span><h3>Separate propagation, serialization, and queueing</h3></header>
  <p>A link’s bandwidth describes how quickly it can transmit bits. Latency also includes signal propagation, switches, protocol processing, and waiting in queues. A short message can be dominated by fixed overhead; a large transfer often exposes the payload bandwidth. The basic lower-bound model is <code>time ≈ fixed latency + bytes / effective bytes per second</code>.</p>
  <div class="network-equations"><div><span>400 Gb/s link</span><strong>50 GB/s</strong><p>Divide bits by eight before comparing with memory bandwidth. Encoding and protocol overhead reduce useful throughput.</p></div><div><span>1 GB payload</span><strong>20 ms minimum</strong><p>At 50 GB/s, serialization alone takes 0.02 seconds. A nominal link rate is not an application-level guarantee.</p></div><div><span>100 m of fiber</span><strong>≈ 0.5 μs</strong><p>Using an illustrative propagation speed near 2 × 10⁸ m/s. Transceivers, switches, and queueing add latency.</p></div></div>
  <p>An optical transmitter modulates light; a receiver detects it and reconstructs the electrical signal. Multiple wavelengths can share one fiber, and multiple lanes can be aggregated into a port. Connectors, wavelength count, fiber count, and port bit rate are separate quantities. SerDes and forward error correction remain part of the path even when the cable is optical.</p>
  <h4>Place communication according to how often it happens</h4><p>Tensor parallelism communicates inside layers, so its latency and bandwidth requirements often favor the strongest local fabric. Data parallelism can overlap gradient collectives with backward work. Expert parallelism redistributes tokens and is sensitive to imbalanced destinations. Placement is a workload decision: topology, message size, overlap, and the slowest rank all matter.</p>
  ${check("Worked check: how much data does a ring all-reduce send per rank?", "For p ranks and an S-byte tensor, an ideal ring reduce-scatter followed by all-gather sends 2(p−1)S/p bytes per rank. For eight ranks and a 1 GB tensor, that is 1.75 GB sent per rank, spread across 14 steps. Startup latency and the achievable payload rate determine elapsed time; this is not a claim that every collective uses a ring.")}
  ${source("https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/usage/collectives.html", "NCCL collective operations")}
</section>`;

export const inferenceLesson = `
<section class="lesson" id="paged-kv" data-lesson="Paged KV memory">
  <header><span>7.4 / State with an address book</span><h3>A sequence can be contiguous in meaning and scattered in memory</h3></header>
  <p>Each request has a logical order of tokens. Its KV tensors can occupy fixed-size physical blocks anywhere in an allocation pool. A block table maps logical positions to physical blocks; the attention kernel follows this mapping. That lets a growing request acquire another free block without moving its entire history.</p>
  <figure class="textbook-lab"><figcaption><span>Lab 7.D</span><strong>Two requests share an eight-token prefix</strong><p>Blocks contain four token positions. Advance decode to allocate a new block, then finish a request to release its private blocks.</p></figcaption><div class="cache-tables" data-cache-tables></div><div class="physical-cache" data-physical-cache aria-label="Physical KV block pool"></div><div class="lab-action-row"><button data-cache-append="A">Decode A</button><button data-cache-append="B">Decode B</button><button data-cache-release="A">Finish A</button><button data-cache-reset>Reset</button></div><p class="diagram-explanation" data-cache-status aria-live="polite"></p><p class="figure-boundary">A logical illustration of one layer’s block map. Production layouts include K and V, heads, dtype, alignment, reference counts, eviction policy, and distributed ownership.</p></figure>
  <p>Complete matching prefixes can share immutable blocks. A shared block stays allocated until every dependent request releases it. If a system allows sharing an unfinished block and one branch appends to it, that branch needs a private copy before writing. This is copy-on-write.</p>
  <p>Prefix reuse requires more than identical visible words: token IDs and their preceding context must match, and model, adapter, position handling, and relevant multimodal inputs must agree. Prefix caching saves repeated prefill work. It does not eliminate attention over the cached context during later decode.</p>
  ${source("https://arxiv.org/abs/2309.06180", "PagedAttention and the original vLLM system")}
  ${source("https://docs.vllm.ai/en/latest/features/automatic_prefix_caching/", "vLLM automatic prefix caching")}
  ${check("Check your understanding: when A finishes, may blocks shared with B return to the free list?", "No. Finishing A removes A’s references. Shared prefix blocks still have a live reference from B, so only A’s private blocks become free. Reusing a referenced block would corrupt B’s context.")}
</section>
<section class="lesson" id="serving-budgets" data-lesson="Serving latency and quantization">
  <header><span>7.5 / Measure the service a user receives</span><h3>Throughput is only one part of a serving result</h3></header>
  <div class="lesson-reading"><div><h4>Prefill and decode compete for different resources</h4><p>Prefill has many known input positions and can form larger matrix multiplications. Decode adds one position per active sequence per iteration. At low batch sizes, reading model weights can dominate; with enough batching, those reads are amortized. Long contexts add substantial KV reads, and MoE routing or collectives can change the dominant cost.</p><p>Continuous batching changes membership between iterations: finished requests leave and new requests enter. Chunked prefill breaks large prompts into smaller pieces so one prompt has less opportunity to delay active decoders. The scheduler must budget both token work and available cache blocks.</p></div><aside><h4>Report the workload</h4><p>Model revision, precision, input/output lengths, concurrency, request-arrival process, hardware, software versions, and latency percentiles belong beside a tokens-per-second number. Average latency hides queueing tails.</p></aside></div>
  <div class="service-timeline"><span>arrival</span><div>queue</div><div>prefill</div><b>first token</b><div>decode → decode → decode</div><span>complete</span></div>
  <p>Time to first token (TTFT) includes queueing and prompt processing. Inter-token latency describes how quickly subsequent tokens arrive. End-to-end latency adds the whole generation. Goodput counts completed work that meets the chosen service-level objective; raising raw throughput while missing deadlines can lower goodput.</p>
  <h4>Quantization changes both storage and numerical error</h4><p>A simple uniform quantizer represents a value approximately as <code>x ≈ scale × (integer − zero_point)</code>. Per-channel or per-group scales trade metadata for a closer fit to local ranges. Weight-only quantization compresses weights; activation and KV quantization affect different tensors and therefore different accuracy and bandwidth paths.</p><p>Four-bit weights ideally use half a byte per parameter: 7 billion parameters need 3.5 GB of raw payload. Scales, packing, untouched tensors, temporary buffers, and runtime state increase that figure. A four-bit file does not establish that every operation executes with four-bit arithmetic. Kernel support and the actual dequantization path determine speed.</p>
  ${check("Design an experiment: how would you compare two serving configurations fairly?", "Replay the same tokenized request set and arrival schedule; warm up both configurations; keep the model, output constraints, and sampling policy fixed. Report throughput together with TTFT, inter-token latency, end-to-end percentiles, error rate, and cache behavior. Repeat runs and identify whether the load is below or above saturation.")}
  ${source("https://docs.vllm.ai/en/latest/configuration/optimization/", "vLLM optimization and performance tuning")}
</section>`;

export const lpuLesson = `
<section class="lesson" id="lpu-schedule" data-lesson="A compiler owns the timetable">
  <header><span>8.3 / Deterministic execution</span><h3>Schedule when an operand arrives, not only what computes it</h3></header>
  <p>In the published Tensor Streaming Processor design, the compiler coordinates operations and data movement across functional slices. A matrix unit needs its operands in the correct place at the correct time. Explicit scheduling turns those dependencies into a timetable that accounts for movement latency and resource use.</p>
  <figure class="textbook-lab"><figcaption><span>Figure 8.C</span><strong>A teaching schedule for one tensor tile</strong><p>Read across for time, down for a resource. The marked delay is a dependency, not idle work the compiler can always remove.</p></figcaption><div class="schedule-grid"><span>resource / step</span><b>0</b><b>1</b><b>2</b><b>3</b><b>4</b><b>5</b><span>MEM / SRAM</span><i class="scheduled">read A</i><i class="scheduled">read B</i><i></i><i></i><i></i><i class="scheduled">write C</i><span>SXM / routing</span><i></i><i class="scheduled">move A</i><i class="scheduled">move B</i><i></i><i class="scheduled">move C</i><i></i><span>MXM / matrix</span><i></i><i></i><i class="waiting">operands</i><i class="scheduled">A × B</i><i></i><i></i><span>VXM / vector</span><i></i><i></i><i></i><i></i><i class="scheduled">activate</i><i></i></div><p class="figure-boundary">Original conceptual schedule; columns are abstract stages, not measured chip cycles. This is not an executable Groq program or a disclosure of current-generation instruction timing.</p></figure>
  <h4>Why model placement spans many chips</h4><p>On-chip SRAM is fast but has limited capacity. When weights and state exceed one chip’s memory, a compiled deployment partitions them across chips. The resulting system must move activations and coordinate schedules across links. Predictable execution does not make communication free or remove the need for enough aggregate storage.</p>
  <p>For inference, ask where each layer’s weights live, where persistent attention state lives, how batches and sequence lengths are represented, and what recompilation or specialization is needed. A recurrent attention layer and a growing KV cache have different storage behavior; the compiler and runtime must implement the model’s actual mechanism.</p>
  <p>The historical TSP papers support the functional-slice explanation here. Public product specifications for later LPUs may describe rack capacity and throughput without disclosing enough detail to construct an accurate die floorplan. The interactive model is therefore a conceptual view of the published architecture.</p>
  ${source("https://doi.org/10.1109/ISCA45697.2020.00023", "Think Fast: A Tensor Streaming Processor")}
  ${check("Check your understanding: does deterministic chip execution guarantee constant API latency?", "No. Request queueing, admission, input length, output length, network delay, and host work still vary. Determinism describes the scheduled execution under specified conditions; the service includes more than the chip.")}
</section>`;
