const source = (url: string, title: string) => `<a class="lesson-source" href="${url}" target="_blank" rel="noreferrer">Read: ${title}</a>`;
const check = (question: string, answer: string) => `<details class="knowledge-check"><summary>${question}</summary><p>${answer}</p></details>`;

export const tensorLesson = `
<section class="lesson" id="probability-and-loss" data-lesson="Loss and training targets"><header><span>Learning signal</span><h3>A wrong answer needs a measurable penalty</h3></header>
<p>During training, the text supplies the answer: at each position, ask the model to predict the next recorded token. Measure how much probability it gave that answer, combine the penalties, and use that single loss to update the shared weights. First make the input–answer pairing explicit.</p>
<h4>One text window provides several training questions</h4>
<p>Take the bytes for “cat” followed by a newline: <code>[99,97,116,10]</code>. A four-token window provides three questions. The input is <code>[99,97,116]</code>; its targets are <code>[97,116,10]</code>, shifted one position ahead.</p>
<div class="method-table"><table><caption>Each row predicts the next byte using only its permitted prefix</caption><thead><tr><th>Output position</th><th>Prefix it may use</th><th>Target byte</th></tr></thead><tbody><tr><th>0</th><td>c · [99]</td><td>a · 97</td></tr><tr><th>1</th><td>ca · [99,97]</td><td>t · 116</td></tr><tr><th>2</th><td>cat · [99,97,116]</td><td>newline · 10</td></tr></tbody></table></div>
<p>The model returns <code>[1,3,256]</code> scores: one batch item, three prediction positions, 256 possible bytes at each position. It can calculate these rows together because the recorded input is available. The <a href="#attention-by-hand">causal mask</a> prevents a row from reading later input positions, even though those bytes already exist elsewhere in memory. Targets are used to score the outputs, not passed in as an extra feature that reveals the answer.</p>
<p>Generation uses the same next-token rule with an unknown answer. Given “ca,” take the output at its final position and select a token. If it selects byte 116, append “t,” then predict again from “cat.” This dependence makes successive generated tokens sequential. During training, the recorded prefixes supply every row; the model does not have to sample “a” before learning from the “ca” row.</p>
<details class="deep-dive"><summary>Locate the shift in the runnable decoder</summary><p>In <a href="#capstone-forward">the companion decoder</a>, <code>loss(sequence)</code> sends <code>sequence[:, :-1]</code> into the model and uses <code>sequence[:, 1:]</code> as targets. The colon selects every batch item; the slices omit the last and first position respectively. Pass the complete window to that method: shifting it again in the caller would teach a different alignment. Other APIs can place this shift elsewhere, so inspect their contract.</p><p>The companion flattens logits from [B,T,V] to [B×T,V] and targets from [B,T] to [B×T] before cross-entropy. Each score row remains paired with its target. These windows have no padding or excluded labels; the <a href="#packing-loss">training objective lesson</a> adds those cases and their loss denominator.</p></details>
${check("If you use [99,97,116] as both input and target, what task have you accidentally created?", "You reward copying the token already visible at the same position. To learn next-token prediction from this window, the targets must be [97,116,10]. A causal mask alone cannot repair a label shift error: it intentionally permits each position to see its own input token.")}
<h4>Turn each answer’s probability into a loss</h4>
<p>Logits are unrestricted real-valued scores. Softmax turns them into probabilities: <code>pᵢ=exp(zᵢ)/Σⱼexp(zⱼ)</code>. Here zᵢ is the score for vocabulary entry i, pᵢ is its probability, and the denominator sums over every vocabulary entry j. Exponentiation makes the unnormalized values positive; division makes the probabilities sum to one.</p>
<p>For target class y, cross-entropy is <code>L=−ln(pᵧ)</code>, where ln is the natural logarithm (the inverse of exp). If the target receives probability 0.5, the penalty is about 0.693 nats; at 0.1, about 2.303. Predicting the correct class with argmax (choosing the highest score) and assigning it a high probability are different tests. A model can keep the same top prediction while substantially improving its loss.</p>
<div class="derivation"><h4>Combine three predictions into one learning signal</h4><p>Suppose the correct bytes in the table receive probabilities ½, ¼ and ⅛. Their losses are approximately 0.693, 1.386 and 2.079. The mean is <code>(0.693+1.386+2.079)/3 ≈ 1.386</code>. Lowering this mean encourages the model to assign more probability to the recorded next bytes. These are illustrative probabilities, not measurements from a trained model.</p></div>
<details class="deep-dive"><summary>Compute the loss safely and read its gradient</summary><p>Adding the same constant to every logit leaves softmax unchanged. Numerically, subtract the maximum score before exponentiating to avoid overflowing on large positive logits. A stable implementation computes <code>L=logsumexp(z)−zᵧ</code>, avoiding the logarithm of a probability that underflowed to zero. Here <code>logsumexp(z)</code> means the logarithm of the sum of the exponentiated scores, evaluated with that stable rearrangement.</p><p>The loss derivative with respect to a logit is <code>∂L/∂zᵢ=pᵢ−1[i=y]</code>, where the indicator is one for the target and zero otherwise. The target score receives a negative derivative; gradient descent increases it. The <a href="#first-weight-update">next lesson</a> follows that derivative back into individual weights.</p></details>
<p>Perplexity is exp(mean negative log-likelihood), using the same tokenization, masking and averaging convention. A uniform distribution over four tokens has loss ln(4) and perplexity 4. Perplexity is not a percentage correct, and comparing it across vocabularies or datasets without context is misleading.</p>
${check("Why must cross-entropy receive logits if the API says it performs log-softmax internally?", "The operation already performs the required normalization. Applying softmax first changes the numbers treated as logits and therefore changes both loss and gradients. Read the API contract and keep the stable logit-to-loss path.")}
${source("https://docs.pytorch.org/docs/2.8/generated/torch.nn.CrossEntropyLoss.html", "PyTorch 2.8: cross-entropy input and target contract")}
${source("https://arxiv.org/abs/1706.03762", "Vaswani et al.: shifted predictions and causal decoder masking")}
</section>
<section class="lesson" id="autodiff" data-lesson="Loss and gradients">
  <header><span>1.2 / From numbers to learning</span><h3>What a gradient actually tells the optimizer</h3></header>
  <div class="lesson-reading"><div>
    <p>A model contains adjustable numbers called parameters. A forward pass uses them to compute predictions. A loss function turns prediction error into one scalar. The gradient tells us how a tiny change to each parameter would change that loss, with the current data held fixed.</p>
    <p>Start with a single prediction: <code>ŷ = wx</code>. If <code>x = 2</code>, <code>w = 3</code>, and the target is <code>y = 4</code>, then <code>ŷ = 6</code>. Using <code>L = ½(ŷ − y)²</code>, the loss is 2. The chain rule gives <code>∂L/∂w = (ŷ − y)x = 4</code>. A gradient-descent update at learning rate 0.1 changes the weight to 2.6; the new prediction is 5.2 and the loss falls to 0.72.</p>
    <p>Backpropagation applies this same chain rule across the tensor graph. For <code>Y = XW</code> and upstream gradient <code>G = ∂L/∂Y</code>, the two matrix derivatives are <code>∂L/∂X = GWᵀ</code> and <code>∂L/∂W = XᵀG</code>. That explains both the extra matrix multiplication during training and why backward needs forward values such as X.</p>
  </div><aside><h4>Follow the shapes</h4><dl><dt>X</dt><dd>[tokens, input features]</dd><dt>W</dt><dd>[input features, output features]</dd><dt>G</dt><dd>[tokens, output features]</dd><dt>XᵀG</dt><dd>[input features, output features]</dd></dl><p>The gradient of a parameter has the same shape as that parameter. A gradient is a sensitivity, not an instruction to change every weight by the same amount.</p></aside></div>
  <div class="lesson-code"><div><h4>One scalar update in TensorFlow</h4><button data-copy-target="gradient-code" class="copy-button">Copy code</button></div><pre id="gradient-code"><code>import tensorflow as tf
w = tf.Variable(3.0)
with tf.GradientTape() as tape:
    prediction = w * 2.0
    loss = 0.5 * tf.square(prediction - 4.0)
gradient = tape.gradient(loss, w)
w.assign_sub(0.1 * gradient)
print(float(gradient), float(w))  # 4.0, approximately 2.6</code></pre></div>
  <h4>A forward value can become backward state</h4>
  <p>The <a href="#probability-and-loss">next-token lesson</a> defines shifted targets and stable cross-entropy; the <a href="#chain-rule-and-sharing">chain-rule derivation</a> explains the matrix gradients above. Now track the values they require. To calculate XᵀG, backward needs the input X from this forward pass. To calculate GWᵀ, it needs the corresponding weights W. Overwriting either before its last reader completes can change the gradient even when the forward output looked correct.</p>
  <p>For a projection with X[2,3] and W[3,4], forward produces Y[2,4]. Backward receives G[2,4] and returns dX[2,3] plus dW[3,4]. The gradient shapes match their owners, while the saved activation shape follows the input. A parameter count alone cannot describe this training memory. <a href="#activation-recomputation">Activation recomputation</a> trades storage for rebuilding selected forward values under a matching computation contract.</p>
  <p>An optimizer updates trainable parameters after the intended gradient accumulation is complete. Autodiff computes derivatives; it does not decide the learning rate, loss denominator or update boundary. In particular, a missing gradient and a numerical gradient of zero need not have the same meaning to a framework or optimizer. Inspect the recorded graph and the API's state rules when connecting a derivative to an update.</p>
  ${check("Check your understanding: why can training process many positions together while decode is sequential?", "During teacher-forced training, the input tokens are known in advance. A causal mask allows their hidden states to be computed in parallel without future leakage. At inference time, the next sampled token is not known until the preceding step completes, so a single sequence has an autoregressive dependency.")}
  ${source("https://www.tensorflow.org/guide/autodiff", "TensorFlow automatic differentiation")}
</section>
<section class="lesson" id="first-weight-update" data-lesson="A weight update"><header><span>Interactive derivation</span><h3>Follow the error back to six weights</h3></header>
<p>A derivative describes how an output changes under a tiny input change. For f(w)=w², the derivative is 2w. For a composed function, multiply local derivatives along a path; when several paths contribute, add them. Reverse-mode automatic differentiation starts at a scalar loss and accumulates these contributions backward through the computation graph.</p>
<p>Here the features are x=[1,2], the vocabulary has three tokens, and W has one row per token. Compute z=Wx, p=softmax(z), then L=−ln(pᵧ). The gradient is <code>∂L/∂Wᵢⱼ=(pᵢ−1[i=y])xⱼ</code>. Gradient descent uses <code>W ← W−η∂L/∂W</code>, where η is the learning rate. This is a deliberately small vocabulary projection, not a full Transformer.</p>
<figure class="textbook-lab" data-first-update><figcaption><span>Interactive 1.2</span><strong>Make the target more likely</strong><p>Step through an update, inspect every derivative, then change the target.</p></figcaption><div class="method-toolbar"><label>Target token<select data-first-target><option value="0">cat</option><option value="1" selected>sat</option><option value="2">ran</option></select></label><label>Learning rate<select data-first-rate><option>0.01</option><option selected>0.1</option><option>1</option></select></label><button data-first-step>Apply one update</button><button data-first-reset>Reset weights</button></div><div class="manual-diagram" data-first-bars></div><div class="method-table" data-first-table></div><p class="manual-status" aria-live="polite" data-first-status></p><p class="figure-boundary">Double-precision browser arithmetic for one linear projection and one example. It omits context, embeddings, attention, optimizer history and stochastic batches. The gradient is checked independently with finite differences.</p></figure>
<p>Initially z=[0.1,0.7,0]. The second token has probability about 0.489 and loss about 0.716. Its row gradient is about [−0.511,−1.021]; with η=0.1, [0.1,0.3] becomes approximately [0.151,0.402]. The other rows move in the opposite direction. Learning changes a distribution through all affected weights, not by setting a single “correct-answer” switch.</p>
<p>A finite-difference check estimates a derivative by <code>(L(w+ε)−L(w−ε))/(2ε)</code>. Compare it with backpropagation on a small smooth problem in FP64. ε must be small enough to approximate a local change but large enough to avoid cancellation. Passing one check does not establish every shape, dtype or distributed reduction; it establishes the derivative tested.</p>
${check("Why can an excessive learning rate make a training run unstable?", "A derivative describes local behavior. A large update can move far beyond the region where that local approximation predicts the loss. Curvature, optimizer history and noisy batches all matter. A simple one-example projection does not model the full stability problem.")}
${source("https://docs.pytorch.org/tutorials/beginner/basics/autogradqs_tutorial.html", "PyTorch: computation graphs and automatic differentiation")}
<p>Later, use the same reasoning through <a href="#framework-same-update">PyTorch, JAX and TensorFlow APIs</a>. That exercise holds inputs and initial weights fixed, then checks the loss, gradient and complete update. It makes the difference between a mathematical derivative and a framework's gradient storage explicit.</p>
</section>
<section class="lesson" id="learning-from-examples" data-lesson="From one update to learning">
<header><span>Put the steps together</span><h3>Learning fits a shared rule to many examples</h3></header>
<p>One update shows how a weight can change. Learning repeats that process across examples: choose a batch, compute predictions with the current weights, reduce its losses to a scalar, compute derivatives, then apply the update. An epoch is one pass through a finite dataset under a stated sampling policy. A training step is one optimizer update; it can accumulate several microbatches. Neither word means that the model has understood every example.</p>
<div class="derivation"><h4>Fit the simplest shared model</h4><p>Use ŷ=wx with two examples: (x,y)=(1,2) and (2,4). The mean half-squared-error loss is <code>L(w)=[(w−2)²+(2w−4)²]/4</code>. At w=0, the loss is (4+16)/4=5. The two example gradients are −2 and −8; their mean is −5. With learning rate 0.1, the update is <code>w←0−0.1(−5)=0.5</code>.</p><p>Now the predictions are 0.5 and 1. The mean loss is (2.25+9)/4=2.8125, lower than before. Both examples changed the same weight. At w=2, this model fits both exactly. It would predict 6 for x=3, but that extrapolation is justified only if the new examples follow the same underlying relationship.</p></div>
<p>A language model uses the same pattern with many weights and a next-token loss. Its features are also learned: a derivative can flow through the output projection, intermediate layers and embedding lookup. An embedding therefore needs no manually assigned meaning for each coordinate. Repeated examples change the rows and transformations in ways that reduce the objective. That does not make each coordinate a named concept or each stored parameter a particular fact.</p>
<h4>Initialization, generalization and the stopping decision</h4>
<p>The weights need starting values. Zero works for the single linear weight above, but setting every weight in a multi-layer network to zero can block gradients or make several units learn identical functions. Suitable random initialization gives units different starting roles while controlling numerical scale. This is distinct from the randomness used to select batches or sample generated tokens.</p>
<p>Lower training loss means a better fit to the examples used for updates. It does not by itself establish better predictions on new data. A large model can memorize patterns specific to its training set. Use a separate validation set to guide choices such as training duration, and reserve a test set for final assessment. The <a href="#evaluation-generalization">evaluation chapter</a> explains leakage, uncertainty and why repeatedly tuning on a test set makes it part of the development process.</p>
${check("If two examples share w but contribute gradients +3 and −1 to a mean loss, what gradient is used? Does a zero batch gradient always mean every example is fitted?", "The equally weighted mean gradient is (+3−1)/2=1. Opposite contributions can cancel; a zero mean gradient need not mean every individual loss is zero or that the point is a minimum. Gradients describe local sensitivity to the chosen aggregate objective.")}
<p>You can now trace prediction, loss, derivative and update. The next chapter constructs the richer function used by a Transformer. The later optimizer chapter changes how accumulated gradients become updates, while the data and evaluation chapters determine which examples and measurements those updates should serve.</p>
${source("https://d2l.ai/chapter_linear-regression/linear-regression.html", "Dive into Deep Learning: fitting a shared linear model")}
${source("https://www.deeplearningbook.org/contents/ml.html", "Goodfellow, Bengio and Courville: training, validation and generalization")}
</section>`;

export const attentionLesson = `
<section class="lesson" id="flashattention" data-lesson="FlashAttention, tile by tile">
  <header><span>3.2 / Algorithm meets memory</span><h3>Keep the answer. Stop storing every score.</h3></header>
  <p>For one query, attention is a weighted average of value vectors. A straightforward implementation writes every query–key score, reads it to compute softmax, writes the probabilities, then reads them for the weighted sum. Full attention still has quadratic pairwise work, but those large intermediate arrays need not live in HBM.</p>
  <p>FlashAttention visits blocks of keys and values while retaining small running statistics on chip. For each query row, keep the largest score <em>m</em>, a rescaled exponential sum <em>ℓ</em>, and a rescaled value numerator <em>u</em>. A new maximum changes the scale of every prior contribution, so rescale the old statistics before adding the new tile. Finally, output <code>u / ℓ</code>.</p>
  <figure class="textbook-lab" id="softmax-lab">
    <figcaption><span>Lab 3.B</span><strong>Compute one attention row in three tiles</strong><p>Step forward. The final tile contains a new maximum, forcing the old accumulated values to rescale.</p></figcaption>
    <div class="tile-memory-map"><div><span>HBM / six keys and values</span><div data-softmax-tiles></div></div><div class="tile-transfer" aria-hidden="true">↓<small>load one tile</small></div><div class="softmax-registers"><span>On-chip running state</span><dl><div><dt>maximum m</dt><dd data-softmax-max>−∞</dd></div><div><dt>denominator ℓ</dt><dd data-softmax-denom>0</dd></div><div><dt>numerator u</dt><dd data-softmax-num>0</dd></div></dl></div></div>
    <div class="lab-action-row"><button data-softmax-step>Load next tile</button><button data-softmax-reset>Reset</button><output data-softmax-result aria-live="polite">No scores processed yet.</output></div>
    <p class="figure-boundary">One query and one value channel; real kernels process matrix tiles, use vector accumulators, and coordinate asynchronous loads. This is an algorithm demonstration, not a hardware timing trace.</p>
  </figure>
  <div class="derivation"><h4>The online update</h4><p><code>m′ = max(m, max(tile scores))</code></p><p><code>α = exp(m − m′)</code></p><p><code>ℓ′ = αℓ + Σ exp(scoreᵢ − m′)</code></p><p><code>u′ = αu + Σ exp(scoreᵢ − m′) valueᵢ</code></p><p>All sums are over the new tile. Subtracting the common maximum prevents exponential overflow; rescaling preserves the same normalized weighted average, up to floating-point rounding.</p></div>
  ${check("Worked check: does FlashAttention make dense attention linear-time?", "No. Dense attention still evaluates a quadratic number of query–key pairs. FlashAttention changes IO and intermediate storage, and improves how work maps to hardware. Sparse attention changes which pairs are computed; recurrent attention changes the representation of history. These are different choices.")}
  ${source("https://arxiv.org/abs/2205.14135", "FlashAttention, especially the IO analysis and algorithm")}
</section>`;

export const postTrainingLesson = `
<section class="lesson" id="post-training-loss" data-lesson="SFT and preference losses">
  <header><span>4.4 / From an objective to tensors</span><h3>The loss mask defines what you teach</h3></header>
  <p>Supervised fine-tuning often trains on assistant responses while keeping the prompt as context. That needs two different masks. The attention mask controls which tokens can be read. The loss mask controls which prediction targets contribute to the objective. A prompt can be visible to attention while contributing zero direct loss.</p>
  <figure class="textbook-lab"><figcaption><span>Figure 4.E</span><strong>Shift the labels, then identify response targets</strong><p>Each column is one prediction position. The token names are schematic, not a specific chat tokenizer.</p></figcaption>
    <div class="sft-alignment" role="img" aria-label="Inputs BOS, user, question, assistant, answer predict labels user, question, assistant, answer, EOS. Only answer and EOS contribute to response-only loss.">
      <span>Input</span><b>BOS</b><b>user</b><b>question</b><b>assistant</b><b>answer</b>
      <span>Target</span><b>user</b><b>question</b><b>assistant</b><b class="learn-target">answer</b><b class="learn-target">EOS</b>
      <span>Loss mask</span><i>0</i><i>0</i><i>0</i><i class="learn-target">1</i><i class="learn-target">1</i>
    </div><p class="figure-boundary">The prediction of “answer” comes from the assistant-marker input position. Build the mask from target-token roles after shifting; an off-by-one error changes the task.</p>
  </figure>
  <p>If the two response targets have losses 0.4 and 0.8, token-mean SFT loss is <code>(0.4 + 0.8) / 2 = 0.6</code>. Dividing by all five positions would silently change the weighting to 0.24. With variable lengths, averaging each example’s mean gives equal weight to examples; averaging all valid tokens gives equal weight to tokens. Neither reduction should happen accidentally.</p>
  <p>Packed conversations need both valid loss targets and the intended attention boundaries. Padding must not become a target. If examples must be independent, their attention mask must prevent cross-example reading; concatenation alone does not guarantee that. Reject a globally all-masked update instead of reporting a misleading zero loss. A local worker or microbatch may have no valid targets and still participate with a zero contribution when other workers have targets.</p>
  <h4>DPO compares two response likelihood ratios</h4>
  <p>For prompt x and response y, πθ(y|x) denotes the policy’s conditional response probability: the product of its next-token probabilities along y. πref denotes the frozen reference model. β is a chosen positive scale, and softplus(u)=ln(1+exp(u)); implementations evaluate it stably. We omit the common prompt from the notation below.</p>
  <p>Let <code>c</code> and <code>r</code> be the chosen and rejected responses to the same prompt. Sum the response-token log probabilities to obtain each conditional sequence log likelihood. Define <code>z = β[(log πθ(c) − log πref(c)) − (log πθ(r) − log πref(r))]</code>. The DPO pair loss is <code>softplus(−z)</code>; the frozen reference supplies the comparison baseline. This pair loss alone does not guarantee a bound on the policy’s divergence from that reference.</p>
  <div class="derivation"><h4>A pair you can calculate by hand</h4><p>Suppose policy log likelihoods are −4 for the chosen answer and −6 for the rejected answer. Both reference log likelihoods are −5. At β = 0.1, the margin is <code>z = 0.1[(−4 + 5) − (−6 + 5)] = 0.2</code>.</p><p>The loss is <code>log(1 + exp(−0.2)) ≈ 0.5981</code>, below the equal-margin loss <code>log 2 ≈ 0.6931</code>. Increasing this relative margin lowers the loss. It does not guarantee that either answer is factually correct.</p></div>
  <div class="lesson-code"><div><h4>A numerically stable DPO loss in TensorFlow</h4><button data-copy-target="dpo-code" class="copy-button">Copy code</button></div><pre id="dpo-code"><code>import tensorflow as tf

def dpo_loss(policy_chosen, policy_rejected,
             reference_chosen, reference_rejected, beta=0.1):
    # Each argument: [batch] response-summed log likelihoods.
    reference_gap = tf.stop_gradient(
        reference_chosen - reference_rejected)
    margin = beta * (policy_chosen - policy_rejected - reference_gap)
    return tf.reduce_mean(tf.nn.softplus(-margin))

# The companion's sequence_log_probs computes these sums from
# [batch, time, vocabulary] logits and a response-only target mask.</code></pre></div>
  <p>Standard DPO uses sequence sums, not length-normalized token averages. Changing that reduction changes the objective. Keep the tokenizer, chat template, masking, and reference checkpoint fixed and versioned. A falling preference loss needs a separate held-out assessment of helpfulness, correctness, and undesirable behavior.</p>
  ${check("Check your understanding: does masking prompt loss stop gradients from flowing through the prompt?", "No. Response predictions attend to prompt representations. Their loss can backpropagate through those representations and the parameters that produced them. A loss mask removes direct prediction targets; it is not a stop-gradient operation.")}
  ${source("https://arxiv.org/abs/2305.18290", "Direct Preference Optimization")}
</section>
<section class="lesson" id="adapters-rollouts" data-lesson="LoRA and rollout systems">
  <header><span>4.5 / Which weights, which experiences?</span><h3>Adapters change storage. Rollouts change the workload.</h3></header>
  <p>Low-rank adaptation (LoRA) freezes a base matrix and learns a small update. Using row-vector conventions, <code>Y = XW + (α/r)XAB</code>, where W has shape [dᵢₙ, dₒᵤₜ], A is [dᵢₙ, r], and B is [r, dₒᵤₜ]. Only A and B need trainable optimizer state. With a 4,096 × 4,096 base matrix and rank 8, the adapter has 65,536 parameters instead of 16,777,216: 0.39% as many.</p>
  <div class="adapter-flow" role="img" aria-label="Input X takes two paths: a frozen base matrix W and trainable rank-r matrices A then B. The scaled adapter output is added to the base output."><strong>X</strong><div><span>Frozen W · wide → wide</span><span>Train A · wide → r <b>→</b> Train B · r → wide <small>scale α/r</small></span></div><strong>+ → Y</strong></div>
  <p>Initialize A with small random nonzero values and B to zero so the starting output equals the base model. The first step can update B through the nonzero A even though the gradient of A initially vanishes. If both factors start at zero, both gradients vanish and this branch cannot start learning. LoRA reduces trainable state, but the base weights still occupy memory and the backward pass still needs activations. Merging the update into W can remove the extra serving branch when the deployment format permits it.</p>
  ${source("https://arxiv.org/abs/2106.09685", "LoRA: Low-Rank Adaptation of Large Language Models")}
  <h4>A reinforcement-learning step starts by generating experience</h4>
  <p>In supervised learning the target response arrives with the dataset. In on-policy reinforcement learning the current policy first generates responses. A verifier or reward model scores them, then the learner changes the policy. Rollout generation has inference-like scheduling and KV-memory costs; the update has training-like activation and optimizer costs.</p>
  <div class="rollout-flow"><span>Version policy θₖ</span><b>→</b><span>Generate K answers</span><b>→</b><span>Verify + compute advantages</span><b>→</b><span>Optimize → θₖ₊₁</span></div>
  <p>A group-relative method can compare sampled answers to other answers for the same prompt without fitting a separate value network. As an illustrative normalization, rewards <code>[1, 0, 1, 0]</code> have mean 0.5 and population standard deviation 0.5, yielding advantages <code>[1, −1, 1, −1]</code>. An all-equal group has no relative signal; an epsilon prevents division by zero but cannot create information.</p>
  <p>That advantage calculation is only one piece of GRPO-style training. The complete objective must specify old-policy probabilities, probability ratios, clipping, KL treatment, token masking, and sequence/token reduction. Later variants alter these choices. Do not implement a policy optimizer by multiplying log probabilities by rewards and assuming all these objectives are equivalent.</p>
  ${source("https://arxiv.org/abs/2402.03300", "DeepSeekMath and the original GRPO formulation")}
  <h4>Record enough to diagnose an apparent improvement</h4>
  <p>Store the rollout policy version, prompt identity, sampled tokens, old log probabilities, termination reason, verifier version, reward, and token mask. Monitor reward alongside completion length, truncation, entropy, KL, and independent task accuracy. A reward increase caused by exploiting the verifier is a data point about the verifier, not proof of improved reasoning.</p>
  ${check("Design exercise: a code reward gives one point whenever a program prints the expected output. What is missing?", "A solution can hard-code a known answer without solving the task. Evaluate on hidden inputs, isolate execution, enforce resource limits, and distinguish syntax/runtime failures from wrong answers. Keep a held-out task set separate from the verifier feedback used for optimization.")}
  <p class="companion-inline">Runnable loss and adapter implementations, with gradient tests: <a href="https://github.com/djsydney04/inference_and_training_systems/tree/main/examples/tensorflow">examples/tensorflow/post_training.py</a>.</p>
</section>`;

export const hardwareLesson = `
<section class="lesson" id="cpu-execution" data-lesson="Inside a CPU core">
  <header><span>5.3 / The host is part of the machine</span><h3>From an instruction to a committed result</h3></header>
  <p>A CPU core fetches instructions, decodes them, locates operands, performs operations, and retires completed work into the program’s architectural state. Modern high-performance cores overlap many instructions and may execute independent operations before older stalled ones. They still preserve the observable rules of the instruction set.</p>
  <figure class="textbook-lab cpu-figure"><figcaption><span>Figure 5.C</span><strong>A conceptual out-of-order core</strong><p>Select a stage to follow the responsibilities of the hardware.</p></figcaption>
    <div class="cpu-flow"><button data-cpu-stage="fetch">Fetch<small>PC + prediction</small></button><b>→</b><button data-cpu-stage="decode">Decode<small>instructions → operations</small></button><b>→</b><button data-cpu-stage="rename">Rename<small>physical registers</small></button><b>→</b><button data-cpu-stage="issue">Issue<small>ready operands</small></button><b>→</b><button data-cpu-stage="execute">Execute<small>ALU / vector / LSU</small></button><b>→</b><button data-cpu-stage="retire">Retire<small>commit in order</small></button></div>
    <div class="cpu-cache-path"><span>Load/store unit</span><i>↔</i><span>TLB + L1</span><i>↔</i><span>L2 / shared cache</span><i>↔</i><span>DRAM controller</span></div>
    <div class="diagram-explanation" data-cpu-readout aria-live="polite"><strong>Fetch</strong><p>The program counter identifies the next instruction. Branch prediction guesses the next path early enough to keep the pipeline supplied.</p></div>
    <p class="figure-boundary">Conceptual high-performance CPU; pipeline widths, cache topology, instruction decomposition, and ordering details depend on the microarchitecture and ISA.</p>
  </figure>
  <div class="lesson-reading"><div><h4>Registers, caches, and virtual memory solve different problems</h4><p>Registers hold instruction operands and results. An immediate is a literal value encoded in an instruction, a different concept. Caches keep nearby or recently used memory lines close to the core. The translation lookaside buffer (TLB) caches virtual-to-physical address translations. A cache miss and a TLB miss are distinct events, although either can delay a load.</p><p>Register renaming assigns physical storage to logical register names, removing false dependencies caused by reusing a name. It cannot remove a true dependency: an addition that consumes a load must wait for that load’s value. Branch misprediction can discard speculative work and redirect fetch.</p></div><aside><h4>Why an inference engineer cares</h4><p>Tokenization, request parsing, batching, driver launches, sampling setup, and networking use CPU time. A GPU timeline with gaps may indicate a host bottleneck. Measure CPU threads and GPU launches together before optimizing a kernel that is already fast.</p></aside></div>
  ${source("https://developer.arm.com/-/media/Arm%20Developer%20Community/PDF/Learn%20the%20Architecture/Armv8-A%20Instruction%20Set%20Architecture.pdf", "Arm instruction-set and CPU fundamentals")}
</section>
<section class="lesson" id="warp-memory" data-lesson="Warps, registers, and memory">
  <header><span>5.4 / A request becomes transactions</span><h3>Thirty-two loads can be cheap or expensive</h3></header>
  <p>A CUDA warp contains 32 logical threads. If neighboring lanes load neighboring four-byte values, their requests can use a compact set of memory sectors. If the addresses are far apart, each sector carries fewer useful bytes. This is why the tensor’s physical layout matters even when the mathematical operation is unchanged.</p>
  <figure class="textbook-lab"><figcaption><span>Lab 5.D</span><strong>Explore memory coalescing</strong><p>All 32 lanes load one FP32 value. The stride changes the distance between their addresses.</p></figcaption><div class="lab-action-row"><label>Stride, in floats <select data-memory-stride><option value="1">1 · adjacent</option><option value="2">2 · every other</option><option value="4">4 · spread out</option><option value="8">8 · one sector each</option></select></label><output data-memory-efficiency aria-live="polite"></output></div><div class="lane-strip" data-memory-lanes aria-label="32 lane requests"></div><div class="sector-map" data-memory-sectors aria-label="Memory sectors touched"></div><p class="figure-boundary">Aligned base, four-byte loads, ideal 32-byte sector counting. Cache hits, instruction splitting, larger transfers, ECC, and architecture-specific behavior affect actual DRAM traffic.</p></figure>
  <h4>A warp waits; the scheduler looks for another ready warp</h4><p>A dependent instruction cannot issue until its input is ready. The scheduler can issue an eligible instruction from another resident warp while that load is outstanding. Registers for those resident warps remain allocated on the SM; switching among them does not require an operating-system context switch.</p>
  <p>Occupancy measures resident work relative to a hardware maximum. Register allocation, shared-memory allocation, threads per block, and block limits constrain it. More occupancy helps only if additional independent work covers otherwise exposed latency. A kernel can be fast at moderate occupancy when it has enough instruction-level parallelism or a well-pipelined tensor-core workload.</p>
  <div class="lesson-code"><div><h4>The same operation, different lane addresses</h4><button data-copy-target="coalescing-code" class="copy-button">Copy code</button></div><pre id="coalescing-code"><code>// Demonstration kernel; x must contain at least n * stride floats.
__global__ void gather(const float* x, float* y, int n, int stride) {
    int i = blockIdx.x * blockDim.x + threadIdx.x;
    if (i &lt; n) y[i] = x[i * stride];
}
// Compare stride=1 with stride=8 using a memory profiler.
// Keep n, dtype, launch dimensions, and cache conditions fixed.</code></pre></div>
  ${check("Worked check: 32 lanes load 4 bytes each at stride 8. What is useful-sector efficiency?", "Each address is 32 bytes from the previous address, so the simplified model touches 32 sectors. It transfers 32 × 32 = 1,024 bytes for 128 useful bytes: 12.5%. At stride 1, the same payload fits into four aligned sectors, giving 100% useful-sector efficiency.")}
  ${source("https://docs.nvidia.com/cuda/cuda-programming-guide/", "NVIDIA’s current CUDA Programming Guide")}
</section>`;

export const rackLesson = `
<section class="lesson" id="hardware-photographs" data-lesson="Read the real hardware">
  <header><span>6.2 / Reference images</span><h3>Connect the cutaway to the physical system</h3></header>
  <p>Use these NVIDIA reference images as visual anchors. The rack view establishes scale; the tray view reveals serviceable components; the block diagram distinguishes the GPU fabric from host and network connections. Open any figure to inspect it at full size.</p>
  <div class="reference-gallery">
    <figure><button class="figure-open" data-figure-open="figures/gb200-racks.png" aria-label="Enlarge NVIDIA DGX GB200 rack image"><img src="figures/gb200-racks.png" alt="NVIDIA reference image showing four DGX GB200 racks with stacked compute and switch trays" loading="lazy" width="1200" height="680" /></button><figcaption><strong>Rack scale</strong><p>Four DGX GB200 racks shown; each rack is its own NVLink domain. Source: NVIDIA reference architecture, Figure 2.</p></figcaption></figure>
    <figure><button class="figure-open" data-figure-open="figures/gb200-tray.png" aria-label="Enlarge GB200 compute tray image"><img src="figures/gb200-tray.png" alt="Front of a NVIDIA GB200 compute tray showing networking and service interfaces" loading="lazy" width="1200" height="420" /></button><figcaption><strong>Compute tray</strong><p>Front access exposes service and scale-out connections. Source: NVIDIA reference architecture, Figure 3.</p></figcaption></figure>
    <figure class="reference-wide"><button class="figure-open" data-figure-open="figures/gb200-topology.png" aria-label="Enlarge official GB200 compute-tray block diagram"><img src="figures/gb200-topology.png" alt="Official block diagram locating two Grace CPUs, four B200 GPUs, and network interfaces within a GB200 compute tray" loading="lazy" width="1400" height="700" /></button><figcaption><strong>Trace an interface</strong><p>Locate a CPU–GPU connection, a GPU–GPU fabric connection, and a network adapter. They serve different communication scopes. Source: NVIDIA reference architecture, Figure 5. Images © NVIDIA; captions are original.</p></figcaption></figure>
  </div>
  ${source("https://docs.nvidia.com/dgx-superpod/reference-architecture-scalable-infrastructure-gb200/latest/dgx-superpod-components.html", "NVIDIA DGX GB200 reference architecture and full-resolution figures")}
</section>
<section class="lesson" id="network-budget" data-lesson="Fiber and communication budgets">
  <header><span>6.3 / Bytes across distance</span><h3>Separate propagation, serialization, and queueing</h3></header>
  <p>A link’s bandwidth describes how quickly it can transmit bits. Latency also includes signal propagation, switches, protocol processing, and waiting in queues. A short message can be dominated by fixed overhead; a large transfer often exposes the payload bandwidth. The basic lower-bound model is <code>time ≈ fixed latency + bytes / effective bytes per second</code>.</p>
  <div class="network-equations"><div><span>400 Gb/s link</span><strong>50 GB/s</strong><p>Divide bits by eight before comparing with memory bandwidth. Encoding and protocol overhead reduce useful throughput.</p></div><div><span>1 GB payload</span><strong>20 ms minimum</strong><p>At 50 GB/s, serialization alone takes 0.02 seconds. A nominal link rate is not an application-level guarantee.</p></div><div><span>100 m of fiber</span><strong>≈ 0.5 μs</strong><p>Using an illustrative propagation speed near 2 × 10⁸ m/s. Transceivers, switches, and queueing add latency.</p></div></div>
  <p>An optical transmitter modulates light; a receiver detects it and reconstructs the electrical signal. Multiple wavelengths can share one fiber, and multiple lanes can be aggregated into a port. Connectors, wavelength count, fiber count, and port bit rate are separate quantities. SerDes and forward error correction remain part of the path even when the cable is optical.</p>
  <h4>Place communication according to how often it happens</h4><p>Tensor parallelism communicates inside layers, so its latency and bandwidth requirements often favor the strongest local fabric. Data parallelism can overlap gradient collectives with backward work. Expert parallelism redistributes tokens and is sensitive to imbalanced destinations. Placement is a workload decision: topology, message size, overlap, and the slowest rank all matter.</p>
  ${check("Worked check: how much data does a ring all-reduce send per rank?", "For p ranks and an S-byte tensor, an ideal ring reduce-scatter followed by all-gather sends 2(p−1)S/p bytes per rank. For eight ranks and a 1 GB tensor, that is 1.75 GB sent per rank, spread across 14 steps. Startup latency and the achievable payload rate determine elapsed time; this is not a claim that every collective uses a ring.")}
  ${source("https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/usage/collectives.html", "NCCL collective operations")}
</section>`;

export const inferenceLesson = `
<section class="lesson" id="paged-kv" data-lesson="Paged KV memory">
  <header><span>7.4 / State with an address book</span><h3>A sequence can be contiguous in meaning and scattered in memory</h3></header>
  <p>Each request has a logical order of tokens. Its KV tensors can occupy fixed-size physical blocks anywhere in an allocation pool. A block table maps logical positions to physical blocks; the attention kernel follows this mapping. That lets a growing request acquire another free block without moving its entire history.</p>
  <figure class="textbook-lab"><figcaption><span>Lab 7.D</span><strong>Two requests share an eight-token prefix</strong><p>Blocks contain four token positions. Advance decode to allocate a new block, then finish a request to release its private blocks.</p></figcaption><div class="cache-tables" data-cache-tables></div><div class="physical-cache" data-physical-cache aria-label="Physical KV block pool"></div><div class="lab-action-row"><button data-cache-append="A">Decode A</button><button data-cache-append="B">Decode B</button><button data-cache-release="A">Finish A</button><button data-cache-reset>Reset</button></div><p class="diagram-explanation" data-cache-status aria-live="polite"></p><p class="figure-boundary">A logical illustration of one layer’s block map. Production layouts include K and V, heads, dtype, alignment, reference counts, eviction policy, and distributed ownership.</p></figure>
  <p>Complete matching prefixes can share immutable blocks. A shared block stays allocated until every dependent request releases it. If a system allows sharing an unfinished block and one branch appends to it, that branch needs a private copy before writing. This is copy-on-write.</p>
  <p>Prefix reuse requires more than identical visible words: token IDs and their preceding context must match, and model, adapter, position handling, and relevant multimodal inputs must agree. Prefix caching saves repeated prefill work. It does not eliminate attention over the cached context during later decode.</p>
  ${source("https://arxiv.org/abs/2309.06180", "PagedAttention and the original vLLM system")}
  ${source("https://docs.vllm.ai/en/latest/features/automatic_prefix_caching/", "vLLM automatic prefix caching")}
  ${check("Check your understanding: when A finishes, may blocks shared with B return to the free list?", "No. Finishing A removes A’s references. Shared prefix blocks still have a live reference from B, so only A’s private blocks become free. Reusing a referenced block would corrupt B’s context.")}
</section>
<section class="lesson" id="serving-budgets" data-lesson="Serving latency and quantization">
  <header><span>7.5 / Measure the service a user receives</span><h3>Throughput is only one part of a serving result</h3></header>
  <div class="lesson-reading"><div><h4>Prefill and decode compete for different resources</h4><p>Prefill has many known input positions and can form larger matrix multiplications. Decode adds one position per active sequence per iteration. At low batch sizes, reading model weights can dominate; with enough batching, those reads are amortized. Long contexts add substantial KV reads, and MoE routing or collectives can change the dominant cost.</p><p>Continuous batching changes membership between iterations: finished requests leave and new requests enter. Chunked prefill breaks large prompts into smaller pieces so one prompt has less opportunity to delay active decoders. The scheduler must budget both token work and available cache blocks.</p></div><aside><h4>Report the workload</h4><p>Model revision, precision, input/output lengths, concurrency, request-arrival process, hardware, software versions, and latency percentiles belong beside a tokens-per-second number. Average latency hides queueing tails.</p></aside></div>
  <div class="service-timeline"><span>arrival</span><div>queue</div><div>prefill</div><b>first token</b><div>decode → decode → decode</div><span>complete</span></div>
  <p>Time to first token (TTFT) includes queueing and prompt processing. Inter-token latency describes how quickly subsequent tokens arrive. End-to-end latency adds the whole generation. Goodput counts completed work that meets the chosen service-level objective; raising raw throughput while missing deadlines can lower goodput.</p>
  <h4>Quantization changes both storage and numerical error</h4><p>A simple uniform quantizer represents a value approximately as <code>x ≈ scale × (integer − zero_point)</code>. Per-channel or per-group scales trade metadata for a closer fit to local ranges. Weight-only quantization compresses weights; activation and KV quantization affect different tensors and therefore different accuracy and bandwidth paths.</p><p>Four-bit weights ideally use half a byte per parameter: 7 billion parameters need 3.5 GB of raw payload. Scales, packing, untouched tensors, temporary buffers, and runtime state increase that figure. A four-bit file does not establish that every operation executes with four-bit arithmetic. Kernel support and the actual dequantization path determine speed.</p>
  ${check("Design an experiment: how would you compare two serving configurations fairly?", "Replay the same tokenized request set and arrival schedule; warm up both configurations; keep the model, output constraints, and sampling policy fixed. Report throughput together with TTFT, inter-token latency, end-to-end percentiles, error rate, and cache behavior. Repeat runs and identify whether the load is below or above saturation.")}
  ${source("https://docs.vllm.ai/en/latest/configuration/optimization/", "vLLM optimization and performance tuning")}
</section>`;

export const lpuLesson = `
<section class="lesson" id="lpu-schedule" data-lesson="A compiler owns the timetable">
  <header><span>8.3 / Deterministic execution</span><h3>Schedule when an operand arrives, not only what computes it</h3></header>
  <p>In the published Tensor Streaming Processor design, the compiler coordinates operations and data movement across functional slices. A matrix unit needs its operands in the correct place at the correct time. Explicit scheduling turns those dependencies into a timetable that accounts for movement latency and resource use.</p>
  <figure class="textbook-lab"><figcaption><span>Figure 8.C</span><strong>A teaching schedule for one tensor tile</strong><p>Read across for time, down for a resource. The marked delay waits for operands. Compute C, activate it to Y, route Y, then store Y in separate abstract stages.</p></figcaption><div class="schedule-grid"><span>resource / step</span><b>0</b><b>1</b><b>2</b><b>3</b><b>4</b><b>5</b><b>6</b><span>MEM / SRAM</span><i class="scheduled">read A</i><i class="scheduled">read B</i><i class=""></i><i class=""></i><i class=""></i><i class=""></i><i class="scheduled">write Y</i><span>SXM / routing</span><i class=""></i><i class="scheduled">move A</i><i class="scheduled">move B</i><i class=""></i><i class=""></i><i class="scheduled">move Y</i><i class=""></i><span>MXM / matrix</span><i class=""></i><i class=""></i><i class="waiting">operands</i><i class="scheduled">C = A × B</i><i class=""></i><i class=""></i><i class=""></i><span>VXM / vector</span><i class=""></i><i class=""></i><i class=""></i><i class=""></i><i class="scheduled">Y = act(C)</i><i class=""></i><i class=""></i></div><p class="figure-boundary">Original conceptual schedule; columns are abstract stages, not measured chip cycles. This is not an executable Groq program or a disclosure of current-generation instruction timing.</p></figure>
  <h4>Why model placement spans many chips</h4><p>On-chip SRAM is fast but has limited capacity. When weights and state exceed one chip’s memory, a compiled deployment partitions them across chips. The resulting system must move activations and coordinate schedules across links. Predictable execution does not make communication free or remove the need for enough aggregate storage.</p>
  <p>For inference, ask where each layer’s weights live, where persistent attention state lives, how batches and sequence lengths are represented, and what recompilation or specialization is needed. A recurrent attention layer and a growing KV cache have different storage behavior; the compiler and runtime must implement the model’s actual mechanism.</p>
  <p>The historical TSP papers support the functional-slice explanation here. Public product specifications for later LPUs may describe rack capacity and throughput without disclosing enough detail to construct an accurate die floorplan. The interactive model is therefore a conceptual view of the published architecture.</p>
  ${source("https://doi.org/10.1109/ISCA45697.2020.00023", "Think Fast: A Tensor Streaming Processor")}
  ${check("Check your understanding: does deterministic chip execution guarantee constant API latency?", "No. Request queueing, admission, input length, output length, network delay, and host work still vary. Determinism describes the scheduled execution under specified conditions; the service includes more than the chip.")}
</section>`;
