import { sourceLink as ref, workedCheck as check } from "./lesson-template";

export const positionLesson = `
<section class="lesson" id="position-rotations" data-lesson="Position and rotary embeddings">
<header><span>Order becomes part of the calculation</span><h3>Content alone does not specify a token’s position</h3></header>
<p>An embedding lookup gives the same initial vector to every occurrence of an ID. Yet “the dog followed the child” and “the child followed the dog” describe different relationships. A model needs a way to use order. The causal mask already distinguishes permitted past positions from forbidden future positions; an explicit position mechanism supplies further information about location or relative displacement.</p>
<p>Without a mask or position-dependent information, self-attention is permutation-equivariant: reorder the input rows and its output rows reorder in the same way. The operation has no independent label saying “this is the third row in the original sentence.” Causal masking changes that symmetry, but should not be confused with learning a complete representation of token distance. Different architectures choose learned position vectors, sinusoidal additions, relative score biases or rotations.</p>
<h4>A rotation is a small linear map you can calculate</h4>
<p>Represent one channel pair as [a,b]. Rotating it by angle φ gives <code>[a cos φ − b sin φ, a sin φ + b cos φ]</code>. Cosine and sine are the horizontal and vertical coordinates of a unit circle at that angle; φ is measured in radians, with 2π radians in a full turn. A quarter turn has φ=π/2, cosine zero and sine one, so [a,b] becomes [−b,a].</p>
<div class="derivation"><h4>The dot product sees the angle difference</h4><p>Let q=[1,0] and k=[1,0]. Before rotation q·k=1. Rotate q by 0 and k by π/2: their dot product becomes [1,0]·[0,1]=0. Rotate both an additional π/2: now q′=[0,1] and k′=[−1,0], and the dot product is still zero.</p><p>More generally, write the pair as a column and its rotation matrix as R(φ). Since R(α)ᵀR(β)=R(β−α), <code>(R(mθ)q)ᵀ(R(nθ)k)=qᵀR((n−m)θ)k</code>. Here m and n are token positions, and θ is a frequency expressed as angle per position. Moving both positions by the same offset preserves this relative-angle term.</p></div>
<p>Rotary position embeddings, or RoPE, apply such rotations to query and key channel pairs. For a common even-width head with d channels, pair i can use <code>θᵢ=base^(−2i/d)</code>, for i=0,…,d/2−1 and a chosen base greater than one. Several frequencies let the score contain several scales of positional variation. This is the standard geometric construction; model variants can rotate a subset of channels or change the frequency schedule.</p>
<p>RoPE does not add channels, convert a position into a vocabulary ID or require rotating the value vectors in the variant used here. It changes the query–key comparison before softmax. Its dot product also depends on the learned q and k content; it is not simply a distance lookup table.</p>
<h4>Cached decoding must retain the position convention</h4>
<p>After a prompt of 100 positions numbered 0 through 99, a newly appended token normally has position 100, even when its current input tensor has length one. Using local tensor index zero as its RoPE position would compare a newly rotated query against keys encoded under a different position system. Cache equivalence requires consistent absolute positions, masks and the model’s selected RoPE variant.</p>
<p>The relative-angle identity is not a guarantee of unlimited context length. A model learned under a particular position distribution, frequency configuration and attention pattern. Extending a context limit changes the problem it encounters. Validate quality and cached/full-prefix agreement under the intended context settings; memory fitting is a separate condition.</p>
${check("If both query and key positions increase by 7 under the same fixed RoPE frequencies, what changes in their pairwise relative-angle term?", "Nothing: (n+7)−(m+7)=n−m. This is a property of that pairwise rotation identity. It does not say that adding seven real tokens to a prompt leaves the full model’s activations or probabilities unchanged.")}
${ref("https://arxiv.org/abs/2104.09864", "Su et al.: RoFormer and the rotary position identity")}
${ref("https://arxiv.org/abs/1706.03762", "Vaswani et al.: attention and positional encodings")}
</section>`;

export const normalizationLesson = `
<section class="lesson" id="normalization-and-residual-math" data-lesson="Normalization and residual derivatives">
<header><span>Scale, direction and a path for gradients</span><h3>Normalize a branch while preserving the residual stream</h3></header>
<p>The preceding drawing puts normalization on a branch before an attention or feed-forward operation. Make that calculation explicit for one token with D channels. Define its mean <code>μ=(1/D)Σᵢ xᵢ</code> and variance <code>v=(1/D)Σᵢ(xᵢ−μ)²</code>. Here the denominator is D because these are the token’s channel statistics, not an unbiased estimate of an unknown population variance.</p>
<p>LayerNorm computes <code>yᵢ=γᵢ(xᵢ−μ)/√(v+ε)+βᵢ</code>. The vectors γ and β are learned per-channel gain and bias; ε is a small positive stability constant. RMSNorm instead uses the root mean square <code>r=√((1/D)Σᵢxᵢ²+ε)</code> and computes <code>yᵢ=γᵢxᵢ/r</code> in the bias-free form used here. It does not subtract μ. Both reduce across channels within one token, leaving [B,T,D] unchanged.</p>
<div class="derivation"><h4>Use the same vector in both normalizations</h4><p>Take x=[3,4], unit gains and zero bias. To keep the arithmetic transparent in this nonzero example, temporarily set ε=0. LayerNorm has μ=3.5 and v=0.25, so its output is [−1,1]. RMSNorm has r=√12.5≈3.5355, so its output is approximately [0.8485,1.1314].</p><p>The RMS of the second output is one, but its mean is not zero. The two operations are therefore not interchangeable. With a nonzero ε, normalization is only approximately invariant to positive rescaling; learned gains also change the output magnitudes.</p></div>
<h4>The denominator also depends on the input</h4>
<p>For RMSNorm and upstream derivative gᵢ=∂L/∂yᵢ, define hᵢ=gᵢγᵢ. Differentiating both the numerator and r gives:</p>
<div class="derivation"><h4>Follow both routes from x to the loss</h4><p><code>∂L/∂xᵢ = hᵢ/r − xᵢ[Σⱼ hⱼxⱼ]/(D r³)</code></p><p>The first term is the direct path through xᵢ. The second is the indirect path through the common denominator, which depends on every channel. Ignoring that path would incorrectly treat r as a constant.</p><p>For x=[3,4], γ=[1,1], g=[1,−1] and ε=0, the dot product Σhⱼxⱼ is −1. The resulting input derivative is approximately [0.31678,−0.23759]. Its dot product with x is zero: infinitesimally scaling this nonzero vector has no effect on this ε=0 normalized output. At ε&gt;0 that exact cancellation generally no longer holds.</p></div>
<p>The gain derivative for one token is <code>∂L/∂γᵢ=gᵢxᵢ/r</code>. Because every token uses the same γ, accumulate its contributions across batch and token positions. The <a href="#cuda-rmsnorm-backward">normalization kernel lesson</a> turns these two different reductions into concrete parallel work: channels for the input derivative, rows for the shared gain derivative.</p>
<h4>A residual adds an identity contribution, not a guarantee</h4>
<p>Write a block as <code>y=x+F(N(x))</code>, where N is normalization and F is the branch. If g is the loss gradient at y, the gradient at x is <code>g + J_N(x)ᵀ J_F(N(x))ᵀ g</code>. J names a Jacobian. The first term follows the direct addition path. The second follows the learned branch backward through F and N.</p>
<p>This structure gives the branch a way to learn an update to an existing representation. It does not guarantee that gradients cannot grow, shrink or cancel, or that every layer is stable without appropriate initialization and optimization. The location of normalization matters: applying it after the addition changes which derivative lies on the direct path.</p>
${check("Why does a normalization gain vector have D parameters rather than B×T×D parameters?", "The same per-channel gain is reused at all batch and token positions. Its gradient sums contributions from those uses. Increasing the input’s batch or sequence length changes activations and arithmetic, not the number of learned gain values.")}
${ref("https://arxiv.org/abs/1910.07467", "Zhang and Sennrich: RMSNorm")}
${ref("https://arxiv.org/abs/1607.06450", "Ba, Kiros and Hinton: Layer Normalization")}
${ref("https://arxiv.org/abs/2002.04745", "Xiong et al.: normalization placement in Transformers")}
</section>`;

export const transformerBudgetLesson = `
<section class="lesson" id="transformer-parameter-budget" data-lesson="Parameters, activations and compute">
<header><span>Turn the block into a resource ledger</span><h3>Count learned values separately from values produced by an input</h3></header>
<p>A block diagram becomes useful for systems work when every box has a shape and an owner. Use the small network’s configuration: L=3 blocks, model width D=8, Hq=2 query heads, head width d=4, Hkv=1 key/value head, feed-forward width F=24 and vocabulary V=32. Assume bias-free projections, two RMSNorm gain vectors per block, a final RMSNorm, and an untied output matrix. These are declared teaching choices, not a vendor model specification.</p>
<div class="method-table"><table><caption>Learned values in the illustrative grouped-query decoder</caption><thead><tr><th>Parameter</th><th>Shape or expression</th><th>Values</th></tr></thead><tbody><tr><th>Query projection</th><td>[D,Hq×d] = [8,8]</td><td>64 per block</td></tr><tr><th>Key and value projections</th><td>Two [D,Hkv×d] = [8,4]</td><td>64 per block together</td></tr><tr><th>Attention output projection</th><td>[Hq×d,D] = [8,8]</td><td>64 per block</td></tr><tr><th>SwiGLU matrices</th><td>Two [D,F] and one [F,D]</td><td>576 per block</td></tr><tr><th>Block normalization gains</th><td>2D</td><td>16 per block</td></tr><tr><th>Input and output matrices</th><td>VD + DV</td><td>512 for the model</td></tr><tr><th>Final normalization gain</th><td>D</td><td>8 for the model</td></tr></tbody></table></div>
<p>Each block has 64+64+64+576+16=784 parameters. The complete model has <code>3×784+512+8=2,872</code>. Tying the input and output weights stores their shared 256 values once and reduces the total to 2,616. Sharing one key/value head reduces K/V projection parameters, but the two query heads still perform their own attention comparisons.</p>
<h4>Input length changes storage even when the model stays fixed</h4>
<p>At B=1 and T=4, one residual activation contains BTD=32 values. In BF16, a two-byte storage format, that is 64 bytes. Across all layers, a dense K/V cache stores <code>2LBTHkv d</code> values: two tensors, layers, batch, cached positions, key/value heads and channels. This configuration uses 96 values or 192 BF16 bytes at T=4. At T=400 it uses 19,200 bytes, while the stored model weights remain 5,744 BF16 bytes.</p>
<p>These are payload counts. Real allocations can add padding, page metadata, alignment and temporary buffers. Training adds gradients, optimizer state and forward values needed by backward; it does not normally use an autoregressive serving cache as its activation-saving strategy. The <a href="#training-state">training ledger</a> and <a href="#paged-kv">KV lesson</a> account for their respective states.</p>
<h4>Derive the arithmetic instead of reading it off the parameter count</h4>
<p>A dense matrix multiplication [M,K]×[K,N] computes MN dot products of length K. Using the common convention of two FLOPs per multiply-add gives approximately 2MKN FLOPs. A projection reuses the same matrix across M=BT token rows, so its matrix arithmetic is approximately twice its weight count per token. Embedding lookup is a gather, not a dense multiplication by a one-hot vector in an efficient implementation.</p>
<div class="derivation"><h4>Why attention becomes expensive at long context</h4><p>For full square score matrices, QKᵀ across B batches and Hq heads costs about <code>2B Hq T²d</code> FLOPs. Multiplying probabilities by V costs about the same, totaling <code>4B Hq T²d</code>, excluding softmax, masking and projections. A causally optimized implementation can skip forbidden pairs; a dense implementation may calculate them before masking.</p><p>For one cached decode query attending to T keys, those two matrix operations instead total approximately <code>4B Hq T d</code> FLOPs. The individual decode step is linear in its current context length, while generating many steps accumulates growing costs. KV caching saves recomputation of earlier keys and values; it does not make reading their history free.</p></div>
<p>For one training projection Y=XW, computing Y, dX and dW uses three matrix multiplications with the same leading FLOP count when both gradients are required. This motivates a rough three-times-forward estimate for their combined work. Real training also includes other operators, saved or recomputed activations, optimizer updates and communication. Count those separately before treating the estimate as a throughput prediction.</p>
${check("If T doubles, which quantities double, which can quadruple, and which stay fixed in this model?", "Residual activations and a dense KV cache double. Dense full-sequence attention pair count can quadruple. The learned weight count stays fixed. A cached single-query attention step doubles its pair count, while its weight projection shapes stay fixed for the same batch.")}
${ref("https://arxiv.org/abs/2305.13245", "Ainslie et al.: grouped-query attention")}
${ref("https://arxiv.org/abs/2002.05202", "Shazeer: gated feed-forward variants")}
${ref("https://arxiv.org/abs/2205.14135", "Dao et al.: attention arithmetic and intermediate storage")}
</section>`;
